/* br_vec.h -- 3D vector math, decompiled from BRD3D.dll.
 *
 * The engine's vector library: a tight cluster of leaf functions at
 * 0x1003AC30-0x1003B060 with no callees of their own, called from 76 sites.
 * Semantics were recovered by tracing the x87 stack instruction by
 * instruction (these are FPU-heavy and full of fxch, so operand order is not
 * apparent without doing that).
 *
 * Argument order follows the original: destination first.
 */
#ifndef BR_VEC_H
#define BR_VEC_H
#ifdef __cplusplus
extern "C" {  /* BR_CLINK_BEGIN: every original function has C linkage */
#endif

typedef struct BrVec2 { float x, y; } BrVec2;
typedef struct BrVec3 { float x, y, z; } BrVec3;
typedef struct BrVec4 { float f00, f04, f08, f0C; } BrVec4;

/* 0x1003AC30  out = a x b   (right-handed cross product) */
/* BrVec3Cross: prototype in br_funcs.h */
/* 0x1003AC90  returns a . b */
/* BrVec3Dot: prototype in br_funcs.h */
/* 0x1003AEE0  out = a - b */
/* BrVec3Sub: prototype in br_funcs.h */
/* 0x1003AF70  a += b */
/* BrVec3AddTo: prototype in br_funcs.h */
/* 0x1003ACE0  out = v * s */
/* BrVec3Scale: prototype in br_funcs.h */
/* 0x1003AD10  v *= s */
/* BrVec3ScaleBy: prototype in br_funcs.h */
/* 0x1003AFE0  out = a + b * s */
/* BrVec3MulAdd: prototype in br_funcs.h */
/* 0x1003B020  a += b * s */
/* BrVec3MulAddTo: prototype in br_funcs.h */
/* 0x1003AFA0  out = (a - b) * t + b   -- note t=0 yields b, t=1 yields a */
/* BrVec3Lerp: prototype in br_funcs.h */

/* 0x1003ACC0  out = -v */
/* BrVec3Negate: prototype in br_funcs.h */
/* 0x1003AF40  out = a + b */
/* BrVec3Add: prototype in br_funcs.h */
/* 0x1003AF10  a -= b */
/* BrVec3SubFrom: prototype in br_funcs.h */
/* 0x1003AD40  out = v / s   (original computes 1.0f/s once, then multiplies) */
/* BrVec3Div: prototype in br_funcs.h */
/* 0x1003AD70  v /= s */
/* BrVec3DivBy: prototype in br_funcs.h */
/* 0x1003B050  out = (a + b) * 0.5f */
/* BrVec3Midpoint: prototype in br_funcs.h */
/* 0x1003B090  v = 0 */
/* BrVec3Zero: prototype in br_funcs.h */

/* 0x1003B130  returns |a - b|^2  (squared, no sqrt) */
/* BrVec3DistSq: prototype in br_funcs.h */

/* 0x1003B0E0  returns |a - b|  (true distance; calls the fsqrt wrapper) */
/* BrVec3Dist: prototype in br_funcs.h */

/* 0x1003B170  returns |v|.
 *
 * Was MISSING from this header until a cross-check found it -- it sits inside the
 * 0x1003AC30-0x1003B130 cluster this file otherwise covers, so "the vector
 * library is complete" was wrong.
 *
 * Note the sum of squares is ROUNDED TO float32 before the sqrt (the original
 * spills it through a 4-byte stack slot), unlike BrVec3dLen which keeps double
 * precision throughout. Do not implement this as sqrtf of a double sum. */
/* BrVec3Length: prototype in br_funcs.h */

/* 0x1006D4B0  v *= 1.0f / |v|  (no zero-length guard) */
/* BrVec3Normalise: prototype in br_funcs.h */
/* 0x1006D410  same over four components */
/* BrVec4Normalise: prototype in br_funcs.h */

/* 0x10071B60  1 if pA->y is strictly below pB->y, or either is NaN; else 0. */
/* BrSub10071B60: prototype in br_funcs.h */































#ifdef __cplusplus
}  /* BR_CLINK_END */
#endif



























/* BR_GLOBALS_BEGIN: generated by ports/brally/tools/unify.py */
#ifdef __cplusplus
extern "C" {
#endif
#pragma push_macro("g_BrDrawDir0")
#undef g_BrDrawDir0
extern BrVec3 g_BrDrawDir0;  /* 0x10273390 */
#pragma pop_macro("g_BrDrawDir0")
#pragma push_macro("g_BrDrawDir1")
#undef g_BrDrawDir1
extern BrVec3 g_BrDrawDir1;  /* 0x10273560 */
#pragma pop_macro("g_BrDrawDir1")
#pragma push_macro("g_BrVisCarDelta")
#undef g_BrVisCarDelta
extern BrVec3 g_BrVisCarDelta;  /* 0x102E0C90 */
#pragma pop_macro("g_BrVisCarDelta")
#pragma push_macro("DAT_1035fb78")
#undef DAT_1035fb78
extern BrVec3 DAT_1035fb78;  /* 0x1035FB78 */
#pragma pop_macro("DAT_1035fb78")
#pragma push_macro("g_BrVisLightDir")
#undef g_BrVisLightDir
extern BrVec3 g_BrVisLightDir;  /* 0x1035FB90 */
#pragma pop_macro("g_BrVisLightDir")
#pragma push_macro("DAT_104abe70")
#undef DAT_104abe70
extern BrVec3 DAT_104abe70[2];  /* 0x104ABE70 */
#pragma pop_macro("DAT_104abe70")
#pragma push_macro("g_vPfxDrift")
#undef g_vPfxDrift
extern BrVec3 g_vPfxDrift;  /* 0x104ADD40 */
#pragma pop_macro("g_vPfxDrift")
#pragma push_macro("DAT_104b15d0")
#undef DAT_104b15d0
extern BrVec3 DAT_104b15d0[2];  /* 0x104B15D0 */
#pragma pop_macro("DAT_104b15d0")
#pragma push_macro("g_pBrRaceFlyPos")
#undef g_pBrRaceFlyPos
extern BrVec3 *g_pBrRaceFlyPos;  /* 0x105BC7DC */
#pragma pop_macro("g_pBrRaceFlyPos")
#pragma push_macro("g_pBrRaceFlyAim")
#undef g_pBrRaceFlyAim
extern BrVec3 *g_pBrRaceFlyAim;  /* 0x105BC7E0 */
#pragma pop_macro("g_pBrRaceFlyAim")
#pragma push_macro("g_brRaceFlyDirPrev")
#undef g_brRaceFlyDirPrev
extern BrVec3 g_brRaceFlyDirPrev;  /* 0x105BC7EC */
#pragma pop_macro("g_brRaceFlyDirPrev")
#pragma push_macro("g_brRaceFlyDirCur")
#undef g_brRaceFlyDirCur
extern BrVec3 g_brRaceFlyDirCur;  /* 0x105BC7F8 */
#pragma pop_macro("g_brRaceFlyDirCur")
#pragma push_macro("g_brRaceFlyDirNext")
#undef g_brRaceFlyDirNext
extern BrVec3 g_brRaceFlyDirNext;  /* 0x105BC804 */
#pragma pop_macro("g_brRaceFlyDirNext")
#pragma push_macro("g_pBrCollVerts")
#undef g_pBrCollVerts
extern BrVec3 *g_pBrCollVerts;  /* 0x106C7C5C */
#pragma pop_macro("g_pBrCollVerts")
#pragma push_macro("g_BrVisLightDefault")
#undef g_BrVisLightDefault
extern BrVec3 g_BrVisLightDefault;  /* 0x106E7700 */
#pragma pop_macro("g_BrVisLightDefault")
#pragma push_macro("g_BrCamExtentU")
#undef g_BrCamExtentU
extern BrVec3 g_BrCamExtentU;  /* 0x106E7720 */
#pragma pop_macro("g_BrCamExtentU")
#pragma push_macro("g_BrCamCentre")
#undef g_BrCamCentre
extern BrVec3 g_BrCamCentre;  /* 0x106E9A20 */
#pragma pop_macro("g_BrCamCentre")
/* 0x106EA3AC: row 1 of g_aBrSpanPt (the hull points), as in the original */
#define g_BrCamCorner0 (*(BrVec3 *)g_aBrSpanPt[1])
/* 0x106EA3B8: row 2 of g_aBrSpanPt (the hull points), as in the original */
#define g_BrCamCorner1 (*(BrVec3 *)g_aBrSpanPt[2])
/* 0x106EA3C4: row 3 of g_aBrSpanPt (the hull points), as in the original */
#define g_BrCamCorner2 (*(BrVec3 *)g_aBrSpanPt[3])
/* 0x106EA3D0: row 4 of g_aBrSpanPt (the hull points), as in the original */
#define g_BrCamCorner3 (*(BrVec3 *)g_aBrSpanPt[4])
/* 0x106EA3DC: row 5 of g_aBrSpanPt (the hull points), as in the original */
#define g_BrCamCentreCopy (*(BrVec3 *)g_aBrSpanPt[5])
#pragma push_macro("g_BrCamExtentR")
#undef g_BrCamExtentR
extern BrVec3 g_BrCamExtentR;  /* 0x106EC788 */
#pragma pop_macro("g_BrCamExtentR")
#pragma push_macro("g_aScanMidA")
#undef g_aScanMidA
extern BrVec3 g_aScanMidA[];  /* row 0x10B1C884 */
#pragma pop_macro("g_aScanMidA")
#pragma push_macro("g_aScanMidB")
#undef g_aScanMidB
extern BrVec3 g_aScanMidB[];  /* 0x10B1C8E4 */
#pragma pop_macro("g_aScanMidB")
#pragma push_macro("g_aScanOut3")
#undef g_aScanOut3
extern BrVec3 g_aScanOut3[];  /* 0x10B1C958 */
#pragma pop_macro("g_aScanOut3")
#pragma push_macro("g_aBrAiScanA")
#undef g_aBrAiScanA
extern BrVec3 g_aBrAiScanA[];  /* 0x10B1C9B8 */
#pragma pop_macro("g_aBrAiScanA")
#pragma push_macro("g_aBrAiScanB")
#undef g_aBrAiScanB
extern BrVec3 g_aBrAiScanB[];  /* 0x10B1CA28 */
#pragma pop_macro("g_aBrAiScanB")
#pragma push_macro("g_aScanCentre")
#undef g_aScanCentre
extern BrVec3 g_aScanCentre[];  /* 0x10B1CA7C */
#pragma pop_macro("g_aScanCentre")
#pragma push_macro("g_aScanInsetB")
#undef g_aScanInsetB
extern BrVec3 g_aScanInsetB[];  /* 0x10B1CADC */
#pragma pop_macro("g_aScanInsetB")
#pragma push_macro("g_aScanInsetA")
#undef g_aScanInsetA
extern BrVec3 g_aScanInsetA[];  /* 0x10B1CB3C */
#pragma pop_macro("g_aScanInsetA")
/* The corridor scan (0x1005D060) keeps five rows of vertices indexed by
 * depth 1..8 (base + depth * 12; [0] lies on whatever precedes the row).
 * The original's other names in that span are [2] of a row. */
#define g_brAiScanEndA  (g_aScanMidB[2])                         /* 0x10B1C8FC */
#define g_brAiScanProbe (g_aScanCentre[2])                       /* 0x10B1CAA0 */
#define g_aScanHitA     (*(BrVec3 (*)[7])&g_aScanInsetB[2])      /* 0x10B1CAF4 */
#define g_aScanHitB     (*(BrVec3 (*)[7])&g_aScanInsetA[2])      /* 0x10B1CB54 */
#pragma push_macro("g_brRacePathPos")
#undef g_brRacePathPos
extern BrVec3 g_brRacePathPos;  /* 0x10B1CE98 */
#pragma pop_macro("g_brRacePathPos")
#pragma push_macro("g_brCrPlaneOut")
#undef g_brCrPlaneOut
extern BrVec3 g_brCrPlaneOut;  /* 0x117781A0 */
#pragma pop_macro("g_brCrPlaneOut")
#ifdef __cplusplus
}
#endif
/* BR_GLOBALS_END */
#endif /* BR_VEC_H */
