/* WHAT IT DOES: loads the player's control settings from disk on top of the
 * settings already in memory.  It snapshots the live settings into a stack
 * copy first, checks the file's "RCfg" magic and version 2, then reads every
 * field straight into the live object; on the first short read it restores
 * the snapshot, closes the file, re-applies the (restored) settings and
 * returns 0, so a partly-read file never leaves them half-updated.  Returns 1
 * on success, 0 if the file cannot be opened. */
/* @implements 0x10063060 glide BrCtrlCfgReadFile
 * @cpp_kind method
 * @cpp_symbol ?m_10063060@BrCtrlCfg_10062B00_10008D60@@QAEHPBD@Z
 *
 * Thiscall (`this` in ecx, the path on the stack, `ret 4`) with an EH frame:
 * the 0x874-byte snapshot is a real object whose constructor (0x10062B00)
 * and destructor (the out-of-line nop 0x10008D60) bracket the reads, which
 * is what routes it to the C++ lane.  The C twin in br_cfgfile.c stays as
 * the port's reader. */
#define _CRTIMP __declspec(dllimport)
#include <stdio.h>
#include "br_ctrltoggle.h"   /* port: the Toggle Remaster action */
#include "slice3_42.h"   /* BrCtrlCfg */
#include <string.h>

/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* VA-encoded class name (ctor_dtor) + m_<VA> methods, so the oracle's reloc
 * resolver maps every thiscall to its real address. */
class BrCtrlCfg_10062B00_10008D60 : public BrCtrlCfg {
public:
    BrCtrlCfg_10062B00_10008D60();                  /* 0x10062B00 */
    ~BrCtrlCfg_10062B00_10008D60();                 /* 0x10008D60 (nop) */
    void m_10062E50(BrCtrlCfg_10062B00_10008D60 *pSrc);   /* copy from pSrc */
    void m_10062D00();                              /* apply */
    int  m_10063060(const char *pszPath);
};

int BrCtrlCfg_10062B00_10008D60::m_10063060(const char *pszPath)
{
    int   version;
    int   magic;
    FILE *pFile;

    pFile = fopen(pszPath, "rb");
    if (pFile == NULL)
        return 0;

    BrCtrlCfg_10062B00_10008D60 save;
    save.m_10062E50(this);

    if (fread(&magic, 4, 1, pFile) != 1) goto fail;
    if (strncmp((char *)&magic, BrGlCfgMagic, strlen(BrGlCfgMagic)) != 0) goto fail;
    if (fread(&version, 4, 1, pFile) != 1) goto fail;
    if (version != 2) goto fail;
    if (fread(&f2A8, 4, 1, pFile) != 1) goto fail;
    if (fread(&f2AC, 4, 1, pFile) != 1) goto fail;
    if (fread(&f2B0, 4, 1, pFile) != 1) goto fail;
    if (fread(f2B4, 0x104, 1, pFile) != 1) goto fail;
    if (fread(f3B8, 0x400, 1, pFile) != 1) goto fail;
    if (fread(&f7B8, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7BC, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7C0, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7C4, 4, 1, pFile) != 1) goto fail;
    if (fread(f7C8, 0x10, 1, pFile) != 1) goto fail;
    if (fread(&f7D8, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7DC, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7E0, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7E4, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7E8, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7EC, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7F0, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7F4, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7F8, 4, 1, pFile) != 1) goto fail;
    if (fread(&f7FC, 4, 1, pFile) != 1) goto fail;
    if (fread(&f800, 4, 1, pFile) != 1) goto fail;
    if (fread(&f804, 4, 1, pFile) != 1) goto fail;
    if (fread(&f808, 4, 1, pFile) != 1) goto fail;
    if (fread(&f80C, 4, 1, pFile) != 1) goto fail;
    if (fread(f810, 0x20, 1, pFile) != 1) goto fail;
    if (fread(f830, 0x40, 1, pFile) != 1) goto fail;
    if (fread(&f870, 4, 1, pFile) != 1) goto fail;
    if (fread(&active, 4, 1, pFile) != 1) goto fail;
    if (fread(&profile[0], 0xa8, 1, pFile) != 1) goto fail;
    if (fread(&profile[1], 0xa8, 1, pFile) != 1) goto fail;
    if (fread(&profile[2], 0xa8, 1, pFile) != 1) goto fail;
    if (fread(&profile[3], 0xa8, 1, pFile) != 1) goto fail;
    BrToggleBindRead(pFile);   /* port: optional, after the original's fields */

    fclose(pFile);
    return 1;
fail:
    m_10062E50(&save);
    fclose(pFile);
    m_10062D00();
    return 0;
}

/* C entry points (generated by ports/brally/tools/methodfwd.py) */
extern "C" int BrCtrlCfgReadFile(void *self, const char * pszPath)
{
    return ((class BrCtrlCfg_10062B00_10008D60 *)self)->m_10063060(pszPath);
}
/* end of C entry points */

/* Methods of the local classes above that other files define: each is
 * the function at its original address, reached through its C entry. */
/* 0x10062B00: the original calls BrCtrlCfgCtor by address */
inline BrCtrlCfg_10062B00_10008D60::BrCtrlCfg_10062B00_10008D60()
{
    BrCtrlCfgCtor((struct BrCtrlCfg *)this);
}

/* 0x10008D60: the original calls BrPodNop by address */
inline BrCtrlCfg_10062B00_10008D60::~BrCtrlCfg_10062B00_10008D60()
{
    BrPodNop();
}

/* 0x10062E50: the original calls BrRec874Copy_10062E50 by address */
inline void BrCtrlCfg_10062B00_10008D60::m_10062E50(BrCtrlCfg_10062B00_10008D60 * a1)
{
    BrRec874Copy_10062E50((void *)this, (struct Rec62E50 *)a1);
}

/* 0x10062D00: the original calls BrCtrlCfgInit by address */
inline void BrCtrlCfg_10062B00_10008D60::m_10062D00()
{
    BrCtrlCfgInit((struct BrCtrlCfg *)this);
}
