#include "slice2_25.h"   /* br_globals: its objects */
#include "br_ui.h"   /* BrUiCtl_, the canonical record */
/* WHAT IT DOES: leave this menu page: run its leave routine, destroy the
 * page object, and make its parent current again. One of a family that
 * differ only in which parent they return to and which state flags they
 * clear. */
/* @implements 0x1003FAC0 glide BrOpt6670
 * @cpp_kind method
 * @cpp_symbol ?BrOpt6670@@YAHPAVGameObj@@@Z
 *
 * Phase-leave family member, generated by tools/gen_phaseleave.py.
 * Slot+0x1C no-arg virtual thiscall, then the slot-0 one-stack-arg
 * vcall (`mov eax,[ecx]; push 1; call [eax]`) that only a real C++
 * virtual call reaches. No EH (no `new`).
 */
#define _CRTIMP __declspec(dllimport)

class GameSub {
public:
    virtual void s0();
    virtual void s1();
    virtual void s2();
    virtual void s3();
    virtual void s4();
    virtual void s5();
    virtual void s6(int);
    virtual void s7();
};

class GameObj {
public:
    char pad[0x2AE8];
    GameSub *pSub;
};

class Phase {
public:
    virtual void *f00(int);
};


/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

int BrOpt6670(GameObj *pGame)
{
    Phase *pObj;

    (*(GameSub * *)&((BrUiCtl_ *)(pGame))->pOwner)->s7();
    pObj = (Phase *)((*(Phase * *)&g_brPAA29B8));
    if (pObj != 0)
        pObj->f00(1);
    g_5CEC = 0;
    DAT_10ac5d44 = 0;
    (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(g_5CD8));
    return 0;
}
