/* WHAT IT DOES: builds the next auto-numbered file name for a save slot.
 * Strips the input name down to its base (dropping an 'X'/'x' placeholder --
 * which it also rewrites to '0' in the caller's buffer -- and everything from
 * the first '.'), scans a 100-entry table of existing names for the ones that
 * share that base and sort after the input, keeps the last such as the
 * template, lifts that template's extension and its trailing decimal counter,
 * bumps the counter by one, and writes base + newcounter + extension into
 * *ppOut. */
/* @implements 0x10055F40 glide BrSaveNextName_10055F40
 * @cpp_kind method
 * @cpp_symbol ?NextName@Save55F40@@QAEXPAEPAPAD@Z
 *
 * Thiscall, two stack args (`ret 8`), 799 B.  `this` is the name-table
 * object; the 100 candidate strings start at this+4 (stride 0x104).  All of
 * strcpy/strlen/strcmp are inlined intrinsics; strncmp, atoi and _itoa are
 * real /MD imports.  The four masked _itoa calls into digits+0..+3 are the
 * original's, not a slip -- each writes the decimal of one masked byte and
 * the next overwrites all but its first char.
 *
 * Byte-exact 2026-09-27, re-transcribed from the asm.  The previous body
 * had two behaviour bugs, not just codegen: it never cleared `stripped`
 * (the original memsets all four buffers), and it copied the extension one
 * byte short -- the original copies strlen(cand) - (p - cand) bytes from
 * the '.', i.e. the dot and the whole extension.  Source shape: unsigned
 * `i < strlen()` loops (no pre-test `if`), a `short` copy of the kept
 * length, and a plain 0..99 walk of the table that VC5 turns into the
 * pointer and down-counter.
 */
#define _CRTIMP __declspec(dllimport)
#include <stdlib.h>
#include <string.h>

class Save55F40 {
public:
    int  head;                      /* +0x00 */
    char table[100][0x104];         /* +0x04 candidate names */

    void NextName(unsigned char *pIn, char **ppOut);   /* 0x10055F40 */
};

void Save55F40::NextName(unsigned char *pIn, char **ppOut)
{
    char         cand[0x104];
    char         digits[0x104];
    char         suffix[0x104];
    char         stripped[0x104];
    unsigned int i;
    int          flag;
    int          n;
    int          k;
    short        len;
    char        *p;
    int          num;

    memset(cand, 0, sizeof(cand));
    memset(digits, 0, sizeof(digits));
    memset(stripped, 0, sizeof(stripped));
    flag = 0;
    memset(suffix, 0, sizeof(suffix));

    strcpy(cand, (char *)pIn);

    n = 0;
    for (i = 0; i < strlen((char *)pIn); i++) {
        if (pIn[i] == 'X' || pIn[i] == 'x') {
            pIn[i] = '0';
            flag = 1;
        } else if (flag == 0) {
            if (pIn[i] == '.') {
                flag = 1;
            } else {
                stripped[i] = pIn[i];
                n++;
            }
        }
    }

    len = (short)n;
    for (k = 0; k < 100; k++) {
        if (strncmp((char *)pIn, table[k], len) == 0
            && strcmp((char *)pIn, table[k]) < 0)
            strcpy(cand, table[k]);
    }

    p = cand + strlen(cand) - 1;
    while (p != cand && *p != '.')
        p--;
    if (p != cand) {
        k = strlen(cand) - (p - cand);
        memcpy(suffix, p, k);
        suffix[k] = 0;
    }

    for (i = len; i < strlen(cand); i++) {
        if (cand[i] < '0' || cand[i] > '9')
            break;
        digits[i - len] = cand[i];
    }

    num = atoi(digits) + 1;
    memset(digits, 0, sizeof(digits));
    _itoa(num & 0xff000000, digits + 0, 10);
    _itoa(num & 0xff0000, digits + 1, 10);
    _itoa(num & 0xff00, digits + 2, 10);
    _itoa(num & 0xff, digits + 3, 10);

    strcpy(*ppOut, stripped);
    strcat(*ppOut, digits);
    strcat(*ppOut, suffix);
}

/* C entry points (generated by ports/brally/tools/methodfwd.py) */
extern "C" void BrSaveNextName_10055F40(void *self, unsigned char * pIn, char ** ppOut)
{
    ((class Save55F40 *)self)->NextName(pIn, ppOut);
}
/* end of C entry points */
