#include "br_ui.h"   /* BrUiCtl_, the canonical record */
/* WHAT IT DOES: advance the page's timed step sequence -- accumulates real
 * elapsed time and moves to the next step once this one's duration has
 * passed. */
/* @implements 0x100414F0 glide BrUiTickSteps_100480A0
 * @cpp_kind method
 * @cpp_symbol ?TickSteps@UiPage@@QAEHXZ
 *
 * 218 B thiscall step-timer tick. KEY SPELLING: the accumulate is
 * t-less: `f2974 += now - f2970; f2970 = now;` (scheduler emits the
 * f2970 store first). A temp form (`t = now - f2970; ... f2974 += t`)
 * makes VC5 FORWARD the stored value into the branch (mov ecx,edx)
 * where the original RE-READS f2974: 147-diff cascade from that one
 * fork. Stepped branch is early-return style (jle/jg cross-jump to the
 * final return 1, the wrap path gets its own epilogue); both arms are
 * f1C |= then f3850 |= (the stepped arm's swapped stores are
 * scheduling). w128 is a SIGNED short here (movsx index).
 */
extern "C" {
/* BrSub10075020: prototype in br_funcs.h */
}

class UiPage {
public:
    char pad00[0x1C];
    unsigned int f1C;               /* +0x1C */
    char pad20[0x108];              /* +0x20 */
    short w128;                     /* +0x128 */
    char pad12A[0x283E];            /* +0x12A */
    int f2968;                      /* +0x2968 */
    int f296C;                      /* +0x296C */
    int f2970;                      /* +0x2970 */
    int f2974;                      /* +0x2974 */
    int a2978[0x3B6];               /* +0x2978 */
    int f3850;                      /* +0x3850 */
    int TickSteps();
};


int UiPage::TickSteps()
{
    int now;

    if ((*(int *)&((BrUiCtl_ *)(this))->f2968) == 0)
        return 1;
    now = BrSub10075020();
    (*(int *)&((BrUiCtl_ *)(this))->f2974) += now - (*(int *)&((BrUiCtl_ *)(this))->f2970);
    (*(int *)&((BrUiCtl_ *)(this))->f2970) = now;
    if ((*(int *)&((BrUiCtl_ *)(this))->f296C) != 0) {
        if ((*(int *)&((BrUiCtl_ *)(this))->f2974) <= (*(int (*)[950])&((BrUiCtl_ *)(this))->aStepMs[0])[(*(short *)&((BrUiCtl_ *)(this))->wStep)])
            return 1;
        (*(int *)&((BrUiCtl_ *)(this))->f2974) = 0;
        (*(unsigned int *)&((BrUiCtl_ *)(this))->flags1C) |= 0x100;
        (*(int *)&((BrUiCtl_ *)(this))->list.f18) |= 0x100;
        ++(*(short *)&((BrUiCtl_ *)(this))->wStep);
        if ((*(int (*)[950])&((BrUiCtl_ *)(this))->aStepMs[0])[(*(short *)&((BrUiCtl_ *)(this))->wStep)] > 0)
            return 1;
        (*(short *)&((BrUiCtl_ *)(this))->wStep) = 0;
        return 1;
    }
    if ((*(int *)&((BrUiCtl_ *)(this))->f2974) > 0x3c) {
        (*(int *)&((BrUiCtl_ *)(this))->f2974) = 0;
        (*(unsigned int *)&((BrUiCtl_ *)(this))->flags1C) |= 0x100;
        (*(int *)&((BrUiCtl_ *)(this))->list.f18) |= 0x100;
    }
    return 1;
}

/* C entry points (generated by ports/brally/tools/methodfwd.py) */
extern "C" int BrUiTickSteps_100480A0(void *self)
{
    return ((class UiPage *)self)->TickSteps();
}
/* end of C entry points */
