#include "br_phase.h"   /* BrPhase_, the canonical record */
#include "br_ui.h"   /* BrUiCtl_, the canonical record */
/* WHAT IT DOES: check whether a DIFFERENT page is already the active one and
 * flag the clash if so, which is what stops two pages both thinking they
 * have the focus. */
/* @implements 0x100414B0 glide BrUiCheckOther_10048060
 * @cpp_kind method
 * @cpp_symbol ?CheckOther@UiPage@@QAEHXZ
 *
 * 52 B thiscall. Tests the global current-page pointer against this;
 * the 1 is materialized once (mov eax,1) and serves the f70 compare,
 * the flag store, and the return value. this==current skips both flag
 * stores straight to return 0.
 */
class UiCont {
public:
    char pad[0x70];
    int f70;                        /* +0x70 */
};

class UiPage {
public:
    char pad[0x2AE8];
    UiCont *f2AE8;                  /* +0x2AE8 */
    int CheckOther();
};

extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
}

int UiPage::CheckOther()
{
    UiPage *p;

    p = (*(UiPage * *)&DAT_10ac5d18);
    if (p != 0 && (*(int *)&((BrPhase_ *)((*(UiCont * *)&((BrUiCtl_ *)(p))->pOwner)))->aFlags[1]) == 1) {
        if (this != p) {
            DAT_10ac5bb0 = 1;
            return 1;
        }
    } else {
        DAT_10ac5bb0 = 0;
    }
    return 0;
}

/* C entry points (generated by ports/brally/tools/methodfwd.py) */
extern "C" int BrUiCheckOther_10048060(void *self)
{
    return ((class UiPage *)self)->CheckOther();
}
/* end of C entry points */
