/* WHAT IT DOES: the same table-driven caption hook as its siblings, with its
 * own table and index. */
/* @implements 0x10038ED0 glide BrUiText3F990
 * @cpp_kind method
 * @cpp_symbol ?BrUiText3F990@@YAHPAVGameObj@@@Z
 *
 * UI text-refresh family member, generated by tools/brally/gen_uitext.py from
 * the 0x10038D30 skeleton (strcpy looked-up string into the item text
 * buffer, slot-1 virtual thiscall on the embedded item, apply). No EH.
 */
#define _CRTIMP __declspec(dllimport)
#include "br_coretypes.h"   /* br_globals: its objects */
#include "br_ui.h"   /* BrUiCtl_, the canonical record */
#include <string.h>

class Item {
public:
    virtual void i0();
    virtual void i1();
};

class GameObj {
public:
    char pad[0x2B5C];
    Item item;
    char pad2[5];
    char text[256];
};




extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_idx DAT_100abdf0
#define g_tab (DAT_100abae8 + 4)   /* 0x100ABAF8 */
/* BrStrGet: prototype in br_funcs.h */
/* Br85ItemApply: prototype in br_funcs.h */
}

int BrUiText3F990(GameObj *pGame)
{
    strcpy((*(char (*)[256])&((BrUiCtl_ *)(pGame))->aText[0].sz[0]), BrStrGet(g_tab[g_idx]));
    (*(class Item *)&((BrUiCtl_ *)(pGame))->aText[0]).i1();
    Br85ItemApply((struct BrCtl85 *)(pGame), 0);
    return 1;
}
