#include "br_ui.h"   /* BrUiCtl_, the canonical record */
/* WHAT IT DOES: begin an animated move: works out the per-step increment
 * from the distance and the number of steps, and remembers where the item
 * started. */
/* @implements 0x10041100 glide BrUiTweenBegin_10047CB0
 * @cpp_kind method
 * @cpp_symbol ?Begin@Tween41100@@QAEHH@Z
 *
 * Thiscall, one stack arg (`ret 4`), 48 B. Work out the per-step delta for
 * a tween -- the span divided by the step count -- and move the target
 * triple back into the current one. Returns 1.
 *
 * The divisor is an INT argument divided into a float, which VC5 spells as
 * a single `fidiv dword ptr [arg]` against the integer in memory; casting
 * it to float first would emit a fild instead.
 *
 * The port body in slice3_32.c takes a globals-struct pointer it does not
 * need; the original is a bare thiscall. Same split as the siblings.
 */
#define _CRTIMP __declspec(dllimport)

class Tween41100 {
public:
    char  pad000[0x30];
    int   f030;                 /* +0x030 */
    int   f034;
    int   f038;
    int   f03C;
    int   f040;
    int   f044;
    char  pad048[0x3818 - 0x48];
    int   f3818;                /* +0x3818 */
    float f381C;                /* +0x381C */
    float f3820;
    float f3824;

    int Begin(int nSteps);
};


int Tween41100::Begin(int nSteps)
{
    (*(float *)&((BrUiCtl_ *)(this))->twRate) = ((*(float *)&((BrUiCtl_ *)(this))->twHi) - (*(float *)&((BrUiCtl_ *)(this))->twLo)) / nSteps;

    (*(int *)&((BrUiCtl_ *)(this))->fTweenX) = (*(int *)&((BrUiCtl_ *)(this))->x);
    (*(int *)&((BrUiCtl_ *)(this))->fTweenY) = (*(int *)&((BrUiCtl_ *)(this))->y);
    (*(int *)&((BrUiCtl_ *)(this))->fTweenZ) = (*(int *)&((BrUiCtl_ *)(this))->f44);

    return 1;
}

/* C entry points (generated by ports/brally/tools/methodfwd.py) */
extern "C" int BrUiTweenBegin_10047CB0(void *self, int nSteps)
{
    return ((class Tween41100 *)self)->Begin(nSteps);
}
/* end of C entry points */
