#include "slice2_25.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and
 * this one clears its buffer before opening. */
/* @implements 0x1003E0E0 glide Ctl3E0E0
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3E0E0@@QAEHXZ
 *
 * ResetBuf(&g_buf) then the shared-return activate (cpp-family2-notes.md).
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot g_5CB4
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls BrExt_10059760 (?BrExt_10059760@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrExt_10059760: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrExt_10059760)
/* ResetBuf: prototype in br_funcs.h */

class Ctl3E0E0 {
public:
    int Activate();
};

int Ctl3E0E0::Activate()
{
    Phase *p;

    BrExt_100419D0(&(g_strA[0]));
    p = g_slot;
    if (p == 0) {
        p = ((Phase *)br_new_obj(sizeof(BrPhase_), (void *(*)(void *))BrOptObjCtor));
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = 1;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    return 1;
}

/* C entry points (generated by ports/brally/tools/methodfwd.py) */
extern "C" int Ctl3E0E0_fn(void *self)
{
    return ((class Ctl3E0E0 *)self)->Activate();
}
/* end of C entry points */
