/* tgr_syms.h: the game's initialised data and functions, by original
 * address (generated by tools/globals.py into build/tgrally/gen).
 *
 * Every data symbol lives in the arena at its original address with the
 * original's layout (tgr_addr.h); the ROM's .data/.rodata is copied there
 * at start-up and each symbol's multi-byte units turned from big-endian to
 * native (tgr_lift).  Texel, display-list and other RSP data are byte
 * arrays or be16_t/be32_t, so they stay as the cartridge has them. */
#ifndef TGR_SYMS_H
#define TGR_SYMS_H
#include <stdint.h>

typedef struct TgrRun {     /* count units of size bytes, from off, stride apart */
    uint32_t off, size, count, stride;
} TgrRun;

typedef struct TgrSym {     /* a .data symbol: its address, size and runs */
    uint32_t addr, size, run0, nruns;
} TgrSym;

typedef struct TgrFn {      /* a game function: its original address */
    uint32_t va;
    void    *fn;
} TgrFn;

extern const TgrRun tgr_runs[];
extern const TgrSym tgr_syms[];
extern const int tgr_nsyms;
extern const TgrFn tgr_fns[];
extern const int tgr_nfns;
#endif

#ifndef TGR_SYMS_NATIVE
#define TGR_SYMS_NATIVE
typedef struct TgrNat {     /* a pointer variable or table: native, outside the arena */
    void   **nat;
    uint32_t addr;          /* its original address */
    uint32_t count;         /* pointers in it */
    uint32_t lifted;        /* in .data: its values come from the ROM */
    uint32_t run0, nruns;   /* the layout of what each pointer points at: an
                             * object in .data reached only through it is
                             * lifted with these runs */
} TgrNat;
extern const TgrNat tgr_natives[];
extern const int tgr_nnatives;
#endif
