"""Write the READMEs of n64/src from the sources themselves.

    .venv/bin/python n64/tools/n64index.py

Each area folder gets a README listing its files (with the one-line purpose
from each file's header) and every function in them with its tier.  Run it
after filing; never hand-edit the READMEs.
"""
import csv
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
N64 = os.path.join(ROOT, 'n64')
sys.path.insert(0, os.path.join(N64, 'tools'))
import n64build as B  # noqa: E402
import n64tiers as TI  # noqa: E402

AREAS = {
    'audio': 'sound effects, the music player and the audio driver',
    'controls': 'controllers, the Rumble Pak',
    'drawing': 'frames, display-list helpers, text, fades, per-frame pools',
    'driving': 'car physics, collision, tyres, the computer drivers',
    'gamedata': 'ROM loading, memory pools, saves, random numbers',
    'geometry': 'vector and matrix maths',
    'menus': 'the front-end screens',
    'racing': 'race state, the race display, car artwork, the camera',
    'startup': 'boot, the main loop\'s game modes, fatal errors',
}


def main():
    fmap, tier = TI.classify(fresh=True)
    src = os.path.join(N64, 'src')
    folders = {}
    for f in B.all_sources():
        # the top-level folder (library trees nest deeper)
        folders.setdefault(os.path.relpath(f, src).split(os.sep)[0], []).append(f)
    total = {}
    for area, files in sorted(folders.items()):
        lines = ['# %s: %s' % (area, AREAS.get(area, '')), '',
                 'Generated by `n64/tools/n64index.py` from the sources; do not edit.', '']
        cnt = {}
        for f in sorted(files):
            text = open(f).read()
            head = re.match(r'/\*\s*\S+\s*--\s*(.*?)\n', text)
            lines.append('## `%s`%s' % (os.path.basename(f), head and ': ' + head.group(1).strip() or ''))
            lines.append('')
            lines.append('| address | function | tier |')
            lines.append('|---|---|---|')
            for va, name, _ in sorted(B.tags_in(text)):
                t = tier.get('%08X' % va, '?')
                cnt[t] = cnt.get(t, 0) + 1
                lines.append('| `%08X` | `%s` | %s |' % (va, name, t))
            lines.append('')
        lines.insert(3, 'Functions: ' + ', '.join('%s %d' % kv for kv in sorted(cnt.items())) + '.\n')
        open(os.path.join(src, area, 'README.md'), 'w').write('\n'.join(lines))
        for k, v in cnt.items():
            total[k] = total.get(k, 0) + v
    open(os.path.join(src, 'README.md'), 'w').write('\n'.join([
        '# n64/src/: the Top Gear Rally decomp',
        '',
        'Generated by `n64/tools/n64index.py`; do not edit.',
        '',
        'The N64 game\'s own C, transcribed from the ROM and matched under IDO 5.3.',
        'It shares names and layout with the PC decomp (`src/core/`) so the two read',
        'the same, but it is its own source: the 1997 and 1999 code differ, and',
        'nothing here includes a PC header or is included by the PC build.',
        '',
        'One folder per area; a file per responsibility.  Every function carries a',
        '`WHAT IT DOES:` comment and an `@implements 0x80XXXXXX tgr Name` tag.',
        '',
        '| area | what it is |',
        '|---|---|',
    ] + ['| [`%s/`](%s/README.md) | %s |' % (a, a, AREAS.get(a, '')) for a in sorted(folders)]
      + ['', 'Tagged functions: ' + ', '.join('%s %d' % kv for kv in sorted(total.items())) + '.', '']))
    print('wrote %d area READMEs' % len(folders))


if __name__ == '__main__':
    main()
