/* generated by ports/64b/tools/unify.py */
#define DAT_100b2f04 (*(int *)&g_BrCarCount)
#define DAT_100b32b0 (DAT_100b32b0[0])
#define DAT_100b32bc (DAT_100b32bc[0])
#define DAT_100b32c0 (DAT_100b32c0[0])
#define DAT_10af3bb0 (*(int *)((char *)&g_aBrRaceCar + 0x29A8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71338 (*(int *)((char *)&g_BrCtrlCfg + 0xA8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b713e0 (*(int *)((char *)&g_BrCtrlCfg + 0x150)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71488 (*(int *)((char *)&g_BrCtrlCfg + 0x1F8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71530 (*(int *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71534 g_BrPadModeBytes
#define g_BrCtrlCfg (*(int *)&g_BrCtrlCfg)
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define FUN_1006c290 BrSfxBankLoad
