/* generated by ports/64b/tools/unify.py */
#define DAT_100aa044 (*(int32_t *)&g_brMode0AA8B4)
#define DAT_100b2f04 g_BrCarCount
#define DAT_100b32b0 (*(int32_t (*)[])&DAT_100b32b0)
#define DAT_106e86c8 (BrG_6C1628[4])
#define DAT_106e8720 g_brRaceBegin6E8720
#define DAT_10af2108 (*(uint8_t * *)((char *)&g_aBrRaceCar + 0xF00)) /* BR_LP64_BYTE_VIEW */
#define DAT_118eef90 (*(int64_t *)((char *)&g_aBrSfxChan + 0x50)) /* byte view: the object holds no pointers */
#define DAT_118eef98 (*(int32_t *)((char *)&g_aBrSfxChan + 0x58)) /* byte view: the object holds no pointers */
#define DAT_118eef9c (*(uint32_t *)((char *)&g_aBrSfxChan + 0x5C)) /* byte view: the object holds no pointers */
#define g_BrSndAA3470 (*(int32_t *)&g_BrSndAA3470)
#define g_brCViews g_brMode0AA8B4
#define g_brCfgChosenTrack g_Br0B380C
#define g_brRaceNCar g_BrCarCount
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define _ftol ftol
