/* generated by ports/64b/tools/unify.py */
#define BrSndG0B5DE8 (*(int *)&DAT_100b51e4[1036])
#define BrSndPDS (*(int *)&BrSndPDS)
#define DAT_100b32b0 (DAT_100b32b0[0])
#define DAT_100b32bc (DAT_100b32bc[0])
#define DAT_100b32c0 (DAT_100b32c0[0])
#define DAT_100b55f8 BrSndVoices
#define DAT_100b5cb8 (BrSndVoices[432])
#define DAT_100b5d00 (BrSndVoices[450])
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_aBrSndBankVoice (g_apBrSfxChanVoice[0])
#define g_tab (*(struct Dim (*)[7])&g_tab)
