/* generated by ports/64b/tools/unify.py */
#define DAT_1021c780 (*(uint16_t *)&g_brEarEvent)
#define DAT_1021c782 (*(uint16_t *)((char *)&g_brEarEvent + 0x2)) /* byte view: the object holds no pointers */
#define DAT_1021c784 (*(int *)((char *)&g_brEarEvent + 0x4)) /* byte view: the object holds no pointers */
#define DAT_1021c788 (*(int *)((char *)&g_brEarEvent + 0x8)) /* byte view: the object holds no pointers */
#define DAT_1021c78c (*(uint16_t *)((char *)&g_brEarEvent + 0xC)) /* byte view: the object holds no pointers */
#define DAT_1021c78e (*(uint16_t *)((char *)&g_brEarEvent + 0xE)) /* byte view: the object holds no pointers */
#define DAT_1021c790 (*(uint16_t *)((char *)&g_brEarEvent + 0x10)) /* byte view: the object holds no pointers */
#define DAT_1021c792 (*(uint16_t *)((char *)&g_brEarEvent + 0x12)) /* byte view: the object holds no pointers */
#define DAT_1021c794 (*(int *)((char *)&g_brEarEvent + 0x14)) /* byte view: the object holds no pointers */
#define DAT_1021c798 (*(int *)((char *)&g_brEarEvent + 0x18)) /* byte view: the object holds no pointers */
#define DAT_1021c79c (*(int *)((char *)&g_brEarEvent + 0x1C)) /* byte view: the object holds no pointers */
#define DAT_1021c7a0 (*(int *)((char *)&g_brEarEvent + 0x20)) /* byte view: the object holds no pointers */
#define DAT_1021c7a4 (*(int *)((char *)&g_brEarEvent + 0x24)) /* byte view: the object holds no pointers */
#define DAT_1021c7a8 (*(uint16_t *)((char *)&g_brEarEvent + 0x28)) /* byte view: the object holds no pointers */
#define DAT_1021c7aa (*(uint16_t *)((char *)&g_brEarEvent + 0x2A)) /* byte view: the object holds no pointers */
#define DAT_1021c7ac (*(int *)((char *)&g_brEarEvent + 0x2C)) /* byte view: the object holds no pointers */
#define DAT_1021c7b0 (*(int *)((char *)&g_brEarEvent + 0x30)) /* byte view: the object holds no pointers */
#define DAT_1021c7b4 (*(int *)((char *)&g_brEarEvent + 0x34)) /* byte view: the object holds no pointers */
#define DAT_1021c7b8 (*(int *)((char *)&g_brEarEvent + 0x38)) /* byte view: the object holds no pointers */
#define DAT_1021c7bc (*(uint16_t *)((char *)&g_brEarEvent + 0x3C)) /* byte view: the object holds no pointers */
#define DAT_1021c7be (*(uint16_t *)((char *)&g_brEarEvent + 0x3E)) /* byte view: the object holds no pointers */
#define DAT_1021c7c0 (*(uint16_t *)((char *)&g_brEarEvent + 0x40)) /* byte view: the object holds no pointers */
#define DAT_1021c7c2 (*(uint16_t *)((char *)&g_brEarEvent + 0x42)) /* byte view: the object holds no pointers */
#define DAT_104b1628 (*(int (**)(int, int))&g_pfn575480)
#define g_0940A4 DAT_1007b074
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br0940A8 g_0940A8
#define g_brCdEnabled DAT_1007b074
#define g_brCdMediaOk g_220C3C
#define g_brCdPlaying g_220CD0
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10002c50 BrCdTrackGet
