/* generated by ports/64b/tools/unify.py */
#define DAT_100aa044 g_brMode0AA8B4
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_105ccb5c (*(int *)&g_BrX06909B4)
#define DAT_106e86c8 (*(int *)&BrG_6C1628[4])
#define DAT_106e8720 (*(int *)&g_brRaceBegin6E8720)
#define DAT_106eed38 g_BrDrawTrackFlags
#define DAT_10af2180 (*(int *)((char *)&g_aBrRaceCar + 0xF78)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af393c (*(int *)((char *)&g_aBrRaceCar + 0x2734)) /* BR_LP64_BYTE_VIEW */
#define DAT_1184c454 g_184C454
#define DAT_118eef48 (*(int *)((char *)&g_aBrSfxChan + 0x8)) /* byte view: the object holds no pointers */
#define DAT_118eef4c (*(int *)((char *)&g_aBrSfxChan + 0xC)) /* byte view: the object holds no pointers */
#define DAT_118eef54 (*(int *)((char *)&g_aBrSfxChan + 0x14)) /* byte view: the object holds no pointers */
#define DAT_118eef60 (*(int *)((char *)&g_aBrSfxChan + 0x20)) /* byte view: the object holds no pointers */
#define DAT_118eef64 (*(int *)((char *)&g_aBrSfxChan + 0x24)) /* byte view: the object holds no pointers */
#define DAT_118eef6c (*(int *)((char *)&g_aBrSfxChan + 0x2C)) /* byte view: the object holds no pointers */
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrSndPlaySimple BrSub10072AF0
#define FUN_1006ba80 BrWrap_10072B10
#define FUN_1006baf0 BrWrap_10072B80
#define _ftol ftol
