/* generated by ports/64b/tools/unify.py */
#define BrSndG0B5DE8 (*(int *)&DAT_100b51e4[1036])
#define BrSndPDS (*(int *)&BrSndPDS)
#define DAT_100b55f8 BrSndVoices
/* functions */
#define FUN_1006b4c0 BrSndVoiceBufStop
#define FUN_1006b790 BrSndVoiceSetLR
#define _ftol ftol
