/* generated by ports/64b/tools/unify.py */
#define BrSndG0B5DE8 (*(int32_t *)&DAT_100b51e4[1036])
#define BrSndPDS (*(struct BrDSound * *)&BrSndPDS)
#define DAT_100b55f8 BrSndVoices
#define DAT_100b5d00 (BrSndVoices[450])
#define DAT_11849e60 g_hBrSndWake86
#define DAT_1184c078 (*(int *)&g_fBrSndThread86)
#define DAT_1184c07c g_hBrSndThread86
#define DAT_1184c080 (*(int *)&g_aBrSfxChanApplied)
#define DAT_1184c088 (*(int64_t (*)[])((char *)&g_aBrSfxChanApplied + 0x8)) /* byte view: the object holds no pointers */
#define DAT_1184c08c (*(int *)((char *)&g_aBrSfxChanApplied + 0xC)) /* byte view: the object holds no pointers */
#define DAT_1184c094 (*(int *)((char *)&g_aBrSfxChanApplied + 0x14)) /* byte view: the object holds no pointers */
#define DAT_1184c268 (g_apBrSfxChanVoice[0])
#define DAT_1184c454 g_184C454
#define DAT_118eef40 (*(int *)&g_aBrSfxChan)
#define DAT_118eef48 (*(int *)((char *)&g_aBrSfxChan + 0x8)) /* byte view: the object holds no pointers */
#define DAT_118eef4c (*(int *)((char *)&g_aBrSfxChan + 0xC)) /* byte view: the object holds no pointers */
#define DAT_118eef54 (*(int *)((char *)&g_aBrSfxChan + 0x14)) /* byte view: the object holds no pointers */
#define g_aBrSndBankVoice (g_apBrSfxChanVoice[0])
/* functions */
#define BrSndVoiceStop BrSndVoiceBufStop
#define FUN_1006bf50 BrSndVoiceIsPlaying
#define _ftol ftol
