/* generated by ports/64b/tools/unify.py */
#define DAT_10ac2c50 (*(int *)&g_brSpanColHi)
#define DAT_10ac2c54 g_BrVisRowHi
#define DAT_10ac2c58 (*(int *)&g_brSpanColLo)
#define DAT_10ac2c5c g_BrVisRowLo
#define DAT_10ac2c60 (g_BrVisColLo[0])
#define DAT_10ac2d60 (g_BrVisColHi[0])
/* functions */
#define BrFtolTrunc BrFtolArg
