/* generated by ports/64b/tools/unify.py */
#define BrSndG0B5DE8 (*(int *)&DAT_100b51e4[1036])
#define g_aBrSndBankVoice (g_apBrSfxChanVoice[0])
#define g_apBrSfxChanVoice (*(BrSndVoice * (*)[15])&g_apBrSfxChanVoice)
/* functions */
#define BrSfxChanBind BrSndChanBind
#define BrSfxChanSetLevels BrSndVoiceSetFreq
#define BrSfxSrcTrigger BrSfxBankPlay
#define BrSndVoiceSetLoopAndStart BrSndBufSetPan
#define FUN_1006b790 BrSndVoiceSetLR
#define FUN_1006e590 BrNop6E590
#define _ftol ftol
