/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br0940A8 g_0940A8
#define g_brCdEnabled DAT_1007b074
#define g_brCdMediaOk g_220C3C
#define g_brCdPlaying g_220CD0
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub100027F0 BrCdPlayClamped
#define BrSub10002870 BrCdTrackRequest
