/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5b9c BrGlNavOff5B9C
#define DAT_10ac61e0 (*(BrDIPollRec * *)&g_pBrAA2E80)
#define DAT_10ac66b0 (*(unsigned char *)&g_BrDikState[200])
#define DAT_10ac66b3 (*(unsigned char *)&g_BrDikState[203])
#define DAT_10ac66b5 (*(unsigned char *)&g_BrDikState[205])
#define DAT_10ac66b8 (*(unsigned char *)&g_BrDikState[208])
#define DAT_10ac6720 BrGlNavEdge6720
#define DAT_10ac6730 g_act0
#define DAT_118ee9cc (*(int *)&g_brInKeyPrev)
#define DAT_118ee9d0 (*(int *)&g_brInKeys)
#define DAT_118eebf0 (*(int *)&g_brInKeyCur)
#define DAT_118eebf8 (*(int *)&g_brInJoy)
#define DAT_118eee88 (*(int * *)&g_pBr18ABD70)
#define DAT_118eee94 (*(int *)&g_brInJoyPrev)
#define DAT_118eeeec (*(int * *)&g_brFfb)
#define DAT_118eeef0 (*(int *)((char *)&g_brFfb + 0x4)) /* BR_LP64_BYTE_VIEW */
#define g_BrAA33E0 (*(int32_t *)&g_BrAA33E0)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br100A9354 (*(int32_t *)&g_brRaceRules)
#define g_br100BCBE8 (*(int32_t *)&g_CBE8)
#define g_br1021C770 (*(int32_t *)&g_220C40)
#define g_br10226A44 g_brRaceTick
#define g_br10226A48 g_brRaceNet
#define g_br105BC8DC (*(int32_t *)&DAT_105bc8dc)
#define g_br105CCB5C g_BrX06909B4
#define g_br105CCB88 (DAT_105ccb68[8])
#define g_br10AC408C (*(int32_t *)&g_guardA)
#define g_br10AC5C58 g_obj400
#define g_br10AC5C5C g_brPAA29B8
#define g_br10AF21B0 (*(int32_t *)((char *)&g_aBrRaceCar + 0xFA8)) /* BR_LP64_BYTE_VIEW */
#define g_brAA33E4 (*(int32_t *)&DAT_10ac6744)
#define g_brActivateGate1 (*(uint32_t *)&DAT_105bc740)
#define g_brActivateGate2 (*(uint32_t *)&DAT_105bc744)
#define g_brActivateGate3 (*(uint32_t *)&DAT_105bc748)
#define g_brAppModeH (*(int32_t *)&BrGbiRectG_A7518)
#define g_brAppModeW (*(int32_t *)&BrGbiRectG_A7514)
#define g_brAudioMode (*(int32_t *)&DAT_1007b074)
#define g_brEarMsg (*(int32_t *)&DAT_104b1620)
#define g_brP680584 g_brOwner5BC72C
#define g_brhWnd (*(void * *)&g_brOwner5BC72C)
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrAC61E0 g_pBrAA2E80
#define g_pBrDik18ABDD0 (*(int * *)&g_pBrDik18ABDD0)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrGet1021C788 BrGetGlobal_1C788
#define BrOnActivateTail BrPodNop
#define BrSetVideoMode BrGlideResOpen
#define BrStrId BrStrGet
#define BrSub10002580 BrCdEarChannelOpen
#define BrSub10002760 BrCdMaybeClose
#define BrSub10002830 FUN_10002830
#define BrSub10002AF0 BrCdTrackPlay
#define BrSub10002CF0 BrCdTrackNextWrap
#define BrSub10002EB0 BrCdPause
#define BrSub10002F70 BrCdStop
#define BrSub10004F50 BrNetLockSetIfZero22AAF4
#define BrSub10005330 BrNetBeaconTick
#define BrSub10019A40 BrRaceClockReset
#define BrSub100325B0 BrExt_10038F30
#define BrSub10035A30 BrWmAppHook35A30
#define BrSub100609F0 BrWrap_10067980
#define BrSub10061440 BrSndTableClear
#define BrSub1006BD70 BrSndBankMute
#define BrSub1007296C grSstWinClose
#define FUN_100706d0 BrInputPoll
