/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brCfgB71290 (*(Cfg39870 *)&g_BrCtrlCfg)
#define g_brFlag4648 g_brTbl4648
#define g_obj (*(DiDev * *)&g_pBrAA2E80)
#define g_tab (*(struct Dim (*)[7])&g_tab)
