/* generated by ports/64b/tools/unify.py */
#define g_hinst g_brhInstance2
#define g_hwnd (*(void * *)&g_brOwner5BC72C)
#define g_obj (*(DiDev * *)&g_pBrAA2E80)
#define g_pDI (*(void * *)&g_pBr18ABD70)
#define g_refcount g_BrDInputUsers
/* functions */
#define GetStr BrStrGet
