/* generated by ports/64b/tools/unify.py */
#define DAT_100aaad4 (*(int (*)[])&g_brBindAAAD4)
#define DAT_10ac5b98 g_brSel5B98
#define DAT_10ac5b9c (*(int *)&BrGlNavOff5B9C)
#define DAT_10ac5c30 g_5C30
#define DAT_10ac5d64 g_brKind5D64
#define DAT_10ac6720 (*(int *)&BrGlNavEdge6720)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_Cfg_10B71290 (*(Cfg39990 *)&g_BrCtrlCfg)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrCtrlConflicts_10039870 BrCfgFindConflicts
#define BrDikScan_10059040 BrFn1005FFD0
#define BrInputPollButton_100704E0 BrJoyScanAny
#define BrInputPollPressed_100705F0 BrInputPollPressed
