/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brBindAAAD4 (*(BrBind39620 (*)[21])&g_brBindAAAD4)
#define g_brCfgB71290 (*(Cfg39620 *)&g_BrCtrlCfg)
#define g_brFlag5B9C (*(int *)&BrGlNavOff5B9C)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrItemApply_10038380 Br85ItemApply
#define BrStrByIndex BrStrGet
