/* generated by ports/64b/tools/unify.py */
#define DAT_118eeee8 (*(int * *)&g_pBrDik18ABDD0)
#define DAT_118eeef0 (*(int *)((char *)&g_brFfb + 0x4)) /* BR_LP64_BYTE_VIEW */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br100BCBE8 (*(int32_t *)&g_CBE8)
#define g_br100BCBF4 g_br0BCBF4
#define g_br100BCBF8 (*(int32_t *)&DAT_100bcbf8)
#define g_br100BCBFC DAT_100bcbfc
#define g_br100BCC04 (*(int32_t *)&DAT_100bcc04)
#define g_br10226A44 g_brRaceTick
#define g_br10226A48 g_brRaceNet
#define g_br10226A50 (*(int32_t *)&DAT_10226a50)
#define g_br105CCB5C g_BrX06909B4
#define g_br105CCB88 (DAT_105ccb68[8])
#define g_br10AF21B0 (*(int32_t *)((char *)&g_aBrRaceCar + 0xFA8)) /* BR_LP64_BYTE_VIEW */
#define g_br118EEEE0 (*(int32_t *)&DAT_118eeee0)
#define g_br118EEEE4 (*(int32_t *)&DAT_118eeee4)
#define g_brB4E1D0 (*(int32_t *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_brCfgGameMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_brCfgRunBenchmark (*(int32_t *)&g_demoFlag)
#define g_brInJoyCur (*(int32_t *)&DAT_118eebd0)
#define g_brInMouse (*(BrInMouse (*)[])&g_18ABD38)
#define g_brInMouseCur (*(int32_t *)&g_18ABD80)
#define g_brInputFrame (*(int32_t *)((char *)&g_brFfb + 0x8)) /* BR_LP64_BYTE_VIEW */
#define g_brInputLast (*(int32_t *)&g_BrX18ABAD0)
#define g_brMouseSens (*(int32_t *)((char *)&g_aBrRaceCar + 0xE98)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrDik18ABDD0 (*(BrInDiDev * *)&g_pBrDik18ABDD0)
#define g_pBrInDiRoot (*(BrInDiRoot * *)&g_pBrAA2E80)
#define g_pBrInJoyDev (*(BrInDiDev * *)&g_brFfb)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub10004F20 BrNetLockSet22AAA8
#define BrSub10004F50 BrNetLockSetIfZero22AAF4
#define BrSub10063A40 BrSet_1006AA90
