/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_aBrCtlNameJoy (*(BrCfgRec (*)[134])&g_aBrCtlNameJoy)
#define g_aBrCtlNameKey (*(const BrCfgRec (*)[120])&g_aBrCtlNameKey)
#define g_aBrCtlNameMouse (*(BrCfgRec (*)[10])&g_aBrCtlNameMouse)
#define g_tab (*(struct Dim (*)[7])&g_tab)
