/* generated by ports/64b/tools/unify.py */
#define g_br18ABDBC (*(int32_t *)&DAT_118eeed4)
#define g_brB4E1D0 (*(int32_t *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_brB4E1E0 (*(int32_t *)&DAT_10b71540)
#define g_brFlag6909E0 (*(int *)&DAT_105ccb68[8])
#define g_brP680584 (*(void * *)&g_brOwner5BC72C)
