/* generated by ports/64b/tools/unify.py */
#define BrG_6C65EC (*(int32_t *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_f6C2CFC g_brRaceFlyStep
#define g_tab (*(struct Dim (*)[7])&g_tab)
