/* generated by ports/64b/tools/unify.py */
#define DAT_1035f7d8 (*(uint32_t * *)&DAT_1035f7d8)
#define DAT_106e7290 BrG_6C0200
#define DAT_106e72f0 BrG_6C0260
#define DAT_106e7710 g_BrGfxPtr
#define DAT_106e7718 BrG_6C0688
#define DAT_106e78f0 (*(float (*)[16])&g_BrDrawCombined)
#define DAT_106e7930 (*(float (*)[16])&g_BrDrawScale)
#define DAT_106e86a4 BrG_6C1614
#define DAT_106e9d88 g_pBr63Race
#define DAT_106ec798 (*(int *)&g_BrEnvSection)
#define DAT_106ed520 g_BrCamera
#define DAT_106ed69c (*(int *)((char *)&g_aBrEntRecs + 0x6C)) /* byte view: the object holds no pointers */
#define DAT_106ed6a8 (*(int *)((char *)&g_aBrEntRecs + 0x78)) /* byte view: the object holds no pointers */
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_106eed38 g_BrDrawTrackFlags
#define DAT_1184c470 (*(uint32_t *)&DAT_1184c470)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_1000dc00 BrPolyClipTri
#define FUN_10018990 BrFtolArg
#define FUN_1002f26b BrLogSet
#define FUN_100344d0 br_dl_normalise
#define FUN_10034840 BrVec3LenXY
#define FUN_10034af0 BrMtxMul
