/* generated by ports/64b/tools/unify.py */
#define DAT_10077750 PTR_FUN_10077750
#define DAT_10396f08 g_aBr39B720
#define g_AA2858 (*(int32_t *)&DAT_10ac5bb0)
#define g_AA2870 g_wAA2870
#define g_AA28D8 (*(int32_t *)&g_5C30)
/* functions */
#define operator_delete BrOperatorDelete
