/* generated by ports/64b/tools/unify.py */
#define DAT_10273308 (*(int *)((char *)&g_BrDPlay + 0x4)) /* BR_LP64_BYTE_VIEW */
#define DAT_1035e710 (*(uint16_t (*)[])&g_BrVisSpans)
#define DAT_106eed3c g_BrSpanCount
