/* generated by ports/64b/tools/unify.py */
#define DAT_100a7514 BrGbiRectG_A7514
#define DAT_100a7518 BrGbiRectG_A7518
#define DAT_106b7ab8 (*(void (**)(void))&BrGlFlipHook)
/* functions */
#define FUN_10001000 BrAdler32
#define FUN_10003320 BrChkFReadOpen
#define FUN_100034c0 BrChkFRead
#define FUN_100035e0 BrChkFClose
#define FUN_100283c0 BrTex3dDownloadAt
