/* generated by ports/64b/tools/unify.py */
#define BrG_6C65EC (*(int32_t *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define DAT_100a7514 BrGbiRectG_A7514
#define DAT_100a7518 BrGbiRectG_A7518
#define DAT_100a9ec0 (*(char *)&DAT_100a9ec0)
#define DAT_100a9f00 BrG_0AA770
#define DAT_100aa044 g_brMode0AA8B4
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_104b16a4 (*(int *)&g_brFadeA4)
#define DAT_104b16a8 (*(int *)&g_brFadePos2)
#define DAT_104b16b0 (*(int *)&g_brFadePos)
#define DAT_104b16b4 (*(int *)&g_brFadeB4)
#define DAT_106b7c78 (*(unsigned char *)&g_BrDrawByte78)
#define DAT_106b7c80 (*(unsigned char *)&g_BrDrawByte80)
#define DAT_106e7290 (*(unsigned char *)&BrG_6C0200)
#define DAT_106e72e8 (*(int *)&g_BrEnvOthermode)
#define DAT_106e72f0 (*(unsigned char *)&BrG_6C0260)
#define DAT_106e7700 (*(float *)&g_BrVisLightDefault)
#define DAT_106e7704 (*(float *)((char *)&g_BrVisLightDefault + 0x4)) /* byte view: the object holds no pointers */
#define DAT_106e7708 (*(float *)((char *)&g_BrVisLightDefault + 0x8)) /* byte view: the object holds no pointers */
#define DAT_106e7710 (*(BrDlCmd * *)&g_BrGfxPtr)
#define DAT_106e7714 g_scrW4
#define DAT_106e7718 (*(int *)&BrG_6C0688)
#define DAT_106e79f0 (*(unsigned char *)&BrG_6C0960)
#define DAT_106e79f8 (*(unsigned char *)&BrG_6C0968)
#define DAT_106e8610 (*(unsigned char *)&BrG_6C1580)
#define DAT_106e86a4 (*(unsigned char *)&BrG_6C1614)
#define DAT_106e9a2c (*(int *)&g_brRaceCueBase)
#define DAT_106e9d88 (*(BrFogCam * *)&g_pBr63Race)
#define DAT_106ea3ec (*(unsigned char *)&BrG_6C335C)
#define DAT_106ed520 (*(BrFogSrc * *)&g_BrCamera)
#define DAT_106ed64c (*(unsigned char *)((char *)&g_aBrEntRecs + 0x1C)) /* byte view: the object holds no pointers */
#define DAT_106ed670 (*(int *)((char *)&g_aBrEntRecs + 0x40)) /* byte view: the object holds no pointers */
#define DAT_106ed674 (*(int *)((char *)&g_aBrEntRecs + 0x44)) /* byte view: the object holds no pointers */
#define DAT_106ed678 (*(int *)((char *)&g_aBrEntRecs + 0x48)) /* byte view: the object holds no pointers */
#define DAT_106ed67c (*(int *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define DAT_106ed684 (*(int *)((char *)&g_aBrEntRecs + 0x54)) /* byte view: the object holds no pointers */
#define DAT_106ed688 (*(int *)((char *)&g_aBrEntRecs + 0x58)) /* byte view: the object holds no pointers */
#define DAT_106ed68c (*(int *)((char *)&g_aBrEntRecs + 0x5C)) /* byte view: the object holds no pointers */
#define DAT_106ed6a8 (*(int *)((char *)&g_aBrEntRecs + 0x78)) /* byte view: the object holds no pointers */
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_106ed6e8 (*(int *)((char *)&g_aBrEntRecs + 0xB8)) /* byte view: the object holds no pointers */
#define DAT_106ed6ec (*(int *)((char *)&g_aBrEntRecs + 0xBC)) /* byte view: the object holds no pointers */
#define DAT_106ed6f0 (*(int *)((char *)&g_aBrEntRecs + 0xC0)) /* byte view: the object holds no pointers */
#define DAT_106ed6f4 (*(int *)((char *)&g_aBrEntRecs + 0xC4)) /* byte view: the object holds no pointers */
#define DAT_106ed6f8 (*(int *)((char *)&g_aBrEntRecs + 0xC8)) /* byte view: the object holds no pointers */
#define DAT_10b73530 (*(void (**)(int))&DAT_10b73530)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrFrameBegin BrFrameBeginDl
#define FUN_10008d60 BrPodNop
#define FUN_100192d0 BrS17BankFlip
#define FUN_1001cf90 BrRdpSetCombineLERP
#define FUN_1002a8d7 BrRenderCountersReset
#define FUN_1002bf50 BrSub_1003289F
#define FUN_1002f26b BrLogSet
#define FUN_100344d0 br_dl_normalise
#define FUN_10034720 BrVec3DistXY
#define FUN_100385e0 BrStubTrue
#define FUN_10059f00 BrTickAdd_10078C10
#define FUN_100625f0 BrGfx69580
#define _ftol ftol
