/* generated by ports/64b/tools/unify.py */
#define DAT_10ac0808 (*(int *)&g_brKeyCount)
#define DAT_1186c960 (*(int *)&g_brTexLowThreshold)
/* functions */
#define FUN_10003320 BrChkFReadOpen
#define FUN_10003530 BrChkFReadLine
#define FUN_100035e0 BrChkFClose
#define FUN_10003680 BrChkFileExists
