/* generated by ports/64b/tools/unify.py */
#define DAT_100a7514 BrGbiRectG_A7514
#define DAT_100a7518 BrGbiRectG_A7518
#define DAT_105cccf8 BrGbiRectG_5CCCF8
#define DAT_105ccd40 (*(unsigned char *)&BrGlFillR)
#define DAT_105ccd44 BrGbiRectG_5CCD44
#define DAT_105ccfd8 (*(unsigned char *)&BrGlFillG)
#define DAT_105ccfe0 (*(int *)&BrGlClipMaxY)
#define DAT_105cd9f4 BrGbiRectG_5CD9F4
#define DAT_105cda00 g_pClipFree
#define DAT_105ce208 (*(unsigned char *)&BrGlFillA)
#define DAT_105ce2d0 BrGbiRectG_5CE2D0
#define DAT_105d17a0 (*(unsigned char *)&BrGlFillB)
#define DAT_105d17a4 BrGbiRectG_5D17A4
#define DAT_105d17b4 BrGbiRectG_5D17B4
#define DAT_105d17b8 (*(int *)&BrGlClipMaxX)
#define DAT_105d17bc (*(int *)&BrGlClipMinX)
#define DAT_105d17c0 (*(int *)&BrGlClipMinY)
#define DAT_105d17d4 (*(int *)&BrGlBlendLatch)
#define DAT_106e7710 (*(int * *)&g_BrGfxPtr)
#define DAT_106e8204 (*(int *)&BrG_6C1174)
#define DAT_106ea3f4 (*(int *)&g_brRaceBeginDifficulty)
#define DAT_106ed674 (*(int *)((char *)&g_aBrEntRecs + 0x44)) /* byte view: the object holds no pointers */
#define DAT_106ed6e4 (*(int *)((char *)&g_aBrEntRecs + 0xB4)) /* byte view: the object holds no pointers */
#define _DAT_106ed368 DAT_106ed368
#define _DAT_106ed648 (*(int *)((char *)&g_aBrEntRecs + 0x18)) /* byte view: the object holds no pointers */
#define g_brDlDepthFn (*(int32_t *)&BrGlDepthFuncShadow)
#define g_brDlFogSel (*(int32_t *)&BrGbiRectG_5CDA04)
#define g_brDlGeoNew (*(uint32_t *)&BrGbiRectG_5D17C8)
#define g_brDlGeoOld (*(uint32_t *)&DAT_105d17cc)
#define g_pBrDlTri1Slot (*(void * *)((char *)&g_brGbi0A79F0 + 0x2FC)) /* BR_LP64_BYTE_VIEW */
#define g_pBrDlTri2Slot (*(void * *)((char *)&g_brGbi0A79F0 + 0x2C4)) /* BR_LP64_BYTE_VIEW */
#define g_pBrDlVtxSlot (*(void * *)((char *)&g_brGbi0A79F0 + 0x10)) /* BR_LP64_BYTE_VIEW */
/* functions */
#define BrDlTri1NoZ BrDlCmdTri1NoZ
#define BrDlTri1NoZFlat BrDlCmdTri1Flat
#define BrDlTri1Z BrDlCmdTri1
#define BrDlTri1ZFlat BrDlCmdTri1FlatZ
#define BrDlTri2NoZ BrDlCmdTri2NoZ
#define BrDlTri2NoZFlat BrDlCmdTri2Flat
#define BrDlTri2Z BrDlCmdTri2
#define BrDlTri2ZFlat BrDlCmdTri2FlatZ
#define BrDlVtxPlain BrDlCmdVtx
#define BrGlSetCullMode grFogMode
#define BrGlSetCullSide grCullMode
#define BrGlSetDepthFn grDepthBufferFunction
#define FUN_1001e380 BrGlRectFill
#define FUN_1002bf50 BrSub_1003289F
