/* generated by ports/64b/tools/unify.py */
#define DAT_100a7500 g_brFadeTgtB
#define DAT_100a7504 g_brFadeCurB
#define DAT_100a7508 g_brFadeTgtA
#define DAT_100a750c g_brFadeCurA
#define DAT_104b16b8 (*(float *)&g_brCursor575510)
#define DAT_104b16c0 (*(float *)&g_brCursor575518)
#define DAT_104b16cc (*(int *)&g_brFadeKick)
#define DAT_104b16d0 (*(int *)&g_brFadeKickB)
#define DAT_104b16d4 (*(int *)&g_brFadeKickA)
#define DAT_104b16d8 (*(int *)&g_brFadeBounce)
#define DAT_106e9d8c g_brRaceFlyStep
#define _DAT_104abb24 (*(float *)&g_brRace4ABB24)
#define kF300_S_S537 (*(float *)&kF300)
