/* generated by ports/64b/tools/unify.py */
#define DAT_1186c950 BrGbiRectG_186C950
#define DAT_1186c954 BrGbiRectG_186C954
#define DAT_118ec988 BrGbiRectG_18EC988
#define DAT_118ed198 BrGbiRectG_18ED198
/* functions */
#define FUN_100215c0 BrGbiCall10021560
