/* generated by ports/64b/tools/unify.py */
#define DAT_100b2f00 (*(int *)&g_brRaceNDriver)
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_106e7710 (*(unsigned int * *)&g_BrGfxPtr)
#define DAT_106ea360 g_BrMtxSlot
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
/* functions */
#define FUN_1001cf90 BrRdpSetCombineLERP
