/* generated by ports/64b/tools/unify.py */
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_118ed1d4 (*(void * (**)(int, unsigned int *))&DAT_118ed1d4)
#define g_AC300 (*(int *)&g_AC300)
#define g_f6C2CFC g_brRaceFlyStep
#define g_i0AC300 (*(int *)&g_AC300)
#define g_i6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_i6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
/* functions */
#define BrSub100088B0 M8A90
#define FUN_1006e1d0 BrTexQueuePush
