/* generated by ports/64b/tools/unify.py */
#define DAT_105ccc78 (*(BrDlLight (*)[2])&DAT_105ccc78)
#define DAT_105ce318 g_aBrDlVtxPool
#define DAT_1186c950 BrGbiRectG_186C950
#define DAT_118ed198 BrGbiRectG_18ED198
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10022070 br_dl_project
#define FUN_10022120 BrDlsClipCodes
#define FUN_10022AC0 br_dl_light_vertex
#define FUN_100344D0 br_dl_normalise
