/* generated by ports/64b/tools/unify.py */
#define BrG_6C0258 g_BrEnvOthermode
#define BrG_6C0680 g_BrGfxPtr
#define BrG_6C65EC (*(int32_t *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define BrG_6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define g_BrDrawWheelAlt (*(int32_t *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define g_BrFpsScreenW BrGbiRectG_A7514
