/* generated by ports/64b/tools/unify.py */
#define DAT_11778800 (*(uint16_t (*)[4])((char *)&g_brCrPlane + 0x10)) /* byte view: the object holds no pointers */
#define g_brNetLastFull (*(BrCarState *)((char *)&g_aBrNetSlot + 0x3E98)) /* BR_LP64_BYTE_VIEW */
