/* generated by ports/64b/tools/unify.py */
#define DAT_105ce2d0 BrGbiRectG_5CE2D0
#define DAT_105d17a4 BrGbiRectG_5D17A4
#define DAT_105d17ac (*(int *)&BrGlCombineW0)
#define DAT_105d17b0 (*(int *)&BrGlCombineW1)
#define DAT_105d17b4 BrGbiRectG_5D17B4
#define _DAT_105cd9f0 BrGlPrimA
#define g_brDlTexScaleS DAT_118ed1a4
#define g_brDlTexScaleT DAT_118ed1a8
/* functions */
#define BrDlClipTri BrDlClipTriZ
#define FUN_1001e7a0 BrGlSetCombine
