/* generated by ports/64b/tools/unify.py */
#define BrG_6C65EC (*(int32_t *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define DAT_106e9d8c (*(float (*)[])&g_brRaceFlyStep)
#define DAT_10ac0c38 (*(int *)&g_iPfxFree)
#define DAT_10ac0c40 (*(unsigned short *)&g_iPfxHeadB0)
#define DAT_10ac0c48 (*(char *)&g_aPfxRec)
#define DAT_10ac0c54 (*(char *)((char *)&g_aPfxRec + 0xC)) /* byte view: the object holds no pointers */
#define DAT_10ac0c60 (*(char *)((char *)&g_aPfxRec + 0x18)) /* byte view: the object holds no pointers */
#define DAT_10ac0c64 (*(char *)((char *)&g_aPfxRec + 0x1C)) /* byte view: the object holds no pointers */
#define DAT_10ac0c66 (*(char *)((char *)&g_aPfxRec + 0x1E)) /* byte view: the object holds no pointers */
#define DAT_10ac0c67 (*(char *)((char *)&g_aPfxRec + 0x1F)) /* byte view: the object holds no pointers */
#define g_f6C2CFC g_brRaceFlyStep
#define g_i0AC300 (*(int *)&g_AC300)
#define g_i6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_i6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
/* functions */
#define BrSub10034560 BrVec3Sub
#define BrSub10034660 BrVec3MulAdd
#define BrSub100347F0 BrVec3Length
#define _ftol ftol
