/* generated by ports/64b/tools/unify.py */
#define DAT_105ccfe0 (*(int *)&BrGlClipMaxY)
#define DAT_105d17b8 (*(int *)&BrGlClipMaxX)
#define _DAT_105ccd48 DAT_105ccd48
#define _DAT_105ccfdc DAT_105ccfdc
#define _DAT_105cd9f8 DAT_105cd9f8
#define _DAT_105cd9fc DAT_105cd9fc
#define g_Br0A81C0 (*(int32_t *)&BrGbiRectG_A7514)
#define g_Br0A81C4 (*(int32_t *)&BrGbiRectG_A7518)
#define g_BrAA33B4 BrGlNavMaxY
#define g_BrAA33B8 BrGlNavMaxX
#define g_BrFpsScreenH BrGbiRectG_A7518
#define g_BrFpsScreenW BrGbiRectG_A7514
