/* generated by ports/64b/tools/unify.py */
#define DAT_10396eb8 (*(float *)&DAT_10396eb8)
#define DAT_106e7710 (*(uint32_t_ * *)&g_BrGfxPtr)
#define DAT_106ec798 (*(int *)&g_BrEnvSection)
/* functions */
#define _ftol ftol
