/* generated by ports/64b/tools/unify.py */
#define DAT_100a7518 (*(int32_t *)&BrGbiRectG_A7518)
#define DAT_105d17c8 BrGbiRectG_5D17C8
#define g_br4B035C DAT_104abb44
#define g_br4BC198 DAT_105ccfdc
#define g_brAA26F4 (g_aBrAA26F4[0])
#define g_brAA26F5 (g_aBrAA26F4[1])
#define g_brGbi0A79E8 (*(uint32_t *)&BrGbiRectG_A9A54)
#define g_brGbi4C1694 BrGlRectMode
#define g_brGbi4C5174 (*(uint32_t *)&BrGbiRectG_5D17C4)
/* functions */
#define BrGbiCall10020FA0 BrGlGbiCall
#define BrGbiCall100243D0 br_dl_skip
#define BrGbiGeoModeChanged BrDlVtxRoutine
