/* generated by ports/64b/tools/unify.py */
#define DAT_106ed668 (*(int *)((char *)&g_aBrEntRecs + 0x38)) /* byte view: the object holds no pointers */
#define DAT_106ed66c (*(int *)((char *)&g_aBrEntRecs + 0x3C)) /* byte view: the object holds no pointers */
/* functions */
#define FUN_100385e0 BrStubTrue
