/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100a9368 (*(const char * (*)[][8])((char *)&g_brRaceRules + 0x14)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_10273688 (*(int *)&g_BrDrawRefIndex)
#define DAT_10396f4c (*(uint8_t (*)[])((char *)&g_aBrSnap + 0x4)) /* BR_LP64_BYTE_VIEW */
#define DAT_10397950 (*(uint8_t (*)[])((char *)&g_aBrSnap + 0xA08)) /* BR_LP64_BYTE_VIEW */
#define DAT_103c2fd0 (*(uint8_t (*)[])((char *)&g_aBrSnap + 0x2C088)) /* BR_LP64_BYTE_VIEW */
#define DAT_103c302c (*(uint8_t (*)[])((char *)&g_aBrSnap + 0x2C0E4)) /* BR_LP64_BYTE_VIEW */
#define DAT_105bc768 (*(int *)&g_brRaceBeginSeqIdx)
#define DAT_105bc884 g_brRaceBeginSeqT
#define DAT_105ccb5c (*(int *)&g_BrX06909B4)
#define DAT_105ccb88 (*(int *)&DAT_105ccb68[8])
#define DAT_106e7714 g_scrW4
#define DAT_106e8a18 (*(uint8_t (*)[])&g_BrEnvFlagCount)
#define DAT_106e9a2c (*(int *)&g_brRaceCueBase)
#define DAT_106e9d88 (*(uint8_t * *)&g_pBr63Race)
#define DAT_106ed520 (*(BrCamObj * *)&g_BrCamera)
#define DAT_106ed528 (*(uint8_t (*)[])&g_BrEnvFlagIndices)
#define DAT_106ed698 (*(int *)((char *)&g_aBrEntRecs + 0x68)) /* byte view: the object holds no pointers */
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_106ed6bc (*(int *)((char *)&g_aBrEntRecs + 0x8C)) /* byte view: the object holds no pointers */
#define g_BrCarCount (*(int *)&g_BrCarCount)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brB4E708 (*(int *)&g_brItemIconCount)
#define g_brB4E70C (*(int *)&g_brRaceB71A6C)
#define g_brCViews g_brMode0AA8B4
#define g_brIView (*(int *)&g_BrEnvSection)
#define g_brRaceBeginStage g_5bc760
#define g_brRaceNDriver (*(int *)&g_brRaceNDriver)
#define g_brRaceNet (*(int *)&g_brRaceNet)
#define g_f6C2CFC g_brRaceFlyStep
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10014e00 BrHudDrawEntrants
#define FUN_1002af17 BrFrameFogEmit
#define FUN_1002b480 BrFrameTintSetup
#define FUN_1002cb49 BrTexAnimStep
#define FUN_1002cee9 BrFrameEnd
