/* generated by ports/64b/tools/unify.py */
#define DAT_100b8498 (*(int *)&s_level)
#define DAT_105e1828 (*(int *)&DAT_105e1828)
#define DAT_10ac67a4 (*(int *)((char *)&BrImgTintState + 0x4)) /* byte view: the object holds no pointers */
#define DAT_1186c988 (*(int *)&DAT_1186c988)
/* functions */
#define FUN_10023cb0 BrTexRgbaToArgb1555
#define FUN_100242e0 BrTexShiftFromSize
#define FUN_10024490 BrTexResample
#define FUN_1005a020 BrBmpRect4Get
#define FUN_1005a070 BrBmpGetHandle
#define FUN_1005a630 BrImgRegionHasKey
