/* generated by ports/64b/tools/unify.py */
#define BrG_6C7CB8 g_pBrRaceLapRec
#define g_BrFpsCountA (*(int32_t *)((char *)&g_brRaceRules + 0x4)) /* BR_LP64_BYTE_VIEW */
#define g_BrFpsGateA (*(int32_t *)((char *)&g_brRaceRules + 0x8)) /* BR_LP64_BYTE_VIEW */
#define g_BrFpsScreenH (*(int32_t *)&BrGbiRectG_A7518)
#define g_BrFpsScreenW (*(int32_t *)&BrGbiRectG_A7514)
/* functions */
#define BrTextAlignCentre BrSet_10019270
#define BrTextSetSize BrSetGlobal_ABB30
#define FUN_1006e590 BrNop6E590
