/* generated by ports/64b/tools/unify.py */
#define DAT_105ccb58 (*(int *)&g_brRaceHudA)
#define DAT_106e7710 g_BrGfxPtr
#define DAT_106e9d8c (*(int *)&g_brRaceFlyStep)
/* functions */
#define BrX1003563A BrAnimUpdate
