/* generated by ports/64b/tools/unify.py */
#define g_BrDrawWheelAlt (*(int32_t *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define g_BrFrameDelta g_brRaceFlyStep
#define g_BrTrackKind g_Br0B380C
#define g_BrTrailDim (*(int32_t *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_BrTrailNight (*(int32_t *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define g_brRacePaused g_BrX06909B4
#define g_brRaceReplay (DAT_105ccb68[8])
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define _ftol ftol
