/* generated by ports/64b/tools/unify.py */
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_106e72a8 g_BrProjMat
#define DAT_106e72e8 (*(int *)&g_BrEnvOthermode)
#define DAT_106e7710 (*(int * *)&g_BrGfxPtr)
#define DAT_106e7718 (*(int *)&BrG_6C0688)
#define DAT_106e78f0 g_BrDrawCombined
#define DAT_106e7930 g_BrDrawScale
#define DAT_106ed520 g_BrCamera
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_1184c478 (*(int *)&g_BrEnvTexDefault)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10010fb0 BrPanelDlBuild
#define FUN_10011300 BrPaceNoteEmit_10011300
