/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br0BD3E0 (*(int32_t *)&g_CBE8)
#define g_br0BD3E8 g_br100BCBF0
#define g_br0BD3F8 g_br100BCC00
#define g_brCViews (*(int32_t *)&g_brMode0AA8B4)
#define g_brF22AF1C g_brRaceBegin226A4C
#define g_brIView g_BrEnvSection
#define g_pBrHudRace (*(Br70Race * *)&g_pBr63Race)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub_10019250 BrClear_10019250
#define BrSub_10019260 BrTextFlag358Clear
#define BrSub_100192F0 BrSetGlobal_ABB30
#define BrSub_100193C0 BrFontMeasure
