/* generated by ports/64b/tools/unify.py */
#define BrG_0AA860 (*(void * *)&g_BrVisLightTemplate)
#define BrG_0AA868 (*(void * *)((char *)&g_BrVisLightTemplate + 0x8)) /* byte view: the object holds no pointers */
#define BrG_6C0258 g_BrEnvOthermode
#define BrG_6C0670 g_BrVisLightDefault
#define BrG_6C0680 g_BrGfxPtr
#define BrG_6C2CF8 (*(void * *)&g_pBr63Race)
#define BrG_6C6490 (*(void * *)&g_BrCamera)
#define BrG_6C65BC (*(uint8_t *)((char *)&g_aBrEntRecs + 0x1C)) /* byte view: the object holds no pointers */
#define BrG_6C65EC (*(int32_t *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define BrG_6C6614 (*(int32_t *)((char *)&g_aBrEntRecs + 0x74)) /* byte view: the object holds no pointers */
#define BrG_6C6618 (*(int32_t *)((char *)&g_aBrEntRecs + 0x78)) /* byte view: the object holds no pointers */
#define BrG_6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define BrG_6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define g_BrDrawLodFloor (*(int32_t *)((char *)&g_aBrEntRecs + 0x90)) /* byte view: the object holds no pointers */
#define g_BrDrawSuppress (*(int32_t *)&g_BrDPlay)
#define g_BrDrawView g_BrCurMat
#define g_BrDrawWheelAlt (*(int32_t *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brCfgGameMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_brRaceBeginNTexSet (*(int32_t *)&g_brMode0AA8B4)
#define g_f6C2CFC g_brRaceFlyStep
#define g_i0AC300 (*(int *)&g_AC300)
#define g_i6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_i6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrCarDrawWheels_raw BrCarDrawWheels
#define BrFogFactorAtPoint BrPointDepthFrac
#define BrVec3NormaliseGuard br_dl_normalise
#define _ftol ftol
