/* generated by ports/64b/tools/unify.py */
#define g_br094294 (*(int32_t *)&g_id)
#define g_brAD0854 (*(uint8_t (*)[3])((char *)&g_aBrRaceCar + 0x29AC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
