/* generated by ports/64b/tools/unify.py */
#define BrG_6C65EC (*(int32_t *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100aa044 g_brMode0AA8B4
#define DAT_100bcdcc (*(int *)&g_BrCamDemo)
#define DAT_105ccb88 (*(int *)&DAT_105ccb68[8])
#define DAT_11773698 (*(BrCamPlane (*)[][150])&DAT_11773698)
#define DAT_11778800 (*(unsigned short (*)[])((char *)&g_brCrPlane + 0x10)) /* byte view: the object holds no pointers */
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
#define g_i0AC300 (*(int *)&g_AC300)
#define g_i6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_i6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
/* functions */
#define BrSub10034660 BrVec3MulAdd
#define BrSub100347F0 BrVec3Length
#define FUN_10034310 BrVec3Dot
#define FUN_10034390 BrVec3ScaleBy
#define FUN_10034560 BrVec3Sub
#define FUN_100345c0 BrVec3Add
#define FUN_10034660 BrVec3MulAdd
#define FUN_10034760 BrVec3Dist
#define FUN_100347f0 BrVec3Length
#define FUN_10034fc0 BrTriContainsPoint
#define FUN_100686d0 BrCollGridCellAcquire
