/* generated by ports/64b/tools/unify.py */
#define DAT_100a7514 BrGbiRectG_A7514
#define DAT_100a7518 BrGbiRectG_A7518
#define DAT_100aad0c (*(int *)&g_aBrUiSprite[4])
#define DAT_100aad1c (*(int *)&g_aBrUiSprite[20])
#define DAT_10ac53e8 (*(int *)&g_img)
#define DAT_10ac53ec (*(int *)((char *)&g_img + 0x4)) /* BR_LP64_BYTE_VIEW */
#define DAT_10ac5c5c g_brPAA29B8
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
