/* generated by ports/64b/tools/unify.py */
#define DAT_10226e80 g_226e80
#define DAT_105e17fc (*(int *)&g_brTexScanState)
#define DAT_106b7a94 (*(int *)&g_brTexScanMaxTile)
#define DAT_106b7a9c g_brTexScanRunEnd
