/* generated by ports/64b/tools/unify.py */
#define DAT_105ccc78 (*(BrDlLight (*)[2])&DAT_105ccc78)
#define DAT_105ce2d0 BrGbiRectG_5CE2D0
#define DAT_105ce318 g_aBrDlVtxPool
#define DAT_105d17a4 BrGbiRectG_5D17A4
#define DAT_105d17b4 BrGbiRectG_5D17B4
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10022070 br_dl_project
#define FUN_10022120 BrDlsClipCodes
#define FUN_100344D0 br_dl_normalise
