/* generated by ports/64b/tools/unify.py */
#define DAT_100a6b80 g_aBr63Prefix
#define DAT_100a7514 (*(int32_t *)&BrGbiRectG_A7514)
#define DAT_100a7518 (*(int32_t *)&BrGbiRectG_A7518)
#define DAT_100aa044 (*(int32_t *)&g_brMode0AA8B4)
#define DAT_100b2f04 g_BrCarCount
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_10226a4c g_brRaceBegin226A4C
#define DAT_104abb20 (*(const char * *)&DAT_104abb20)
#define DAT_104abb60 (DAT_104abb60[0])
#define DAT_104add38 g_BrEnvSegCount
#define DAT_104add40 (*(float *)&g_vPfxDrift)
#define DAT_104add44 (*(float *)((char *)&g_vPfxDrift + 0x4)) /* byte view: the object holds no pointers */
#define DAT_104add48 (*(float *)((char *)&g_vPfxDrift + 0x8)) /* byte view: the object holds no pointers */
#define DAT_105ccb5c g_BrX06909B4
#define DAT_106b7c78 (*(unsigned char *)&g_BrDrawByte78)
#define DAT_106e7290 (*(unsigned char *)&BrG_6C0200)
#define DAT_106e72e8 (*(int *)&g_BrEnvOthermode)
#define DAT_106e72f0 (*(unsigned char *)&BrG_6C0260)
#define DAT_106e7710 (*(BrGfxCmd * *)&g_BrGfxPtr)
#define DAT_106e7714 (*(int32_t *)&g_scrW4)
#define DAT_106e78f0 g_BrDrawCombined
#define DAT_106e8204 (*(int *)&BrG_6C1174)
#define DAT_106e86a4 (*(unsigned char *)&BrG_6C1614)
#define DAT_106e9a2c g_brRaceCueBase
#define DAT_106e9d88 (*(unsigned char * *)&g_pBr63Race)
#define DAT_106e9d8c g_brRaceFlyStep
#define DAT_106ea360 g_BrMtxSlot
#define DAT_106ea3f4 (*(int *)&g_brRaceBeginDifficulty)
#define DAT_106ec798 g_BrEnvSection
#define DAT_106ed520 (*(BrSceneCam * *)&g_BrCamera)
#define DAT_106ed67c (*(int32_t *)((char *)&g_aBrEntRecs + 0x4C)) /* byte view: the object holds no pointers */
#define DAT_106ed698 (*(int *)((char *)&g_aBrEntRecs + 0x68)) /* byte view: the object holds no pointers */
#define DAT_106ed6a8 (*(int *)((char *)&g_aBrEntRecs + 0x78)) /* byte view: the object holds no pointers */
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_106eed10 (*(int *)&DAT_106eed10)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_f6C2CFC g_brRaceFlyStep
#define g_hudSpriteTable (*(const uint8_t (*)[])&g_ab0C12A0)
#define g_out g_BrGfxPtr
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrHudDrawSplitList BrHudDrawSplitTimes
#define BrMat4Copy BrGuMtxStore
#define BrSub_100020D0 BrTimeFormat
#define BrSub_10019260 BrTextFlag358Clear
#define BrSub_10019270 BrSet_10019270
#define BrSub_100192F0 BrSetGlobal_ABB30
#define BrSub_1002B2A0 BrFadeIsClosing
#define BrSub_1002F900 BrRdpSetCombineLERP
#define BrSub_10031140 BrMat4Translate
#define BrSub_10031688 BrGfxFillRect
#define BrSub_1003407D BrCamMatrixSetupOrtho
#define _ftol ftol
