/* generated by ports/64b/tools/unify.py */
#define BrGlCombineDecal BrGbiRectG_5CDA04
#define BrGlDlSlot04 (*(void * *)((char *)&g_brGbi0A79F0 + 0x10)) /* BR_LP64_BYTE_VIEW */
#define BrGlHwParamA (DAT_105ccb68[26])
#define BrGlPrimB BrGbiRectG_5CE2D0
#define BrGlPrimG BrGbiRectG_5D17B4
#define BrGlPrimR BrGbiRectG_5D17A4
#define BrGlScreenH (*(int32_t *)&BrGbiRectG_A7518)
#define BrGlScreenW (*(int32_t *)&BrGbiRectG_A7514)
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
/* functions */
#define BrDlLightSetup_10021C70 BrDlVtxLit
#define BrDlLightSetup_100221D0 BrDlVtxLitDecal
#define BrGl_1001DD80 BrGlideResOpen
#define _ftol ftol
