/* generated by ports/64b/tools/unify.py */
#define DAT_10697a58 (*(int *)&DAT_10697a58)
#define DAT_10697a5c (*(int *)&DAT_10697a5c)
#define DAT_106b7a7c (*(int *)&g_brTexScan575414)
#define DAT_118ed19c (*(void (**)(void))&g_pfn18AA084)
#define DAT_118ed1bc (*(void (**)(void))&g_BrDrawModelDlHook)
#define DAT_118ed1c0 (*(void (**)(void))&g_18ED1C0)
#define DAT_118ed1c4 (*(void (**)(void))&g_pfn18ED1C4)
#define DAT_118ed1c8 (*(void (**)(void))&g_pfn18AA0B0)
#define DAT_118ed1cc (*(void (**)(void))&DAT_118ed1cc)
#define DAT_118ed1d0 (*(void (**)(void))&DAT_118ed1d0)
#define DAT_118ed1d8 (*(void (**)(void))&g_BrGfxSubmit)
#define DAT_118ed1dc (*(void (**)(void))&g_pfn18AA0C4)
#define DAT_118ed1e0 (*(void (**)(void))&g_pfn18AA0C8)
#define DAT_118ed1e8 (*(void (**)(void))&g_18ED1E8)
#define g_brTexTmuCount (DAT_105ccb68[26])
/* functions */
#define FUN_10023d20 BrTex3dRecCopyHead
#define FUN_10024e60 BrTex3dExpandInto
#define FUN_100272f0 BrTex3dCreate
#define FUN_10027f00 BrGbiBlit
#define FUN_100284e0 BrTex3dMakeCurrent
#define FUN_100285e0 BrTex3dReDownload
#define FUN_10028620 BrTexSlotFetchPixels
#define FUN_100287e0 BrTex3dReconvert
#define FUN_10028820 BrGbiTexScanRun
#define FUN_100297f0 BrGbiTexCreate
#define FUN_100299a0 BrTexInstallRecords
#define FUN_10029c70 BrGbiSolidTexBuild
#define FUN_10029cd0 BrTex3dFreeAll
#define FUN_1006e180 BrMutexCreateAA0A0
#define FUN_10072a14 grTexMinAddress
#define FUN_10072a1a grTexMaxAddress
