/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5bb4 g_5BB4
#define DAT_10ac5de4 (*(int *)&g_BrDikEdge[1])
#define DAT_10ac5e50 (*(int *)&g_BrDikEdge[28])
#define DAT_10ac5ecc (*(int *)&g_BrDikEdge[59])
#define DAT_10ac5ed0 (*(int *)&g_BrDikEdge[60])
#define DAT_10ac5ed4 (*(int *)&g_BrDikEdge[61])
#define DAT_10ac5ed8 (*(int *)&g_BrDikEdge[62])
#define DAT_10ac6050 (*(int *)&g_BrDikEdge[156])
#define g_brAA2854 g_track
#define g_brAA33E4 DAT_10ac6744
/* functions */
#define FUN_10037040 BrSub1003D9A0
#define FUN_10037720 BrInputAnyActive
#define FUN_10054360 BrCharMapLookup
#define FUN_10058380 BrSprFontDraw
#define FUN_1006ba60 BrSub10072AF0
#define _ftol ftol
