/* generated by ports/64b/tools/unify.py */
#define DAT_105cda00 g_pClipFree
#define DAT_105ce310 (*(int32_t *)&DAT_105ce2e8[10])
#define g_brDlTexScaleS DAT_118ed1a4
#define g_brDlTexScaleT DAT_118ed1a8
