/* generated by ports/64b/tools/unify.py */
#define DAT_106e7710 (*(int * *)&g_BrGfxPtr)
#define g_br4B035C DAT_104abb44
#define g_br4B0360 g_4B0360
#define g_brAA26F4 (g_aBrAA26F4[0])
#define g_brAA26F5 (g_aBrAA26F4[1])
/* functions */
#define _ftol ftol
