/* generated by ports/64b/tools/unify.py */
#define DAT_106e7710 g_BrGfxPtr
#define DAT_106e7714 g_scrW4
#define DAT_106e9a2c (*(int *)&g_brRaceCueBase)
#define DAT_106ed674 (*(int *)((char *)&g_aBrEntRecs + 0x44)) /* byte view: the object holds no pointers */
