/* generated by ports/64b/tools/unify.py */
#define DAT_105b76f0 (*(int *)&g_brRca67B548)
#define DAT_105b76f4 (*(int *)&g_brRca67B54C)
#define DAT_105b96f8 (*(int *)&g_67D550)
#define g_br67B548 (*(int *)&g_brRca67B548)
#define g_br67B550 DAT_105b76f8
