/* generated by ports/64b/tools/unify.py */
#define DAT_100b8498 (*(int *)&s_level)
#define DAT_105ccbd0 (*(int *)&DAT_105ccb68[26])
#define DAT_105d17ec (*(int *)&DAT_105d17ec)
#define DAT_105e17fc (*(int *)&g_brTexScanState)
#define DAT_105e1828 (*(int *)&DAT_105e1828)
#define DAT_10697840 (*(BrTexTile40 (*)[])&g_brTexScanTiles)
#define DAT_10697a64 g_brTexScanRunStart
#define DAT_106b7a94 (*(int *)&g_brTexScanMaxTile)
#define DAT_106b7a98 g_brTexScanSrcSeen
#define DAT_106b7a9c g_brTexScanRunEnd
#define DAT_106b7c7c g_brRcaBlob
#define DAT_1186c968 (*(int (*)[])&g_BrX1829850)
#define DAT_1186c988 (*(int *)&DAT_1186c988)
#define DAT_118ed1b4 g_18ED1B4
#define PTR_DAT_100a9e58 (*(void * *)&DAT_100a9e58)
#define _DAT_10697a48 DAT_10697a48
#define _DAT_10697a50 DAT_10697a50
/* functions */
#define FUN_10001000 BrAdler32
#define FUN_100242e0 BrTexShiftFromSize
#define FUN_10024490 BrTexResample
#define FUN_100250d0 BrTex3dExpand
#define FUN_10027220 BrTexFormatCode
#define FUN_10027290 BrGbiSizeShift
#define FUN_100283c0 BrTex3dDownloadAt
#define FUN_10028BB0 BrTex3dRegister
#define FUN_10029290 BrTexSizeFromShiftAspect
#define FUN_100306d0 BrPendListAdd
#define FUN_10030710 BrDevRecMatch
#define FUN_10030fd0 BrKeyTableFind
#define FUN_1005a070 BrBmpGetHandle
#define FUN_1006e1a0 BrMutexCloseAA0A0
