/* generated by ports/64b/tools/unify.py */
#define DAT_104ab4e8 g_brRbB4E8
#define DAT_104ab4ec g_brRbB4EC
#define DAT_104ab500 g_brRbB500
#define g_aBrRbCar (*(BrRbCar (*)[5])&g_aBrSnap)
#define g_aBrSnapLocked (*(int32_t (*)[5])&g_aBrRbPerCar)
#define g_brCfgInterpolate (*(int32_t *)&DAT_100a5eac)
#define g_brRaceBeginLimitOn (*(int *)&g_brRaceBeginLimitOn)
#define g_brRaceNCar g_BrCarCount
#define g_brSnapCur (*(int32_t *)&g_brRbB4EC)
#define g_brSnapFrames (*(int32_t *)&g_brRbB4F0)
#define g_brSnapFrom (*(int32_t *)&g_brRbB4FC)
#define g_brSnapOrigin (*(float *)&g_brRb6F24)
#define g_brSnapPrev (*(int32_t *)&g_brRbB500)
#define g_brSnapT0 (*(int32_t *)&g_brRbB4F4)
#define g_brSnapTo (*(int32_t *)&g_brRb6F44)
#define g_f6C2CFC g_brRaceFlyStep
