/* generated by ports/64b/tools/unify.py */
#define DAT_100a7514 BrGbiRectG_A7514
#define DAT_100a7518 BrGbiRectG_A7518
#define DAT_104add38 (*(int *)&g_BrEnvSegCount)
#define DAT_104af547 (*(unsigned char *)((char *)&DAT_104add50 + 0x17F7)) /* byte view: the object holds no pointers */
#define DAT_104af586 (*(unsigned char *)((char *)&DAT_104add50 + 0x1836)) /* byte view: the object holds no pointers */
#define DAT_104af587 (*(unsigned char *)((char *)&DAT_104add50 + 0x1837)) /* byte view: the object holds no pointers */
#define DAT_104af588 (*(unsigned char *)((char *)&DAT_104add50 + 0x1838)) /* byte view: the object holds no pointers */
#define DAT_104af589 (*(unsigned char *)((char *)&DAT_104add50 + 0x1839)) /* byte view: the object holds no pointers */
#define DAT_104af58a (*(unsigned char *)((char *)&DAT_104add50 + 0x183A)) /* byte view: the object holds no pointers */
#define DAT_104af5c6 (*(unsigned char *)((char *)&DAT_104add50 + 0x1876)) /* byte view: the object holds no pointers */
#define DAT_104af5c7 (*(unsigned char *)((char *)&DAT_104add50 + 0x1877)) /* byte view: the object holds no pointers */
#define DAT_104af5c8 g_BrEnvBitmap
#define DAT_104af5c9 (*(unsigned char *)((char *)&g_BrEnvBitmap + 0x1)) /* byte view: the object holds no pointers */
#define DAT_104af5ca (*(unsigned char *)((char *)&g_BrEnvBitmap + 0x2)) /* byte view: the object holds no pointers */
#define DAT_104b15d0 (*(float *)&DAT_104b15d0)
#define DAT_106e72a8 g_BrProjMat
#define DAT_106e72e8 (*(int *)&g_BrEnvOthermode)
#define DAT_106e7710 (*(unsigned int * *)&g_BrGfxPtr)
#define DAT_106e78f0 g_BrDrawCombined
#define DAT_106e7930 g_BrDrawScale
#define DAT_106e8204 (*(int *)&BrG_6C1174)
#define DAT_106e8a18 (*(int *)&g_BrEnvFlagCount)
#define DAT_106ea3f4 (*(int *)&g_brRaceBeginDifficulty)
#define DAT_106ec798 (*(int *)&g_BrEnvSection)
#define DAT_106ed520 g_BrCamera
#define DAT_106ed528 (g_BrEnvFlagIndices[0])
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_106eed38 g_BrDrawTrackFlags
#define DAT_1184c460 g_BrEnvTexLookup
#define DAT_1184c478 (*(unsigned int *)&g_BrEnvTexDefault)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10008d60 BrPodNop
#define FUN_1001cf90 BrRdpSetCombineLERP
#define FUN_100344d0 br_dl_normalise
#define FUN_100349c0 BrVec3Project
#define FUN_10034af0 BrMtxMul
#define FUN_10034b70 BrMtxInvert
#define _ftol ftol
