/* generated by ports/64b/tools/unify.py */
#define g_Br6C666C (*(int32_t *)((char *)&g_aBrEntRecs + 0xCC)) /* byte view: the object holds no pointers */
#define g_f6C2CFC g_brRaceFlyStep
#define g_i0AC300 (*(int *)&g_AC300)
#define g_i6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_i6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
/* functions */
#define BrSub100341B3 BrDlRecolor
