/* generated by ports/64b/tools/unify.py */
#define DAT_10077218 g_BrVisRangeRecip
#define DAT_100a5ca8 (*(uint8_t (*)[])&g_BrVisLightHist)
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100aa044 g_brMode0AA8B4
#define DAT_100b2f04 (*(int *)&g_BrCarCount)
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_10226e80 g_226e80
#define DAT_102e16a8 g_BrVisFirstMid
#define DAT_102e170c g_BrVisFirstFar
#define DAT_1035e710 (*(uint16_t (*)[])&g_BrVisSpans)
#define DAT_1035f7d4 g_BrVisFirstNear
#define DAT_1035f7d8 (*(uint32_t * *)&DAT_1035f7d8)
#define DAT_1035fb70 g_BrVisLightHistIdx
#define DAT_1035fb8c g_BrVisSpanCount
#define DAT_1035fba0 g_BrVisLights
#define DAT_10386ca8 (*(uint8_t (*)[])&g_BrSpanPending)
#define DAT_106e72e8 g_BrEnvOthermode
#define DAT_106e770c g_BrPerspNorm
#define DAT_106e7710 g_BrGfxPtr
#define DAT_106e7718 BrG_6C0688
#define DAT_106e78f0 (*(float (*)[16])&g_BrDrawCombined)
#define DAT_106e79b0 (*(uint32_t *)&DAT_106e79b0)
#define DAT_106e79e0 (*(uint32_t (*)[])&DAT_106e79e0)
#define DAT_106e8204 (*(int *)&BrG_6C1174)
#define DAT_106e9a38 (*(float (*)[16])&g_BrCurMat)
#define DAT_106e9a48 (*(float (*)[4])((char *)&g_BrCurMat + 0x10)) /* byte view: the object holds no pointers */
#define DAT_106e9a58 (*(float (*)[4])((char *)&g_BrCurMat + 0x20)) /* byte view: the object holds no pointers */
#define DAT_106e9a68 (*(float (*)[4])((char *)&g_BrCurMat + 0x30)) /* byte view: the object holds no pointers */
#define DAT_106e9a78 (*(uint32_t *)&DAT_106e9a78)
#define DAT_106ea360 g_BrMtxSlot
#define DAT_106ea3f4 (*(int *)&g_brRaceBeginDifficulty)
#define DAT_106ecb40 (*(uint32_t *)&DAT_106ecb40)
#define DAT_106ed6a8 (*(int *)((char *)&g_aBrEntRecs + 0x78)) /* byte view: the object holds no pointers */
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_106eed38 g_BrDrawTrackFlags
#define DAT_1184c470 (*(uint32_t *)&DAT_1184c470)
#define g_0B2F04 (*(int *)&g_BrCarCount)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrMtxPoolAlloc BrSub_10069490
#define FUN_10008f90 BrObjSelCycle
#define FUN_1000cba0 BrObjDlBuild
#define FUN_1000e320 BrSceneVisPrepare
#define FUN_1002af17 BrFrameFogEmit
