/* generated by ports/64b/tools/unify.py */
#define g_0A6498 (*(void * *)&g_BrDrawRefColors)
#define g_1829314 g_BrDrawReflectTexA
#define g_18AA0B0 (*(void * (**)(void *, void *, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t))&g_pfn18AA0B0)
#define g_18AA0D8 (*(uint8_t (*)[])&DAT_118ed1f0)
#define g_18AA0F8 (*(char *)&DAT_118ed210)
#define g_18AA8F8 (*(uint8_t (*)[])&DAT_118eda10)
#define g_18AB0F8 (*(char *)&DAT_118ee210)
#define g_pfn18AA0B0 (*(BrTexCreateFn10073B00 *)&g_pfn18AA0B0)
