/* generated by ports/64b/tools/unify.py */
#define DAT_105ccc78 (*(uint32_t *)&DAT_105ccc78)
#define DAT_105ccc7a (*(uint8_t *)&DAT_105ccc78[2])
#define DAT_105ccc80 (*(int8_t *)&DAT_105ccc78[8])
#define DAT_105ccc81 (*(int8_t *)&DAT_105ccc78[9])
#define DAT_105ccc82 (*(int8_t *)&DAT_105ccc78[10])
#define DAT_105ccc88 (*(uint32_t *)&DAT_105ccc78[16])
#define DAT_105ccc8a (*(uint8_t *)&DAT_105ccc78[18])
#define DAT_105ce318 g_aBrDlVtxPool
#define DAT_1186c950 BrGbiRectG_186C950
#define DAT_118ed198 BrGbiRectG_18ED198
/* functions */
#define FUN_10022070 br_dl_project
#define FUN_10022120 BrDlsClipCodes
#define FUN_10022AC0 br_dl_light_vertex
#define FUN_100344D0 br_dl_normalise
#define FUN_10074600 asin
