/* generated by ports/64b/tools/unify.py */
#define g_BrProjMatFixed g_BrDrawScale
#define g_f6C2CFC g_brRaceFlyStep
#define g_i0AC300 (*(int *)&g_AC300)
#define g_i6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_i6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
