/* generated by ports/64b/tools/unify.py */
#define BrG_6C0680 g_BrGfxPtr
#define DAT_1007b618 (*(int *)&g_aBrFontBlockLarge)
#define DAT_1009d218 (*(int *)&g_aBrFontBlockSmall)
#define DAT_100a5978 (*(int (*)[])&g_aBrFontOffLarge)
#define DAT_100a5a58 (*(int (*)[])&g_aBrFontOffSmall)
#define DAT_104af5c8 g_BrEnvBitmap
#define DAT_106ed674 (*(int *)((char *)&g_aBrEntRecs + 0x44)) /* byte view: the object holds no pointers */
#define DAT_10ac53e8 (*(int *)&g_img)
#define DAT_1184c478 (*(int *)&g_BrEnvTexDefault)
#define DAT_1184c480 (*(int *)&g_BrDrawReflectTexB)
#define _DAT_1184c460 g_BrEnvTexLookup
#define g_1829108 DAT_1184c468
#define g_18AA0B0 (*(BrSub10073980Fn *)&g_pfn18AA0B0)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brFont6E72E8 g_BrEnvOthermode
#define g_brFontAltColour (*(char *)&g_br4B0358)
#define g_brFontAltRamp (*(char *)&g_4B0360)
#define g_brFontEnvB (*(int32_t *)&DAT_100a6c70)
#define g_brFontEnvG (*(int32_t *)&DAT_100a6c6c)
#define g_brFontEnvR (*(int32_t *)&DAT_100a6c68)
#define g_brFontHiRes (*(int32_t *)((char *)&g_aBrEntRecs + 0x44)) /* byte view: the object holds no pointers */
#define g_brFontPrimB (*(int32_t *)&DAT_104abb58)
#define g_brFontPrimG (*(int32_t *)&DAT_104abb54)
#define g_brFontPrimR (*(int32_t *)&DAT_104abb50)
#define g_brFontScale (*(int32_t *)&DAT_104abb30)
#define g_brFontTexLarge (*(uint32_t *)&DAT_1184c47c)
#define g_brFontTexSmall (*(uint32_t *)&DAT_1184c46c)
#define g_brFontUserColour (*(int32_t *)&DAT_104abb4c)
#define g_brFontX (*(int32_t *)&DAT_104abb28)
#define g_brFontY (*(int32_t *)&DAT_104abb2c)
#define g_i0B8C90 (*(int *)&g_brTex0B8C90)
#define g_pfn18AA0B0 (*(funcptr *)&g_pfn18AA0B0)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrUiSprClip BrUiSprBlit
#define FUN_10001000 BrAdler32
#define FUN_10001190 BrSurfFree
#define FUN_10027fb0 BrTex3dCreateBlank
#define FUN_1006c750 BrFontTexCreate
#define FUN_1006c800 BrFontTexCreateAlt
#define FUN_1006c880 BrFontTexCreateFlat
#define FUN_1006c8b0 BrFontTexCreatePair
