/* generated by ports/64b/tools/unify.py */
#define BrG_6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define BrG_6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_105ccbd0 (*(int *)&DAT_105ccb68[26])
#define DAT_105ccfd4 (*(int *)&BrGlBlendSrcA)
#define DAT_105ccfe4 (*(int *)&BrGlBlendDstA)
#define DAT_105d1758 (*(int *)&BrGlBlendDstRGB)
#define DAT_105d17a8 (*(int *)&BrGlBlendSrcRGB)
#define DAT_105e1808 (*(int *)&s_g5E1808)
#define DAT_105e1820 (*(int *)&s_g5E1820)
#define DAT_106b7ab8 BrGlFlipHook
#define DAT_106e7710 (*(BrGfxWords * *)&g_BrGfxPtr)
#define DAT_106ed6a8 (*(int *)((char *)&g_aBrEntRecs + 0x78)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_118ee590 (DAT_118ee590[0])
#define _DAT_1186c950 BrGbiRectG_186C950
#define _DAT_1186c954 BrGbiRectG_186C954
#define _DAT_118ec988 BrGbiRectG_18EC988
#define _DAT_118ed198 BrGbiRectG_18ED198
#define _DAT_118ed1a4 DAT_118ed1a4
#define _DAT_118ed1a8 DAT_118ed1a8
#define g_BrFpsCountB (*(int *)&g_BrFpsCountB)
#define g_BrFpsGateB (*(int *)&g_BrFpsGateB)
#define g_BrFpsScreenH BrGbiRectG_A7518
#define g_BrFpsScreenW BrGbiRectG_A7514
