/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100aa044 g_brMode0AA8B4
#define DAT_105ccb88 (*(int *)&DAT_105ccb68[8])
#define DAT_106e86c8 (*(int *)&BrG_6C1628[4])
#define DAT_106e8720_100AA044 g_brMode0AA8B4
#define DAT_106ea3f4 (*(int *)&g_brRaceBeginDifficulty)
#define DAT_10b1cf10 (*(int *)&g_BrCamHold2)
#define DAT_10b1cf14 (*(int *)&g_BrCamHold)
#define DAT_118eebe8 (*(unsigned int *)&g_BrX18ABAD0)
/* functions */
#define FUN_10002570 BrSqrtF
#define FUN_1002de6b BrAccumAddClamp
#define FUN_10034310 BrVec3Dot
#define FUN_10034390 BrVec3ScaleBy
#define FUN_10034560 BrVec3Sub
#define FUN_100345c0 BrVec3Add
#define FUN_100345f0 BrVec3AddTo
#define FUN_100346a0 BrVec3MulAddTo
#define FUN_10034760 BrVec3Dist
#define FUN_100347f0 BrVec3Length
