/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100aa044 g_brMode0AA8B4
#define DAT_10226a44 (*(int *)&g_brRaceTick)
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_105ccb88 (*(int *)&DAT_105ccb68[8])
#define DAT_106e86c8 (*(int *)&BrG_6C1628[4])
#define DAT_106e9d8c g_brRaceFlyStep
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrCarSub1005A7A0 BrCarPhysStep
#define BrCollRayCast_1006EC30 FUN_1006ec30
