/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b301c (*(BrDmgStage (*)[])((char *)&g_brStages + 0x4)) /* byte view: the object holds no pointers */
#define DAT_100b3028 (*(BrDmgBit (*)[])&g_aBr0B3820)
#define DAT_100b3094 (*(int *)&g_aBr0B3820[108])
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_10af2094 (*(int *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
