/* generated by ports/64b/tools/unify.py */
#define DAT_10077a78 BrCrK_Zero
#define DAT_117781b0 s_aNode
#define DAT_11778800 (*(int *)((char *)&g_brCrPlane + 0x10)) /* byte view: the object holds no pointers */
#define _DAT_10077780 DAT_10077780
#define _DAT_10077784 DAT_10077784
#define _DAT_10077788 DAT_10077788
#define g_brCarPhysWeather (*(int32_t *)&DAT_104b15e8)
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrCarPhysTyre_port BrCarPhysTyre
#define BrCrRespWalk_portproto BrCrRespWalk
#define FUN_10064210 BrRbAccumAll
#define FUN_1006d530 BrRbQuatDerivative
