/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b2f00 (*(int *)&g_brRaceNDriver)
#define DAT_10b71534 (*(unsigned short * *)&g_BrPadModeBytes)
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define _CIpow CIpow
