/* generated by ports/64b/tools/unify.py */
#define g_brAiBiasNeg (*(int32_t *)&DAT_10b1cf04)
#define g_brAiBlend g_brRaceFlyStep
#define g_brAiScanAim (*(BrVec3 *)&DAT_10b1ce88)
#define g_brAiScanN (*(int32_t *)&DAT_10ac680c)
#define g_brAiScanPt (*(BrVec3 *)&DAT_10af11f8)
#define g_brCarPhysWeather (*(int32_t *)&DAT_104b15e8)
#define g_brRaceMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrAiPathRoot (*(BrAiPathNode * *)&g_pBrRaceLapRec)
#define g_pBrMenuRec (*(BrAiMenuRec * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
/* functions */
#define BrCarCtlChain_1006F170 BrCarStep
#define BrCtlAiLineStep BrCarPathEval
#define BrCtlAiRespawn BrCarRespawn_1005C6D0
#define BrVec3NormaliseGuard br_dl_normalise
