/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_105ccb88 (*(int *)&DAT_105ccb68[8])
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define FUN_10029d70 BrMat4Mul
#define FUN_1002a590 BrMat4RotateAxis
#define FUN_1005ac60 BrCarBuildMatrices
#define FUN_10063a60 BrReplayRecord
#define FUN_10063b80 BrReplayApply
#define FUN_10063ca0 BrReplayApplyCar
