/* generated by ports/64b/tools/unify.py */
#define DAT_11773698 (*(BrCollPlaneZ (*)[4][150])&DAT_11773698)
#define DAT_11778198 (*(void * *)&g_pBrCollRespList)
#define DAT_117781b0 (*(BrCollNodeZ (*)[200])&s_aNode)
#define DAT_11778800 (*(int *)((char *)&g_brCrPlane + 0x10)) /* byte view: the object holds no pointers */
#define DAT_11778804 (*(int *)((char *)&g_brCrPlane + 0x14)) /* byte view: the object holds no pointers */
#define DAT_11778844 (*(void * *)&g_pBrCrCursor)
