/* generated by ports/64b/tools/unify.py */
#define DAT_10077a78 BrCrK_Zero
#define DAT_10077ac8 BrCrK_Half
#define DAT_11778800 (*(uint16_t (*)[4])((char *)&g_brCrPlane + 0x10)) /* byte view: the object holds no pointers */
#define g_brCollRespWalkBack (*(int *)&g_brRaceBeginMirrorOff)
#define s_iNode g_pBrCrCursor
/* functions */
#define BrPlaneEval BrCrPlaneDist
