/* generated by ports/64b/tools/unify.py */
#define g_BrPodCount (*(uint32_t *)&g_BrPodCount)
/* functions */
#define BrFileWriteCheckedT BrFileWriteChecked
#define BrPodWriterMakeName BrPathBasename
