/* generated by ports/64b/tools/unify.py */
#define g_ab0C12A0 (*(uint8_t (*)[])&g_ab0C12A0)
#define g_i0AC300 (*(int *)&g_AC300)
#define g_i0B8C90 (*(int *)&g_brTex0B8C90)
#define g_i6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_i6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define g_p6C7C3C (*(void * *)&g_brP6EECCC)
/* functions */
#define BrDlIsRegistered BrPtrListContains
#define BrDlRegister BrF3DListFixup
#define BrGlFixupAt BrSegPtrFixup
#define BrSegSetBasesG BrSegSetBases
#define BrSub10074DC0 BrFontSetRenderDst
#define BrSwapRec24Array BrRcaFixupArray
