/* generated by ports/64b/tools/unify.py */
#define DAT_100b2f00 (*(int *)&g_brRaceNDriver)
#define DAT_100b2f04 g_BrCarCount
#define DAT_106ed6ac (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_106ed6b4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_10ac0c38 g_iPfxFree
#define DAT_10ac0c3c (*(uint16_t *)&g_iPfxHeadAC)
#define DAT_10ac0c40 (*(uint16_t *)&g_iPfxHeadB0)
#define DAT_10ac0c44 (*(uint16_t *)&g_iPfxHeadB4)
#define DAT_10ac0c84 (*(unsigned char (*)[])((char *)&g_aPfxRec + 0x3C)) /* byte view: the object holds no pointers */
#define DAT_10ac2c44 (*(uint16_t *)((char *)&g_aPfxRec + 0x1FFC)) /* byte view: the object holds no pointers */
#define DAT_10ac2c64 (*(unsigned char (*)[])&g_BrVisColLo[1])
#define DAT_10af2264 (*(int32_t (*)[])((char *)&g_aBrRaceCar + 0x105C)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
#define g_fPfxDt g_brRaceFlyStep
/* functions */
#define _ftol ftol
