/* generated by ports/64b/tools/unify.py */
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_100b3028 (*(unsigned char (*)[])&g_aBr0B3820)
#define DAT_100b3029 (*(unsigned char (*)[])&g_aBr0B3820[1])
#define DAT_10af2094 (*(BrSelInM * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
