/* generated by ports/64b/tools/unify.py */
#define DAT_100b7d00 (BrSfxCarCode[1])
#define DAT_100b8498 (*(int *)&s_level)
#define DAT_100bcdd0 (g_ab0C12A0[0])
#define DAT_10ac67a4 (*(int *)((char *)&BrImgTintState + 0x4)) /* byte view: the object holds no pointers */
/* functions */
#define BrGbiCall10075330 BrNop6E590
#define BrSub10030770 BrRcaFixup
