/* generated by ports/64b/tools/unify.py */
#define g_br0AB3F4 (*(int32_t *)&g_AB94)
#define g_brAA26F4 (g_aBrAA26F4[0])
#define g_brAA26F5 (g_aBrAA26F4[1])
/* functions */
#define BrUiHook81Activate_100451E0 Ctl3E730_fn
#define BrUiHook81Activate_10045BC0 CtlF060_fn
#define BrUiHook81_10046AD0 BrOpt6AD0
