/* generated by ports/64b/tools/unify.py */
#define DAT_100aabc8 (*(int32_t *)&g_hot2)
#define DAT_100aabcc (*(int32_t *)((char *)&g_hot2 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_100aabe8 (*(unsigned char *)&g_hot0)
#define DAT_100aabf8 (*(unsigned char *)&DAT_100aabf8)
#define DAT_100aac08 (*(unsigned char *)&DAT_100aac08)
#define DAT_100aac18 (*(unsigned char *)&DAT_100aac18)
#define DAT_100aac98 (*(unsigned char *)&DAT_100aac98)
#define DAT_100aaca8 (*(unsigned char *)&DAT_100aaca8)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
