/* generated by ports/64b/tools/unify.py */
#define DAT_100aabc8 (*(int *)&g_hot2)
#define DAT_100aabcc (*(int *)((char *)&g_hot2 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100acad8 (g_strA[0])
#define DAT_10396f08 (g_aBr39B720[0])
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrMenuText15A0 BrItemSetRemaining_1003AB00
#define BrUiHook84_10047060 BrOpt7060
#define FUN_10038f40 BrItemSetPickLabel_10038F40
#define FUN_100393c0 BrItemSetModeLabel_100393C0
#define FUN_1003a910 BrItemSetTitle_1003A910
#define FUN_1003aa10 BrItemSetTotal_1003AA10
#define _ftol ftol
