/* generated by ports/64b/tools/unify.py */
#define g_brFlag5C40 DAT_10ac5c40
#define g_brPhase5C5C g_brPAA29B8
#define g_brRoot5CBC DAT_10ac5cbc
#define g_brTblABB08 (*(int (*)[])&g_aBrAC368)
/* functions */
#define BrItemApply_10038380 Br85ItemApply
#define BrStrByIndex BrStrGet
