/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100aacf8 (*(char *)&DAT_100aacf8)
#define DAT_100acad8 (g_strA[0])
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrMenuSub10044B90 Ctl3E0E0_fn
#define BrPhaseActivate_10044F50 Ctl3E4A0_fn
#define BrPhaseActivate_100451E0 Ctl3E730_fn
#define BrPhaseActivate_10045900 Ctl3ED90_fn
#define BrPhaseActivate_10046170 Ctl3F610_fn
#define BrSub10043BF0 Ctl3D140_fn
