/* generated by ports/64b/tools/unify.py */
#define DAT_10ac408c g_guardA
#define DAT_10ac53ec (*(int *)((char *)&g_img + 0x4)) /* BR_LP64_BYTE_VIEW */
#define DAT_10ac5874 (*(int *)&g_aBrAA2518[4])
#define DAT_10ac5c58 (*(PodObj * *)&g_obj400)
#define DAT_10ac5c60 (*(Ph * *)&g_2908)
#define DAT_10ac5c64 (*(Ph * *)&g_5C64)
#define DAT_10ac5c68 (*(Ph * *)&g_5C68)
#define DAT_10ac5c6c (*(Ph * *)&g_5C6C)
#define DAT_10ac5c70 (*(Ph * *)&g_5C70)
#define DAT_10ac5c74 (*(Ph * *)&g_5C74)
#define DAT_10ac5c7c (*(Ph * *)&g_5C7C)
#define DAT_10ac5c80 (*(Ph * *)&g_5C80)
#define DAT_10ac5c88 (*(Ph * *)&g_5C88)
#define DAT_10ac5c8c (*(Ph * *)&g_5C8C)
#define DAT_10ac5c90 (*(Ph * *)&g_5C90)
#define DAT_10ac5c98 (*(Ph * *)&g_5C98)
#define DAT_10ac5ca0 (*(Ph * *)&g_2948)
#define DAT_10ac5ca4 (*(Ph * *)&g_294C)
#define DAT_10ac5ca8 (*(Ph * *)&g_brPAA2950)
#define DAT_10ac5cac g_5CAC
#define DAT_10ac5cb0 (*(Ph * *)&g_5CB0)
#define DAT_10ac5cb4 (*(Ph * *)&g_5CB4)
#define DAT_10ac5cbc (*(Ph * *)&DAT_10ac5cbc)
#define DAT_10ac5cc0 (*(Ph * *)&g_5CC0)
#define DAT_10ac5cd4 (*(Ph * *)&g_5CD4)
#define DAT_10ac5cd8 (*(Ph * *)&g_5CD8)
#define DAT_10ac5cdc (*(Ph * *)&g_5CDC)
#define DAT_10ac5ce0 (*(Ph * *)&g_5CE0)
#define DAT_10ac5ce4 (*(Ph * *)&g_298C)
#define DAT_10ac5cec (*(Ph * *)&g_5CEC)
#define DAT_10ac5cf0 (*(Ph * *)&g_5CF0)
#define DAT_10ac5d04 g_hookObj
#define DAT_10ac5d10 g_29B8
#define DAT_10ac5d24 g_5D24
#define DAT_10ac5d28 g_brPAA29D0
#define DAT_10ac5d30 g_brPAA29D8
#define DAT_10ac5d38 g_pGame
#define g_AA29F4 g_brUipAA29F4
#define g_AC300 (*(int *)&g_AC300)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brAA2854 g_track
#define g_brAA2970 (*(Ph * *)&DAT_10ac5cc8)
#define g_brAA29B0 DAT_10ac5d08
#define g_brPhaseAA2904 g_brPAA29B8
#define g_brPhaseAA293C (*(Ph * *)&g_5C94)
#define g_iAA2880 g_5BD8
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10058a30 BrRaceSettingsCommit
