/* generated by ports/64b/tools/unify.py */
#define DAT_100776f0 PTR_FUN_100776f0
#define PTR_FUN_100776F0 PTR_FUN_100776f0
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrTextBoxDtor BrVtInit53EE0
