/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100acad8 (g_strA[0])
#define g_AA29C8 (*(BrCtl * *)&g_brUipAA29C8)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrPhaseActivate_100452C0 CtlE810_fn
#define BrPhaseActivate_10045390 CtlE8E0_fn
#define BrPhaseActivate_100455E0 CtlEA70_fn
#define BrPhaseActivate_100456B0 CtlEB40_fn
#define FUN_1003f9c0 BrOpt6520
