/* generated by ports/64b/tools/unify.py */
#define g_9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_nav (*(Nav *)&g_BrCtrlCfg)
/* functions */
#define Fn7920 BrOptSave
#define FnB0B0 BrMenuAutoSaveName
