/* generated by ports/64b/tools/unify.py */
#define DAT_100aab94 g_AB94
#define DAT_10396f08 (g_aBr39B720[0])
#define DAT_10ac3e80 (g_aBrA9CDF0[0])
#define DAT_10ac4100 (g_aBrA9D078[0])
#define DAT_10ac5a48 (DAT_10ac5a48[0])
#define DAT_10ac5a4c (g_aBrAA26F4[0])
#define DAT_10ac5a4d (*(unsigned char *)&g_aBrAA26F4[1])
#define DAT_10ac5bf8 g_brPhase5BF8
#define DAT_10ac5bfc g_brIdx5BFC
#define DAT_10ac5c10 (*(char *)&DAT_10ac5c10)
#define DAT_10ac5c30 g_5C30
#define DAT_10ac5c3c g_5C3C
#define DAT_10ac5c5c g_brPAA29B8
#define DAT_10ac5d24 g_5D24
#define DAT_10ac5d28 g_brPAA29D0
#define DAT_10ac5d98 g_5D98
#define DAT_10b71544 (DAT_10b71544[0])
#define g_AA287C (*(uint32_t *)&DAT_10ac5bd4)
#define g_AA29C8 (*(uint32_t * *)&g_brUipAA29C8)
#define g_AA29F4 (*(uint32_t * *)&g_brUipAA29F4)
#define g_brAA2854 g_track
#define g_brAA28A4 g_brIdx5BFC
#define g_brAA28D8 g_5C30
#define g_i0AB3F4 g_AB94
/* functions */
#define BrExt_10043E70 Ctl3D3C0_fn
#define BrExt_100451E0 Ctl3E730_fn
#define BrExt_10045BC0 CtlF060_fn
#define BrExt_10046750 BrOpt6750
#define BrExt_10046790 BrMenuResetTrackStr
#define BrExt_10046910 BrOpt6910
#define BrExt_10046950 FUN_1003fda0
#define BrExt_100469F0 BrOpt69F0
#define BrExt_10046A30 FUN_1003fe80
#define BrExt_10046BB0 BrOpt6BB0
#define FUN_10038380 Br85ItemApply
