/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_C17C (*(short *)((char *)&g_BrGlyphFontA12 + 0x2F8)) /* byte view: the object holds no pointers */
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FnE280 BrSub10075020
