/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_10396f08 (g_aBr39B720[0])
#define DAT_10ac40a8 (*(char *)&DAT_10ac40a8)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrOptOpen2950B Ctl3D930_fn
