/* generated by ports/64b/tools/unify.py */
#define g_4098 g_brPA9D008
#define g_nav (*(Nav *)&g_BrCtrlCfg)
/* functions */
#define Fn25B0 BrExt_10038F30
#define Fn7920 BrOptSave
#define Fn9A40 BrDPlayShutdown
