/* generated by ports/64b/tools/unify.py */
#define g_brPanel5C8C (*(Sub2AE8_40420 * *)&g_5C8C)
#define g_brPanel5C90 (*(Sub2AE8_40420 * *)&g_5C90)
#define g_brPanel5C94 (*(Sub2AE8_40420 * *)&g_5C94)
#define g_brPending5CCC g_brPhaseAA2974
#define g_brPhase5C5C (*(Phase40420 * *)&g_brPAA29B8)
#define g_brRoot5C60 (*(Phase40420 * *)&g_2908)
