/* generated by ports/64b/tools/unify.py */
#define g_brMap3028 (*(unsigned char (*)[])&g_aBr0B3820)
#define g_brMode5BF4 g_5BF4
#define g_brSel5C10 (*(char *)&DAT_10ac5c10)
/* functions */
#define _ftol ftol
