/* generated by ports/64b/tools/unify.py */
#define DAT_100aab94 g_AB94
#define DAT_10ac5d24 g_5D24
#define DAT_10ac5d28 g_brPAA29D0
#define g_brRootPhase (*(BrRoot55C50 * *)&g_2908)
#define g_brSeasonMode g_brGate5BA0
