/* generated by ports/64b/tools/unify.py */
#define DAT_100aabc8 (*(int *)&g_hot2)
#define DAT_100aabcc (*(int *)((char *)&g_hot2 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_10396f08 (g_aBr39B720[0])
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrUiHook81_100470E0 BrOpt70E0
#define FUN_1003a910 BrItemSetTitle_1003A910
#define _ftol ftol
