/* generated by ports/64b/tools/unify.py */
#define DAT_100aab94 g_AB94
#define DAT_10ac4100 g_aBrA9D078
#define DAT_10ac5bf4 g_5BF4
#define DAT_10ac5c3c g_5C3C
#define DAT_10ac5c44 (*(int *)&g_brUinAA28EC)
#define DAT_10ac5c60 g_2908
#define g_brRootPhase (*(BrRoot55C50 * *)&g_2908)
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define FUN_10069de0 BrGhostSave
