/* generated by ports/64b/tools/unify.py */
#define g_2948 (*(Phase * *)&g_2948)
#define g_29D8 (*(FlagObj * *)&g_brPAA29D8)
#define g_A9D000 g_guardB
#define g_AA2898 DAT_10ac5bf0
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_mode (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
/* functions */
#define FnBF60 BrExt_1003BF60
#define FnC020 FUN_100356b0
