/* generated by ports/64b/tools/unify.py */
#define g_br0AC648 (*(int32_t *)&g_brIdx0ABDE8)
#define g_br0AC64C (*(int32_t *)&DAT_100abdec)
#define g_br0AC650 (*(int32_t *)&DAT_100abdf0)
#define g_br0AC654 (*(int32_t *)&g_brSel0ABDF4)
#define g_br0AC658 (*(int32_t *)&DAT_100abdf8)
#define g_br0AC65C g_i0AC65C
#define g_brAA2A00 (*(int32_t *)&DAT_10ac5d58)
#define g_brAA2A08 (*(int32_t *)&DAT_10ac5d60)
#define g_brAA2A0C (*(int32_t *)&g_brKind5D64)
#define g_brAA2A10 (*(int32_t *)&DAT_10ac5d68)
#define g_brAA2A14 (*(int32_t *)&DAT_10ac5d6c)
#define g_brAA2A18 (*(int32_t *)&DAT_10ac5d70)
