/* generated by ports/64b/tools/unify.py */
#define g_brAC5BAC g_track
#define g_pBrAC5DD8 (*(BrTime553B0 * *)&BrGlNavThis5DD8)
#define g_pBrAC61E0 (*(BrPad553B0 * *)&g_pBrAA2E80)
/* functions */
#define BrFn10037710 BrFn1003E070
#define BrFn10037720 BrInputAnyActive
#define BrFn1006BA60 BrSub10072AF0
#define BrFn1006E280 BrSub10075020
#define _ftol ftol
