/* generated by ports/64b/tools/unify.py */
#define g_brFlag0A9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_brFlag5C00 DAT_10ac5c00
#define g_brFlag5C40 DAT_10ac5c40
#define g_brMap3028 (*(unsigned char (*)[])&g_aBr0B3820)
#define g_brPhase5C5C g_brPAA29B8
#define g_brRoot5CBC DAT_10ac5cbc
#define g_brSel5C10 (*(char *)&DAT_10ac5c10)
#define g_brTblBCAB0 (*(BrDesc38F40 * (*)[])&g_apBrRaceDiff)
/* functions */
#define BrItemApply_10038380 Br85ItemApply
#define BrStrByIndex BrStrGet
