/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brFlag0A9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_brFlag21C650 (*(int *)&g_a220B20)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrStrByIndex BrStrGet
