/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define g_AA29C8 (*(BrCtl * *)&g_brUipAA29C8)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brSel5D8C g_5D8C
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10037fa0 BrItemDrawIconRow
#define FUN_100476C0 BrUiHook85_1004E810
#define _ftol ftol
