/* generated by ports/64b/tools/unify.py */
#define DAT_10ac40a8 (*(char (*)[])&DAT_10ac40a8)
#define DAT_10ac4db0 g_szBrName4DB0
#define DAT_10b71648 g_aBrCfgPlayerName
#define g_brSlot4098 g_brPA9D008
#define g_szBrEmpty396F08 g_aBr39B720
/* functions */
#define BrFn1003D210_glide FUN_100368a0
