/* generated by ports/64b/tools/unify.py */
#define DAT_10ac4090 g_guardB
#define DAT_10ac5c5c (*(CurPhase * *)&g_brPAA29B8)
#define DAT_10ac5ca4 (*(CurPhase * *)&g_294C)
#define DAT_10ac5ca8 g_brPAA2950
#define DAT_10ac5d30 (*(D30Obj * *)&g_brPAA29D8)
/* functions */
#define BrSub100325B0 BrExt_10038F30
#define BrSub100355F0 BrExt_1003BF60
#define BrSub100356B0 FUN_100356b0
