/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_10ac5d44 (*(BrCtl * *)&DAT_10ac5d44)
#define g_AA29C8 (*(BrCtl * *)&g_brUipAA29C8)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_1003fac0 BrOpt6670
