/* generated by ports/64b/tools/unify.py */
#define g_br0AA010 (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br0AC304 (*(int32_t *)&DAT_100abaa4)
#define g_brAA29B0 (*(BrPhase * *)&DAT_10ac5d08)
#define g_brAA29B4 (*(BrPhase * *)&DAT_10ac5d0c)
#define g_brAA29F4 (*(BrPhase * *)&g_brUipAA29F4)
/* functions */
#define BrExt_10041BD0 BrSaveResumeAutoSave
#define BrExt_10045C90 Ctl3F130_fn
#define BrExt_10046CD0 BrUiHook89_10046CD0
#define BrExt_10046DC0 BrOpt6DC0
#define BrPhaseActivate_10045110 CtlE660_fn
