/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100acad8 (g_strA[0])
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brRoot5C60 (*(Root052A60 * *)&g_2908)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrMenuTime1040 BrItemSetLapTime_1003A580
#define BrMenuTime1180 BrItemSetBestTime_1003A6D0
#define FUN_10038f40 BrItemSetPickLabel_10038F40
#define FUN_100393c0 BrItemSetModeLabel_100393C0
#define FUN_1003bde0 BrSaveBeginTimeAttack
