/* generated by ports/64b/tools/unify.py */
#define g_brVp0AB164 (*(int *)&g_aBrUiSprite[1116])
#define g_brVp0AB168 (*(int *)&g_aBrUiSprite[1120])
#define g_brVp0AB18C (*(int *)&g_aBrUiSprite[1156])
#define g_brVp0AB190 (*(int *)&g_aBrUiSprite[1160])
#define g_brVp0AB194 (*(int *)&g_aBrUiSprite[1164])
#define g_brVp0AB198 (*(int *)&g_aBrUiSprite[1168])
/* functions */
#define _ftol ftol
