/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5c68 (*(Phase * *)&g_5C68)
#define g_buf (g_strA[0])
#define g_cur (*(Phase * *)&g_brPAA29B8)
/* functions */
#define ResetBuf BrExt_100419D0
