/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_aBrA9DD28 g_szBrName4DB0
#define g_aBrAA26F0 (*(int32_t (*)[83])&DAT_10ac5a48)
#define g_aBrB4DF30 (*(unsigned char (*)[4][168])&g_BrCtrlCfg)
#define g_br094350 (*(int32_t *)&g_7b320)
#define g_br094354 (*(int32_t *)&g_7b324)
#define g_br094358 (*(int32_t *)&g_7b328)
#define g_br09435C (*(int32_t *)&g_7b32c)
#define g_br0AA010 (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br0AB3D8 (*(int32_t *)((char *)&g_brBindAAAD4 + 0xA4)) /* byte view: the object holds no pointers */
#define g_br0AC648 (*(int32_t *)&g_brIdx0ABDE8)
#define g_br0AC64C (*(int32_t *)&DAT_100abdec)
#define g_br0AC650 (*(int32_t *)&DAT_100abdf0)
#define g_br0AC654 (*(int32_t *)&g_brSel0ABDF4)
#define g_br0AC658 (*(int32_t *)&DAT_100abdf8)
#define g_br0AC65C g_i0AC65C
#define g_br0B380C g_Br0B380C
#define g_br0B4050 BrG_0B4050
#define g_br0BD3E0 (*(int32_t *)&g_CBE8)
#define g_br22B34C (*(int32_t *)&g_226e7c)
#define g_br22B350 (*(int32_t *)&g_226e80)
#define g_br680738 (*(signed char *)&g_aBrTexSlot[126712])
#define g_br68073F (*(signed char *)&g_aBrTexSlot[126719])
#define g_br690A18 (*(int32_t *)&g_aBrTexSlot[192984])
#define g_brAA287C (*(int32_t *)&DAT_10ac5bd4)
#define g_brAA288C (*(int32_t *)&DAT_10ac5be4)
#define g_brAA28D8 (*(int32_t *)&g_5C30)
#define g_brAA28FC (*(int32_t *)&DAT_10ac5c54)
#define g_brAA2A00 (*(int32_t *)&DAT_10ac5d58)
#define g_brAA2A08 (*(int32_t *)&DAT_10ac5d60)
#define g_brAA2A0C (*(int32_t *)&g_brKind5D64)
#define g_brAA2A18 (*(int32_t *)&DAT_10ac5d70)
#define g_brAA33D0 g_act0
#define g_brAA33D4 g_act1
#define g_brB4E1D0 (*(int32_t *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_brB4E1D4 (*(void * *)&g_BrPadModeBytes)
#define g_brB4E1E0 (*(int32_t *)&DAT_10b71540)
#define g_brB4E708 (*(int32_t *)&g_brItemIconCount)
#define g_brB4E70C g_brRaceB71A6C
#define g_brB4E728 (g_aBrB4E710[6])
#define g_brP680584 (*(void * *)&g_brOwner5BC72C)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub1003D210 FUN_100368a0
#define BrSub1003F320 BrOptAvailB
#define BrOptObjCtor BrOptObjCtor
