/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100acad8 (g_strA[0])
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_10ac4090 g_guardB
#define DAT_10ac5d10 (*(BrCtl * *)&g_29B8)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brAA2884 g_host
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrOptOpen2954 Ctl3DC20_fn
#define FUN_10038f40 BrItemSetPickLabel_10038F40
#define FUN_100393c0 BrItemSetModeLabel_100393C0
