/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10ac5c64 g_5C64
#define g_0ABAA4 DAT_100abaa4
#define g_5BC8E0 (g_aBrRaceBeginRec[0])
#define g_AF2094 (*(int *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_AF3CE4 (*(int *)((char *)&g_aBrRaceCar + 0x2ADC)) /* BR_LP64_BYTE_VIEW */
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_f6C2CFC g_brRaceFlyStep
#define g_mode (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
/* functions */
#define Fn08D60 BrPodNop
#define Fn37660 BrUiFn1003DFC0
#define Fn37B20 BrSub1003E510
#define ResetBuf BrSub1003E680
