/* generated by ports/64b/tools/unify.py */
#define DAT_100aabc8 (*(int *)&g_hot2)
#define DAT_100aabcc (*(int *)((char *)&g_hot2 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100acad8 (g_strA[0])
#define DAT_100b301c (*(Sel301C (*)[])((char *)&g_brStages + 0x4)) /* byte view: the object holds no pointers */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_aBr39B720 (g_aBr39B720[0])
#define g_brAA28A4 g_brIdx5BFC
#define g_brSel5C10 (*(char *)&DAT_10ac5c10)
#define g_iAA28AC g_brIdx5C04
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrPhaseActivate_100460A0 CtlF540_fn
#define BrUiNum1003EA90 BrItemSetNumWord_100380B0
#define FUN_10038f40 BrItemSetPickLabel_10038F40
#define FUN_100393c0 BrItemSetModeLabel_100393C0
#define FUN_1003a910 BrItemSetTitle_1003A910
#define FUN_100404f0 BrOpt70A0
#define _ftol ftol
#define br23_num_common BrItemSetNumByte_10037EF0
