/* generated by ports/64b/tools/unify.py */
#define g_br094350 (*(int32_t *)&g_7b320)
#define g_br094354 (*(int32_t *)&g_7b324)
#define g_br094358 (*(int32_t *)&g_7b328)
#define g_br09435C (*(int32_t *)&g_7b32c)
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br0AC648 (*(int32_t *)&g_brIdx0ABDE8)
#define g_br0AC64C (*(int32_t *)&DAT_100abdec)
#define g_br0AC650 (*(int32_t *)&DAT_100abdf0)
#define g_br0AC654 (*(int32_t *)&g_brSel0ABDF4)
#define g_br0AC658 (*(int32_t *)&DAT_100abdf8)
#define g_br0AC65C g_i0AC65C
#define g_br0B380C g_Br0B380C
#define g_br0BD3E0 (*(int32_t *)&g_CBE8)
#define g_br22B34C (*(int32_t *)&g_226e7c)
#define g_br22B350 (*(int32_t *)&g_226e80)
#define g_br4B035C DAT_104abb44
#define g_brAA26F4 (g_aBrAA26F4[0])
#define g_brAA26F5 (g_aBrAA26F4[1])
#define g_brAA28FC (*(int32_t *)&DAT_10ac5c54)
#define g_brAA2A00 (*(int32_t *)&DAT_10ac5d58)
#define g_brAA2A08 (*(int32_t *)&DAT_10ac5d60)
/* functions */
#define BrSub1003F2B0 BrInputBitHeld
#define BrSub1003F320 BrOptAvailB
#define BrSub1005FCF0 BrRaceSettingsCommit
