/* generated by ports/64b/tools/unify.py */
#define DAT_10ac4090 g_guardB
#define DAT_10ac5bb4 g_5BB4
#define DAT_10ac5ca8 (*(Phase8 * *)&g_brPAA2950)
#define DAT_10ac5d30 (*(Wnd * *)&g_brPAA29D8)
#define g_brAA2854 g_track
#define g_brAA287C DAT_10ac5bd4
#define g_brAA2884 g_host
#define g_brAA288C DAT_10ac5be4
#define g_brPA9D008 (*(NetHost * *)&g_brPA9D008)
#define g_cur (*(Phase8 * *)&g_brPAA29B8)
#define g_nav (*(Nav *)&g_BrCtrlCfg)
/* functions */
#define BrExt8F30 BrExt_10038F30
#define Fn355F0 BrExt_1003BF60
#define Fn7920 BrOptSave
