/* generated by ports/64b/tools/unify.py */
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_10ac5ca8 (*(Phase * *)&g_brPAA2950)
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_hookOwner g_29B8
