/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100acad8 (g_strA[0])
#define DAT_10ac5d04 (*(BrCtl * *)&g_hookObj)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrPhaseActivate_10045110 CtlE660_fn
#define FUN_10038f40 BrItemSetPickLabel_10038F40
#define FUN_100393c0 BrItemSetModeLabel_100393C0
#define FUN_1003f8f0 BrOpt6450
