/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100ac9c8 (DAT_100ac9c8[0])
#define DAT_10396f08 (g_aBr39B720[0])
#define DAT_10ac5ba0 g_brGate5BA0
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brRoot5C60 (*(Root0485B0 * *)&g_2908)
#define g_i0AB3F4 g_AB94
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_1003b6d0 BrSaveBeginRallySeason
