/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5c5c g_brPAA29B8
#define DAT_10ac5c60 g_2908
#define g_aBrA9DD28 g_szBrName4DB0
#define g_br0AB3E0 (*(int32_t *)&g_brRec0AAB80)
#define g_brAA287C DAT_10ac5bd4
#define g_brAA2884 g_host
#define g_brAA2888 g_inited
#define g_brAA288C DAT_10ac5be4
#define g_brP680584 g_brOwner5BC72C
/* functions */
#define BrOptOpen2940 CtlD220_fn
#define BrOptOpen2948 Ctl3D3C0_fn
#define BrOptOpen294C CtlD620_fn
#define BrOptOpen2950B Ctl3D930_fn
#define BrSub1003CE80 BrNetSessionApply
#define BrSub1003D0B0 FUN_10036740
#define BrSub1003D210 FUN_100368a0
#define BrSub10043BF0 Ctl3D140_fn
