/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10ac5c64 g_5C64
#define g_buf (g_strA[0])
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_mode (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
/* functions */
#define ResetBuf BrExt_100419D0
#define SetupA BrUiFn1003DFC0
#define SetupB BrSub1003E510
