/* generated by ports/64b/tools/unify.py */
#define DAT_100aabc8 (*(int *)&g_hot2)
#define DAT_100aabcc (*(int *)((char *)&g_hot2 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100acad8 (g_strA[0])
#define DAT_10ac5d0c (*(BrCtl * *)&DAT_10ac5d0c)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrUiText1003F7F0 BrUiText3F7F0
#define BrUiText1003F990 BrUiText3F990
#define FUN_10038da0 BrUiText3F860
#define FUN_1003f980 BrOpt64E0
#define _ftol ftol
