/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100abaa8 g_brTblABAA8
#define DAT_100abc78 (g_aBrAC4D8[0])
#define DAT_100abde8 g_brIdx0ABDE8
#define DAT_10396f08 g_aBr39B720
#define DAT_10ac40a0 (*(int *)&DAT_10ac40a0)
#define DAT_10ac4db0 g_szBrName4DB0
#define DAT_10ac5b3a (*(unsigned short *)((char *)&DAT_10ac5b38 + 0x2)) /* byte view: the object holds no pointers */
#define DAT_10ac5bf4 g_5BF4
#define DAT_10ac5d74 g_brSel5D74
#define DAT_10ac5d78 (*(int *)&DAT_10ac5d78)
#define DAT_10ac5d80 g_brSel5D80
#define DAT_10ac6730 (*(int *)&g_act0)
#define DAT_10ac6734 (*(int *)&g_act1)
#define PTR_PTR_100bcab0 (*(char * (*)[])&g_apBrRaceDiff)
#define g_Br0B380C (*(int *)&g_Br0B380C)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br0AB3D8 (*(int32_t *)((char *)&g_brBindAAAD4 + 0xA4)) /* byte view: the object holds no pointers */
#define g_br0AB3F4 (*(int32_t *)&g_AB94)
#define g_brAA287C (*(int32_t *)&DAT_10ac5bd4)
#define g_brAA28D8 g_5C30
#define g_brB4E708 (*(int32_t *)&g_brItemIconCount)
#define g_brB4E70C g_brRaceB71A6C
#define g_brP680584 g_brOwner5BC72C
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrOptOpen2948 Ctl3D3C0_fn
#define BrSprFontKindHook_10047360 BrSub10047360
#define FUN_100387f0 BrInputBitHeld
#define FUN_10059e00 BrUiVolumeApply
