/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5cc0 g_5CC0
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_dst1 (*(int *)&g_brTime5C24)
#define g_dst2 (*(int *)&g_brTime5C20)
#define g_f6C2CFC g_brRaceFlyStep
#define g_src1 (*(int *)((char *)&g_aBrRaceCar + 0xFE4)) /* BR_LP64_BYTE_VIEW */
#define g_src2 (*(int *)((char *)&g_aBrRaceCar + 0xFEC)) /* BR_LP64_BYTE_VIEW */
