/* generated by ports/64b/tools/unify.py */
#define DAT_1007b320 (*(int32_t *)&g_7b320)
#define DAT_1007b324 (*(int32_t *)&g_7b324)
#define DAT_1007b328 (*(int32_t *)&g_7b328)
#define DAT_1007b32c (*(int32_t *)&g_7b32c)
#define DAT_100b3014 g_Br0B380C
#define DAT_10226e7c (*(int32_t *)&g_226e7c)
#define DAT_10226e80 (*(int32_t *)&g_226e80)
#define DAT_10ac5b38 (*(int16_t *)&DAT_10ac5b38)
#define DAT_10ac5b3a (*(int16_t *)((char *)&DAT_10ac5b38 + 0x2)) /* byte view: the object holds no pointers */
#define DAT_10ac5d88 (*(int *)&g_iAA2A30)
#define DAT_10b71290 (*(unsigned char (*)[])&g_BrCtrlCfg)
#define DAT_10b71530 (*(int32_t *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71534 (*(void * *)&g_BrPadModeBytes)
#define g_i0AB3F4 (*(int32_t *)&g_AB94)
#define g_iAA2840 (*(int32_t *)&g_brSel5B98)
#define g_iAA2880 (*(int32_t *)&g_5BD8)
#define g_iAA28AC (*(int32_t *)&g_brIdx5C04)
/* functions */
#define FUN_1003fac0 BrOpt6670
