/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10ac408c g_guardA
#define DAT_10ac5cac g_5CAC
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_mode (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_obj_10AC4098 (*(Obj * *)&g_brPA9D008)
#define g_pHost (*(void * *)&g_brP277B40)
/* functions */
#define ActivateD140 Ctl3D140_fn
#define ActivateD220 CtlD220_fn
#define ActivateD3C0 Ctl3D3C0_fn
#define ActivateD620 CtlD620_fn
#define ActivateD7D0 BrOptOpen2950A
#define ActivateD930 Ctl3D930_fn
#define GetDesc FUN_10036740
#define HostAgain BrSub1003CDA0
#define HostFirst BrSub1003C150
#define ObjHook BrExt_1003DB00
#define ResetSlots BrSub100586A0
