/* generated by ports/64b/tools/unify.py */
#define BrGlNavAccum6710 (g_BrAA3398[6])
#define BrGlNavF66F8 (g_BrAA3398[0])
#define BrGlNavF66FC (g_BrAA3398[1])
#define BrGlNavF6700 (g_BrAA3398[2])
#define BrGlNavF6704 (g_BrAA3398[3])
#define BrGlNavK610C (g_BrDikEdge[203])
#define BrGlNavK6114 (g_BrDikEdge[205])
#define BrGlNavKey5F3C (g_BrDikEdge[87])
#define BrGlNavKey5F40 (g_BrDikEdge[88])
#define BrGlNavKey66B0 (g_BrDikState[200])
#define BrGlNavKey66B8 (g_BrDikState[208])
#define BrGlNavT6708 (g_BrAA3398[4])
#define BrGlNavTick670C (g_BrAA3398[5])
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_act5 (g_BrDikEdge[28])
#define g_act6 (g_BrDikEdge[156])
#define g_actOverride (*(int32_t *)&g_5BB4)
#define g_navCursor (*(int32_t * *)&BrGlNavThis5DD8)
#define g_pAA2E80 (*(BrObj2C * *)&g_pBrAA2E80)
#define g_tab (*(struct Dim (*)[7])&g_tab)
#define g_w0AB3DC (*(uint16_t *)&BrGlNavStepAB7C)
#define g_wAA286C BrGlNavCur5BC4
/* functions */
#define BrGlNavKeyLeft BrCdTrackPrev
#define BrGlNavKeyRight BrCdTrackNext
#define BrGlNavTail BrInputLatchUpdate
#define BrGlNavTimeNow BrSub10075020
#define BrIsAnyActiveGlide BrInputAnyActive
#define BrUiNavPageSelectGlide BrUiPageSelect_100484F0
#define BrOptObjCtor BrOptObjCtor
