/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100abb50 (*(int (*)[])&g_aBrAC3B0)
#define DAT_100b3029 (*(unsigned char (*)[])&g_aBr0B3820[1])
#define DAT_10ac5bfc g_brIdx5BFC
#define DAT_10ac5c04 g_brIdx5C04
#define DAT_10ac5c10 (*(char *)&DAT_10ac5c10)
#define DAT_10ac5c5c g_brPAA29B8
/* functions */
#define BrItemApply_10038380 Br85ItemApply
#define BrStrByIndex BrStrGet
