/* generated by ports/64b/tools/unify.py */
#define DAT_100abde8 g_brIdx0ABDE8
#define DAT_100abdec (*(int *)&DAT_100abdec)
#define DAT_100abdf0 (*(int *)&DAT_100abdf0)
#define DAT_100abdf4 g_brSel0ABDF4
#define DAT_1021c650 (*(int (*)[70])&g_a220B20)
#define DAT_10ac40f8 (*(float *)&g_brVal40F8)
#define DAT_10ac4c60 (*(int (*)[83])&g_aBrA9DBD8)
#define DAT_10ac5870 g_aBrAA2518
#define DAT_10ac5a40 (*(int *)&g_brVal5A40)
#define DAT_10ac5b38 (*(unsigned short *)&DAT_10ac5b38)
#define DAT_10ac5bf4 g_5BF4
#define DAT_10ac5bf8 g_brPhase5BF8
#define DAT_10ac5bfc g_brIdx5BFC
#define DAT_10ac5c04 g_brIdx5C04
#define DAT_10ac5c10 (*(unsigned char *)&DAT_10ac5c10)
#define DAT_10ac5c1c (*(int *)&DAT_10ac5c1c)
#define DAT_10ac5c20 g_brTime5C20
#define DAT_10ac5c28 (*(int *)&DAT_10ac5c28)
#define DAT_10ac5d60 (*(int *)&DAT_10ac5d60)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub10037B20 BrSub1003E510
