/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_mode (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
