/* generated by ports/64b/tools/unify.py */
#define DAT_1007b320 g_7b320
#define DAT_1007b324 g_7b324
#define DAT_1007b328 g_7b328
#define DAT_1007b32c g_7b32c
#define DAT_100a6b84 g_szBrFmt6B84
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100abbc0 (*(int (*)[])&g_aBrAC420)
#define DAT_100abc40 (*(int (*)[])&g_aBrAC4A0)
#define DAT_100abc50 (*(int (*)[])&g_aBrAC4B0)
#define DAT_100abc60 (*(int (*)[])&g_aBrAC4C0)
#define DAT_100abc78 (*(int (*)[])&g_aBrAC4D8)
#define DAT_100abcb8 (*(int (*)[])&g_aBrAC518)
#define DAT_100abde8 g_brIdx0ABDE8
#define DAT_100abdec (*(int *)&DAT_100abdec)
#define DAT_100abdf0 (*(int *)&DAT_100abdf0)
#define DAT_100abdf4 g_brSel0ABDF4
#define DAT_100abdfc (*(int *)&g_i0AC65C)
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_100bcbe8 g_CBE8
#define DAT_10226e7c g_226e7c
#define DAT_10226e80 g_226e80
#define DAT_10396f08 g_aBr39B720
#define DAT_105bc8e0 (g_aBrRaceBeginRec[0])
#define DAT_105bc8e7 (*(signed char *)&g_aBrRaceBeginRec[7])
#define DAT_105ccbc4 (*(int *)&DAT_105ccb68[23])
#define DAT_10ac40f8 (*(int *)&g_brVal40F8)
#define DAT_10ac40fc (*(int *)&DAT_10ac40fc)
#define DAT_10ac5870 g_aBrAA2518
#define DAT_10ac5a40 (*(int *)&g_brVal5A40)
#define DAT_10ac5a4e (*(int (*)[])&g_aBrAA26F6)
#define DAT_10ac5a66 (*(unsigned short (*)[])&g_aBrAA270E)
#define DAT_10ac5bf4 g_5BF4
#define DAT_10ac5bf8 g_brPhase5BF8
#define DAT_10ac5bfc g_brIdx5BFC
#define DAT_10ac5c04 g_brIdx5C04
#define DAT_10ac5c10 (*(char *)&DAT_10ac5c10)
#define DAT_10ac5c1c (*(int *)&DAT_10ac5c1c)
#define DAT_10ac5c38 g_5C38
#define DAT_10ac5d60 (*(int *)&DAT_10ac5d60)
#define DAT_10af2094 (*(int * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3cd8 (*(int *)((char *)&g_aBrRaceCar + 0x2AD0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3cdc (*(int *)((char *)&g_aBrRaceCar + 0x2AD4)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3ce0 (*(int *)((char *)&g_aBrRaceCar + 0x2AD8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3ce4 (*(int *)((char *)&g_aBrRaceCar + 0x2ADC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3ce8 (*(int *)((char *)&g_aBrRaceCar + 0x2AE0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3cec (*(int *)((char *)&g_aBrRaceCar + 0x2AE4)) /* BR_LP64_BYTE_VIEW */
#define g_aBrAA26F0 (*(int32_t (*)[83])&DAT_10ac5a48)
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br0B380C g_Br0B380C
#define g_br0B4050 BrG_0B4050
#define g_br0BD3E0 (*(int32_t *)&g_CBE8)
#define g_br680738 (*(signed char *)&g_aBrTexSlot[126712])
#define g_br68073F (*(signed char *)&g_aBrTexSlot[126719])
#define g_br690A18 (*(int32_t *)&g_aBrTexSlot[192984])
#define g_brAA2A00 (*(int32_t *)&DAT_10ac5d58)
#define g_brAA2A08 (*(int32_t *)&DAT_10ac5d60)
#define g_f6C2CFC g_brRaceFlyStep
#define s_AutoSave_brf_100acae8 s_AutoSave_brf
/* functions */
#define BrSub10071130 BrSaveLoad
