/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_1003cc60 BrOpt3710
#define FUN_1003f940 BrOpt64A0
