/* generated by ports/64b/tools/unify.py */
#define g_5CA0 g_2948
#define g_5D10 g_29B8
#define g_5D2C g_brPAA29D4
#define g_5D30 g_brPAA29D8
#define g_cur (*(Phase * *)&g_brPAA29B8)
/* functions */
#define Fn55F0 BrExt_1003BF60
