/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5bc0 g_bc0
#define DAT_10ac5c58 (*(BrPhase41 * *)&g_obj400)
#define DAT_10ac5c60 (*(BrPhase41 * *)&g_2908)
#define DAT_10b72f48 g_navArg
#define g_BrCtrlCfg (*(BrCtrlCfg41 *)&g_BrCtrlCfg)
#define g_brPhaseAA2904 (*(BrPhase41 * *)&g_brPAA29B8)
#define g_cur (*(Phase * *)&g_brPAA29B8)
/* functions */
#define FUN_10037920 BrOptSave
