/* generated by ports/64b/tools/unify.py */
#define g_br0A9360_mode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br6EDE80_maskB DAT_10ac58f0
#define g_br6EE0C8_maskPair (*(int32_t *)&DAT_10ac5b38)
#define g_br6EE184_fAlt (*(int32_t *)&g_5BF4)
#define g_br6EE1DC_fRebaseB (*(int32_t *)&DAT_10ac5c4c)
#define g_brAAB84_maskBDef (*(int16_t *)&DAT_100aab84)
#define g_brAAB88_maskB6 (*(int32_t *)&g_br0AB3E8)
#define g_brAF3CE4_nAlwaysB (*(int32_t *)((char *)&g_aBrRaceCar + 0x2ADC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
