/* generated by ports/64b/tools/unify.py */
#define DAT_100b3028 (*(unsigned char (*)[])&g_aBr0B3820)
#define DAT_10ac5bf4 g_5BF4
#define DAT_10ac5c04 g_brIdx5C04
#define DAT_10ac5c10 (*(signed char *)&DAT_10ac5c10)
/* functions */
#define _ftol ftol
