/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5c74 g_5C74
#define g_buf (g_strA[0])
#define g_cur (*(Phase * *)&g_brPAA29B8)
/* functions */
#define CdCheck FUN_1003ee90
#define GetStr BrStrGet
#define ResetBuf BrExt_100419D0
