/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_10396f08 (g_aBr39B720[0])
#define g_AA29F4 (*(BrCtl * *)&g_brUipAA29F4)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brCtl5D18 (*(BrCtl * *)&DAT_10ac5d18)
#define g_brRoot5C60 (*(Root48F10 * *)&g_2908)
#define g_i0AB3F4 g_AB94
#define g_tab (*(struct Dim (*)[7])&g_tab)
#define s_RallySeason_BRF_100acb20 (s_RallySeason_BRF[0])
/* functions */
#define FUN_1003b350 BrSaveNameCommitRallySeason
#define FUN_1003b580 BrSaveProbeRallySeason
