/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10ac5d08 (*(char * *)&DAT_10ac5d08)
#define DAT_10af2094 (*(void * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_AA29F4 g_brUipAA29F4
#define g_aBrA9D618 DAT_10ac46a0
#define g_br0AA010 (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br0AC304 (*(int32_t *)&DAT_100abaa4)
#define g_br0AC6A4 (*(uint16_t *)&g_ABE44)
#define g_brAA26F0 (DAT_10ac5a48[0])
#define g_brAA26F4 (g_aBrAA26F4[0])
#define g_brAA26F5 (g_aBrAA26F4[1])
#define g_brAA284C g_nAA284C
#define g_brAA2854 (*(int32_t *)&g_track)
#define g_brAA28A4 (*(int32_t *)&g_brIdx5BFC)
#define g_brAA28B0 (*(int32_t *)&DAT_10ac5c08)
#define g_brAA28B4 (*(int32_t *)&DAT_10ac5c0c)
#define g_brAA28C4 DAT_10ac5c1c
#define g_brAA28F0 g_br6EE1D8_fLowAlways
#define g_brAA28FC (*(int32_t *)&DAT_10ac5c54)
#define g_brAA2934 (*(BrPhase * *)&g_5C8C)
#define g_brAA2938 (*(BrPhase * *)&g_5C90)
#define g_brAA293C (*(BrPhase * *)&g_5C94)
#define g_brAA296C (*(BrPhase * *)&DAT_10ac5cc4)
#define g_brAA2970 (*(BrPhase * *)&DAT_10ac5cc8)
#define g_brAA29B4 (*(BrPhase * *)&DAT_10ac5d0c)
#define g_brAA29F4 (*(BrPhase * *)&g_brUipAA29F4)
#define g_brAA2A48 (*(int32_t *)&g_brKeyRingPos)
#define g_brAA2AD4 (g_BrDikEdge[21])
#define g_brAA2E80 (*(BrObjAA2E80 * *)&g_pBrAA2E80)
#define g_brAA33E4 (*(int32_t *)&DAT_10ac6744)
#define g_brPhaseAA2904 (*(BrPhase_ * *)&g_brPAA29B8)
#define g_brPhaseAA292C (*(BrPhase_ * *)&g_brPhaseAA292C)
#define g_brPhaseAA293C (*(BrPhase_ * *)&g_5C94)
#define g_brPhaseAA2974 (*(BrPhase_ * *)&g_brPhaseAA2974)
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrExt_1003E0E0 BrInputOrPlaybackActive
#define BrExt_10041AC0 BrMenuCopyTrackName
#define BrExt_10043260 CtlC7B0_fn
#define BrExt_10043330 CtlC880_fn
#define BrExt_10045C90 Ctl3F130_fn
#define BrExt_10047660 BrCheatCodeScan
#define BrExt_10072AF0 BrSub10072AF0
#define BrPhaseActivate_10045110 CtlE660_fn
#define BrPhaseActivate_10045BC0 CtlF060_fn
#define BrPhaseLeave_10046D20 BrOpt6D20
#define BrSub10037B20 BrSub1003E510
#define BrSub10037C90 BrSub1003E680
#define BrSub1003F130 Ctl3F130_fn
#define BrOptObjCtor BrOptObjCtor
