/* generated by ports/64b/tools/unify.py */
#define DAT_106b7ab8 (*(funcptr *)&BrGlFlipHook)
#define PTR_FUN_100776C0 PTR_FUN_100776c0
/* functions */
#define BrSub1005F5A0 BrSprFontDraw
#define FUN_100014e0 BrGlideLfbWrite
#define FUN_10041930 BrVtInit41930
#define FUN_10041cc0 BrPhaseDtor_10048870
