/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(char *)&g_hot0)
#define DAT_100abcc0 (*(int (*)[])&g_aBrAC520)
#define DAT_100acad8 (g_strA[0])
#define DAT_10ac5b98 g_brSel5B98
#define DAT_10ac5d64 g_brKind5D64
#define g_AA29C8 (*(BrCtl * *)&g_brUipAA29C8)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrPhaseLeave_10046560 BrOpt6560
#define FUN_10039620 BrCtlBindingToItem
#define FUN_10039990 BrCtrlBindPoll_10039990
