/* generated by ports/64b/tools/unify.py */
#define g_aNetSlot (*(NetSlot (*)[])&g_aBrNetSlot)
#define g_hNetMutex g_hBrNetMutex
#define g_netStamp g_brNetPktTick
#define g_netTarget g_brP277B40
/* functions */
#define BrNetClock_100037D0 BrTicks30FromMs
#define InitPkt BrNetPktStamp
