/* generated by ports/64b/tools/unify.py */
#define DAT_1007b264 g_id
#define DAT_10226e7c g_226e7c
#define DAT_10273328 g_brP277B40
#define DAT_10273330 (*(int *)&g_br277B48)
#define DAT_10af3bb4 (*(unsigned char *)((char *)&g_aBrRaceCar + 0x29AC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3bb5 (*(unsigned char *)((char *)&g_aBrRaceCar + 0x29AD)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3bb6 (*(unsigned char *)((char *)&g_aBrRaceCar + 0x29AE)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71648 (*(int *)&g_aBrCfgPlayerName)
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define FUN_10004900 BrNetSend4900
#define FUN_10004ad0 BrNetSend4AD0
#define FUN_10004d30 BrPalFetch
