/* generated by ports/64b/tools/unify.py */
#define DAT_11849e60 g_hBrSndWake86
#define DAT_1184c070 (*(int *)&DAT_1184c070)
#define DAT_1184c074 (*(int *)&DAT_1184c074)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_aBr178FEF8 (*(int *)&g_aBr178FEF8)
#define g_aBrPeer71 (*(int *)&g_aBrPeer71)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub10071560 BrNetPeerMutexInit
#define BrSub10071630 BrSecondTickStart
