/* generated by ports/64b/tools/unify.py */
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_10226e80 g_226e80
#define DAT_10ac315c (*(int *)((char *)&g_aBrNetSession + 0xDC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10ac4090 g_guardB
#define DAT_10b71648 g_aBrCfgPlayerName
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brAA287C (*(int32_t *)&DAT_10ac5bd4)
#define g_brUiapJoinBlob (*(void *const * *)&g_brPAA29D4)
#define g_brUinAA2880 (*(int32_t *)&g_5BD8)
#define g_tab (*(struct Dim (*)[7])&g_tab)
