/* generated by ports/64b/tools/unify.py */
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_10396f08 g_aBr39B720
#define DAT_105bc72c g_brOwner5BC72C
#define DAT_10ac3e80 g_aBrA9CDF0
#define DAT_10ac408c g_guardA
#define DAT_10ac4090 g_guardB
#define DAT_10ac4098 g_brPA9D008
#define DAT_10ac5bdc g_host
#define DAT_10ac5d2c g_brPAA29D4
#define DAT_10ac5d30 g_brPAA29D8
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brAA287C DAT_10ac5bd4
#define g_brAA2884 g_host
#define g_brAA2888 g_inited
#define g_brP277B40 (*(int * *)&g_brP277B40)
#define g_brP680584 g_brOwner5BC72C
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_10005f50 BrNetShutdown
#define FUN_10032320 BrDpLobbyConnect
#define FUN_10035bb0 BrComCreateInstance
#define FUN_10035be0 BrDpShutdown
#define FUN_10035c50 BrNetSessionHost
#define FUN_10036300 BrNetEnumSessionsStart
#define FUN_10036650 BrSub1003CFC0
#define FUN_10036b20 BrDpAddressBuild
#define FUN_10037260 BrNetErrMsgBox
#define FUN_1006d280 BrStrGet
