/* generated by ports/64b/tools/unify.py */
#define DAT_11849e60 g_hBrSndWake86
#define g_1826BD0 (*(int *)&g_aBrPeerMsg)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_aBr178FEF8 (*(Br71510Rec (*)[1])&g_aBr178FEF8)
#define g_aBrNetSendBs (*(BrNetSendBs (*)[16])&g_aBrPeerMsg)
#define g_aBrPeer71 (*(Br71Peer (*)[])&g_aBrPeer71)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub10003580 FUN_100038f0
