/* generated by ports/64b/tools/unify.py */
#define DAT_100aabe8 (*(int *)&g_hot0)
#define DAT_10ac5bd8 g_5BD8
#define DAT_10ac5d2c g_brPAA29D4
#define DAT_10ac5d30 g_brPAA29D8
#define g_brP680584 (*(void * *)&g_brOwner5BC72C)
/* functions */
#define FUN_10036130 BrWmHook36130
