/* generated by ports/64b/tools/unify.py */
#define g_br094294 g_id
#define g_br22AAA8 (*(int32_t *)&DAT_102265d8)
#define g_br22B34C (*(int32_t *)&g_226e7c)
#define g_brAD0854 (*(uint8_t (*)[3])((char *)&g_aBrRaceCar + 0x29AC)) /* BR_LP64_BYTE_VIEW */
#define g_brPB4E2E8 g_aBrCfgPlayerName
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrNetSend4760 BrNetSend4AD0
