/* generated by ports/64b/tools/unify.py */
#define DAT_1007b264 g_id
#define DAT_100bcbe8 g_CBE8
#define DAT_1021c90c g_brH220DDC
#define DAT_1021c9b0 (DAT_1021c9b0[0])
#define DAT_1021ce00 (DAT_1021ce00[0])
#define DAT_1021ce40 g_brNetPktTick
#define DAT_1021ce48 (*(int *)&g_i10221318)
#define DAT_1021ce54 g_brH221324
#define DAT_1021ce58 (*(int *)&g_aBrNetSlot)
#define DAT_1021d3c8 (*(char *)((char *)&g_aBrNetSlot + 0x570)) /* BR_LP64_BYTE_VIEW */
#define DAT_10226624 (*(int *)&g_br22AAF4)
#define DAT_10226a30 (*(int *)&DAT_10226a30)
#define DAT_10226a34 g_brH22AF04
#define DAT_10226a44 (*(int *)&g_brRaceTick)
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_10226a60 g_h1022AF30
#define DAT_10226a64 g_hBrNetMutex
#define DAT_10226a6c (*(int *)&g_brPingBestRtt)
#define DAT_10226e7c g_226e7c
#define DAT_10273328 g_brP277B40
#define DAT_10273330 (*(int *)&g_br277B48)
#define DAT_105ccb80 (*(int *)&DAT_105ccb68[6])
#define DAT_105ccb88 (*(int *)&DAT_105ccb68[8])
#define DAT_10af21b0 (*(int *)((char *)&g_aBrRaceCar + 0xFA8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3bb4 (*(unsigned char *)((char *)&g_aBrRaceCar + 0x29AC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3bb5 (*(unsigned char *)((char *)&g_aBrRaceCar + 0x29AD)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3bb6 (*(unsigned char *)((char *)&g_aBrRaceCar + 0x29AE)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71648 g_aBrCfgPlayerName
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br094294 g_id
#define g_br0BD3E0 (*(int32_t *)&g_CBE8)
#define g_br22AAA8 (*(int32_t *)&DAT_102265d8)
#define g_br22B34C (*(int32_t *)&g_226e7c)
#define g_brAD0854 (*(uint8_t (*)[3])((char *)&g_aBrRaceCar + 0x29AC)) /* BR_LP64_BYTE_VIEW */
#define g_brClockOffset DAT_1021c908
#define g_brFlag6909E0 (*(int *)&DAT_105ccb68[8])
#define g_brPB4E2E8 g_aBrCfgPlayerName
#define g_f6C2CFC g_brRaceFlyStep
#define g_i10221318 (*(int *)&g_i10221318)
#define g_tab (*(struct Dim (*)[7])&g_tab)
#define slots (*(BrNetSlot978 (*)[])&g_aBrNetSlot)
/* functions */
#define BrNetAnnounce FUN_100038a0
#define FUN_10004fd0 BrNetSendCarState
#define FUN_100051c0 BrNetSendCarStateDelta
#define FUN_10005330 BrNetBeaconTick
