/* generated by ports/64b/tools/unify.py */
#define DAT_100abaa0 (*(int32_t *)&g_AC300)
#define DAT_100abde8 g_brIdx0ABDE8
#define DAT_100abdf4 g_brSel0ABDF4
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_100bcbe8 g_CBE8
#define DAT_10226e80 g_226e80
#define DAT_10273328 (*(BrDPlay4Obj * *)&g_brP277B40)
#define DAT_105bc72c g_brOwner5BC72C
#define DAT_10ac40a8 (*(char (*)[])&DAT_10ac40a8)
#define g_brP277B40 (*(void * *)&g_brP277B40)
#define g_brPA9D008 (*(int * *)&g_brPA9D008)
/* functions */
#define BrSub10005FE0 BrNetDropMatching
#define BrSub1000BAF0 BrDpAppMsgHandle
#define BrSub100360F0 FUN_1002f790
#define BrSub1003CE80 BrNetSessionApply
#define BrSub1003D0B0 FUN_10036740
#define BrSub10071480 BrNetPeerMsgCancel
#define FUN_10072960 DirectPlayCreate
