/* generated by ports/64b/tools/unify.py */
#define DAT_10ac5bb4 g_5BB4
#define DAT_10ac5e50 (*(int *)&g_BrDikEdge[28])
#define DAT_10ac6050 (*(int *)&g_BrDikEdge[156])
#define DAT_10ac610c (*(int *)&g_BrDikEdge[203])
#define DAT_10ac6114 (*(int *)&g_BrDikEdge[205])
#define DAT_10ac6730 g_act0
#define DAT_10ac6734 (*(int *)&g_act1)
#define DAT_10ac6738 (*(int *)&g_act2)
#define DAT_10ac673c (*(int *)&g_act3)
