/* generated by ports/64b/tools/unify.py */
#define DAT_11849e60 g_hBrSndWake86
#define DAT_1184c070 (*(int *)&DAT_1184c070)
#define g_1826BD0 (*(unsigned char (*)[16][532])&g_aBrPeerMsg)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub1006AFA0 BrNetWriteTagC0
