/* generated by ports/64b/tools/unify.py */
#define DAT_1007b264 g_id
#define DAT_10226a64 (*(HANDLE *)&g_hBrNetMutex)
/* functions */
#define BrAngleWrap_10005C40 BrCarClampUnit
#define BrAngleWrap_10005C70 BrCarClampPosXY
#define BrAngleWrap_10005CA0 BrCarClampPosZ
#define BrQuatNormalise_1006D410 BrVec4Normalise
#define BrVec3Length_100682C0 BrGroundProbeZ
