/* generated by ports/64b/tools/unify.py */
#define DAT_100abde8 (*(DWORD *)&g_brIdx0ABDE8)
#define DAT_100abdf8 (*(DWORD *)&DAT_100abdf8)
#define DAT_100b3014 (*(DWORD *)&g_Br0B380C)
#define DAT_100bcbe8 (*(DWORD *)&g_CBE8)
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_10226a4c (*(int *)&g_brRaceBegin226A4C)
#define DAT_10226e80 (*(DWORD *)&g_226e80)
#define DAT_10273328 g_brP277B40
#define DAT_10ac4090 g_guardB
#define DAT_10ac4098 g_brPA9D008
#define DAT_10ac5d2c (*(char * *)&g_brPAA29D4)
#define DAT_10ac5d30 g_brPAA29D8
#define DAT_10ac5d58 (*(DWORD *)&DAT_10ac5d58)
#define DAT_10ac5d70 (*(DWORD *)&DAT_10ac5d70)
#define DAT_10b71648 g_aBrCfgPlayerName
#define g_brSlot4098 (*(int * *)&g_brPA9D008)
/* functions */
#define BrSub10005B10 BrNetMutexInit
#define BrSub100355F0 BrExt_1003BF60
#define BrSub100356B0 FUN_100356b0
#define BrSub100385E0 BrStubTrue
#define BrSub1003C740 BrDpSessionJoin
#define BrSub1003CE80 BrNetSessionApply
