/* generated by ports/64b/tools/unify.py */
#define g_netHold g_host
#define g_timerArg g_brP277B40
#define g_timerOn g_brPAA29D4
/* functions */
#define BrTick36300 BrNetEnumSessionsStart
#define BrTick36510 BrNetSessionApply
