/* generated by ports/64b/tools/unify.py */
#define DAT_100b3014 (*(unsigned char *)&g_Br0B380C)
#define DAT_1021cdb0 (*(unsigned char *)&DAT_1021cdb0)
#define DAT_1021cdf8 (*(unsigned char *)&g_brCfgPlayers)
#define DAT_1021ce50 (*(unsigned short *)&DAT_1021ce50)
#define DAT_10226a3c (*(unsigned char *)&DAT_10226a3c)
#define DAT_10226a40 (*(unsigned char *)&DAT_10226a40)
#define DAT_10226e80 (*(unsigned char *)&g_226e80)
