/* generated by ports/64b/tools/unify.py */
#define DAT_100abdf8 (*(int32_t *)&DAT_100abdf8)
#define DAT_100b3014 g_Br0B380C
#define DAT_10226e80 (*(int32_t *)&g_226e80)
#define DAT_10273328 (*(void * *)&g_brP277B40)
#define DAT_10ac5d70 (*(int32_t *)&DAT_10ac5d70)
/* functions */
#define BrDpGetSessionDesc FUN_10036740
#define BrDpRefreshSettings BrSub10044540
