/* generated by ports/64b/tools/unify.py */
#define BrG_6909B4 g_BrX06909B4
#define g_brLapBound (*(int32_t *)&g_CBE8)
/* functions */
#define BrCarApplyState BrCarGhostApply_10059A80
#define BrNetCarStateSend FUN_100054a0
#define BrNetSlotPredictOrig BrGhostPickBlend
#define BrSub10005D30 BrGetGlobal_94294
#define BrSub100607B0 BrCarRecordToState
