/* generated by ports/64b/tools/unify.py */
#define DAT_105bc72c g_brOwner5BC72C
#define DAT_10ac5890 (*(int *)&g_aBrAA2538)
#define DAT_10ac5894 (*(int *)((char *)&g_aBrAA2538 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_10ac5bac g_track
/* functions */
#define BrChatLineFinishTwin FUN_10036a30
#define FUN_1006ba60 BrSub10072AF0
