/* generated by ports/64b/tools/unify.py */
#define DAT_117a9b88 g_aBrPeer71
#define DAT_117a9b8c (*(int *)((char *)&g_aBrPeer71 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_117a9b94 (*(unsigned int (*)[])((char *)&g_aBrPeer71 + 0xC)) /* byte view: the object holds no pointers */
#define DAT_117a9bb4 (*(int *)((char *)&g_aBrPeer71 + 0x2C)) /* byte view: the object holds no pointers */
#define DAT_117a9bb8 (*(int *)((char *)&g_aBrPeer71 + 0x30)) /* byte view: the object holds no pointers */
#define DAT_117a9bbc (*(char *)((char *)&g_aBrPeer71 + 0x34)) /* byte view: the object holds no pointers */
#define DAT_117a9bbd (*(char *)((char *)&g_aBrPeer71 + 0x35)) /* byte view: the object holds no pointers */
#define DAT_117a9bbe (*(char *)((char *)&g_aBrPeer71 + 0x36)) /* byte view: the object holds no pointers */
#define DAT_117a9bc0 (*(int (*)[])((char *)&g_aBrPeer71 + 0x38)) /* byte view: the object holds no pointers */
#define DAT_117a9be0 (*(BrCarState (*)[])((char *)&g_aBrPeer71 + 0x58)) /* byte view: the object holds no pointers */
#define DAT_117aa0e0 (*(int *)((char *)&g_aBrPeer71 + 0x558)) /* byte view: the object holds no pointers */
#define DAT_117aa0e4 (*(char *)((char *)&g_aBrPeer71 + 0x55C)) /* byte view: the object holds no pointers */
#define DAT_117aa4e4 (*(int *)((char *)&g_aBrPeer71 + 0x95C)) /* byte view: the object holds no pointers */
#define DAT_117aa4e8 (*(int *)((char *)&g_aBrPeer71 + 0x960)) /* byte view: the object holds no pointers */
#define DAT_117aa4ec (*(int *)((char *)&g_aBrPeer71 + 0x964)) /* byte view: the object holds no pointers */
#define DAT_117aa4f0 (*(int *)((char *)&g_aBrPeer71 + 0x968)) /* byte view: the object holds no pointers */
#define DAT_117b3258 g_aBr178FEF8
#define DAT_117b325c (*(int *)((char *)&g_aBr178FEF8 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_117b3260 (*(unsigned int *)((char *)&g_aBr178FEF8 + 0x8)) /* byte view: the object holds no pointers */
#define DAT_117b3284 (*(int *)((char *)&g_aBr178FEF8 + 0x2C)) /* byte view: the object holds no pointers */
#define DAT_117b3288 (*(int *)((char *)&g_aBr178FEF8 + 0x30)) /* byte view: the object holds no pointers */
#define DAT_117b328c (*(char *)((char *)&g_aBr178FEF8 + 0x34)) /* byte view: the object holds no pointers */
#define DAT_117b328d (*(char *)((char *)&g_aBr178FEF8 + 0x35)) /* byte view: the object holds no pointers */
#define DAT_117b328e (*(char *)((char *)&g_aBr178FEF8 + 0x36)) /* byte view: the object holds no pointers */
#define DAT_117b37b4 (*(char *)((char *)&g_aBr178FEF8 + 0x55C)) /* byte view: the object holds no pointers */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_tab (*(struct Dim (*)[7])&g_tab)
