/* generated by ports/64b/tools/unify.py */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_aBrAA26F0 (*(int32_t (*)[83])&DAT_10ac5a48)
#define g_brCarPhysWeather (*(int32_t *)&DAT_104b15e8)
#define g_brCfgChosenTrack g_Br0B380C
#define g_brRaceMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrMenuACED34 (*(uint8_t * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub1001CA30 BrCarDamageTick
