/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100a9560 (*(signed char (*)[])&g_tblBrA9560)
#define DAT_100b2f00 g_brRaceNDriver
#define DAT_100b2f04 g_BrCarCount
#define DAT_100b3858 g_brRaceNEntrant
#define DAT_100bcbe8 (*(int32_t *)&g_CBE8)
#define DAT_105ccb60 (*(int32_t *)&DAT_105ccb60)
#define DAT_10af0858 (*(unsigned char (*)[])((char *)&g_aBrRaceDriver + 0x60)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af1208 (*(unsigned char (*)[])&g_aBrRaceCar)
#define DAT_10af2110 (*(unsigned char (*)[])((char *)&g_aBrRaceCar + 0xF08)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrX10005DE0 BrNetSlotGetF030
#define BrX10005E70 BrNetSlotName
#define BrX10068260 BrSfxCarBankInit
#define BrX10076AE0 BrEntitySetIndex
#define FUN_10008d60 BrPodNop
