/* generated by ports/64b/tools/unify.py */
#define g_0773C4 g_brRaceFlySpeedA
#define g_0773C8 g_brRaceFlySpeedB
#define g_0773CC g_brRaceFlyBlendA
#define g_0773D0 g_brRaceFlyBlendB
#define g_0A5EA8 (*(int *)&g_brRaceBeginLimitOn)
#define g_0A6B68 (DAT_100a6b68[0])
#define g_0A9358 (*(int *)((char *)&g_brRaceRules + 0x4)) /* BR_LP64_BYTE_VIEW */
#define g_0A935C (*(int *)((char *)&g_brRaceRules + 0x8)) /* BR_LP64_BYTE_VIEW */
#define g_0A9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_0A9368 (*(int *)((char *)&g_brRaceRules + 0x14)) /* BR_LP64_BYTE_VIEW */
#define g_0AA044 g_brMode0AA8B4
#define g_0B2F00 (*(int *)&g_brRaceNDriver)
#define g_0B2F04 (*(int *)&g_BrCarCount)
#define g_0B3014 (*(int *)&g_Br0B380C)
#define g_0B3858 (*(int *)&g_brRaceNEntrant)
#define g_0B55F0 (*(int *)&DAT_100b51e4[1036])
#define g_0B849C (*(int (**)())&PTR_FUN_100b849c)
#define g_0BB2E0 (*(char *)&DAT_100bb2e0)
#define g_0BCBE8 g_CBE8
#define g_0BCDD0 (*(int *)&g_ab0C12A0)
#define g_1778848 (*(int *)&g_brRaceBeginMirrorOff)
#define g_1778850 (*(int *)&g_aBrRaceBeginRecIn)
#define g_18ED1C4 (*(int (**)(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int))&g_pfn18ED1C4)
#define g_18EE588 (*(int *)&g_brRaceNFinished)
#define g_18EEBE8 (*(int *)&g_BrX18ABAD0)
#define g_18EEED8 (*(int *)&g_brRace18EEED8)
#define g_18EEF50 (*(int *)((char *)&g_aBrSfxChan + 0x10)) /* byte view: the object holds no pointers */
#define g_226A44 (*(int *)&g_brRaceTick)
#define g_226A48 (*(int *)&g_brRaceNet)
#define g_226A4C (*(int *)&g_brRaceBegin226A4C)
#define g_226A50 DAT_10226a50
#define g_226E7C g_226e7c
#define g_226E80 g_226e80
#define g_396FAC (*(char (*)[])((char *)&g_aBrSnap + 0x64)) /* BR_LP64_BYTE_VIEW */
#define g_397950 (*(char (*)[])((char *)&g_aBrSnap + 0xA08)) /* BR_LP64_BYTE_VIEW */
#define g_3C2FD0 (*(char (*)[])((char *)&g_aBrSnap + 0x2C088)) /* BR_LP64_BYTE_VIEW */
#define g_4B15E8 DAT_104b15e8
#define g_5BC750 (*(int *)&g_brRaceScript)
#define g_5BC760 g_5bc760
#define g_5BC764 g_brRaceFade
#define g_5BC768 (*(int *)&g_brRaceBeginSeqIdx)
#define g_5BC778 (g_aBrRaceBeginFx[0])
#define g_5BC7B8 (*(int *)&g_brRaceBeginRecArmed)
#define g_5BC7C0 (*(int *)&g_brRaceBeginAirplane)
#define g_5BC7C4 (*(int *)&g_brRaceBeginAirTrigger)
#define g_5BC7C8 (*(int *)&g_brRaceBeginCamMinus1)
#define g_5BC7CC (*(int *)&g_brRaceBeginAirArmed)
#define g_5BC7D0 (*(int *)&g_brRaceBeginPathIdx)
#define g_5BC7D4 (*(int *)&g_brRaceBeginPathLen)
#define g_5BC7D8 g_brRaceBeginPathScale
#define g_5BC7DC g_pBrRaceFlyPos
#define g_5BC7E0 g_pBrRaceFlyAim
#define g_5BC7E4 g_brRaceBeginPathT
#define g_5BC7E8 g_brRaceBeginPathSeg
#define g_5BC7EC (*(float *)&g_brRaceFlyDirPrev)
#define g_5BC7F0 (*(float *)((char *)&g_brRaceFlyDirPrev + 0x4)) /* byte view: the object holds no pointers */
#define g_5BC7F4 (*(float *)((char *)&g_brRaceFlyDirPrev + 0x8)) /* byte view: the object holds no pointers */
#define g_5BC7F8 (*(float *)&g_brRaceFlyDirCur)
#define g_5BC7FC (*(float *)((char *)&g_brRaceFlyDirCur + 0x4)) /* byte view: the object holds no pointers */
#define g_5BC800 (*(float *)((char *)&g_brRaceFlyDirCur + 0x8)) /* byte view: the object holds no pointers */
#define g_5BC804 (*(float *)&g_brRaceFlyDirNext)
#define g_5BC808 (*(float *)((char *)&g_brRaceFlyDirNext + 0x4)) /* byte view: the object holds no pointers */
#define g_5BC80C (*(float *)((char *)&g_brRaceFlyDirNext + 0x8)) /* byte view: the object holds no pointers */
#define g_5BC810 (*(int *)&g_brRaceBeginBestCar)
#define g_5BC880 g_brRaceLightT
#define g_5BC884 g_brRaceBeginSeqT
#define g_5BC888 (*(int *)&g_brRaceBeginSeq888)
#define g_5BC8D8 (*(int *)&g_brRace5BC8D8)
#define g_5BC8DC DAT_105bc8dc
#define g_5BC8E0 (*(int *)&g_aBrRaceBeginRec)
#define g_5BC8E4 (*(int *)&g_aBrRaceBeginRec[4])
#define g_5BC8F8 (*(int *)&g_brRaceLights)
#define g_5BC900 g_BrFpsSamplesA
#define g_5BCAE0 (*(int *)&g_brRaceBeginMovieDone)
#define g_5BCAE4 (*(int *)&g_brRaceClockCount)
#define g_5BCAE8 (*(int *)&g_brRaceBeginFxCount)
#define g_5BCAEC DAT_105bcaec
#define g_5CCB58 (*(int *)&g_brRaceHudA)
#define g_5CCB5C (*(int *)&g_BrX06909B4)
#define g_5CCB60 DAT_105ccb60
#define g_5CCB70 (*(int *)&DAT_105ccb68[2])
#define g_5CCB74 (*(int *)&DAT_105ccb68[3])
#define g_5CCB78 (*(int *)&DAT_105ccb68[4])
#define g_5CCB7C (*(int *)&DAT_105ccb68[5])
#define g_5CCB80 (*(int *)&DAT_105ccb68[6])
#define g_5CCB88 (*(int *)&DAT_105ccb68[8])
#define g_5CCB8C (*(int *)&DAT_105ccb68[9])
#define g_5CCB90 (*(int *)&DAT_105ccb68[10])
#define g_5CCB94 (*(int *)&DAT_105ccb68[11])
#define g_5CCB98 (*(int *)&DAT_105ccb68[12])
#define g_5CCB9C (*(int *)&DAT_105ccb68[13])
#define g_5CCBA0 (*(int *)&DAT_105ccb68[14])
#define g_5CCBA4 (*(int *)&DAT_105ccb68[15])
#define g_6E7970 (*(int *)&g_brRaceSpecialM)
#define g_6E86B8 (BrG_6C1628[0])
#define g_6E86C8 (*(int *)&BrG_6C1628[4])
#define g_6E86CC (*(int *)&BrG_6C1628[5])
#define g_6E8720 (*(int *)&g_brRaceBegin6E8720)
#define g_6E9A34 (*(int *)&g_brRace6E9A34)
#define g_6E9D8C g_brRaceFlyStep
#define g_6EA3F4 (*(int *)&g_brRaceBeginDifficulty)
#define g_6EC760 (*(int *)&g_brRace6EC760)
#define g_6ED684 (*(int *)((char *)&g_aBrEntRecs + 0x54)) /* byte view: the object holds no pointers */
#define g_6ED6AC (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_6ED6B0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define g_6ED6B4 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define g_6ED6D8 (*(int *)((char *)&g_aBrEntRecs + 0xA8)) /* byte view: the object holds no pointers */
#define g_6ED708 (*(char (*)[])&g_aBrEnts)
#define g_6ED9C0 (*(char (*)[])((char *)&g_aBrEnts + 0x2B8)) /* BR_LP64_BYTE_VIEW */
#define g_6EED38 g_BrDrawTrackFlags
#define g_6EEE3C (*(int *)&g_aBrRaceSpecial)
#define g_6EEEFC (*(int *)&g_brRaceBeginSpecialsN)
#define g_AF07F8 (*(int *)&g_aBrRaceDriver)
#define g_AF0858 (*(char (*)[])((char *)&g_aBrRaceDriver + 0x60)) /* BR_LP64_BYTE_VIEW */
#define g_AF0860 (*(int *)((char *)&g_aBrRaceDriver + 0x68)) /* BR_LP64_BYTE_VIEW */
#define g_AF1208 (*(Driver (*)[])&g_aBrRaceCar)
#define g_AF134C (*(int *)((char *)&g_aBrRaceCar + 0x144)) /* BR_LP64_BYTE_VIEW */
#define g_AF1350 (*(char (*)[])((char *)&g_aBrRaceCar + 0x148)) /* BR_LP64_BYTE_VIEW */
#define g_AF1370 (*(int *)((char *)&g_aBrRaceCar + 0x168)) /* BR_LP64_BYTE_VIEW */
#define g_AF1374 (*(int *)((char *)&g_aBrRaceCar + 0x16C)) /* BR_LP64_BYTE_VIEW */
#define g_AF1575 (*(char *)((char *)&g_aBrRaceCar + 0x36D)) /* BR_LP64_BYTE_VIEW */
#define g_AF2090 (*(int *)((char *)&g_aBrRaceCar + 0xE88)) /* BR_LP64_BYTE_VIEW */
#define g_AF2094 (*(int *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_AF2098 (*(int *)((char *)&g_aBrRaceCar + 0xE90)) /* BR_LP64_BYTE_VIEW */
#define g_AF209C (*(int *)((char *)&g_aBrRaceCar + 0xE94)) /* BR_LP64_BYTE_VIEW */
#define g_AF20A0 (*(int *)((char *)&g_aBrRaceCar + 0xE98)) /* BR_LP64_BYTE_VIEW */
#define g_AF20A4 (*(int *)((char *)&g_aBrRaceCar + 0xE9C)) /* BR_LP64_BYTE_VIEW */
#define g_AF2110 (*(int *)((char *)&g_aBrRaceCar + 0xF08)) /* BR_LP64_BYTE_VIEW */
#define g_AF21F4 (*(float *)((char *)&g_aBrRaceCar + 0xFEC)) /* BR_LP64_BYTE_VIEW */
#define g_AF2200 (*(int *)((char *)&g_aBrRaceCar + 0xFF8)) /* BR_LP64_BYTE_VIEW */
#define g_AF2204 (*(int *)((char *)&g_aBrRaceCar + 0xFFC)) /* BR_LP64_BYTE_VIEW */
#define g_AF2208 (*(int *)((char *)&g_aBrRaceCar + 0x1000)) /* BR_LP64_BYTE_VIEW */
#define g_AF220C (*(int *)((char *)&g_aBrRaceCar + 0x1004)) /* BR_LP64_BYTE_VIEW */
#define g_AF2210 (*(int *)((char *)&g_aBrRaceCar + 0x1008)) /* BR_LP64_BYTE_VIEW */
#define g_AF2214 (*(int *)((char *)&g_aBrRaceCar + 0x100C)) /* BR_LP64_BYTE_VIEW */
#define g_AF393C (*(int *)((char *)&g_aBrRaceCar + 0x2734)) /* BR_LP64_BYTE_VIEW */
#define g_AF3940 (*(int *)((char *)&g_aBrRaceCar + 0x2738)) /* BR_LP64_BYTE_VIEW */
#define g_AF3944 (*(int *)((char *)&g_aBrRaceCar + 0x273C)) /* BR_LP64_BYTE_VIEW */
#define g_AF397C (*(float *)((char *)&g_aBrRaceCar + 0x2774)) /* BR_LP64_BYTE_VIEW */
#define g_AF3988 (*(int *)((char *)&g_aBrRaceCar + 0x2780)) /* BR_LP64_BYTE_VIEW */
#define g_AF39CC (*(int *)((char *)&g_aBrRaceCar + 0x27C4)) /* BR_LP64_BYTE_VIEW */
#define g_AF3A10 (*(int *)((char *)&g_aBrRaceCar + 0x2808)) /* BR_LP64_BYTE_VIEW */
#define g_AF3A98 (*(int *)((char *)&g_aBrRaceCar + 0x2890)) /* BR_LP64_BYTE_VIEW */
#define g_AF3B14 (*(int *)((char *)&g_aBrRaceCar + 0x290C)) /* BR_LP64_BYTE_VIEW */
#define g_AF3B54 (*(int *)((char *)&g_aBrRaceCar + 0x294C)) /* BR_LP64_BYTE_VIEW */
#define g_AF3BAC (*(int *)((char *)&g_aBrRaceCar + 0x29A4)) /* BR_LP64_BYTE_VIEW */
#define g_AF3BB4 (*(char *)((char *)&g_aBrRaceCar + 0x29AC)) /* BR_LP64_BYTE_VIEW */
#define g_AF3BB5 (*(char *)((char *)&g_aBrRaceCar + 0x29AD)) /* BR_LP64_BYTE_VIEW */
#define g_AF3BB6 (*(char *)((char *)&g_aBrRaceCar + 0x29AE)) /* BR_LP64_BYTE_VIEW */
#define g_AF3BC8 (*(Driver (*)[])((char *)&g_aBrRaceCar + 0x29C0)) /* BR_LP64_BYTE_VIEW */
#define g_AF3D70 (*(Driver (*)[])((char *)&g_aBrRaceCar + 0x2B68)) /* BR_LP64_BYTE_VIEW */
#define g_AF4C00 (*(int *)((char *)&g_aBrRaceCar + 0x39F8)) /* BR_LP64_BYTE_VIEW */
#define g_AF4C04 (*(int *)((char *)&g_aBrRaceCar + 0x39FC)) /* BR_LP64_BYTE_VIEW */
#define g_AF4C08 (*(int *)((char *)&g_aBrRaceCar + 0x3A00)) /* BR_LP64_BYTE_VIEW */
#define g_AF4C0C (*(int *)((char *)&g_aBrRaceCar + 0x3A04)) /* BR_LP64_BYTE_VIEW */
#define g_AF6724 (*(int *)((char *)&g_aBrRaceCar + 0x551C)) /* BR_LP64_BYTE_VIEW */
#define g_AF6730 (*(int *)((char *)&g_aBrRaceCar + 0x5528)) /* BR_LP64_BYTE_VIEW */
#define g_B1CF10 (*(int *)&g_BrCamHold2)
#define g_B71290 (*(int *)&g_BrCtrlCfg)
#define g_B71530 (*(int *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_B71648 g_aBrCfgPlayerName
#define g_B71A68 (*(int *)&g_brItemIconCount)
#define g_B71A6C (*(int *)&g_brRaceB71A6C)
#define g_B72F48 g_navArg
#define g_B73528 (*(int (**)())&DAT_10b73528)
#define g_B7352C (*(int (**)())&DAT_10b7352c)
#define g_BCAB0 (g_apBrRaceDiff[0])
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define sub_100023F0 BrTimeFormat
#define sub_10002460 BrRaceSelFromMenu
#define sub_10002AF0 BrCdTrackPlay
#define sub_10002C00 BrCdTrackRandom
#define sub_10002D30 BrCdVolumeSet
#define sub_10002EB0 BrCdPause
#define sub_10002F10 BrCdResume
#define sub_10004E00 BrNetOpenAnnounce
#define sub_10004F90 BrNetLockSetIfZero221314
#define sub_10005400 BrNetSlotBroadcastTick
#define sub_10005CD0 BrNetReset
#define sub_100060A0 BrGetGlobal_94294
#define sub_100060B0 BrNetStackPop
#define sub_10006100 BrNetStackPop221288
#define sub_10006250 BrNetSlotSetName
#define sub_10006400 BrNetSetF10220DD0
#define sub_10006430 BrNetClearF10220DD0
#define sub_10006460 FUN_10006460
#define sub_100064D0 BrNetCheckDeadline
#define sub_10008D60 BrPodNop
#define sub_10008EF0 BrLogPrint
#define sub_10009BA0 BrDPlayGetCurrentPlayers
#define sub_1000CB80 BrClearTables_1000F620
#define sub_100131E0 BrSnapInterpDraw
#define sub_10013E80 BrRaceBeginResetOnce
#define sub_10013F00 BrClearFlag_AB504
#define sub_10013F20 BrSnapPickSlot
#define sub_10014CB0 FUN_10014cb0
#define sub_10016C90 BrWeatherStepParticles
#define sub_100181A0 BrFadeSetTarget
#define sub_10018230 BrFadeSetTargetA
#define sub_10018290 BrFadeSetTargetB
#define sub_10018310 BrFadeIsClosing
#define sub_10018340 BrFadeIsSettled
#define sub_100189C0 BrFlagInit_1002B950
#define sub_10019890 BrRaceHudFrame
#define sub_10019900 BrRaceEnterOutro
#define sub_10019930 BrRaceCueLayout
#define sub_10019980 BrRaceCueRewind
#define sub_100199A0 BrRaceCarCtlOutro
#define sub_10019A10 BrRaceDriverReset
#define sub_10019A40 BrRaceClockReset
#define sub_1001C6A0 BrCarTableAdd
#define sub_1001C7A0 BrCarTableRemove
#define sub_1001C810 BrCarStateSave
#define sub_1001C890 BrCarStateRestore
#define sub_1001C9D0 BrSelLookup
#define sub_10029D70 BrMat4Mul
#define sub_1002A590 BrMat4RotateAxis
#define sub_1002BF24 BrFrameBeginRec
#define sub_1002CB3F BrNop_1002CB3F
#define sub_1002E13B BrReset_1002E13B
#define sub_1002E186 BrFrameClockStep
#define sub_1002E317 BrGameStepSet
#define sub_1002ECAC BrAnimSetOnce
#define sub_10030270 BrModelLoad
#define sub_10031140 BrTrackLoadHandling
#define sub_100311C0 BrTrackLoad
#define sub_100325B0 BrExt_10038F30
#define sub_10032680 BrInit220B20
#define sub_10033B50 BrPfxReset
#define sub_10033BB0 BrPfxTick
#define sub_10033C90 BrPfxSaveState
#define sub_100342B0 BrVec3Cross
#define sub_10034390 BrVec3ScaleBy
#define sub_100344D0 br_dl_normalise
#define sub_10034560 BrVec3Sub
#define sub_10034620 BrVec3Lerp
#define sub_100346D0 BrVec3Midpoint
#define sub_10034760 BrVec3Dist
#define sub_100347F0 BrVec3Length
#define sub_10034870 BrVec3TransformDivW
#define sub_100353C0 BrStore_1003BD40
#define sub_10037180 BrDPlayMsg6SendSelf
#define sub_10059DC0 BrUiSelAInc
#define sub_10059DE0 BrUiSelADec
#define sub_10059E30 BrUiSelBInc
#define sub_10059E50 BrUiSelBDec
#define sub_1005C450 BrZeroRegions
#define sub_1005D050 BrCtlHuman
#define sub_1005E690 BrCtlAi
#define sub_1005F580 BrRankAssign
#define sub_100609D0 BrWrap_10067960
#define sub_100609F0 BrWrap_10067980
#define sub_10060A10 BrWrap_100679A0
#define sub_10060DF0 BrSfxSrcBeep
#define sub_10060E00 BrSfxSrcBeep2
#define sub_10060E10 BrSndNearestInvalidate
#define sub_10060E30 BrSndNearestReset
#define sub_10060F40 BrSndNearestCommit
#define sub_100611F0 BrSndNearestOfferTrack
#define sub_10061280 BrSndNearestOfferDefault
#define sub_10061310 FUN_10061310
#define sub_10061440 BrSndTableClear
#define sub_100627B0 BrRaceDifficultySet
#define sub_10062830 BrRaceDifficultyApply
#define sub_10063A00 BrReplayReset
#define sub_10063A40 BrSet_1006AA90
#define sub_10063AD0 BrReplayAdvance
#define sub_10063B60 BrReplayRewind
#define sub_10063CC0 BrReplaySeek
#define sub_10063DD0 BrCollRespReset
#define sub_10069A80 BrGhostLoad
#define sub_1006A070 BrSetMode5
#define sub_1006B4F0 BrX10072580
#define sub_1006BD70 BrSndBankMute
#define sub_1006BDD0 FUN_1006bdd0
#define sub_1006C460 BrSndBankFree
#define sub_1006D280 BrStrGet
#define sub_1006E030 BrFontTexInitAll
#define sub_1006E280 BrSub10075020
#define sub_1006E360 BrTimeUpdate
#define sub_1006E3B0 BrSub10075150
#define sub_10072210 BrFfbUpdateSpring
