/* generated by ports/64b/tools/unify.py */
#define g_brCarPhysWeather (*(int32_t *)&DAT_104b15e8)
#define g_brCfgChosenTrack g_Br0B380C
#define g_brRaceDiffRow (*(int32_t *)((char *)&g_aBrRaceCar + 0xE64)) /* BR_LP64_BYTE_VIEW */
#define g_brRaceMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_brRaceNCar g_BrCarCount
#define g_brRaceNLap (*(int32_t *)&g_CBE8)
#define g_brRaceReplay (DAT_105ccb68[8])
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrRaceRecords (*(BrRaceRecords * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
/* functions */
#define BrExt_10008D60 BrPodNop
#define BrFtolTrunc BrFtolArg
