/* generated by ports/64b/tools/unify.py */
#define BrPathCrossCount (*(int32_t *)((char *)&g_aBrRaceCar + 0x84B8)) /* BR_LP64_BYTE_VIEW */
#define BrPathWrapCount (*(int32_t *)((char *)&g_aBrRaceCar + 0x893C)) /* BR_LP64_BYTE_VIEW */
#define DAT_106eed70 (*(PwSeg (*)[])&g_aBrRaceGate)
#define DAT_106eee38 (*(int *)&g_brRaceNGate)
#define DAT_10af07f0 (*(int *)&g_brRacePathIndex)
#define DAT_10b1ca20 (*(int *)&DAT_10b1ca20)
#define DAT_10b1cbec (*(PwNode * *)&g_brRacePathNode)
#define DAT_10b1ce98 g_brRacePathPos
#define DAT_10b1cea4 (*(int *)&DAT_10b1cea4)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brRacePathIndex (*(int *)&g_brRacePathIndex)
#define g_f6C2CFC g_brRaceFlyStep
#define g_tab (*(struct Dim (*)[7])&g_tab)
