/* generated by ports/64b/tools/unify.py */
#define DAT_105bc858 (*(int *)&g_br6806B0)
#define DAT_10af07f8 g_aBrRaceDriver
#define g_aBrRaceBeginLink (*(int32_t (*)[4])((char *)&g_aBrRaceCar + 0x39F8)) /* BR_LP64_BYTE_VIEW */
#define g_aBrRaceBeginName g_aBrCfgPlayerName
#define g_aBrRaceBeginNameCopy (*(char (*)[64])((char *)&g_aBrRaceCar + 0x148)) /* BR_LP64_BYTE_VIEW */
#define g_aBrRaceClockRing g_BrFpsSamplesA
#define g_brCarPhysWeather (*(int32_t *)&DAT_104b15e8)
#define g_brCfgChosenCar (*(int32_t *)&g_226e7c)
#define g_brCfgChosenTrack g_Br0B380C
#define g_brCfgChosenWeather (*(int32_t *)&g_226e80)
#define g_brRaceBegin6E86C8 (BrG_6C1628[4])
#define g_brRaceBeginAF397C (*(float *)((char *)&g_aBrRaceCar + 0x2774)) /* BR_LP64_BYTE_VIEW */
#define g_brRaceBeginAF6724 (*(int32_t *)((char *)&g_aBrRaceCar + 0x551C)) /* BR_LP64_BYTE_VIEW */
#define g_brRaceBeginActive (*(int32_t *)((char *)&g_aBrEntRecs + 0x54)) /* byte view: the object holds no pointers */
#define g_brRaceBeginB1CF10 g_BrCamHold2
#define g_brRaceBeginDrawn (*(int32_t *)((char *)&g_aBrEntRecs + 0xA8)) /* byte view: the object holds no pointers */
#define g_brRaceBeginFade (DAT_105ccb68[9])
#define g_brRaceBeginIntroSide (DAT_105ccb68[13])
#define g_brRaceBeginLights (*(int32_t *)((char *)&g_aBrRaceCar + 0xE88)) /* BR_LP64_BYTE_VIEW */
#define g_brRaceBeginNTexSet (*(int32_t *)&g_brMode0AA8B4)
#define g_brRaceBeginPathLeft g_pBrRaceFlyPos
#define g_brRaceBeginPathRight g_pBrRaceFlyAim
#define g_brRaceBeginRamped (DAT_105ccb68[12])
#define g_brRaceBeginRecLen g_brRace5BC8D8
#define g_brRaceBeginStage (*(int32_t *)&g_5bc760)
#define g_brRaceClockAccum (*(uint32_t *)&DAT_105ccb68[5])
#define g_brRaceClockCursor (*(int32_t *)((char *)&g_brRaceRules + 0x8)) /* BR_LP64_BYTE_VIEW */
#define g_brRaceClockLast (*(uint32_t *)&DAT_105ccb68[10])
#define g_brRaceCueArmed (*(int32_t *)((char *)&g_aBrRaceCue + 0xC)) /* byte view: the object holds no pointers */
#define g_brRaceNCar g_BrCarCount
#define g_brRacePaused g_BrX06909B4
#define g_brRaceReplay (DAT_105ccb68[8])
#define g_brRaceSubstate (DAT_105ccb68[11])
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrRaceBeginSession (*(void * *)((char *)&g_aBrRaceCar + 0x144)) /* BR_LP64_BYTE_VIEW */
#define g_pBrRaceCar g_aBrRaceCar
#define g_pBrRaceDriver g_aBrRaceDriver
/* functions */
#define BrCarCtlChain_1006F170 BrCarStep
#define BrExt_10008D60 BrPodNop
#define BrExt_10019840 BrS17DrawGated
#define BrExt_10032E40 BrCarTrailStep
#define BrRaceStepFrame BrRaceStep
#define FUN_1005f530 BrDriverAssetsFree
#define FUN_1006e360 BrTimeUpdate
#define FUN_1006e3f0 br86_timer_restart
