/* generated by ports/64b/tools/unify.py */
#define DAT_106e9d8c (*(int *)&g_brRaceFlyStep)
#define DAT_106ec740 (*(int *)&DAT_106ec740)
#define DAT_106ec744 (*(int *)((char *)&DAT_106ec740 + 0x4)) /* byte view: the object holds no pointers */
