/* generated by ports/64b/tools/unify.py */
#define DAT_100b2f04 (*(int *)&g_BrCarCount)
#define g_226A48 (*(int *)&g_brRaceNet)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brRaceAirSuppressA (*(int32_t *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define g_brRaceAirSuppressB (*(int32_t *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define g_brRaceAirSuppressC (*(int32_t *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define g_brRaceBeep (DAT_105ccb68[3])
#define g_brRaceFlyNode g_brRaceBeginPathIdx
#define g_brRaceFlyNodeN g_brRaceBeginPathLen
#define g_brRaceFlyRemain g_brRaceBeginPathT
#define g_brRaceFlyScale g_brRaceBeginPathScale
#define g_brRaceFlySegLen g_brRaceBeginPathSeg
#define g_brRaceHudB (DAT_105ccb68[4])
#define g_brRaceNCar g_BrCarCount
#define g_brRacePaused g_BrX06909B4
#define g_brRaceReplay (DAT_105ccb68[8])
#define g_brRaceSpecialN g_brRaceBeginSpecialsN
#define g_brRaceStepDt g_brRaceFlyStep
#define g_brRaceSubstate (DAT_105ccb68[11])
#define g_brRaceTrack g_Br0B380C
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrRaceCar g_aBrRaceCar
#define g_pBrRaceDriver g_aBrRaceDriver
#define g_pBrRaceObjRec (*(uint8_t * *)&g_BrDrawTrackFlags)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub10001CF0 BrCamChaseStep
#define BrSub1005ACE0 BrCarWheelSteerStep_1005ACE0
#define BrRaceDriverPost BrRaceDriverPost
