/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b2fd8 (*(unsigned char (*)[])&g_aBr0B37D0)
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_10af1208 (*(unsigned char (*)[])&g_aBrRaceCar)
#define DAT_10af2094 (*(unsigned char * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3bb0 (*(int *)((char *)&g_aBrRaceCar + 0x29A8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b1cbf0 (*(unsigned char (*)[])&g_brPairStaticA)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrMenuACED34 (*(uint8_t * *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_1006ff00 BrEntityBindAux
