/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b2f00 (*(int *)&g_brRaceNDriver)
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_106eed48 g_pBrRaceLapRec
#define PTR_PTR_100bcab0 (*(char * (*)[])&g_apBrRaceDiff)
