/* generated by ports/64b/tools/unify.py */
#define DAT_10b7364c (*(unsigned int *)&g_BrReplayCount[1])
#define DAT_10b73668 (*(int *)&g_BrReplayBuf)
#define DAT_10cf3668 (*(int *)&g_BrReplayBuf[1572864])
#define g_1750308 (*(uint32_t *)&g_BrReplayOn)
#define g_178FEE8 (*(uint32_t *)&g_178FEE8)
#define g_690A20 (*(uint32_t *)&g_aBrTexSlot[192992])
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_BrReplayOn (*(int *)&g_BrReplayOn)
#define g_a220B20 (*(int *)&g_a220B20)
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrExt_10075020 BrSub10075020
#define FUN_1002f282 BrSessionReinitVideo
