/* generated by ports/64b/tools/unify.py */
#define BrG_6C7CB8 g_pBrRaceLapRec
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrFtolTrunc BrFtolArg
#define FUN_1006e5c0 BrCarTrackLocate
