/* generated by ports/64b/tools/unify.py */
#define BrG_6C661C (*(int *)((char *)&g_aBrEntRecs + 0x7C)) /* byte view: the object holds no pointers */
#define BrG_6C6624 (*(int *)((char *)&g_aBrEntRecs + 0x84)) /* byte view: the object holds no pointers */
#define DAT_1007b320 g_7b320
#define DAT_1007b324 g_7b324
#define DAT_1007b328 g_7b328
#define DAT_1007b32c g_7b32c
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b2f04 (*(int *)&g_BrCarCount)
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_10226a44 (*(int *)&g_brRaceTick)
#define DAT_10226e80 g_226e80
#define DAT_104abb24 (*(float *)&g_brRace4ABB24)
#define DAT_105bc8d8 (*(int *)&g_brRace5BC8D8)
#define DAT_105ccb80 (*(int *)&DAT_105ccb68[6])
#define DAT_106ed6a8 (*(int *)((char *)&g_aBrEntRecs + 0x78)) /* byte view: the object holds no pointers */
#define DAT_106ed6b0 (*(int *)((char *)&g_aBrEntRecs + 0x80)) /* byte view: the object holds no pointers */
#define DAT_10af2094 (*(int *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define g_brCarPhysWeather (*(int32_t *)&DAT_104b15e8)
#define g_brCfgChosenWeather (*(int32_t *)&g_226e80)
#define g_brCfgGameMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_brCfgHandlingType (*(int32_t *)&g_7b320)
#define g_brCfgSuspensionType (*(int32_t *)&g_7b328)
#define g_brCfgTireType (*(int32_t *)&g_7b32c)
#define g_brCfgTransmission (*(int32_t *)&g_7b324)
#define g_brRace4ABB20 DAT_104abb20
#define g_brRace5CCB80 (DAT_105ccb68[6])
#define g_brRace6ED6DC (*(int32_t *)((char *)&g_aBrEntRecs + 0xAC)) /* byte view: the object holds no pointers */
#define g_brRaceB71A68 (*(int32_t *)&g_brItemIconCount)
#define g_brRaceNCar g_BrCarCount
#define g_f6C2CFC g_brRaceFlyStep
#define g_pBrRaceCar g_aBrRaceCar
/* functions */
#define BrEntInit_1002F680 BrEntInit
#define BrRaceNullStep BrPodNop
#define BrRaceStep_10019A70 BrRaceStep
#define FUN_1002db88 BrEntGfxRebindAll
#define FUN_1005c560 BrRaceCarReset
#define FUN_100627b0 BrRaceDifficultySet
#define FUN_10062850 BrRaceEntrantCountSet
#define FUN_100703a0 BrSub100770C0
