/* generated by ports/64b/tools/unify.py */
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b3858 (*(int *)&g_brRaceNEntrant)
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_105ccb5c (*(int *)&g_BrX06909B4)
#define DAT_106e9d8c g_brRaceFlyStep
#define DAT_106eed48 g_pBrRaceLapRec
#define DAT_10af07f0 (*(int *)&g_brRacePathIndex)
#define DAT_10b1cbec g_brRacePathNode
#define DAT_10b1ce98 (*(int *)&g_brRacePathPos)
#define DAT_10b1ce9c (*(int *)((char *)&g_brRacePathPos + 0x4)) /* byte view: the object holds no pointers */
#define DAT_10b1cea0 (*(int *)((char *)&g_brRacePathPos + 0x8)) /* byte view: the object holds no pointers */
#define DAT_118eef48 (*(int *)((char *)&g_aBrSfxChan + 0x8)) /* byte view: the object holds no pointers */
#define DAT_118eef4c (*(int *)((char *)&g_aBrSfxChan + 0xC)) /* byte view: the object holds no pointers */
#define DAT_118eef54 (*(int *)((char *)&g_aBrSfxChan + 0x14)) /* byte view: the object holds no pointers */
#define DAT_118eef60 (*(int *)((char *)&g_aBrSfxChan + 0x20)) /* byte view: the object holds no pointers */
#define DAT_118eef64 (*(int *)((char *)&g_aBrSfxChan + 0x24)) /* byte view: the object holds no pointers */
#define DAT_118eef6c (*(int *)((char *)&g_aBrSfxChan + 0x2C)) /* byte view: the object holds no pointers */
#define DAT_118eef78 (*(int *)((char *)&g_aBrSfxChan + 0x38)) /* byte view: the object holds no pointers */
#define DAT_118eef7c (*(int *)((char *)&g_aBrSfxChan + 0x3C)) /* byte view: the object holds no pointers */
#define DAT_118eef84 (*(int *)((char *)&g_aBrSfxChan + 0x44)) /* byte view: the object holds no pointers */
#define DAT_118eef90 (*(int *)((char *)&g_aBrSfxChan + 0x50)) /* byte view: the object holds no pointers */
#define DAT_118eef94 (*(int *)((char *)&g_aBrSfxChan + 0x54)) /* byte view: the object holds no pointers */
#define DAT_118eef9c (*(int *)((char *)&g_aBrSfxChan + 0x5C)) /* byte view: the object holds no pointers */
#define DAT_118eefa8 (*(int *)((char *)&g_aBrSfxChan + 0x68)) /* byte view: the object holds no pointers */
#define DAT_118eefac (*(int *)((char *)&g_aBrSfxChan + 0x6C)) /* byte view: the object holds no pointers */
#define DAT_118eefb4 (*(int *)((char *)&g_aBrSfxChan + 0x74)) /* byte view: the object holds no pointers */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_f6C2CFC g_brRaceFlyStep
#define g_tab (*(struct Dim (*)[7])&g_tab)
