/* generated by ports/64b/tools/unify.py */
#define DAT_100b2f00 g_brRaceNDriver
#define DAT_100b2f04 g_BrCarCount
#define DAT_100b2fd8 g_aBr0B37D0
#define DAT_100b3014 g_Br0B380C
#define DAT_100b3858 g_brRaceNEntrant
#define DAT_100bcab0 (*(int32_t * (*)[])&g_apBrRaceDiff)
#define DAT_104b15e8 (*(int32_t *)&DAT_104b15e8)
#define DAT_106eed48 g_pBrRaceLapRec
#define DAT_10af07f0 (*(int32_t *)&g_brRacePathIndex)
#define DAT_10af07f8 (*(uint8_t (*)[])&g_aBrRaceDriver)
#define DAT_10af206c (*(int32_t *)((char *)&g_aBrRaceCar + 0xE64)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b1cbec g_brRacePathNode
#define DAT_10b1ce98 (*(int32_t *)&g_brRacePathPos)
#define DAT_10b1ce9c (*(int32_t *)((char *)&g_brRacePathPos + 0x4)) /* byte view: the object holds no pointers */
#define DAT_10b1cea0 (*(int32_t *)((char *)&g_brRacePathPos + 0x8)) /* byte view: the object holds no pointers */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_brRaceMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define FUN_1005edc0 BrMakeEnemyCarColorPanels
