/* generated by ports/64b/tools/unify.py */
#define DAT_100aa068 (*(int *)&g_BrDlTableA)
#define DAT_100b2f04 g_BrCarCount
#define DAT_106ed6fc (*(int *)((char *)&g_aBrEntRecs + 0xCC)) /* byte view: the object holds no pointers */
#define DAT_106ed708 (*(char *)&g_aBrEnts)
#define DAT_10af1208 (*(char *)&g_aBrRaceCar)
#define DAT_10af2110 (*(unsigned char (*)[])((char *)&g_aBrRaceCar + 0xF08)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3bcc (*(char *)((char *)&g_aBrRaceCar + 0x29C4)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define FUN_1002d864 BrDlRecolor
