/* generated by ports/64b/tools/unify.py */
#define g_aBrSpanMax (*(int32_t (*)[64])&g_BrVisColHi)
#define g_aBrSpanMin (*(int32_t (*)[64])&g_BrVisColLo)
#define g_brSpanRowHiG (*(int32_t *)&g_BrVisRowHi)
#define g_brSpanRowLoG (*(int32_t *)&g_BrVisRowLo)
