/* generated by ports/64b/tools/unify.py */
#define DAT_100b559c (*(char (*)[])&DAT_100b51e4[952])
#define DAT_105ccbc4 (*(int *)&DAT_105ccb68[23])
#define DAT_10af2094 (*(struct BrPlayerState (*)[2])((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3cd8 (*(int *)((char *)&g_aBrRaceCar + 0x2AD0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3cdc (*(int *)((char *)&g_aBrRaceCar + 0x2AD4)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3ce0 (*(int *)((char *)&g_aBrRaceCar + 0x2AD8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3ce4 (*(int *)((char *)&g_aBrRaceCar + 0x2ADC)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3ce8 (*(int *)((char *)&g_aBrRaceCar + 0x2AE0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af3cf0 (*(char (*)[])((char *)&g_aBrRaceCar + 0x2AE8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af4bfc (*(int * *)((char *)&g_aBrRaceCar + 0x39F4)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af6858 (*(char (*)[])((char *)&g_aBrRaceCar + 0x5650)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define FUN_10001000 BrAdler32
