/* generated by ports/64b/tools/unify.py */
#define DAT_100a6b84 g_szBrFmt6B84
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_1021c650 (*(int *)&g_a220B20)
#define DAT_1021c654 (*(int *)((char *)&g_a220B20 + 0x4)) /* byte view: the object holds no pointers */
#define DAT_1021c658 (*(int *)((char *)&g_a220B20 + 0x8)) /* byte view: the object holds no pointers */
#define DAT_1021c65c (*(int *)((char *)&g_a220B20 + 0xC)) /* byte view: the object holds no pointers */
#define DAT_1021c660 (*(int *)((char *)&g_a220B20 + 0x10)) /* byte view: the object holds no pointers */
#define DAT_1021c664 (*(int *)((char *)&g_a220B20 + 0x14)) /* byte view: the object holds no pointers */
#define DAT_1021c668 (*(int *)((char *)&g_a220B20 + 0x18)) /* byte view: the object holds no pointers */
#define DAT_1021c66c (*(int *)((char *)&g_a220B20 + 0x1C)) /* byte view: the object holds no pointers */
#define DAT_1021c670 (*(unsigned short *)((char *)&g_a220B20 + 0x20)) /* byte view: the object holds no pointers */
#define DAT_1021c674 (*(int *)((char *)&g_a220B20 + 0x24)) /* byte view: the object holds no pointers */
#define DAT_1021c678 (*(int *)((char *)&g_a220B20 + 0x28)) /* byte view: the object holds no pointers */
#define DAT_10226e80 g_226e80
#define DAT_10ac40f8 (*(unsigned short (*)[])&g_brVal40F8)
#define DAT_10ac4c64 (*(unsigned char *)&g_aBrA9DBD8[1])
#define DAT_10ac5870 g_aBrAA2518
#define DAT_10ac58f8 (g_brFTbl58F8[0])
#define DAT_10ac5a40 g_brVal5A40
#define DAT_10ac5a4c (*(unsigned char (*)[])&g_aBrAA26F4)
#define DAT_10ac5bf8 g_brPhase5BF8
#define DAT_10ac5bfc g_brIdx5BFC
#define DAT_10ac5c10 (*(char *)&DAT_10ac5c10)
#define DAT_10ac5c1c (*(int *)&DAT_10ac5c1c)
#define DAT_10ac5c20 (*(int *)&g_brTime5C20)
#define DAT_10ac5c5c (*(Ui5C5C * *)&g_brPAA29B8)
#define DAT_10af2094 (*(int *)((char *)&g_aBrRaceCar + 0xE8C)) /* BR_LP64_BYTE_VIEW */
#define DAT_10af4bfc (*(int *)((char *)&g_aBrRaceCar + 0x39F4)) /* BR_LP64_BYTE_VIEW */
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_f6C2CFC g_brRaceFlyStep
#define g_tab (*(struct Dim (*)[7])&g_tab)
