/* generated by ports/64b/tools/unify.py */
#define DAT_1007b320 g_7b320
#define DAT_1007b324 g_7b324
#define DAT_1007b328 g_7b328
#define DAT_1007b32c g_7b32c
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_100b55f0 (*(int *)&DAT_100b51e4[1036])
#define DAT_100b74c0 s_tracks__100b74c0
#define DAT_100b7d40 g_aBrCfgSfxDir
#define DAT_1021cdf8 (*(int *)&g_brCfgPlayers)
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_10226a78 g_aBrCfgIniPath
#define DAT_10226e7c g_226e7c
#define DAT_10226e80 g_226e80
#define DAT_10b71290 (*(int *)&g_BrCtrlCfg)
#define DAT_10b71338 (*(int *)((char *)&g_BrCtrlCfg + 0xA8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b713e0 (*(int *)((char *)&g_BrCtrlCfg + 0x150)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71488 (*(int *)((char *)&g_BrCtrlCfg + 0x1F8)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71530 (*(int *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71534 (*(int * *)&g_BrPadModeBytes)
#define DAT_10b71648 g_aBrCfgPlayerName
#define DAT_10b73540 g_aBrCfgBaseDir
#define DAT_118eeedc g_demoFlag
#define s_szBase g_aBrCfgBaseDir
/* functions */
#define FUN_10003320 BrChkFReadOpen
#define FUN_10003530 BrChkFReadLine
#define FUN_100035e0 BrChkFClose
#define FUN_10003680 BrChkFileExists
