/* generated by ports/64b/tools/unify.py */
#define DAT_100abcc0 (*(int (*)[])&g_aBrAC520)
#define DAT_100abde8 g_brIdx0ABDE8
#define DAT_100abdec (*(int *)&DAT_100abdec)
#define DAT_100abdf0 (*(int *)&DAT_100abdf0)
#define DAT_100abdf4 g_brSel0ABDF4
#define DAT_100abdfc (*(int *)&g_i0AC65C)
#define DAT_10ac3e80 g_aBrA9CDF0
#define DAT_10ac5d60 (*(int *)&DAT_10ac5d60)
#define DAT_10ac5d64 g_brKind5D64
#define DAT_10ac5d74 g_brSel5D74
#define DAT_10ac5d78 (*(int *)&DAT_10ac5d78)
#define DAT_10ac5d7c g_brSel5D7C
#define DAT_10ac5d80 g_brSel5D80
#define DAT_10b71290 (*(unsigned char (*)[])&g_BrCtrlCfg)
#define DAT_10b71530 (*(int *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define DAT_10b71534 (*(void * *)&g_BrPadModeBytes)
#define DAT_10b7153c (*(int *)&g_BrDrawReflectEnable)
#define DAT_10b71a70 (g_aBrB4E710[0])
#define DAT_10b71a74 (*(int *)&g_aBrB4E710[1])
#define DAT_10b71a78 (*(int *)&g_aBrB4E710[2])
#define DAT_10b71a7c (*(int *)&g_aBrB4E710[3])
#define DAT_10b71a80 (*(int *)&g_aBrB4E710[4])
#define DAT_10b71a84 (*(int *)&g_aBrB4E710[5])
#define DAT_10b71a88 (*(int *)&g_aBrB4E710[6])
#define DAT_10b71a8c (*(int *)&g_aBrB4E710[7])
#define DAT_10b71a90 (*(int *)&g_aBrB4E710[8])
#define DAT_10b71a94 (*(int *)&g_aBrB4E710[9])
#define DAT_10b71a98 (*(int *)&g_aBrB4E710[10])
#define DAT_10b71a9c (*(int *)&g_aBrB4E710[11])
/* functions */
#define FUN_10008d60 BrPodNop
