/* generated by ports/64b/tools/unify.py */
#define BrG_6C0680 g_BrGfxPtr
#define DAT_1007b324 g_7b324
#define DAT_1007b328 g_7b328
#define DAT_1007b32c g_7b32c
#define DAT_100a9360 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define DAT_100b3014 (*(int *)&g_Br0B380C)
#define DAT_100b3028 (*(unsigned char (*)[][12][2])&g_aBr0B3820)
#define DAT_10226e80 g_226e80
#define DAT_10ac5a48 (DAT_10ac5a48[0])
#define DAT_10ac5a4c (g_aBrAA26F4[0])
#define DAT_10ac5a4d (g_aBrAA26F4[1])
#define DAT_10ac5b3a (*(uint16_t *)((char *)&DAT_10ac5b38 + 0x2)) /* byte view: the object holds no pointers */
#define DAT_10ac5bf8 g_brPhase5BF8
#define DAT_10ac5bfc g_brIdx5BFC
#define DAT_10b71530 (*(int *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_aBrA9D618 DAT_10ac46a0
#define g_aBrAA26F0 (*(int32_t (*)[83])&DAT_10ac5a48)
#define g_aBrB4DF30 (*(unsigned char (*)[4][168])&g_BrCtrlCfg)
#define g_br094354 (*(int32_t *)&g_7b324)
#define g_br094358 (*(int32_t *)&g_7b328)
#define g_br09435C (*(int32_t *)&g_7b32c)
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br0B380C g_Br0B380C
#define g_br22B350 (*(int32_t *)&g_226e80)
#define g_brAA26F0 (DAT_10ac5a48[0])
#define g_brAA27E0 (*(uint32_t *)&DAT_10ac5b38)
#define g_brAA27EC (*(int32_t *)&DAT_10ac5b44)
#define g_brAA27F0 (*(int32_t *)&DAT_10ac5b48)
#define g_brAA27F4 (*(int32_t *)&DAT_10ac5b4c)
#define g_brAA27F8 (*(int32_t *)&DAT_10ac5b50)
#define g_brAA28A0 (*(int32_t *)&g_brPhase5BF8)
#define g_brAA28A4 (*(int32_t *)&g_brIdx5BFC)
#define g_brAA28AC (*(int32_t *)&g_brIdx5C04)
#define g_brAA28B8 (*(int8_t *)&DAT_10ac5c10)
#define g_brAA28C4 DAT_10ac5c1c
#define g_brAA2A10 (*(int32_t *)&DAT_10ac5d68)
#define g_brAA2A14 (*(int32_t *)&DAT_10ac5d6c)
#define g_brB4E1D0 (*(int32_t *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_brB4E1D4 (*(void * *)&g_BrPadModeBytes)
#define g_brCdEnabled DAT_1007b074
