/* generated by ports/64b/tools/unify.py */
#define DAT_100abdec (*(int *)&DAT_100abdec)
#define DAT_100abdf0 (*(int *)&DAT_100abdf0)
#define DAT_100abdf4 g_brSel0ABDF4
#define DAT_100abdfc (*(int *)&g_i0AC65C)
#define DAT_100b55a4 (*(char (*)[])&DAT_100b51e4[960])
#define DAT_105bc8d8 (*(int *)&g_brRace5BC8D8)
#define DAT_105bc8e0 (*(char (*)[])&g_aBrRaceBeginRec)
#define DAT_10ac5c20 (*(int *)&g_brTime5C20)
#define DAT_10ac5c24 (*(int *)&g_brTime5C24)
#define DAT_10ac5d60 (*(int *)&DAT_10ac5d60)
#define DAT_10af3cf0 (*(char (*)[])((char *)&g_aBrRaceCar + 0x2AE8)) /* BR_LP64_BYTE_VIEW */
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define FUN_10001000 BrAdler32
