/* generated by ports/64b/tools/unify.py */
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_106e9a34 (*(int *)&g_brRace6E9A34)
#define DAT_106ec760 (*(int *)&g_brRace6EC760)
#define DAT_106ed6e0 (*(HANDLE *)((char *)&g_aBrEntRecs + 0xB0)) /* byte view: the object holds no pointers */
#define DAT_10b71290 (*(Save1290 *)&g_BrCtrlCfg)
#define DAT_10b71a68 (*(int *)&g_brItemIconCount)
#define DAT_10b71a6c (*(int *)&g_brRaceB71A6C)
#define DAT_10b72f48 g_navArg
/* functions */
#define FUN_10005cd0 BrNetReset
#define FUN_1001cd50 BrFlagInit_1002F690
#define FUN_10063970 BrRenderModeStart
#define FUN_1006a320 FUN_1006a330
#define FUN_1006c460 BrSndBankFree
#define FUN_10072840 BrExt_10079550
