/* generated by ports/64b/tools/unify.py */
#define DAT_1007b074 (*(int32_t *)&DAT_1007b074)
#define DAT_105bc72c (*(void * *)&g_brOwner5BC72C)
#define DAT_105bc73c (*(int32_t *)((char *)&s_args + 0xC)) /* BR_LP64_BYTE_VIEW */
