/* generated by ports/64b/tools/unify.py */
#define g_active (*(int *)&g_AC300)
#define g_b3014 (*(int *)&g_Br0B380C)
#define g_b71290Obj (*(int (*)[])&g_BrCtrlCfg)
#define g_b71530 (*(int *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_b71534 (*(int * *)&g_BrPadModeBytes)
#define g_cur (*(Phase * *)&g_brPAA29B8)
#define g_mode (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_scrH2 (*(int *)&DAT_105ccb68[18])
#define g_scrH3 BrGbiRectG_A7518
#define g_scrH4 (*(int *)&g_brRaceCueBase)
#define g_scrW2 (*(int *)&DAT_105ccb68[19])
#define g_scrW3 BrGbiRectG_A7514
#define g_time (*(int *)&BrGlNavLast6748)
#define g_vidMode (*(int *)&DAT_105ccb68[21])
/* functions */
#define Fn56260 BrUiBootPreLoopGate
#define Fn6C290 BrSfxBankLoad
#define Fn6C460 BrSndBankFree
#define Fn6E280 BrSub10075020
