/* generated by ports/64b/tools/unify.py */
#define BrSndG0B5DE8 (*(int *)&DAT_100b51e4[1036])
#define DAT_10b71290 (*(uint8_t (*)[])&g_BrCtrlCfg)
#define DAT_10b71a48 (*(int32_t *)&DAT_10b71a48)
#define DAT_10b71a4c (*(int32_t *)&DAT_10b71a4c)
#define DAT_10b71a50 (*(int32_t *)&DAT_10b71a50)
#define DAT_10b71a54 (*(int32_t *)&DAT_10b71a54)
#define DAT_10b72f48 (*(char (*)[])&g_navArg)
#define DAT_10b73540 g_aBrCfgBaseDir
#define g_brAppExitCode (DAT_105ccb68[22])
#define g_brAppFrame (DAT_105ccb68[20])
#define g_brAppModeH (*(int32_t *)&BrGbiRectG_A7518)
#define g_brAppModeW (*(int32_t *)&BrGbiRectG_A7514)
#define g_brAppState (DAT_105ccb68[21])
/* functions */
#define BrBootFrontier_10032530 BrBootColdInitRun
#define BrBootFrontier_10058AF0 BrCtlNameInit
#define BrBootFrontier_100628B0 BrGlRaceStart
#define BrBootFrontier_10063970 BrRenderModeStart
#define BrBootFrontier_1006C290 BrSfxBankLoad
#define BrBootFrontier_1006C990 BrImgShowFullScreen
#define BrCfgReadFileT BrCtrlCfgReadFile
#define BrCmdLineParse FUN_10007f40
