/* generated by ports/64b/tools/unify.py */
#define DAT_100b55f0 (*(int *)&DAT_100b51e4[1036])
#define DAT_105bc72c (*(void * *)&g_brOwner5BC72C)
#define g_AC0810 g_brModelMgr
#define g_brCdEnabled DAT_1007b074
/* functions */
#define FUN_1006c4d0 BrSndDevOpen
#define FUN_1006c990 BrImgShowFullScreen
#define FUN_10071fc0 Ctl71FC0_fn
#define BrPodOpen BrPodOpen
