/* generated by ports/64b/tools/unify.py */
#define DAT_100a7514 BrGbiRectG_A7514
#define DAT_100a7518 BrGbiRectG_A7518
#define DAT_102066c8 (*(char *)&g_2066C8)
#define DAT_106e7714 g_scrW4
#define DAT_106e9a2c (*(int *)&g_brRaceCueBase)
#define DAT_10af3bc8 (*(int *)((char *)&g_aBrRaceCar + 0x29C0)) /* BR_LP64_BYTE_VIEW */
#define DAT_118ed1e8 (*(funcptr *)&g_18ED1E8)
#define g_0A81C8 DAT_100a751c
#define g_1826BD0 (*(uint32_t *)&g_aBrPeerMsg)
#define g_57543C (*(uint32_t * *)&g_brTex57543C)
#define g_690A14 (*(uint32_t *)&DAT_105ccb68[21])
#define g_690A24 (*(uint32_t *)&g_aBrTexSlot[192996])
#define g_690A28 (*(uint32_t *)&g_aBrTexSlot[193000])
#define g_AC0810 g_brModelMgr
#define g_B71290 (*(int *)&g_BrCtrlCfg)
#define g_br0AA010 (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_br100BCBE8 g_CBE8
#define g_brFlag6909E0 (*(int *)&DAT_105ccb68[8])
#define g_brRaceNEntrant (*(int *)&g_brRaceNEntrant)
#define g_f6C2CFC g_brRaceFlyStep
/* functions */
#define BrExt_10008B80 BrPodNop
#define BrExt_10038EB0 BrSub10032520
#define BrExt_10067880 BrVarSave
#define BrExt_10067900 BrVarLoad
#define BrExt_10069A80 BrSub10062AF0
#define BrExt_10073B40 FUN_1006cd80
#define BrExt_1007E8B0 BrCrtAtExit
#define BrExt_1007F560 BrEhVecDtor
#define BrExt_1007F680 BrEhVecCtor
#define BrSub10008760 BrObj87Ctor
#define BrSub10008D60 BrPodNop
#define FUN_10032500 BrSub10032500
