/* generated by ports/64b/tools/unify.py */
#define BrSndG0B5DE8 (*(int32_t *)&DAT_100b51e4[1036])
#define DAT_10226e78 (*(int *)&g_brTexSysMem)
#define g_brAppTotalPhysBytes g_brTexSysMem
#define g_brCfgBenchCar (*(int32_t *)&DAT_1021ce50)
#define g_brCfgBenchSuspension (*(int32_t *)&DAT_10226a3c)
#define g_brCfgBenchTire (*(int32_t *)&DAT_10226a40)
#define g_brCfgChosenCar (*(int32_t *)&g_226e7c)
#define g_brCfgChosenTrack g_Br0B380C
#define g_brCfgChosenWeather (*(int32_t *)&g_226e80)
#define g_brCfgD3DCarShadow (*(int32_t *)&DAT_10396eb0)
#define g_brCfgGameMode (*(int32_t *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */
#define g_brCfgHandlingType (*(int32_t *)&g_7b320)
#define g_brCfgInterpolate (*(int32_t *)&DAT_100a5eac)
#define g_brCfgPlayMusic (*(int32_t *)&DAT_1007b074)
#define g_brCfgReadJoystick (*(int32_t *)((char *)&g_BrCtrlCfg + 0x2A0)) /* BR_LP64_BYTE_VIEW */
#define g_brCfgRunBenchmark (*(int32_t *)&g_demoFlag)
#define g_brCfgSpeedSensitive (*(int32_t *)&DAT_100b2e6c)
#define g_brCfgSuspensionType (*(int32_t *)&g_7b328)
#define g_brCfgTireType (*(int32_t *)&g_7b32c)
#define g_brCfgTransmission (*(int32_t *)&g_7b324)
#define g_iBrCfgInputDevice g_BrPadModeBytes
