/* generated by ports/64b/tools/unify.py */
#define DAT_106b7ac0 (*(unsigned int *)&DAT_106b7ac0)
#define DAT_106e9d8c g_brRaceFlyStep
#define DAT_106ec768 (*(unsigned int *)&DAT_106ec768)
#define DAT_106ed588 (*(unsigned int *)&DAT_106ed588)
#define DAT_106ed6d8 (*(int *)((char *)&g_aBrEntRecs + 0xA8)) /* byte view: the object holds no pointers */
#define g_brRaceBeginDrawn (*(int32_t *)((char *)&g_aBrEntRecs + 0xA8)) /* byte view: the object holds no pointers */
/* functions */
#define FUN_10008d60 BrPodNop
#define FUN_10059f00 BrTickAdd_10078C10
