/* generated by ports/64b/tools/unify.py */
#define DAT_10226a48 (*(int *)&g_brRaceNet)
#define DAT_106b7abc (*(funcptr *)&BrGlFlipHook2)
#define DAT_118ed1e8 (*(funcptr *)&g_18ED1E8)
#define g_AC0810 g_brModelMgr
#define g_AC300 (*(int *)&g_AC300)
#define g_brCdEnabled DAT_1007b074
#define g_brPhaseAA2904 (*(Phase * *)&g_brPAA29B8)
/* functions */
#define FUN_10003030 BrCdStopRelease
#define FUN_10005f50 BrNetShutdown
#define FUN_100720a0 BrDInputShutdown
