/* generated by ports/64b/tools/unify.py */
#define DAT_100aa340 g_szBrFmtSS
#define DAT_100b4c30 (g_aBrCarPhysDrvT1A[0])
#define DAT_100b4d50 (g_aBrCarPhysDrvT1B[0])
#define DAT_100b4e70 (g_aBrCarPhysDrvT2A[0])
#define DAT_100b4ed0 (g_aBrCarPhysDrvT2B[0])
#define DAT_100b4f30 (g_aBrCarPhysGripA[0])
#define DAT_100b5050 (g_aBrCarPhysGripB[0])
#define DAT_100b5170 (*(int *)&DAT_100b5170)
#define DAT_106b7c7c (*(unsigned char * *)&g_brRcaBlob)
#define DAT_106eed38 g_BrDrawTrackFlags
#define DAT_106eed3c g_BrSpanCount
#define DAT_10ac080c (*(int *)&g_brKeyBias)
#define DAT_11773690 g_pBrCarPhysGrip
#define DAT_11778808 (*(int *)((char *)&g_brCrPlane + 0x18)) /* byte view: the object holds no pointers */
#define DAT_118ed1dc (*(int (**)())&g_pfn18AA0C4)
#define DAT_118ed1e4 (*(int (**)())&DAT_118ed1e4)
#define g_BrGlyphFontA12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontA12)
#define g_BrGlyphFontB12 (*(BrGlyphMetric12 (*)[])&g_BrGlyphFontB12)
#define g_a220B20 (*(uint32_t (*)[70])&g_a220B20)
#define g_brLoadTexBase g_brRcaBlob
#define g_tab (*(struct Dim (*)[7])&g_tab)
/* functions */
#define BrSub10035BD1 BrSessionReinitVideo
#define FUN_100032d0 BrChkFileSize
#define FUN_10003320 BrChkFReadOpen
#define FUN_100034c0 BrChkFRead
#define FUN_100035e0 BrChkFClose
#define FUN_10018a10 BrSegSetBases
#define FUN_10018a40 BrSegSetFlag
#define FUN_10030f50 BrFileReadInto
#define FUN_10031140 BrTrackLoadHandling
#define FUN_100314d0 BrGlTrackFixupAll
#define FUN_10031b80 BrGlTrackHdrRead
#define FUN_10032190 BrGlTrackFixupCmds
#define FUN_100347f0 BrVec3Length
#define FUN_10034a70 BrMtxXfmDir3
#define FUN_1005a780 BrNodeRunMarkPass
#define FUN_10069530 BrTrackSurfaceSet
#define FUN_1006c910 BrSub10073AC0
#define FUN_1006c950 BrSub10073B00
