/* generated by ports/64b/tools/unify.py */
#define DAT_104b1634 (*(int (**)(void *))&DAT_104b1634)
#define DAT_104b1650 (*(int (**)(void))&DAT_104b1650)
#define DAT_104b1658 (*(int (**)(int))&DAT_104b1658)
#define DAT_104b1668 (*(int (**)(int))&DAT_104b1668)
#define DAT_104b166c (*(int (**)(void))&DAT_104b166c)
#define g_brAppModeH (*(int32_t *)&BrGbiRectG_A7518)
#define g_brAppModeW (*(int32_t *)&BrGbiRectG_A7514)
#define g_brhInstance (*(void * *)&s_args)
#define g_brhWnd (*(void * *)&g_brOwner5BC72C)
/* functions */
#define FUN_10017910 BrEarLoad
#define FUN_1006d280 BrStrGet
