/* br_globals.c: the one definition of each original global (generated by
 * ports/64b/tools/unify.py). Initial values: the data lift. */
/* A global with the original's extent (tools/globext.py): the declared
 * object at offset 0 and the bytes up to the next address the original
 * names, under the global's own linker symbol -- code that walks past the
 * declared type, as the original does, stays inside it. */
#define BR_SYM_STR2(x) #x
#define BR_SYM_STR(x) BR_SYM_STR2(x)
#define BR_GLOBAL_EXTENT(T, name, dims, pad) \
    struct { T v dims; unsigned char extent[pad]; } name##__extent \
        __asm__(BR_SYM_STR(__USER_LABEL_PREFIX__) #name)

#include "br_boot.h"
#include "br_collresp.h"
#include "br_collrespsolve.h"
#include "br_coretypes.h"
#include "br_dl.h"
#include "br_dxver.h"
#include "br_gamestep.h"
#include "br_mat.h"
#include "br_phase.h"
#include "br_race.h"
#include "br_trkhdr.h"
#include "br_racebegin.h"
#include "br_sfxsrc.h"
#include "br_slots.h"
#include "br_ui.h"
#include "br_uispr.h"
#include "br_vec.h"
#include "slice1_02.h"
#include "slice1_03.h"
#include "slice1_05.h"
#include "slice1_06.h"
#include "slice1_07.h"
#include "slice1_08.h"
#include "slice1_09.h"
#include "slice1_10.h"
#include "slice2_12.h"
#include "slice2_13.h"
#include "slice2_14.h"
#include "slice2_15.h"
#include "slice2_16.h"
#include "slice2_18.h"
#include "slice2_20.h"
#include "slice2_21.h"
#include "slice2_24.h"
#include "slice2_25.h"
#include "slice2_26.h"
#include "slice3_32.h"
#include "slice3_39.h"
#include "slice3_40.h"
#include "slice3_41.h"
#include "slice3_42.h"
#include "slice3_45.h"
#include "slice4_52.h"
#include "slice6_72.h"

BR_GLOBAL_EXTENT(char, g_DataFormat, [24], 0x1008);  /* 0x10072AC0 */
BR_GLOBAL_EXTENT(int, DAT_10073ae0, , 0x351C);  /* 0x10073AE0 */
float _DAT_10077000;  /* 0x10077000 */
float _DAT_10077004;  /* 0x10077004 */
BR_GLOBAL_EXTENT(float, _DAT_10077008, , 0x8);  /* 0x10077008 */
float _DAT_10077014;  /* 0x10077014 */
float _DAT_10077018;  /* 0x10077018 */
float _DAT_1007701c;  /* 0x1007701C */
float _DAT_10077020;  /* 0x10077020 */
float _DAT_10077024;  /* 0x10077024 */
float _DAT_10077028;  /* 0x10077028 */
float _DAT_1007702c;  /* 0x1007702C */
float _DAT_10077030;  /* 0x10077030 */
float _DAT_10077034;  /* 0x10077034 */
float _DAT_10077038;  /* 0x10077038 */
float _DAT_1007703c;  /* 0x1007703C */
float _DAT_10077040;  /* 0x10077040 */
float _DAT_10077044;  /* 0x10077044 */
float _DAT_10077048;  /* 0x10077048 */
float _DAT_1007704c;  /* 0x1007704C */
float _DAT_10077050;  /* 0x10077050 */
float _DAT_10077054;  /* 0x10077054 */
float _DAT_10077058;  /* 0x10077058 */
float _DAT_1007705c;  /* 0x1007705C */
float _DAT_10077060;  /* 0x10077060 */
float _DAT_10077064;  /* 0x10077064 */
float _DAT_10077068;  /* 0x10077068 */
float _DAT_1007706c;  /* 0x1007706C */
float _DAT_10077070;  /* 0x10077070 */
float _DAT_10077074;  /* 0x10077074 */
float _DAT_10077078;  /* 0x10077078 */
BR_GLOBAL_EXTENT(float, _DAT_1007707c, , 0x4);  /* 0x1007707C */
float _DAT_10077084;  /* 0x10077084 */
float _DAT_10077088;  /* 0x10077088 */
float _DAT_1007708c;  /* 0x1007708C */
float _DAT_10077090;  /* 0x10077090 */
BR_GLOBAL_EXTENT(float, _DAT_10077094, , 0x14);  /* 0x10077094 */
float _DAT_100770ac;  /* 0x100770AC */
BR_GLOBAL_EXTENT(float, DAT_100770b0, , 0x14);  /* 0x100770B0 */
float DAT_100770c8;  /* 0x100770C8 */
BR_GLOBAL_EXTENT(float, DAT_100770cc, , 0x40);  /* 0x100770CC */
float DAT_10077110;  /* 0x10077110 */
float DAT_10077114;  /* 0x10077114 */
BR_GLOBAL_EXTENT(float, DAT_10077118, , 0x34);  /* 0x10077118 */
BR_GLOBAL_EXTENT(void *, BrObj87Vtbl, , 0x9C);  /* 0x10077150 */
float DAT_100771f0;  /* 0x100771F0 */
float DAT_100771f4;  /* 0x100771F4 */
float DAT_100771f8;  /* 0x100771F8 */
float DAT_100771fc;  /* 0x100771FC */
float DAT_10077200;  /* 0x10077200 */
BR_GLOBAL_EXTENT(float, DAT_10077204, , 0x4);  /* 0x10077204 */
BR_GLOBAL_EXTENT(float, DAT_1007720c, , 0x4);  /* 0x1007720C */
float g_BrVisCellRecip;  /* 0x10077214 */
float g_BrVisRangeRecip;  /* 0x10077218 */
float g_BrVisAheadMin;  /* 0x1007721C */
BR_GLOBAL_EXTENT(double, g_BrZeroD, , 0x4);  /* 0x10077220 */
float g_BrVisEyeScale;  /* 0x1007722C */
BR_GLOBAL_EXTENT(float, g_BrVisVelScale, , 0x4);  /* 0x10077230 */
double DAT_10077238;  /* 0x10077238 */
double DAT_10077240;  /* 0x10077240 */
float DAT_10077248;  /* 0x10077248 */
float DAT_1007724c;  /* 0x1007724C */
float DAT_10077250;  /* 0x10077250 */
float DAT_10077254;  /* 0x10077254 */
float DAT_10077258;  /* 0x10077258 */
float _DAT_1007725c;  /* 0x1007725C */
float _DAT_10077260;  /* 0x10077260 */
float _DAT_10077264;  /* 0x10077264 */
float _DAT_10077268;  /* 0x10077268 */
float _DAT_1007726c;  /* 0x1007726C */
float _DAT_10077270;  /* 0x10077270 */
BR_GLOBAL_EXTENT(float, _DAT_10077274, , 0xC);  /* 0x10077274 */
BR_GLOBAL_EXTENT(float, _DAT_10077284, , 0x28);  /* 0x10077284 */
BR_GLOBAL_EXTENT(float, kF300, , 0x4C);  /* 0x100772B0 */
float DAT_10077300;  /* 0x10077300 */
BR_GLOBAL_EXTENT(float, DAT_10077304, , 0xC);  /* 0x10077304 */
float DAT_10077314;  /* 0x10077314 */
float DAT_10077318;  /* 0x10077318 */
float DAT_1007731c;  /* 0x1007731C */
double DAT_10077320;  /* 0x10077320 */
float DAT_10077328;  /* 0x10077328 */
BR_GLOBAL_EXTENT(float, DAT_1007732c, , 0x4);  /* 0x1007732C */
float DAT_10077334;  /* 0x10077334 */
BR_GLOBAL_EXTENT(double, DAT_10077338, , 0x4);  /* 0x10077338 */
float DAT_10077344;  /* 0x10077344 */
float DAT_10077348;  /* 0x10077348 */
float DAT_1007734c;  /* 0x1007734C */
float DAT_10077350;  /* 0x10077350 */
BR_GLOBAL_EXTENT(float, DAT_10077354, , 0xC);  /* 0x10077354 */
float DAT_10077364;  /* 0x10077364 */
BR_GLOBAL_EXTENT(float, DAT_10077368, , 0x4);  /* 0x10077368 */
BR_GLOBAL_EXTENT(float, DAT_10077370, , 0xC);  /* 0x10077370 */
BR_GLOBAL_EXTENT(float, DAT_10077380, , 0x4);  /* 0x10077380 */
double DAT_10077388;  /* 0x10077388 */
BR_GLOBAL_EXTENT(float, DAT_10077390, , 0xC);  /* 0x10077390 */
float DAT_100773a0;  /* 0x100773A0 */
BR_GLOBAL_EXTENT(float, g_0773A4, , 0x8);  /* 0x100773A4 */
float g_0773B0;  /* 0x100773B0 */
float g_0773B4;  /* 0x100773B4 */
float g_0773B8;  /* 0x100773B8 */
float g_0773BC;  /* 0x100773BC */
float g_0773C0;  /* 0x100773C0 */
float g_brRaceFlySpeedA;  /* 0x100773C4 */
float g_brRaceFlySpeedB;  /* 0x100773C8 */
float g_brRaceFlyBlendA;  /* 0x100773CC */
BR_GLOBAL_EXTENT(float, g_brRaceFlyBlendB, , 0x30);  /* 0x100773D0 */
float DAT_10077404;  /* 0x10077404 */
float BrGbiRectK_FIXED;  /* 0x10077408 */
float DAT_1007740c;  /* 0x1007740C */
float DAT_10077410;  /* 0x10077410 */
float BrGbiRectK_HALF;  /* 0x10077414 */
BR_GLOBAL_EXTENT(float, DAT_10077418, , 0x4);  /* 0x10077418 */
float DAT_10077420;  /* 0x10077420 */
float DAT_10077424;  /* 0x10077424 */
float DAT_10077428;  /* 0x10077428 */
float DAT_1007742c;  /* 0x1007742C */
float DAT_10077430;  /* 0x10077430 */
float DAT_10077434;  /* 0x10077434 */
float DAT_10077438;  /* 0x10077438 */
float DAT_1007743c;  /* 0x1007743C */
float DAT_10077440;  /* 0x10077440 */
float DAT_10077444;  /* 0x10077444 */
BR_GLOBAL_EXTENT(float, DAT_10077448, , 0x10);  /* 0x10077448 */
float DAT_1007745c;  /* 0x1007745C */
BR_GLOBAL_EXTENT(float, _DAT_10077460, , 0x24);  /* 0x10077460 */
double _DAT_10077488;  /* 0x10077488 */
BR_GLOBAL_EXTENT(double, _DAT_10077490, , 0x18);  /* 0x10077490 */
float DAT_100774b0;  /* 0x100774B0 */
float DAT_100774b4;  /* 0x100774B4 */
float DAT_100774b8;  /* 0x100774B8 */
float DAT_100774bc;  /* 0x100774BC */
float DAT_100774c0;  /* 0x100774C0 */
float DAT_100774c4;  /* 0x100774C4 */
float DAT_100774c8;  /* 0x100774C8 */
float DAT_100774cc;  /* 0x100774CC */
BR_GLOBAL_EXTENT(float, DAT_100774d0, , 0x8);  /* 0x100774D0 */
float g_BrK08F514;  /* 0x100774DC */
float g_BrK08F518;  /* 0x100774E0 */
float g_BrK08F51C;  /* 0x100774E4 */
float g_BrK08F520;  /* 0x100774E8 */
float g_BrK08F524;  /* 0x100774EC */
float DAT_100774f0;  /* 0x100774F0 */
float g_BrK08F52C;  /* 0x100774F4 */
float g_BrK08F530;  /* 0x100774F8 */
float g_BrK08F534;  /* 0x100774FC */
int DAT_10077500;  /* 0x10077500 */
int DAT_10077504;  /* 0x10077504 */
int DAT_10077508;  /* 0x10077508 */
int DAT_1007750c;  /* 0x1007750C */
BR_GLOBAL_EXTENT(float, g_BrK08F548, , 0x8);  /* 0x10077510 */
BR_GLOBAL_EXTENT(float, DAT_1007751c, , 0x4);  /* 0x1007751C */
float _DAT_10077524;  /* 0x10077524 */
BR_GLOBAL_EXTENT(float, _DAT_10077528, , 0x58);  /* 0x10077528 */
BR_GLOBAL_EXTENT(float, g_BrTrailDimK, , 0x10);  /* 0x10077584 */
float g_BrTrailFixK;  /* 0x10077598 */
float g_BrTrailScaleK;  /* 0x1007759C */
float g_BrTrailStepK;  /* 0x100775A0 */
float g_BrTrailUnfixK;  /* 0x100775A4 */
float g_BrTrailNightMulK;  /* 0x100775A8 */
BR_GLOBAL_EXTENT(float, g_BrTrailNightBaseK, , 0x14);  /* 0x100775AC */
float kPfxRecip;  /* 0x100775C4 */
float kPfxNeg0_8;  /* 0x100775C8 */
float kPfx5_7375;  /* 0x100775CC */
float kPfxCell;  /* 0x100775D0 */
float kPfx0_7;  /* 0x100775D4 */
float kPfx19_62;  /* 0x100775D8 */
float kPfx102;  /* 0x100775DC */
BR_GLOBAL_EXTENT(float, kPfxNeg30, , 0x40);  /* 0x100775E0 */
float g_f077624;  /* 0x10077624 */
float DAT_10077628;  /* 0x10077628 */
float DAT_1007762c;  /* 0x1007762C */
float g_f077630;  /* 0x10077630 */
float g_f077634;  /* 0x10077634 */
float g_f077638;  /* 0x10077638 */
BR_GLOBAL_EXTENT(float, g_f07763C, , 0x8);  /* 0x1007763C */
float DAT_10077648;  /* 0x10077648 */
float DAT_1007764c;  /* 0x1007764C */
float DAT_10077650;  /* 0x10077650 */
float DAT_10077654;  /* 0x10077654 */
float DAT_10077658;  /* 0x10077658 */
float DAT_1007765c;  /* 0x1007765C */
float DAT_10077660;  /* 0x10077660 */
float DAT_10077664;  /* 0x10077664 */
float DAT_10077668;  /* 0x10077668 */
float DAT_1007766c;  /* 0x1007766C */
float DAT_10077670;  /* 0x10077670 */
BR_GLOBAL_EXTENT(float, g_077674, , 0x48);  /* 0x10077674 */
BR_GLOBAL_EXTENT(funcptr, PTR_FUN_100776c0, , 0x2C);  /* 0x100776C0 */
BR_GLOBAL_EXTENT(funcptr, PTR_FUN_100776f0, , 0x2C);  /* 0x100776F0 */
BR_GLOBAL_EXTENT(funcptr, PTR_FUN_10077720, , 0x2C);  /* 0x10077720 */
BR_GLOBAL_EXTENT(funcptr, PTR_FUN_10077750, , 0x18);  /* 0x10077750 */
float DAT_1007776c;  /* 0x1007776C */
float DAT_10077770;  /* 0x10077770 */
float DAT_10077774;  /* 0x10077774 */
BR_GLOBAL_EXTENT(float, DAT_10077778, , 0x4);  /* 0x10077778 */
float DAT_10077780;  /* 0x10077780 */
float DAT_10077784;  /* 0x10077784 */
float DAT_10077788;  /* 0x10077788 */
float DAT_1007778c;  /* 0x1007778C */
BR_GLOBAL_EXTENT(float, DAT_10077790, , 0x4);  /* 0x10077790 */
float DAT_10077798;  /* 0x10077798 */
float DAT_1007779c;  /* 0x1007779C */
float DAT_100777a0;  /* 0x100777A0 */
float DAT_100777a4;  /* 0x100777A4 */
float DAT_100777a8;  /* 0x100777A8 */
BR_GLOBAL_EXTENT(float, DAT_100777ac, , 0x8);  /* 0x100777AC */
BR_GLOBAL_EXTENT(float, DAT_100777b8, , 0x4);  /* 0x100777B8 */
BR_GLOBAL_EXTENT(float, DAT_100777c0, , 0x4);  /* 0x100777C0 */
BR_GLOBAL_EXTENT(float, DAT_100777c8, , 0x4);  /* 0x100777C8 */
BR_GLOBAL_EXTENT(float, DAT_100777d0, , 0x10);  /* 0x100777D0 */
float DAT_100777e4;  /* 0x100777E4 */
float DAT_100777e8;  /* 0x100777E8 */
float DAT_100777ec;  /* 0x100777EC */
float DAT_100777f0;  /* 0x100777F0 */
float DAT_100777f4;  /* 0x100777F4 */
float DAT_100777f8;  /* 0x100777F8 */
float DAT_100777fc;  /* 0x100777FC */
float DAT_10077800;  /* 0x10077800 */
BR_GLOBAL_EXTENT(float, DAT_10077804, , 0x8);  /* 0x10077804 */
double DAT_10077810;  /* 0x10077810 */
float DAT_10077818;  /* 0x10077818 */
float DAT_1007781c;  /* 0x1007781C */
BR_GLOBAL_EXTENT(float, DAT_10077820, , 0x4);  /* 0x10077820 */
double DAT_10077828;  /* 0x10077828 */
float DAT_10077830;  /* 0x10077830 */
float DAT_10077834;  /* 0x10077834 */
float DAT_10077838;  /* 0x10077838 */
float DAT_1007783c;  /* 0x1007783C */
float DAT_10077840;  /* 0x10077840 */
BR_GLOBAL_EXTENT(float, DAT_10077844, , 0x4);  /* 0x10077844 */
float DAT_1007784c;  /* 0x1007784C */
float DAT_10077850;  /* 0x10077850 */
float DAT_10077854;  /* 0x10077854 */
float DAT_10077858;  /* 0x10077858 */
float DAT_1007785c;  /* 0x1007785C */
float DAT_10077860;  /* 0x10077860 */
float DAT_10077864;  /* 0x10077864 */
float DAT_10077868;  /* 0x10077868 */
float DAT_1007786c;  /* 0x1007786C */
float DAT_10077870;  /* 0x10077870 */
float DAT_10077874;  /* 0x10077874 */
float DAT_10077878;  /* 0x10077878 */
float DAT_1007787c;  /* 0x1007787C */
float DAT_10077880;  /* 0x10077880 */
float DAT_10077884;  /* 0x10077884 */
float DAT_10077888;  /* 0x10077888 */
float _DAT_1007788c;  /* 0x1007788C */
BR_GLOBAL_EXTENT(float, _DAT_10077890, , 0x4);  /* 0x10077890 */
float DAT_10077898;  /* 0x10077898 */
float DAT_1007789c;  /* 0x1007789C */
float DAT_100778a0;  /* 0x100778A0 */
float DAT_100778a4;  /* 0x100778A4 */
float DAT_100778a8;  /* 0x100778A8 */
BR_GLOBAL_EXTENT(float, DAT_100778ac, , 0x4);  /* 0x100778AC */
float DAT_100778b4;  /* 0x100778B4 */
float DAT_100778b8;  /* 0x100778B8 */
float DAT_100778bc;  /* 0x100778BC */
float DAT_100778c0;  /* 0x100778C0 */
float DAT_100778c4;  /* 0x100778C4 */
float DAT_100778c8;  /* 0x100778C8 */
float DAT_100778cc;  /* 0x100778CC */
float DAT_100778d0;  /* 0x100778D0 */
float DAT_100778d4;  /* 0x100778D4 */
float DAT_100778d8;  /* 0x100778D8 */
float DAT_100778dc;  /* 0x100778DC */
float DAT_100778e0;  /* 0x100778E0 */
float DAT_100778e4;  /* 0x100778E4 */
BR_GLOBAL_EXTENT(float, DAT_100778e8, , 0x4);  /* 0x100778E8 */
float DAT_100778f0;  /* 0x100778F0 */
float DAT_100778f4;  /* 0x100778F4 */
BR_GLOBAL_EXTENT(float, DAT_100778f8, , 0x94);  /* 0x100778F8 */
BR_GLOBAL_EXTENT(double, DAT_10077990, , 0x74);  /* 0x10077990 */
float DAT_10077a0c;  /* 0x10077A0C */
float DAT_10077a10;  /* 0x10077A10 */
BR_GLOBAL_EXTENT(float, DAT_10077a14, , 0x14);  /* 0x10077A14 */
BR_GLOBAL_EXTENT(unsigned char, BrGlCfgVersion, [4], 0x48);  /* 0x10077A2C */
float BrCrK_Zero;  /* 0x10077A78 */
float DAT_10077a7c;  /* 0x10077A7C */
float DAT_10077a80;  /* 0x10077A80 */
float DAT_10077a84;  /* 0x10077A84 */
float _DAT_10077a88;  /* 0x10077A88 */
float _DAT_10077a8c;  /* 0x10077A8C */
BR_GLOBAL_EXTENT(float, _DAT_10077a90, , 0x4);  /* 0x10077A90 */
double _DAT_10077a98;  /* 0x10077A98 */
float _DAT_10077aa0;  /* 0x10077AA0 */
float _DAT_10077aa4;  /* 0x10077AA4 */
float _DAT_10077aa8;  /* 0x10077AA8 */
float _DAT_10077aac;  /* 0x10077AAC */
double _DAT_10077ab0;  /* 0x10077AB0 */
float _DAT_10077ab8;  /* 0x10077AB8 */
float _DAT_10077abc;  /* 0x10077ABC */
float _DAT_10077ac0;  /* 0x10077AC0 */
float _DAT_10077ac4;  /* 0x10077AC4 */
BR_GLOBAL_EXTENT(float, BrCrK_Half, , 0x4);  /* 0x10077AC8 */
float DAT_10077ad0;  /* 0x10077AD0 */
float _DAT_10077ad4;  /* 0x10077AD4 */
BR_GLOBAL_EXTENT(float, _DAT_10077ad8, , 0x4);  /* 0x10077AD8 */
double DAT_10077ae0;  /* 0x10077AE0 */
float DAT_10077ae8;  /* 0x10077AE8 */
float DAT_10077aec;  /* 0x10077AEC */
float DAT_10077af0;  /* 0x10077AF0 */
float DAT_10077af4;  /* 0x10077AF4 */
float DAT_10077af8;  /* 0x10077AF8 */
float DAT_10077afc;  /* 0x10077AFC */
BR_GLOBAL_EXTENT(float, DAT_10077b00, , 0x4);  /* 0x10077B00 */
double DAT_10077b08;  /* 0x10077B08 */
double DAT_10077b10;  /* 0x10077B10 */
double DAT_10077b18;  /* 0x10077B18 */
double DAT_10077b20;  /* 0x10077B20 */
BR_GLOBAL_EXTENT(float, DAT_10077b28, , 0x4);  /* 0x10077B28 */
float _DAT_10077b30;  /* 0x10077B30 */
float _DAT_10077b34;  /* 0x10077B34 */
BR_GLOBAL_EXTENT(float, DAT_10077b38, , 0x4);  /* 0x10077B38 */
float DAT_10077b40;  /* 0x10077B40 */
BR_GLOBAL_EXTENT(float, DAT_10077b44, , 0x28);  /* 0x10077B44 */
BR_GLOBAL_EXTENT(float, DAT_10077b70, , 0x4);  /* 0x10077B70 */
BR_GLOBAL_EXTENT(double, DAT_10077b78, , 0x8);  /* 0x10077B78 */
float BrCrK_Flat;  /* 0x10077B88 */
BR_GLOBAL_EXTENT(float, BrCrK_Pushout, , 0x4);  /* 0x10077B8C */
float _DAT_10077b94;  /* 0x10077B94 */
BR_GLOBAL_EXTENT(float, _DAT_10077b98, , 0x2C);  /* 0x10077B98 */
BR_GLOBAL_EXTENT(float, _DAT_10077bc8, , 0x4);  /* 0x10077BC8 */
double DAT_10077bd0;  /* 0x10077BD0 */
float DAT_10077bd8;  /* 0x10077BD8 */
float _DAT_10077bdc;  /* 0x10077BDC */
float _DAT_10077be0;  /* 0x10077BE0 */
BR_GLOBAL_EXTENT(int, DAT_10077be4, , 0x4);  /* 0x10077BE4 */
BR_GLOBAL_EXTENT(float, DAT_10077bec, , 0x10);  /* 0x10077BEC */
BR_GLOBAL_EXTENT(double, DAT_10077c00, , 0x14);  /* 0x10077C00 */
BR_GLOBAL_EXTENT(float, _DAT_10077c1c, , 0x10);  /* 0x10077C1C */
float DAT_10077c30;  /* 0x10077C30 */
float DAT_10077c34;  /* 0x10077C34 */
float DAT_10077c38;  /* 0x10077C38 */
float DAT_10077c3c;  /* 0x10077C3C */
BR_GLOBAL_EXTENT(double, _DAT_10077c40, , 0x4);  /* 0x10077C40 */
float g_077C4C;  /* 0x10077C4C */
BR_GLOBAL_EXTENT(float, g_077C50, , 0xC);  /* 0x10077C50 */
float DAT_10077c60;  /* 0x10077C60 */
float DAT_10077c64;  /* 0x10077C64 */
float DAT_10077c68;  /* 0x10077C68 */
float DAT_10077c6c;  /* 0x10077C6C */
float DAT_10077c70;  /* 0x10077C70 */
float DAT_10077c74;  /* 0x10077C74 */
BR_GLOBAL_EXTENT(float, DAT_10077c78, , 0x3C);  /* 0x10077C78 */
BR_GLOBAL_EXTENT(BrDxGuid, BrIidIDirectDraw2, , 0x30);  /* 0x10077CB8 */
BrDxGuid BrIidIDirectDrawSurface3;  /* 0x10077CF8 */
BR_GLOBAL_EXTENT(BrDxGuid, BrIidIDirectDrawSurface4, , 0x9F0);  /* 0x10077D08 */
char g_DeviceGuid[16];  /* 0x10078708 */
BR_GLOBAL_EXTENT(int, DAT_10078718, , 0x10C);  /* 0x10078718 */
BR_GLOBAL_EXTENT(int, DAT_10078828, , 0x1C);  /* 0x10078828 */
BR_GLOBAL_EXTENT(int, DAT_10078848, , 0xC);  /* 0x10078848 */
BR_GLOBAL_EXTENT(int, DAT_10078858, , 0xC);  /* 0x10078858 */
unsigned char DAT_10078868[16];  /* 0x10078868 */
unsigned char DAT_10078878[16];  /* 0x10078878 */
unsigned char DAT_10078888[16];  /* 0x10078888 */
unsigned char DAT_10078898[80];  /* 0x10078898 */
BR_GLOBAL_EXTENT(int, DAT_100788e8, , 0x1C);  /* 0x100788E8 */
BR_GLOBAL_EXTENT(int, DAT_10078908, , 0xC);  /* 0x10078908 */
BR_GLOBAL_EXTENT(int, DAT_10078918, , 0x5C);  /* 0x10078918 */
BR_GLOBAL_EXTENT(BrDpGuid, DAT_10078978, , 0x10);  /* 0x10078978 */
BR_GLOBAL_EXTENT(BrDpGuid, DAT_10078998, , 0x10);  /* 0x10078998 */
BR_GLOBAL_EXTENT(BrDpGuid, DAT_100789b8, , 0x10);  /* 0x100789B8 */
BR_GLOBAL_EXTENT(BrDpGuid, DAT_100789d8, , 0x10);  /* 0x100789D8 */
BR_GLOBAL_EXTENT(BrDpGuid, DAT_100789f8, , 0x10);  /* 0x100789F8 */
BR_GLOBAL_EXTENT(GUID, DAT_10078a18, , 0x10);  /* 0x10078A18 */
BR_GLOBAL_EXTENT(GUID, DAT_10078a38, , 0x261C);  /* 0x10078A38 */
char g_szBrFmtTime[16];  /* 0x1007B064 */
int DAT_1007b074;  /* 0x1007B074 */
int g_0940A8;  /* 0x1007B078 */
char s_MCI_STATUS_returned__d_1007b07c[24];  /* 0x1007B07C */
char s_cdaudio_1007b094[76];  /* 0x1007B094 */
char DAT_1007b0e0[388];  /* 0x1007B0E0 */
int g_id;  /* 0x1007B264 */
int DAT_1007b268;  /* 0x1007B268 */
char s_Error__unknown_command__02X_rece_1007b26c[64];  /* 0x1007B26C */
char s__s_finished__s_1007b2ac[16];  /* 0x1007B2AC */
char s_returned_to_race_lobby__1007b2bc[28];  /* 0x1007B2BC */
char s_left_the_race__1007b2d8[16];  /* 0x1007B2D8 */
char s_booted_you_from_the_game__1007b2e8[28];  /* 0x1007B2E8 */
BR_GLOBAL_EXTENT(char, DAT_1007b304, [4], 0x18);  /* 0x1007B304 */
int g_7b320;  /* 0x1007B320 */
int g_7b324;  /* 0x1007B324 */
int g_7b328;  /* 0x1007B328 */
BR_GLOBAL_EXTENT(int, g_7b32c, , 0x54);  /* 0x1007B32C */
char s_Boss_Rally_1007b384[12];  /* 0x1007B384 */
char s_bsuspension__1007b390[16];  /* 0x1007B390 */
char s_btire__1007b3a0[8];  /* 0x1007B3A0 */
char s_bcar__1007b3a8[8];  /* 0x1007B3A8 */
char s_cPlayers__1007b3b0[12];  /* 0x1007B3B0 */
char s_szPlayerName__1007b3bc[16];  /* 0x1007B3BC */
char s_PlaySFX__1007b3cc[12];  /* 0x1007B3CC */
char s_PlayMusic__1007b3d8[12];  /* 0x1007B3D8 */
char s_RunBenchmark__1007b3e4[16];  /* 0x1007B3E4 */
char s_D3DDrawCarShadow__1007b3f4[20];  /* 0x1007B3F4 */
char s_SpeedSensitive__1007b408[16];  /* 0x1007B408 */
char s_Interpolate__1007b418[16];  /* 0x1007B418 */
char s_SFXDir__1007b428[8];  /* 0x1007B428 */
char s_CarDir__1007b430[8];  /* 0x1007B430 */
char s_TrackDir__1007b438[12];  /* 0x1007B438 */
char s_TransmissionType__1007b444[20];  /* 0x1007B444 */
char s_TireType__1007b458[12];  /* 0x1007B458 */
char s_SuspensionType__1007b464[16];  /* 0x1007B464 */
char s_HandlingType__1007b474[16];  /* 0x1007B474 */
char s_ReadJoystick__1007b484[16];  /* 0x1007B484 */
char s_gameMode__1007b494[12];  /* 0x1007B494 */
char s_chosenWeather__1007b4a0[16];  /* 0x1007B4A0 */
char s_chosenCar__1007b4b0[12];  /* 0x1007B4B0 */
char s_chosenTrack__1007b4bc[16];  /* 0x1007B4BC */
char s_NetworkPlay__1007b4cc[16];  /* 0x1007B4CC */
char s_BossRally_ini_1007b4dc[0x50];  /* 0x1007B4DC */
char DAT_1007b52c[0x20];  /* 0x1007B52C */
char DAT_1007b54c[0x20];  /* 0x1007B54C */
char DAT_1007b56c[0x18];  /* 0x1007B56C */
char DAT_1007b584[0x1C];  /* 0x1007B584 */
char s__s_is_not_a_valid_POD_file_1007b5a0[28];  /* 0x1007B5A0 */
char DAT_1007b5bc[68];  /* 0x1007B5BC */
char DAT_1007b600[24];  /* 0x1007B600 */
uint8_t g_aBrFontBlockLarge[54 * 0xA00];  /* 0x1007B618: 54 glyph strips of 64x40, up to the small sheet */
BrUiCtlVtbl_ g_brUiCtlVtbl_1008F6B8;  /* 0x1008F6B8 */
BrUiPageVtbl BrUiPageVtbl_1008F6F8;  /* 0x1008F6F8 */
BR_GLOBAL_EXTENT(BrPhaseFullVtbl, BrPhaseVtbl_1008F700, , 0x4);  /* 0x1008F700 */
BrTextBoxVtbl g_BrTextBoxVtbl;  /* 0x1008F728 */
BR_GLOBAL_EXTENT(BrTextListVtbl *, g_pBrTextListVtbl, , 0x4B3C);  /* 0x1008F758 */
BR_GLOBAL_EXTENT(int, g_brNetSendCount, , 0x8F7C);  /* 0x10094298 */
uint8_t g_aBrFontBlockSmall[54 * 0x280];  /* 0x1009D218: 54 glyph strips of 32x20 */
signed char DAT_100a58f7[33];  /* 0x100A58F7 */
signed char g_aBrFontClass[96];  /* 0x100A5918 */
int32_t g_aBrFontOffLarge[56];  /* 0x100A5978 */
int32_t g_aBrFontOffSmall[58];  /* 0x100A5A58 */
BR_GLOBAL_EXTENT(int32_t, g_BrDrawReflectFlag, , 0xC);  /* 0x100A5B40 */
char s_finished__s_100a5b50[16];  /* 0x100A5B50 */
char s_APPMSG_BOOTPLAYER__received_100a5b60[32];  /* 0x100A5B60 */
char s_APPMSG_HOSTSTARTED__received_100a5b80[32];  /* 0x100A5B80 */
char s_APPMSG_PLAYERREADY__Set___d__ID__100a5ba0[40];  /* 0x100A5BA0 */
char s_Host_set_ready_message_received__100a5bc8[144];  /* 0x100A5BC8 */
uint32_t *g_BrDrawRefColors;  /* 0x100A5C58 */
void *g_0A649C;  /* 0x100A5C5C */
BR_GLOBAL_EXTENT(void *, g_0A64A0, , 0x14);  /* 0x100A5C60 */
int8_t g_BrDrawRefTbl[16];  /* 0x100A5C78 */
uint8_t g_BrDrawTexBlob[0x20];  /* 0x100A5C88 */
BrLightHist g_BrVisLightHist[4];  /* 0x100A5CA8 */
uint8_t DAT_100a5cb0[232];  /* 0x100A5CB0 */
int DAT_100a5d98[4];  /* 0x100A5D98 */
char DAT_100a5da8[12];  /* 0x100A5DA8 */
char DAT_100a5db4[236];  /* 0x100A5DB4 */
char DAT_100a5ea0[8];  /* 0x100A5EA0 */
int32_t g_brRaceBeginLimitOn;  /* 0x100A5EA8 */
int DAT_100a5eac;  /* 0x100A5EAC */
BrRaceCue g_aBrRaceCue[96];  /* 0x100A5EB0: 95 lines and the terminator */
BR_GLOBAL_EXTENT(int32_t, BrTextWidthLarge, [55], 0x4);  /* 0x100A6070 */
BR_GLOBAL_EXTENT(int32_t, BrTextWidthSmall, [55], 0x284);  /* 0x100A6150 */
float g_BrFpsValueA;  /* 0x100A64B0 */
float g_BrFpsValueB;  /* 0x100A64B4 */
int DAT_100a64b8;  /* 0x100A64B8 */
BR_GLOBAL_EXTENT(int, DAT_100a64bc, , 0x6A0);  /* 0x100A64BC */
char DAT_100a6b60[4];  /* 0x100A6B60 */
char DAT_100a6b64[4];  /* 0x100A6B64 */
BR_GLOBAL_EXTENT(int32_t, DAT_100a6b68, [4], 0x8);  /* 0x100A6B68 */
char g_aBr63Prefix[260];  /* 0x100A6B80 */
char g_szBrFmt6B84[20];  /* 0x100A6B84 */
char s___55_s_100a6b98[8];  /* 0x100A6B98 */
char s___55_d__100a6ba0[8];  /* 0x100A6BA0 */
char s___x_02x_02x_02x_s_100a6ba8[20];  /* 0x100A6BA8 */
char s___x_02x_02x_02x_s__s_100a6bbc[24];  /* 0x100A6BBC */
char s___11_s_100a6bd4[8];  /* 0x100A6BD4 */
char s___x_02x_02x_02x_s__dms__c_c_100a6bdc[28];  /* 0x100A6BDC */
char s___x_02x_02x_02x_s__s__dms__c_c_100a6bf8[32];  /* 0x100A6BF8 */
char s___11_s__dms__c_c_100a6c18[20];  /* 0x100A6C18 */
char s___ry_d__100a6c2c[8];  /* 0x100A6C2C */
char s___y1_d__100a6c34[8];  /* 0x100A6C34 */
char s___11_d__100a6c3c[44];  /* 0x100A6C3C */
int DAT_100a6c68;  /* 0x100A6C68 */
int DAT_100a6c6c;  /* 0x100A6C6C */
BR_GLOBAL_EXTENT(int, DAT_100a6c70, , 0x4);  /* 0x100A6C70 */
uint8_t g_aBrFontRampLargeA[320];  /* 0x100A6C78 */
uint8_t g_aBrFontRampLargeB[320];  /* 0x100A6DB8 */
uint8_t g_aBrFontRampSmallA[320];  /* 0x100A6EF8 */
uint8_t g_aBrFontRampSmallB[336];  /* 0x100A7038 */
float DAT_100a7188;  /* 0x100A7188 */
int DAT_100a718c;  /* 0x100A718C */
char s_EAR_Interactive_Around_Sound_100a7190[32];  /* 0x100A7190 */
char s__EAR_DLL_UpdateEar_0_100a71b0[24];  /* 0x100A71B0 */
char s__EAR_DLL_ShutDownTimer_0_100a71c8[28];  /* 0x100A71C8 */
char s__EAR_DLL_StartTimer_0_100a71e4[24];  /* 0x100A71E4 */
char s__EAR_DLL_StartEvent_4_100a71fc[24];  /* 0x100A71FC */
char s__EAR_DLL_ShutDownPreset_4_100a7214[28];  /* 0x100A7214 */
char s__EAR_DLL_ShutDownMatrix_4_100a7230[28];  /* 0x100A7230 */
char s__EAR_DLL_ShutDownEvent_8_100a724c[28];  /* 0x100A724C */
char s__EAR_DLL_ShutDownEnvironment_4_100a7268[32];  /* 0x100A7268 */
char s__EAR_DLL_ShutDownEar_0_100a7288[24];  /* 0x100A7288 */
char s__EAR_DLL_ShutDownChannel_4_100a72a0[28];  /* 0x100A72A0 */
char s__EAR_DLL_ShutDownBank_4_100a72bc[24];  /* 0x100A72BC */
char s__EAR_DLL_ShowLastError_0_100a72d4[28];  /* 0x100A72D4 */
char s__EAR_DLL_SetUserDistanceUnit_8_100a72f0[32];  /* 0x100A72F0 */
char s__EAR_DLL_SetAttenuationLevel_8_100a7310[32];  /* 0x100A7310 */
char s__EAR_DLL_ResetEar_0_100a7330[20];  /* 0x100A7330 */
char s__EAR_DLL_RegisterPreset_8_100a7344[28];  /* 0x100A7344 */
char s__EAR_DLL_RegisterMatrix_4_100a7360[28];  /* 0x100A7360 */
char s__EAR_DLL_RegisterEnvironment_4_100a737c[32];  /* 0x100A737C */
char s__EAR_DLL_RegisterChannel_16_100a739c[28];  /* 0x100A739C */
BR_GLOBAL_EXTENT(char, s__EAR_DLL_RegisterBank_8_100a73b8, [12], 0xC);  /* 0x100A73B8 */
BR_GLOBAL_EXTENT(char, s__EAR_DLL_MoveEvent_4_100a73d0, [4], 0x14);  /* 0x100A73D0 */
char s__EAR_DLL_MixEvent_4_100a73e8[20];  /* 0x100A73E8 */
char s__EAR_DLL_InitializeEar_4_100a73fc[28];  /* 0x100A73FC */
char s__EAR_DLL_GetVersion_0_100a7418[24];  /* 0x100A7418 */
char s__EAR_DLL_GetLastError_0_100a7430[24];  /* 0x100A7430 */
char s__EAR_DLL_GetEventStatus_8_100a7448[28];  /* 0x100A7448 */
char s__EAR_DLL_EarInactive_0_100a7464[24];  /* 0x100A7464 */
char s__EAR_DLL_ClearChannel_8_100a747c[24];  /* 0x100A747C */
char s__EAR_DLL_ChangeChannelControl_8_100a7494[32];  /* 0x100A7494 */
char s__EAR_DLL_AssignHwnd_4_100a74b4[24];  /* 0x100A74B4 */
char s__EAR_DLL_AAA_Validate_4_100a74cc[24];  /* 0x100A74CC */
char s_earias_dll_100a74e4[12];  /* 0x100A74E4 */
char s_earpds_dll_100a74f0[12];  /* 0x100A74F0 */
int32_t DAT_100a74fc;  /* 0x100A74FC */
float g_brFadeTgtB;  /* 0x100A7500 */
float g_brFadeCurB;  /* 0x100A7504 */
float g_brFadeTgtA;  /* 0x100A7508 */
float g_brFadeCurA;  /* 0x100A750C */
int32_t DAT_100a7510;  /* 0x100A7510 */
int BrGbiRectG_A7514;  /* 0x100A7514 */
int BrGbiRectG_A7518;  /* 0x100A7518 */
BR_GLOBAL_EXTENT(float *, DAT_100a751c, , 0x4AC);  /* 0x100A751C */
BR_GLOBAL_EXTENT(int32_t, BrG_0A79CC, , 0x42C);  /* 0x100A79CC */
int32_t g_brTex0A7DFC;  /* 0x100A7DFC */
int32_t g_brTex0A7E00;  /* 0x100A7E00 */
int32_t g_brTex0A7E04;  /* 0x100A7E04 */
BR_GLOBAL_EXTENT(int32_t, g_brTex0A7E08, , 0x3B4);  /* 0x100A7E08 */
int32_t BrG_0A81C0;  /* 0x100A81C0 */
BR_GLOBAL_EXTENT(int32_t, BrG_0A81C4, , 0x118C);  /* 0x100A81C4 */
BR_GLOBAL_EXTENT(BrRaceRules, g_brRaceRules, , 0x18);  /* 0x100A9354 */
BR_GLOBAL_EXTENT(signed char, g_tblBrA9560, [24], 0x40);  /* 0x100A9560 */
int g_0A95B8[108];  /* 0x100A95B8 */
char g_0A9768[36];  /* 0x100A9768 */
char g_0A978C[28];  /* 0x100A978C */
char g_0A97A8[40];  /* 0x100A97A8 */
char g_0A97D0[16];  /* 0x100A97D0 */
char g_0A97E0[24];  /* 0x100A97E0 */
char g_0A97F8[16];  /* 0x100A97F8 */
char g_0A9808[28];  /* 0x100A9808 */
char g_0A9824[28];  /* 0x100A9824 */
char g_0A9840[16];  /* 0x100A9840 */
char g_0A9850[24];  /* 0x100A9850 */
char g_0A9868[16];  /* 0x100A9868 */
char g_0A9878[12];  /* 0x100A9878 */
char g_0A9884[116];  /* 0x100A9884 */
BR_GLOBAL_EXTENT(int32_t, g_brAppContinue, , 0x4);  /* 0x100A98F8 */
int32_t (*s_apfnAppState[5])(void);  /* 0x100A9900 */
uint32_t s17_colAA5D0[4];  /* 0x100A9930 */
char BrDxMsgCreateSurfaceFailed[28];  /* 0x100A9940 */
char BrDxMsgCoopLevelFailed[28];  /* 0x100A995C */
char BrDxMsgQiDDraw2Failed[24];  /* 0x100A9978 */
char BrDxMsgCreateDDrawFailed[24];  /* 0x100A9990 */
char BrDxMsgLoadDDrawFailed[32];  /* 0x100A99A8 */
char BrDxNameDDrawCreate[20];  /* 0x100A99C8 */
char BrDxNameDDrawDll[12];  /* 0x100A99DC */
char BrDxMsgProcDInputFailed[40];  /* 0x100A99E8 */
char BrDxNameDInputCreate[20];  /* 0x100A9A10 */
char BrDxMsgLoadDInputFailed[32];  /* 0x100A9A24 */
char BrDxNameDInputDll[12];  /* 0x100A9A44 */
int DAT_100a9a50;  /* 0x100A9A50 */
float BrGbiRectG_A9A54;  /* 0x100A9A54 */
BrGbiHandler g_brGbi0A79F0[256];  /* 0x100A9A58 */
uint8_t *DAT_100a9e58;  /* 0x100A9E58 */
char s_Out_of_tex_mem__100a9e5c[16];  /* 0x100A9E5C */
char s_AppendTexture__atdb_100a9e6c[76];  /* 0x100A9E6C */
int DAT_100a9eb8;  /* 0x100A9EB8 */
int DAT_100a9ebc;  /* 0x100A9EBC */
uint32_t DAT_100a9ec0[16];  /* 0x100A9EC0 */
uint32_t BrG_0AA770[50];  /* 0x100A9F00 */
uint32_t BrG_0AA838[10];  /* 0x100A9FC8 */
BR_GLOBAL_EXTENT(BrLightHist, g_BrVisLightTemplate, , 0x4);  /* 0x100A9FF0 */
int DAT_100aa00c;  /* 0x100AA00C */
int DAT_100aa010;  /* 0x100AA010 */
int DAT_100aa014;  /* 0x100AA014 */
BR_GLOBAL_EXTENT(int, DAT_100aa018, , 0x4);  /* 0x100AA018 */
int DAT_100aa020;  /* 0x100AA020 */
BR_GLOBAL_EXTENT(int, DAT_100aa024, , 0x4);  /* 0x100AA024 */
int _DAT_100aa02c;  /* 0x100AA02C */
BR_GLOBAL_EXTENT(int, DAT_100aa030, , 0x8);  /* 0x100AA030 */
float g_BrCamScale;  /* 0x100AA03C */
float DAT_100aa040;  /* 0x100AA040 */
int g_brMode0AA8B4;  /* 0x100AA044 */
uint32_t DAT_100aa048[8];  /* 0x100AA048: BrDlRecolor's 0xFC row and its two match pairs */
unsigned char g_BrDlTableA[192];  /* 0x100AA068 */
BR_GLOBAL_EXTENT(int, DAT_100aa128, , 0xBC);  /* 0x100AA128 */
BR_GLOBAL_EXTENT(int, DAT_100aa1e8, , 0xBC);  /* 0x100AA1E8 */
BR_GLOBAL_EXTENT(int, DAT_100aa2a8, , 0x28);  /* 0x100AA2A8 */
char s_HUGE_GLIST_ERROR_100aa2d4[32];  /* 0x100AA2D4 */
char DAT_100aa2f4[20];  /* 0x100AA2F4 */
char DAT_100aa308[8];  /* 0x100AA308 */
char DAT_100aa310[8];  /* 0x100AA310 */
char s_File__s_missing_100aa318[16];  /* 0x100AA318 */
char s__u__x__d__d_100aa328[12];  /* 0x100AA328 */
char DAT_100aa334[4];  /* 0x100AA334 */
char DAT_100aa338[8];  /* 0x100AA338 */
char g_szBrFmtSS[8];  /* 0x100AA340 */
char DAT_100aa348[48];  /* 0x100AA348 */
char DAT_100aa378[44];  /* 0x100AA378 */
char DAT_100aa3a4[68];  /* 0x100AA3A4 */
BR_GLOBAL_EXTENT(char *, PTR_s_First__100aa3e8, [20], 0xA0);  /* 0x100AA3E8 */
char s_Could_not_create_DirectPlay_obje_100aa4d8[60];  /* 0x100AA4D8 */
char s_DirectPlay_interface_final_insta_100aa514[48];  /* 0x100AA514 */
char s_Could_not_select_service_provide_100aa544[60];  /* 0x100AA544 */
char s_Could_not_host_session_because_o_100aa580[48];  /* 0x100AA580 */
char DAT_100aa5b0[376];  /* 0x100AA5B0 */
uintptr_t BrG_0AA728;  /* 0x100AA728 */
uint32_t BrG_0AA72C;  /* 0x100AA72C */
uint8_t BrG_0AA730[0x154];  /* 0x100AA730 */
BR_GLOBAL_EXTENT(int32_t, BrG_0AA884, , 0x8);  /* 0x100AA884 */
BR_GLOBAL_EXTENT(int32_t, BrG_0AA890, , 0x20);  /* 0x100AA890 */
BR_GLOBAL_EXTENT(int32_t, BrG_0AA8B4, , 0x218);  /* 0x100AA8B4 */
KeyEnt g_aKeyEnt0AAAD0[21];  /* 0x100AAAD0 */
BrBind39870 g_brBindAAAD4[21];  /* 0x100AAAD4 */
BR_GLOBAL_EXTENT(int16_t, BrGlNavStepAB7C, , 0x2);  /* 0x100AAB7C */
int g_brRec0AAB80;  /* 0x100AAB80 */
BR_GLOBAL_EXTENT(unsigned short, DAT_100aab84, , 0x2);  /* 0x100AAB84 */
uint32_t g_br0AB3E8;  /* 0x100AAB88 */
BR_GLOBAL_EXTENT(int, DAT_100aab8c, , 0x4);  /* 0x100AAB8C */
int g_AB94;  /* 0x100AAB94 */
BR_GLOBAL_EXTENT(int, g_selArg2, , 0xC);  /* 0x100AAB98 */
BR_GLOBAL_EXTENT(int, g_selArg, , 0xC);  /* 0x100AABA8 */
BrHitRect g_hot1;  /* 0x100AABB8 */
BrHitRect g_hot2;  /* 0x100AABC8 */
BR_GLOBAL_EXTENT(char, DAT_100aabd8, , 0xF);  /* 0x100AABD8 */
BrHitRect g_hot0;  /* 0x100AABE8 */
BR_GLOBAL_EXTENT(char, DAT_100aabf8, , 0xF);  /* 0x100AABF8 */
BR_GLOBAL_EXTENT(char, DAT_100aac08, , 0xF);  /* 0x100AAC08 */
BR_GLOBAL_EXTENT(char, DAT_100aac18, , 0xF);  /* 0x100AAC18 */
BR_GLOBAL_EXTENT(char, DAT_100aac28, , 0xF);  /* 0x100AAC28 */
BR_GLOBAL_EXTENT(char, DAT_100aac38, , 0xF);  /* 0x100AAC38 */
BR_GLOBAL_EXTENT(char, DAT_100aac48, , 0xF);  /* 0x100AAC48 */
BR_GLOBAL_EXTENT(char, DAT_100aac58, , 0xF);  /* 0x100AAC58 */
BR_GLOBAL_EXTENT(char, DAT_100aac68, , 0xF);  /* 0x100AAC68 */
BR_GLOBAL_EXTENT(char, DAT_100aac78, , 0xF);  /* 0x100AAC78 */
BR_GLOBAL_EXTENT(char, DAT_100aac88, , 0xF);  /* 0x100AAC88 */
BR_GLOBAL_EXTENT(char, DAT_100aac98, , 0xF);  /* 0x100AAC98 */
BR_GLOBAL_EXTENT(char, DAT_100aaca8, , 0x1F);  /* 0x100AACA8 */
BR_GLOBAL_EXTENT(char, DAT_100aacc8, , 0xF);  /* 0x100AACC8 */
BR_GLOBAL_EXTENT(char, DAT_100aacd8, , 0xF);  /* 0x100AACD8 */
BR_GLOBAL_EXTENT(char, DAT_100aace8, , 0xF);  /* 0x100AACE8 */
BR_GLOBAL_EXTENT(int, DAT_100aacf8, , 0xC);  /* 0x100AACF8 */
BrUiSprite g_aBrUiSprite[145];  /* 0x100AAD08 */
int g_p0AB3E0;  /* 0x100AB3E0 */
BR_GLOBAL_EXTENT(int16_t, g_br0AB3E4, , 0x6);  /* 0x100AB3E4 */
BR_GLOBAL_EXTENT(uint32_t, g_br0AB3EC, , 0x28);  /* 0x100AB3EC */
BR_GLOBAL_EXTENT(BrTextStyle, g_aBrUiStyle, [21], 0x454);  /* 0x100AB418 */
BR_GLOBAL_EXTENT(int32_t, g_BrSprRect46, [4], 0x20);  /* 0x100AB9BC */
BR_GLOBAL_EXTENT(int32_t, g_BrSprRect48, [4], 0xA4);  /* 0x100AB9EC */
uint32_t g_AC300;  /* 0x100ABAA0 */
int DAT_100abaa4;  /* 0x100ABAA4 */
int g_brTblABAA8[24];  /* 0x100ABAA8 */
int32_t g_aBrAC368[18];  /* 0x100ABB08 */
int32_t g_aBrAC3B0[6];  /* 0x100ABB50 */
int32_t g_aBrAC3C8[6];  /* 0x100ABB68 */
int g_brTblABB80[8];  /* 0x100ABB80 */
int g_brTblABBA0[4];  /* 0x100ABBA0 */
int g_brTblABBB0[2];  /* 0x100ABBB0 */
int g_brTblABBB8[2];  /* 0x100ABBB8 */
int32_t g_aBrAC420[32];  /* 0x100ABBC0 */
int32_t g_aBrAC4A0[4];  /* 0x100ABC40 */
int32_t g_aBrAC4B0[4];  /* 0x100ABC50 */
int32_t g_aBrAC4C0[6];  /* 0x100ABC60 */
int32_t g_aBrAC4D8[16];  /* 0x100ABC78 */
int32_t g_aBrAC518[2];  /* 0x100ABCB8 */
int32_t g_aBrAC520[4];  /* 0x100ABCC0 */
int DAT_100abcd0[2];  /* 0x100ABCD0 */
int DAT_100abcd8[2];  /* 0x100ABCD8 */
int DAT_100abce0[2];  /* 0x100ABCE0 */
int DAT_100abce8[10];  /* 0x100ABCE8 */
uint16_t k_AC570[16];  /* 0x100ABD10 */
int8_t k_AC590[8];  /* 0x100ABD30 */
int8_t k_AC598[4];  /* 0x100ABD38 */
int8_t k_AC59C[4];  /* 0x100ABD3C */
BR_GLOBAL_EXTENT(int8_t, k_AC5A0, [4], 0x84);  /* 0x100ABD40 */
int8_t k_AC628[4];  /* 0x100ABDC8 */
int8_t k_AC62C[4];  /* 0x100ABDCC */
int8_t k_AC630[4];  /* 0x100ABDD0 */
int8_t k_AC634[4];  /* 0x100ABDD4 */
BR_GLOBAL_EXTENT(int8_t, k_AC638, [4], 0x4);  /* 0x100ABDD8 */
uint32_t k_AC640[2];  /* 0x100ABDE0 */
int g_brIdx0ABDE8;  /* 0x100ABDE8 */
int32_t DAT_100abae8[26];  /* 0x100ABAE8 */
uint32_t DAT_100abdec;  /* 0x100ABDEC */
uint32_t DAT_100abdf0;  /* 0x100ABDF0 */
int g_brSel0ABDF4;  /* 0x100ABDF4 */
int DAT_100abdf8;  /* 0x100ABDF8 */
int32_t g_i0AC65C;  /* 0x100ABDFC */
BrErrEnt DAT_100abe00[BR_ERR_COUNT];  /* 0x100ABE00  the error table; entry 8 is also DAT_100abe40 / g_ABE44 */
BrCheatEntry g_aBrCheatCode[16];  /* 0x100ABE48 */
BR_GLOBAL_EXTENT(Metric12, g_BrGlyphFontA12, [95], 0x4);  /* 0x100ABE84 */
Metric12B g_BrGlyphFontB12[95];  /* 0x100AC2FC */
int32_t g_aBrAC308[168];  /* 0x100AC308 */
int32_t g_aBrAC530[2];  /* 0x100AC530 */
int32_t g_aBrAC538[2];  /* 0x100AC538 */
int32_t g_aBrAC540[2];  /* 0x100AC540 */
int32_t g_aBrAC548[44];  /* 0x100AC548 */
BrCharMapEntry g_BrCharMapImage[784];  /* 0x100AC5F8 */
BrGlyphMetric g_BrGlyphFontA[95];  /* 0x100AC6E4 */
BR_GLOBAL_EXTENT(Dim, g_tab, [7], 0x88);  /* 0x100AC908 */
char DAT_100ac9c8[132];  /* 0x100AC9C8 */
BR_GLOBAL_EXTENT(char, DAT_100aca4c, , 0x3);  /* 0x100ACA4C */
char g_szBr0ACA50[124];  /* 0x100ACA50 */
char DAT_100acacc[4];  /* 0x100ACACC */
char DAT_100acad0[8];  /* 0x100ACAD0 */
char g_strA[8];  /* 0x100ACAD8 */
char g_szBrDashes[8];  /* 0x100ACAE0 */
char s_AutoSave_brf[16];  /* 0x100ACAE8 */
char s_brf_100acaf8[8];  /* 0x100ACAF8 */
char s_RallySeason_100acb00[12];  /* 0x100ACB00 */
char s_grf_100acb0c[8];  /* 0x100ACB0C */
char s_TimeAttack_100acb14[12];  /* 0x100ACB14 */
char s_RallySeason_BRF[20];  /* 0x100ACB20 */
BR_GLOBAL_EXTENT(char, s_TimeAttack__GRF_100acb34, , 0xF);  /* 0x100ACB34 */
char DAT_100acb44[8];  /* 0x100ACB44 */
char s_seasondesc_dat_100acb4c[16];  /* 0x100ACB4C */
BR_GLOBAL_EXTENT(BrGlyphMetric, g_BrGlyphFontB, [95], 0x4);  /* 0x100ACB5C */
BR_GLOBAL_EXTENT(BrCharMapEntry, g_BrCharMap, [113], 0x4E8);  /* 0x100ACE58 */
char s_DDraw_DoInit__Bitmap__d_failed_t_100ad6c8[40];  /* 0x100AD6C8 */
char s_DDraw_DoInit__loading_bmp_failed_100ad6f0[44];  /* 0x100AD6F0 */
char s_images_loading_bmp_100ad71c[20];  /* 0x100AD71C */
BR_GLOBAL_EXTENT(char, DAT_100ad730, [4], 0xC);  /* 0x100AD730 */
char DAT_100ad740[32];  /* 0x100AD740 */
int DAT_100ad760;  /* 0x100AD760 */
int DAT_100ad764;  /* 0x100AD764 */
BR_GLOBAL_EXTENT(int, DAT_100ad768, , 0x4);  /* 0x100AD768 */
BR_GLOBAL_EXTENT(unsigned char, DAT_100ad770, , 0x27);  /* 0x100AD770 */
BR_GLOBAL_EXTENT(unsigned char, DAT_100ad798, , 0x27);  /* 0x100AD798 */
unsigned long long DAT_100ad7c0;  /* 0x100AD7C0 */
BR_GLOBAL_EXTENT(int, DAT_100ad7c8, , 0x4);  /* 0x100AD7C8 */
BR_GLOBAL_EXTENT(int, DAT_100ad7d0, , 0x4);  /* 0x100AD7D0 */
BrLivery g_aBrLivery[16][30];  /* 0x100AD7D8 */
BR_GLOBAL_EXTENT(int, DAT_100b22d8, , 0xB70);  /* 0x100B22D8 */
char s_Paint__s_100b2e4c[12];  /* 0x100B2E4C */
char s_Paint_damage_d_bmp_100b2e58[20];  /* 0x100B2E58 */
int DAT_100b2e6c;  /* 0x100B2E6C */
float DAT_100b2e70;  /* 0x100B2E70 */
float DAT_100b2e74;  /* 0x100B2E74 */
BR_GLOBAL_EXTENT(float, DAT_100b2e78, , 0x84);  /* 0x100B2E78 */
int32_t g_brRaceNDriver;  /* 0x100B2F00 */
int32_t g_BrCarCount;  /* 0x100B2F04 */
BrZeroRegion DAT_100b2f08[208];  /* 0x100B2F08 */
uint8_t g_aBr0B37D0[60];  /* 0x100B2FD8 */
int32_t g_Br0B380C;  /* 0x100B3014 */
BrMenuStage g_brStages[128];  /* 0x100B3018 */
BrRec24 g_brTbl0B3020[1];  /* 0x100B3020 */
BrLevelRec DAT_100b3024[1];  /* 0x100B3024 */
uint8_t g_aBr0B3820[260];  /* 0x100B3028 */
float g_aBrAiDiffScale[48];  /* 0x100B30A8 */
int32_t g_aBrRacePlaceMsg[20];  /* 0x100B3168 */
BrVarBlock g_0B39B0[48];  /* 0x100B31B8; 23 entries in the original, ranges split per object here */  /* 0x100B31B8 */
BrVarBlock g_0B3A68[16];  /* 0x100B3270; 8 entries in the original */  /* 0x100B3270 */
int DAT_100b32b0[275];  /* 0x100B32B0; read also as 0x100B32BC and 0x100B32C0 */
BR_GLOBAL_EXTENT(int32_t, g_br0B36FC, , 0x12C);  /* 0x100B36FC */
char s_SAVING_LAST_LAP_INFO_100b382c[24];  /* 0x100B382C */
char DAT_100b3844[20];  /* 0x100B3844 */
int32_t g_brRaceNEntrant;  /* 0x100B3858 */
char s_sizeof_Enemy___d_100b385c[20];  /* 0x100B385C */
char s_sizeof_Vehicle___d_100b3870[20];  /* 0x100B3870 */
char s_sizeof_UltraCarHeader___d_100b3884[28];  /* 0x100B3884 */
BrCtrlProfile g_BrCtrlDefaults[4];  /* 0x100B38A0 */
BrCfgRec39580 g_aBrCtlNameKey[120];  /* 0x100B3B40 */
BR_GLOBAL_EXTENT(char, g_aBrKeyName3B44, [35][36], 0x20);  /* 0x100B3B44 */
BR_GLOBAL_EXTENT(int32_t, BrG_0B4050, , 0xBCC);  /* 0x100B4050 */
char BrGlCfgMagic[8];  /* 0x100B4C20 */
int32_t g_BrFpsCountB;  /* 0x100B4C28 */
int32_t g_BrFpsGateB;  /* 0x100B4C2C */
float g_aBrCarPhysDrvT1A[72];  /* 0x100B4C30 */
float g_aBrCarPhysDrvT1B[72];  /* 0x100B4D50 */
float g_aBrCarPhysDrvT2A[24];  /* 0x100B4E70 */
float g_aBrCarPhysDrvT2B[24];  /* 0x100B4ED0 */
float g_aBrCarPhysGripA[72];  /* 0x100B4F30 */
float g_aBrCarPhysGripB[72];  /* 0x100B5050 */
BR_GLOBAL_EXTENT(float, DAT_100b5170, , 0x4);  /* 0x100B5170 */
BR_GLOBAL_EXTENT(float, g_aBrCarPhysDrvT3, [24], 0xC);  /* 0x100B5178 */
char DAT_100b51e4[19200];  /* 0x100B51E4 */
BrSndRow g_aBrSndRow[26];  /* 0x100B55F8 */
BrSndBankCarSlot g_0B6540[26 * 9];  /* 0x100B5D48: the sound bank, 26 rows of 18 ints to 0x100B6498 (one object: rows 1, 24, 25 were split off as globals of their own) */
char DAT_100b6498[8];  /* 0x100B6498 */
char DAT_100b64a0[8];  /* 0x100B64A0 */
char DAT_100b64a8[8];  /* 0x100B64A8 */
BR_GLOBAL_EXTENT(int, DAT_100b64b0, , 0x100C);  /* 0x100B64B0 */
char s_tracks__100b74c0[1024];  /* 0x100B74C0 */
char *PTR_s_desert_trk_100b78c0[16];  /* 0x100B78C0 */
char DAT_100b7900[1020];  /* 0x100B7900 */
char *BrSfxCarCode[17];  /* 0x100B7CFC */
char g_aBrCfgSfxDir[1024];  /* 0x100B7D40 */
char *g_apszTrackFiles[34];  /* 0x100B80B8 */
char * DAT_100b8140[26];  /* 0x100B8140 */
char * DAT_100b81a8[10];  /* 0x100B81A8 */
BR_GLOBAL_EXTENT(char *, g_aBrNames0B81D0, [12], 0x298);  /* 0x100B81D0 */
int32_t s_level;  /* 0x100B8498 */
BR_GLOBAL_EXTENT(funcptr, PTR_FUN_100b849c, , 0x8);  /* 0x100B849C */
BR_GLOBAL_EXTENT(int, DAT_100b84a8, , 0x4C);  /* 0x100B84A8 */
uint8_t g_apszCarFiles[486 * 4];  /* 0x100B84F8  byte flags, not pointers */
int32_t g_brTex0B8C90;  /* 0x100B8C90 */
BR_GLOBAL_EXTENT(uint32_t, g_0B8C94, , 0x18);  /* 0x100B8C94 */
unsigned char g_0B94A8[2056];  /* 0x100B8CB0 */
unsigned char g_0B9CB0[3608];  /* 0x100B94B8 */
BR_GLOBAL_EXTENT(int, DAT_100ba2d0, , 0xFFC);  /* 0x100BA2D0 */
int32_t g_br0BBAC8[3];  /* 0x100BB2D0 */
int DAT_100bb2dc;  /* 0x100BB2DC */
BR_GLOBAL_EXTENT(unsigned char, DAT_100bb2e0, , 0x3);  /* 0x100BB2E0 */
BR_GLOBAL_EXTENT(uint8_t, g_brFadeOutB, , 0x3);  /* 0x100BB2E4 */
BR_GLOBAL_EXTENT(uint8_t, BrSndMasterVolume, , 0x3);  /* 0x100BB2E8 */
BR_GLOBAL_EXTENT(uint8_t, g_brFadeOutA, , 0x1F);  /* 0x100BB2EC */
BrRaceDiffRec g_aBrRaceDiff[16];  /* 0x100BB2F0 */
BrRaceDiffRec * g_apBrRaceDiff[16];  /* 0x100BCAB0 */
BR_GLOBAL_EXTENT(int, g_CBE8, , 0x4);  /* 0x100BCBE8 */
int32_t g_br100BCBF0;  /* 0x100BCBF0 */
int32_t g_br0BCBF4;  /* 0x100BCBF4 */
int DAT_100bcbf8;  /* 0x100BCBF8 */
int32_t DAT_100bcbfc;  /* 0x100BCBFC */
int32_t g_br100BCC00;  /* 0x100BCC00 */
int DAT_100bcc04;  /* 0x100BCC04 */
BR_GLOBAL_EXTENT(int32_t, g_brMouseDivTable, [8], 0x4);  /* 0x100BCC08 */
int32_t g_br0BD424;  /* 0x100BCC2C */
int32_t g_br0BD428;  /* 0x100BCC30 */
int32_t g_br0BD42C;  /* 0x100BCC34 */
int32_t g_br0BD430[2];  /* 0x100BCC38 */
BR_GLOBAL_EXTENT(int32_t, g_br0BD438, , 0x188);  /* 0x100BCC40 */
int32_t g_BrCamDemo;  /* 0x100BCDCC */
unsigned char g_ab0C12A0[16 * 0x15F88];  /* 0x100BCDD0: the 16 car model slots */
BrRaceSel g_a220B20;  /* 0x1021C650 */
int g_brCdTrackLast;  /* 0x1021C768 */
int g_220C3C;  /* 0x1021C76C */
int g_220C40;  /* 0x1021C770 */
int g_brCdTrackFirst;  /* 0x1021C774 */
int DAT_1021c778;  /* 0x1021C778 */
void *DAT_1021c77c;  /* 0x1021C77C */
BrEarMixEvent g_brEarEvent;  /* 0x1021C780 */
uint16_t DAT_1021c7c4;  /* 0x1021C7C4 */
uint16_t DAT_1021c7c6;  /* 0x1021C7C6 */
int DAT_1021c7c8;  /* 0x1021C7C8 */
uint16_t DAT_1021c7cc;  /* 0x1021C7CC */
uint16_t DAT_1021c7ce;  /* 0x1021C7CE */
int DAT_1021c7d0;  /* 0x1021C7D0 */
int DAT_1021c7d4;  /* 0x1021C7D4 */
int DAT_1021c7d8;  /* 0x1021C7D8 */
int DAT_1021c7dc;  /* 0x1021C7DC */
int DAT_1021c7e0;  /* 0x1021C7E0 */
int DAT_1021c7e4;  /* 0x1021C7E4 */
int DAT_1021c7e8;  /* 0x1021C7E8 */
int DAT_1021c7ec;  /* 0x1021C7EC */
uint16_t DAT_1021c7f0;  /* 0x1021C7F0 */
uint16_t DAT_1021c7f2;  /* 0x1021C7F2 */
uint16_t DAT_1021c7f4;  /* 0x1021C7F4 */
uint16_t DAT_1021c7f6;  /* 0x1021C7F6 */
uint16_t DAT_1021c7f8;  /* 0x1021C7F8 */
uint16_t DAT_1021c7fa;  /* 0x1021C7FA */
BR_GLOBAL_EXTENT(uint16_t, DAT_1021c7fc, , 0x2);  /* 0x1021C7FC */
int g_220CD0;  /* 0x1021C800 */
int g_brCdTrackCur;  /* 0x1021C804 */
int g_220CD8;  /* 0x1021C808 */
BR_GLOBAL_EXTENT(char, DAT_1021c80c, , 0x3);  /* 0x1021C80C */
BR_GLOBAL_EXTENT(int, BrChkVerbose, , 0x8);  /* 0x1021C810 */
void *DAT_1021c81c;  /* 0x1021C81C */
BR_GLOBAL_EXTENT(float, DAT_1021c820, , 0x74);  /* 0x1021C820 */
BR_GLOBAL_EXTENT(float, _DAT_1021c898, , 0x24);  /* 0x1021C898 */
int DAT_1021c8c0[16];  /* 0x1021C8C0 */
int DAT_1021c900;  /* 0x1021C900 */
int DAT_1021c904;  /* 0x1021C904 */
int DAT_1021c908;  /* 0x1021C908 */
BR_GLOBAL_EXTENT(void *, g_brH220DDC, , 0x80);  /* 0x1021C90C */
float DAT_1021c990;  /* 0x1021C990 */
float DAT_1021c994;  /* 0x1021C994 */
float DAT_1021c998;  /* 0x1021C998 */
float DAT_1021c99c;  /* 0x1021C99C */
float DAT_1021c9a0;  /* 0x1021C9A0 */
float DAT_1021c9a4;  /* 0x1021C9A4 */
BR_GLOBAL_EXTENT(float, DAT_1021c9a8, , 0x4);  /* 0x1021C9A8 */
char DAT_1021c9b0[1024];  /* 0x1021C9B0 */
BR_GLOBAL_EXTENT(int, DAT_1021cdb0, , 0x4);  /* 0x1021CDB0 */
int g_a10221288[16];  /* 0x1021CDB8 */
BR_GLOBAL_EXTENT(int32_t, g_brCfgPlayers, , 0x4);  /* 0x1021CDF8 */
int DAT_1021ce00[16];  /* 0x1021CE00 */
int g_brNetPktTick;  /* 0x1021CE40 */
int DAT_1021ce44;  /* 0x1021CE44 */
int32_t g_i10221318;  /* 0x1021CE48 */
void *DAT_1021ce4c;  /* 0x1021CE4C */
int DAT_1021ce50;  /* 0x1021CE50 */
void *g_brH221324;  /* 0x1021CE54 */
BrNetSlot g_aBrNetSlot[16];  /* 0x1021CE58 */
BR_GLOBAL_EXTENT(int, DAT_102265d8, , 0x4);  /* 0x102265D8 */
BrPingSlot g_aBrPing[8];  /* 0x102265E0 */
BR_GLOBAL_EXTENT(int, DAT_102265e4, , 0x3C);  /* 0x102265E4 */
int32_t g_br22AAF4;  /* 0x10226624 */
char DAT_10226628[1024];  /* 0x10226628 */
int DAT_10226a28;  /* 0x10226A28 */
unsigned int DAT_10226a2c;  /* 0x10226A2C */
unsigned int DAT_10226a30;  /* 0x10226A30 */
void *g_brH22AF04;  /* 0x10226A34 */
int DAT_10226a38;  /* 0x10226A38 */
int DAT_10226a3c;  /* 0x10226A3C */
int DAT_10226a40;  /* 0x10226A40 */
int32_t g_brRaceTick;  /* 0x10226A44 */
int32_t g_brRaceNet;  /* 0x10226A48 */
int32_t g_brRaceBegin226A4C;  /* 0x10226A4C */
int DAT_10226a50;  /* 0x10226A50 */
void *DAT_10226a54;  /* 0x10226A54 */
void *DAT_10226a58;  /* 0x10226A58 */
void *DAT_10226a5c;  /* 0x10226A5C */
void *g_h1022AF30;  /* 0x10226A60 */
void *g_hBrNetMutex;  /* 0x10226A64 */
int g_brPingHead;  /* 0x10226A68 */
unsigned int g_brPingBestRtt;  /* 0x10226A6C */
BR_GLOBAL_EXTENT(int, DAT_10226a70, , 0x4);  /* 0x10226A70 */
BR_GLOBAL_EXTENT(char, g_aBrCfgIniPath, [324], 0x2BC);  /* 0x10226A78 */
uint32_t g_brTexSysMem;  /* 0x10226E78 */
int g_226e7c;  /* 0x10226E7C */
BR_GLOBAL_EXTENT(int, g_226e80, , 0x4);  /* 0x10226E80 */
BrPodWriteEntry g_BrPodDir[4096];  /* 0x10226E88 */
unsigned int g_BrPodCount;  /* 0x10272E88 */
BR_GLOBAL_EXTENT(FILE *, g_BrPodFile, , 0x474);  /* 0x10272E8C */
BrDPlayState g_BrDPlay;  /* 0x10273304 */
int g_BrDPlayCrit[6];  /* 0x10273310 */
BrDPlayCtx g_BrDPlayCtx;  /* 0x10273328 */
void *DAT_1027333c;  /* 0x1027333C */
uint32_t DAT_10273340;  /* 0x10273340 */
void *DAT_10273344;  /* 0x10273344 */
BR_GLOBAL_EXTENT(int32_t, DAT_10273348, , 0x4);  /* 0x10273348 */
int32_t g_BrCarVisAny[16];  /* 0x10273350 */
BR_GLOBAL_EXTENT(BrVec3, g_BrDrawDir0, , 0x4);  /* 0x10273390 */
uint8_t g_BrDrawLights[384];  /* 0x102733A0 */
int32_t g_BrDrawClass[16];  /* 0x10273520 */
BR_GLOBAL_EXTENT(BrVec3, g_BrDrawDir1, , 0x4);  /* 0x10273560 */
BrMat4 g_BrDrawWorld;  /* 0x10273570 */
BR_GLOBAL_EXTENT(uint32_t, g_BrCarMtxSlot, [16], 0xC);  /* 0x102735B0 */
int32_t g_BrDrawFogAlpha;  /* 0x102735FC */
uint32_t g_BrCarLightSlot[16];  /* 0x10273600 */
uint32_t g_BrDrawModeBase;  /* 0x10273640 */
uint32_t g_BrDrawRenderMode;  /* 0x10273644 */
int32_t g_BrCarVisOpaque[16];  /* 0x10273648 */
BR_GLOBAL_EXTENT(int32_t, g_BrDrawRefIndex, , 0x4);  /* 0x10273688 */
BrTrailSeg DAT_10273690[8 * 4 * 500];  /* 0x10273690: 500 skid segments per wheel, 4 wheels, 8 cars -- to 0x102E0C90 */
BrVec3 g_BrVisCarDelta;  /* 0x102E0C90 */
int DAT_102e0c9c;  /* 0x102E0C9C */
BR_GLOBAL_EXTENT(int, DAT_102e0ca0, , 0x4);  /* 0x102E0CA0 */
BrLerpNode g_2E54C0[64];  /* 0x102E0CA8 */
int g_BrVisFirstMid;  /* 0x102E16A8 */
void *DAT_102e16ac;  /* 0x102E16AC */
int *DAT_102e16b0;  /* 0x102E16B0 */
BrLerpNode *g_pBrLerpFree;  /* 0x102E16B4 */
int g_BrVisCellOverflow;  /* 0x102E16B8 */
int DAT_102e16bc;  /* 0x102E16BC */
BR_GLOBAL_EXTENT(int, g_BrVisCarCount, , 0x4);  /* 0x102E16C0 */
int g_BrVisCarIdx[17];  /* 0x102E16C8 */
int g_BrVisFirstFar;  /* 0x102E170C */
BR_GLOBAL_EXTENT(char, DAT_102e1710, , 0x7CFFF);  /* 0x102E1710 */
unsigned short g_BrVisSpans[2048];  /* 0x1035E710 */
float g_BrVisCarDot[16];  /* 0x1035F710 */
int DAT_1035f750[32];  /* 0x1035F750 */
float DAT_1035f7d0;  /* 0x1035F7D0 */
int g_BrVisFirstNear;  /* 0x1035F7D4 */
int *DAT_1035f7d8;  /* 0x1035F7D8 */
uint32_t *DAT_1035f7dc;  /* 0x1035F7DC */
BR_GLOBAL_EXTENT(uint32_t, DAT_1035f7e0, , 0x4);  /* 0x1035F7E0 */
BrVisCell g_BrVisCells[193];  /* 0x1035F7E8 */
float *DAT_1035faec;  /* 0x1035FAEC */
int DAT_1035faf0[32];  /* 0x1035FAF0 */
int g_BrVisLightHistIdx;  /* 0x1035FB70 */
int DAT_1035fb74;  /* 0x1035FB74 */
BrVec3 DAT_1035fb78;  /* 0x1035FB78 */
uint32_t DAT_1035fb84;  /* 0x1035FB84 */
uint32_t DAT_1035fb88;  /* 0x1035FB88 */
int g_BrVisSpanCount;  /* 0x1035FB8C */
BrVec3 g_BrVisLightDir;  /* 0x1035FB90 */
int DAT_1035fb9c;  /* 0x1035FB9C */
void *g_BrVisLights;  /* 0x1035FBA0 */
void *DAT_1035fba4;  /* 0x1035FBA4 */
BR_GLOBAL_EXTENT(char, DAT_1035fba8, , 0x270FF);  /* 0x1035FBA8 */
unsigned char g_BrSpanPending[2048];  /* 0x10386CA8 */
BR_GLOBAL_EXTENT(char, DAT_103874a8, , 0xF9FF);  /* 0x103874A8 */
int DAT_10396ea8;  /* 0x10396EA8 */
int DAT_10396eac;  /* 0x10396EAC */
int DAT_10396eb0;  /* 0x10396EB0 */
int DAT_10396eb4;  /* 0x10396EB4 */
BrMat4 DAT_10396eb8;  /* 0x10396EB8 */
unsigned int DAT_10396ef8;  /* 0x10396EF8 */
int DAT_10396efc;  /* 0x10396EFC */
unsigned int DAT_10396f00;  /* 0x10396F00 */
struct BrPaceNote *DAT_10396f04;  /* 0x10396F04 */
char g_aBr39B720[38592];  /* 0x10396F08 */
int g_aBrRbPerCar[5];  /* 0x10396F10 */
int g_brRb6F24;  /* 0x10396F24 */
char DAT_10396f28[28];  /* 0x10396F28 */
int g_brRb6F44;  /* 0x10396F44 */
BrSnap g_aBrSnap[6];  /* 0x10396F48 */
int g_brRbB4E8;  /* 0x104AB4E8 */
int g_brRbB4EC;  /* 0x104AB4EC */
int g_brRbB4F0;  /* 0x104AB4F0 */
BR_GLOBAL_EXTENT(int, g_brRbB4F4, , 0x4);  /* 0x104AB4F4 */
int g_brRbB4FC;  /* 0x104AB4FC */
int g_brRbB500;  /* 0x104AB500 */
int g_brRbInited;  /* 0x104AB504 */
BrHudQuad DAT_104ab508[4];  /* 0x104AB508 */
BR_GLOBAL_EXTENT(char, DAT_104ab708, [32], 0x3F8);  /* 0x104AB708 */
void *DAT_104abb20;  /* 0x104ABB20 */
int32_t g_brRace4ABB24;  /* 0x104ABB24 */
int DAT_104abb28;  /* 0x104ABB28 */
int DAT_104abb2c;  /* 0x104ABB2C */
BR_GLOBAL_EXTENT(int, DAT_104abb30, , 0xC);  /* 0x104ABB30 */
BR_GLOBAL_EXTENT(uint8_t, g_br4B0358, , 0x3);  /* 0x104ABB40 */
BR_GLOBAL_EXTENT(signed char, DAT_104abb44, , 0x3);  /* 0x104ABB44 */
BR_GLOBAL_EXTENT(uint8_t, g_4B0360, , 0x3);  /* 0x104ABB48 */
int DAT_104abb4c;  /* 0x104ABB4C */
int DAT_104abb50;  /* 0x104ABB50 */
int DAT_104abb54;  /* 0x104ABB54 */
BR_GLOBAL_EXTENT(int, DAT_104abb58, , 0x4);  /* 0x104ABB58 */
float DAT_104abb60[1];  /* 0x104ABB60 */
float DAT_104abb64;  /* 0x104ABB64 */
BR_GLOBAL_EXTENT(int, DAT_104abb68, , 0x304);  /* 0x104ABB68 */
BR_GLOBAL_EXTENT(BrVec3, DAT_104abe70, [2], 0x1860);  /* 0x104ABE70 */
BR_GLOBAL_EXTENT(float, DAT_104ad6e8, , 0x64C);  /* 0x104AD6E8 */
int32_t g_BrEnvSegCount;  /* 0x104ADD38 */
float DAT_104add3c;  /* 0x104ADD3C */
BR_GLOBAL_EXTENT(BrVec3, g_vPfxDrift, , 0x4);  /* 0x104ADD40 */
int16_t DAT_104add50[2][522][3];  /* 0x104ADD50 */
uint8_t g_BrEnvBitmap[2][0x1000];  /* 0x104AF5C8 */
BR_GLOBAL_EXTENT(float, DAT_104b15c8, , 0x4);  /* 0x104B15C8 */
BrVec3 DAT_104b15d0[2];  /* 0x104B15D0 */
int DAT_104b15e8;  /* 0x104B15E8 */
BR_GLOBAL_EXTENT(float, DAT_104b15ec, , 0x4);  /* 0x104B15EC */
int DAT_104b15f4;  /* 0x104B15F4 */
FARPROC DAT_104b15f8;  /* 0x104B15F8 */
BrCdVolumeSetFn g_575454;  /* 0x104B15FC */
FARPROC DAT_104b1600;  /* 0x104B1600 */
FARPROC DAT_104b1604;  /* 0x104B1604 */
FARPROC DAT_104b1608;  /* 0x104B1608 */
HMODULE DAT_104b160c;  /* 0x104B160C */
FARPROC DAT_104b1610;  /* 0x104B1610 */
BrEarMixEventFn g_pfn57546C;  /* 0x104B1614 */
BrEarShutdownChannelFn g_575470;  /* 0x104B1618 */
FARPROC DAT_104b161c;  /* 0x104B161C */
UINT DAT_104b1620;  /* 0x104B1620 */
FARPROC DAT_104b1624;  /* 0x104B1624 */
BrEarClearChannelFn g_pfn575480;  /* 0x104B1628 */
int (*DAT_104b162c)(int, int);  /* 0x104B162C */
FARPROC DAT_104b1630;  /* 0x104B1630 */
FARPROC DAT_104b1634;  /* 0x104B1634 */
FARPROC DAT_104b1638;  /* 0x104B1638 */
FARPROC DAT_104b163c;  /* 0x104B163C */
FARPROC DAT_104b1640;  /* 0x104B1640 */
FARPROC DAT_104b1644;  /* 0x104B1644 */
int (*DAT_104b1648)(int, int, int, int);  /* 0x104B1648 */
FARPROC DAT_104b164c;  /* 0x104B164C */
FARPROC DAT_104b1650;  /* 0x104B1650 */
FARPROC DAT_104b1654;  /* 0x104B1654 */
FARPROC DAT_104b1658;  /* 0x104B1658 */
FARPROC DAT_104b165c;  /* 0x104B165C */
FARPROC DAT_104b1660;  /* 0x104B1660 */
FARPROC DAT_104b1664;  /* 0x104B1664 */
FARPROC DAT_104b1668;  /* 0x104B1668 */
FARPROC DAT_104b166c;  /* 0x104B166C */
FARPROC DAT_104b1670;  /* 0x104B1670 */
FARPROC DAT_104b1674;  /* 0x104B1674 */
int (*DAT_104b1678)(int);  /* 0x104B1678 */
int _DAT_104b167c;  /* 0x104B167C */
int _DAT_104b1680;  /* 0x104B1680 */
int _DAT_104b1684;  /* 0x104B1684 */
BR_GLOBAL_EXTENT(int, DAT_104b1688, , 0x4);  /* 0x104B1688 */
int32_t g_brFadePos2Hist[2];  /* 0x104B1690 */
int32_t g_brFadePosHist[2];  /* 0x104B1698 */
float g_4B16A0;  /* 0x104B16A0 */
int32_t g_brFadeA4;  /* 0x104B16A4 */
int32_t g_brFadePos2;  /* 0x104B16A8 */
float g_4B16AC;  /* 0x104B16AC */
int32_t g_brFadePos;  /* 0x104B16B0 */
int32_t g_brFadeB4;  /* 0x104B16B4 */
void *g_brCursor575510;  /* 0x104B16B8 */
float DAT_104b16bc;  /* 0x104B16BC */
void *g_brCursor575518;  /* 0x104B16C0 */
float DAT_104b16c4;  /* 0x104B16C4 */
float DAT_104b16c8;  /* 0x104B16C8 */
int32_t g_brFadeKick;  /* 0x104B16CC */
int32_t g_brFadeKickB;  /* 0x104B16D0 */
int32_t g_brFadeKickA;  /* 0x104B16D4 */
BR_GLOBAL_EXTENT(int32_t, g_brFadeBounce, , 0x4);  /* 0x104B16D8 */
uint8_t *g_brSegHostBase;  /* 0x104B16E0 */
int32_t g_brSegN64Base;  /* 0x104B16E4 */
float g_afBrVtxOut[0x100000 / 4];  /* 0x104B16E8: BrVtxExpand's output, 8 floats a vertex, 1 MB to 0x105B16E8 */
BR_GLOBAL_EXTENT(int32_t, g_br675540, , 0x4);  /* 0x105B16E8 */
BrVtxCacheEnt g_aBrVtxCache[2048];  /* 0x105B16F0 */
int32_t g_brRca67B548;  /* 0x105B76F0 */
int32_t g_brRca67B54C;  /* 0x105B76F4 */
void * DAT_105b76f8[2048];  /* 0x105B76F8 */
BR_GLOBAL_EXTENT(uint32_t, g_67D550, , 0x4);  /* 0x105B96F8 */
unsigned int DAT_105b9700[6];  /* 0x105B9700 */
BR_GLOBAL_EXTENT(int, DAT_105b9718, , 0x4);  /* 0x105B9718 */
int DAT_105b9720;  /* 0x105B9720 */
BR_GLOBAL_EXTENT(int, DAT_105b9724, , 0x4);  /* 0x105B9724 */
unsigned char DAT_105b972c[38592];  /* 0x105B972C */
HWND g_brOwner5BC72C;  /* 0x105BC72C */
BrBootArgs s_args;  /* 0x105BC730 */
int32_t DAT_105bc740;  /* 0x105BC740 */
int32_t DAT_105bc744;  /* 0x105BC744 */
BR_GLOBAL_EXTENT(int32_t, DAT_105bc748, , 0x4);  /* 0x105BC748 */
BR_GLOBAL_EXTENT(int32_t, g_brRaceScript, , 0x4);  /* 0x105BC750 */
int32_t DAT_105bc758[2];  /* 0x105BC758 */
int g_5bc760;  /* 0x105BC760 */
float g_brRaceFade;  /* 0x105BC764 */
int32_t g_brRaceBeginSeqIdx;  /* 0x105BC768 */
int g_5BC76C;  /* 0x105BC76C */
int32_t DAT_105bc770[2];  /* 0x105BC770 */
BR_GLOBAL_EXTENT(int32_t, g_aBrRaceBeginFx, [8], 0x20);  /* 0x105BC778 */
BR_GLOBAL_EXTENT(int32_t, g_brRaceBeginRecArmed, , 0x4);  /* 0x105BC7B8 */
int32_t g_brRaceBeginAirplane;  /* 0x105BC7C0 */
int32_t g_brRaceBeginAirTrigger;  /* 0x105BC7C4 */
int32_t g_brRaceBeginCamMinus1;  /* 0x105BC7C8 */
int32_t g_brRaceBeginAirArmed;  /* 0x105BC7CC */
int32_t g_brRaceBeginPathIdx;  /* 0x105BC7D0 */
int32_t g_brRaceBeginPathLen;  /* 0x105BC7D4 */
float g_brRaceBeginPathScale;  /* 0x105BC7D8 */
BrVec3 *g_pBrRaceFlyPos;  /* 0x105BC7DC */
BrVec3 *g_pBrRaceFlyAim;  /* 0x105BC7E0 */
float g_brRaceBeginPathT;  /* 0x105BC7E4 */
float g_brRaceBeginPathSeg;  /* 0x105BC7E8 */
BrVec3 g_brRaceFlyDirPrev;  /* 0x105BC7EC */
BrVec3 g_brRaceFlyDirCur;  /* 0x105BC7F8 */
BrVec3 g_brRaceFlyDirNext;  /* 0x105BC804 */
int32_t g_brRaceBeginBestCar;  /* 0x105BC810 */
void *g_apBrRaceLeaderRec[17];  /* 0x105BC814  [1..n]: each entrant's record of the leader */
BR_GLOBAL_EXTENT(unsigned char, g_br6806B0, [36], 0x4);  /* 0x105BC858 */
float g_brRaceLightT;  /* 0x105BC880 */
float g_brRaceBeginSeqT;  /* 0x105BC884 */
int32_t g_brRaceBeginSeq888;  /* 0x105BC888 */
int32_t g_aBrRaceLeaderLen[17];  /* 0x105BC88C */
int32_t DAT_105bc8d0[2];  /* 0x105BC8D0 */
int32_t g_brRace5BC8D8;  /* 0x105BC8D8 */
int DAT_105bc8dc;  /* 0x105BC8DC */
uint8_t g_aBrRaceBeginRec[0x10];  /* 0x105BC8E0 */
int32_t DAT_105bc8f0[2];  /* 0x105BC8F0 */
BR_GLOBAL_EXTENT(int32_t, g_brRaceLights, , 0x4);  /* 0x105BC8F8 */
int32_t g_aBrFpsSamples[120];  /* 0x105BC900 */
int32_t g_brRaceBeginMovieDone;  /* 0x105BCAE0 */
int32_t g_brRaceClockCount;  /* 0x105BCAE4 */
int32_t g_brRaceBeginFxCount;  /* 0x105BCAE8 */
void *DAT_105bcaec;  /* 0x105BCAEC */
BR_GLOBAL_EXTENT(int, g_5BCAF0, , 0x4);  /* 0x105BCAF0 */
BR_GLOBAL_EXTENT(int, g_5BCAF8, , 0xFFFC);  /* 0x105BCAF8 */
int32_t DAT_105ccaf8[24];  /* 0x105CCAF8 */
int32_t g_brRaceHudA;  /* 0x105CCB58 */
int32_t g_BrX06909B4;  /* 0x105CCB5C */
int DAT_105ccb60;  /* 0x105CCB60 */
int g_5CCB64;  /* 0x105CCB64 */
int32_t DAT_105ccb68[9648];  /* 0x105CCB68 */
GrHwConfiguration BrGlHw;  /* 0x105CCBD8  grSstQueryHardware's answer */
int32_t BrGlHwParamB;  /* 0x105CCC6C */
uint32_t BrGlAtestFuncShadow;  /* 0x105CCC70 */
float DAT_105ccc74;  /* 0x105CCC74 */
BR_GLOBAL_EXTENT(char, DAT_105ccc78, [64], 0x40);  /* 0x105CCC78 */
BR_GLOBAL_EXTENT(float, BrGbiRectG_5CCCF8, , 0x4);  /* 0x105CCCF8 */
BrMat4 DAT_105ccd00;  /* 0x105CCD00 */
BR_GLOBAL_EXTENT(float, DAT_105ccd10, , 0x2C);  /* 0x105CCD10 */
BR_GLOBAL_EXTENT(uint8_t, BrGlFillR, , 0x3);  /* 0x105CCD40 */
float BrGbiRectG_5CCD44;  /* 0x105CCD44 */
BR_GLOBAL_EXTENT(float, DAT_105ccd48, , 0x4);  /* 0x105CCD48 */
BrDlMtx DAT_105ccd50[10];  /* 0x105CCD50 */
int DAT_105ccfd0;  /* 0x105CCFD0 */
uint32_t BrGlBlendSrcA;  /* 0x105CCFD4 */
BR_GLOBAL_EXTENT(uint8_t, BrGlFillG, , 0x3);  /* 0x105CCFD8 */
float DAT_105ccfdc;  /* 0x105CCFDC */
int32_t BrGlClipMaxY;  /* 0x105CCFE0 */
uint32_t BrGlBlendDstA;  /* 0x105CCFE4 */
BR_GLOBAL_EXTENT(int, DAT_105ccfe8, , 0x4);  /* 0x105CCFE8 */
BrClipVert s_aClipPool[64];  /* 0x105CCFF0 */
float BrGlPrimA;  /* 0x105CD9F0 */
float BrGbiRectG_5CD9F4;  /* 0x105CD9F4 */
float DAT_105cd9f8;  /* 0x105CD9F8 */
float DAT_105cd9fc;  /* 0x105CD9FC */
BrClipVert *g_pClipFree;  /* 0x105CDA00 */
BR_GLOBAL_EXTENT(int, BrGbiRectG_5CDA04, , 0x800);  /* 0x105CDA04 */
BR_GLOBAL_EXTENT(uint8_t, BrGlFillA, , 0x7);  /* 0x105CE208 */
float DAT_105ce210;  /* 0x105CE210 */
float DAT_105ce214;  /* 0x105CE214 */
float DAT_105ce218;  /* 0x105CE218 */
float DAT_105ce21c;  /* 0x105CE21C */
float DAT_105ce220;  /* 0x105CE220 */
float DAT_105ce224;  /* 0x105CE224 */
float DAT_105ce228;  /* 0x105CE228 */
float DAT_105ce22c;  /* 0x105CE22C */
BR_GLOBAL_EXTENT(float, DAT_105ce230, , 0x9C);  /* 0x105CE230 */
float BrGbiRectG_5CE2D0;  /* 0x105CE2D0 */
uint32_t BrGlRectMode;  /* 0x105CE2D4 */
uint8_t *DAT_105ce2d8;  /* 0x105CE2D8 */
uint8_t *DAT_105ce2dc;  /* 0x105CE2DC */
BR_GLOBAL_EXTENT(uint32_t, BrGlDepthFuncShadow, , 0x4);  /* 0x105CE2E0 */
BrGfxWords *g_apBrGbiStack[10];  /* 0x105CE2E8 */
int32_t g_iBrGbiSnap;  /* 0x105CE310 */
int32_t g_aiBr5CE314[5];  /* 0x105CE314 */
BrDlVtx g_aBrDlVtxPool[128];  /* 0x105CE318 */
BR_GLOBAL_EXTENT(int, DAT_105d1718, , 0x3C);  /* 0x105D1718 */
BR_GLOBAL_EXTENT(uint32_t, BrGlBlendDstRGB, , 0x4);  /* 0x105D1758 */
float DAT_105d1760;  /* 0x105D1760 */
float DAT_105d1764;  /* 0x105D1764 */
float DAT_105d1768;  /* 0x105D1768 */
float DAT_105d176c;  /* 0x105D176C */
float DAT_105d1770;  /* 0x105D1770 */
float DAT_105d1774;  /* 0x105D1774 */
float DAT_105d1778;  /* 0x105D1778 */
float DAT_105d177c;  /* 0x105D177C */
float DAT_105d1780;  /* 0x105D1780 */
float DAT_105d1784;  /* 0x105D1784 */
float DAT_105d1788;  /* 0x105D1788 */
float DAT_105d178c;  /* 0x105D178C */
float DAT_105d1790;  /* 0x105D1790 */
float DAT_105d1794;  /* 0x105D1794 */
float DAT_105d1798;  /* 0x105D1798 */
float DAT_105d179c;  /* 0x105D179C */
BR_GLOBAL_EXTENT(uint8_t, BrGlFillB, , 0x3);  /* 0x105D17A0 */
float BrGbiRectG_5D17A4;  /* 0x105D17A4 */
uint32_t BrGlBlendSrcRGB;  /* 0x105D17A8 */
uint32_t BrGlCombineW0;  /* 0x105D17AC */
uint32_t BrGlCombineW1;  /* 0x105D17B0 */
float BrGbiRectG_5D17B4;  /* 0x105D17B4 */
int32_t BrGlClipMaxX;  /* 0x105D17B8 */
int32_t BrGlClipMinX;  /* 0x105D17BC */
int32_t BrGlClipMinY;  /* 0x105D17C0 */
float BrGbiRectG_5D17C4;  /* 0x105D17C4 */
int BrGbiRectG_5D17C8;  /* 0x105D17C8 */
int DAT_105d17cc;  /* 0x105D17CC */
int DAT_105d17d0;  /* 0x105D17D0 */
uint32_t BrGlBlendLatch;  /* 0x105D17D4 */
int32_t g_brDlCullMode;  /* 0x105D17D8 */
int DAT_105d17dc;  /* 0x105D17DC */
BR_GLOBAL_EXTENT(int, DAT_105d17e0, , 0x4);  /* 0x105D17E0 */
BR_GLOBAL_EXTENT(unsigned char, DAT_105d17e8, , 0x3);  /* 0x105D17E8 */
unsigned int DAT_105d17ec;  /* 0x105D17EC */
BR_GLOBAL_EXTENT(void *, DAT_105d17f0, , 0x4);  /* 0x105D17F0 */
BR_GLOBAL_EXTENT(uint8_t, g_brTexScanStage, [8192], 0xE000);  /* 0x105D17F8 */
BR_GLOBAL_EXTENT(unsigned char, DAT_105e17f8, , 0x3);  /* 0x105E17F8 */
int32_t g_brTexScanState;  /* 0x105E17FC */
BR_GLOBAL_EXTENT(unsigned char, DAT_105e1800, , 0x3);  /* 0x105E1800 */
int32_t g_brTexScanTimgSiz;  /* 0x105E1804 */
int32_t s_g5E1808;  /* 0x105E1808 */
void *g_brTexScanTimgAddr;  /* 0x105E180C */
uint8_t DAT_105e1810[16];  /* 0x105E1810 */
BR_GLOBAL_EXTENT(int32_t, s_g5E1820, , 0x4);  /* 0x105E1820 */
unsigned short DAT_105e1828[262144];  /* 0x105E1828 */
BR_GLOBAL_EXTENT(unsigned char, DAT_10661828, , 0x3);  /* 0x10661828 */
BR_GLOBAL_EXTENT(unsigned char, DAT_1066182c, , 0x3);  /* 0x1066182C */
BrTmuMem g_aBrTmuMem[2];  /* 0x10661830 */
BrTexSlot g_aBrTexSlot[1024];  /* 0x10661840 */
BrGbiTile g_brTexScanTiles[8];  /* 0x10697840 */
BR_GLOBAL_EXTENT(unsigned char, DAT_10697a40, , 0x3);  /* 0x10697A40 */
int DAT_10697a44;  /* 0x10697A44 */
int DAT_10697a48;  /* 0x10697A48 */
int DAT_10697a4c;  /* 0x10697A4C */
int DAT_10697a50;  /* 0x10697A50 */
int32_t DAT_10697a54;  /* 0x10697A54 */
unsigned int DAT_10697a58;  /* 0x10697A58 */
unsigned int DAT_10697a5c;  /* 0x10697A5C */
int DAT_10697a60;  /* 0x10697A60 */
BrGfxWords *g_brTexScanRunStart;  /* 0x10697A64 */
BR_GLOBAL_EXTENT(unsigned char, DAT_10697a68, , 0x2000F);  /* 0x10697A68 */
BR_GLOBAL_EXTENT(unsigned char, DAT_106b7a78, , 0x3);  /* 0x106B7A78 */
BR_GLOBAL_EXTENT(int32_t, g_brTexScan575414, , 0x14);  /* 0x106B7A7C */
int32_t g_brTexScanMaxTile;  /* 0x106B7A94 */
void *g_brTexScanSrcSeen;  /* 0x106B7A98 */
BrGfxWords *g_brTexScanRunEnd;  /* 0x106B7A9C */
BrTexRecEnt *DAT_106b7aa0;  /* 0x106B7AA0  the texture table */
int _DAT_106b7aa4;  /* 0x106B7AA4 */
int _DAT_106b7aa8;  /* 0x106B7AA8 */
int DAT_106b7aac;  /* 0x106B7AAC */
int DAT_106b7ab0;  /* 0x106B7AB0 */
funcptr DAT_106b7ab4;  /* 0x106B7AB4 */
void *BrGlFlipHook;  /* 0x106B7AB8 */
void *BrGlFlipHook2;  /* 0x106B7ABC */
int DAT_106b7ac0;  /* 0x106B7AC0 */
uint8_t DAT_106b7ac4[4];  /* 0x106B7AC4 */
BR_GLOBAL_EXTENT(int, DAT_106b7ac8, , 0x1AC);  /* 0x106B7AC8 */
BR_GLOBAL_EXTENT(uint8_t, g_BrDrawByte78, , 0x3);  /* 0x106B7C78 */
uint8_t *g_brRcaBlob;  /* 0x106B7C7C */
BR_GLOBAL_EXTENT(uint8_t, g_BrDrawByte80, , 0x407);  /* 0x106B7C80 */
BR_GLOBAL_EXTENT(unsigned char, DAT_106b8088, [4], 0x4);  /* 0x106B8088 */
BR_GLOBAL_EXTENT(int, DAT_106b8090, , 0x14);  /* 0x106B8090 */
BR_GLOBAL_EXTENT(int, DAT_106b80a8, , 0x815C);  /* 0x106B80A8 */
int32_t BrG_6C0208;  /* 0x106C0208 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C020C, , 0x474);  /* 0x106C020C */
BR_GLOBAL_EXTENT(int32_t, BrG_6C0684, , 0x1D8);  /* 0x106C0684 */
BrMat4 s17_transMtx;  /* 0x106C0860 */
BR_GLOBAL_EXTENT(BrMat4, s17_lightMtx, , 0x40);  /* 0x106C08A0 */
BR_GLOBAL_EXTENT(uint32_t, BrG_6C0920, , 0x20);  /* 0x106C0920 */
BR_GLOBAL_EXTENT(uint8_t *, BrG_6C0944, , 0x8);  /* 0x106C0944 */
BR_GLOBAL_EXTENT(uint32_t, BrG_6C0950, [4], 0x810);  /* 0x106C0950 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C1170, , 0x414);  /* 0x106C1170 */
BrOsTask BrG_6C1588[2];  /* 0x106C1588 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C1608, , 0xC);  /* 0x106C1608 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C1618, , 0x4);  /* 0x106C1618 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C1620, , 0x164);  /* 0x106C1620 */
BR_GLOBAL_EXTENT(BrVpRec, BrG_6C1788, [32], 0x4);  /* 0x106C1788 */
void (*BrG_6C198C)(void);  /* 0x106C198C */
BR_GLOBAL_EXTENT(int32_t, BrG_6C299C, , 0x8);  /* 0x106C299C */
float BrG_6C29A8[16];  /* 0x106C29A8 */
BR_GLOBAL_EXTENT(uint32_t, BrG_6C29E8, , 0x308);  /* 0x106C29E8 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C2CF4, , 0x660);  /* 0x106C2CF4 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C3358, [4], 0x8);  /* 0x106C3358 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C3364, , 0x18);  /* 0x106C3364 */
BR_GLOBAL_EXTENT(void *, BrG_6C3380, , 0x14);  /* 0x106C3380 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C3398, , 0x4);  /* 0x106C3398 */
BR_GLOBAL_EXTENT(void *, BrG_6C33A0, , 0x2340);  /* 0x106C33A0 */
int32_t BrG_6C56E4;  /* 0x106C56E4 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C56E8, , 0x3C4);  /* 0x106C56E8 */
BR_GLOBAL_EXTENT(uint32_t, BrG_6C5AB0, , 0x824);  /* 0x106C5AB0 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C62D8, , 0x1B8);  /* 0x106C62D8 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C6494, [4], 0x40);  /* 0x106C6494 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C64D8, , 0xBC);  /* 0x106C64D8 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C6598, , 0x4);  /* 0x106C6598 */
BR_GLOBAL_EXTENT(void *, BrG_6C65A0, , 0x14);  /* 0x106C65A0 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C65B8, , 0x24);  /* 0x106C65B8 */
int32_t BrG_6C65E0;  /* 0x106C65E0 */
int32_t BrG_6C65E4;  /* 0x106C65E4 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C65E8, , 0x8);  /* 0x106C65E8 */
int32_t BrG_6C65F4;  /* 0x106C65F4 */
int32_t BrG_6C65F8;  /* 0x106C65F8 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C65FC, , 0x4);  /* 0x106C65FC */
BR_GLOBAL_EXTENT(int32_t, BrG_6C6604, , 0x18);  /* 0x106C6604 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C6620, , 0x30);  /* 0x106C6620 */
int32_t BrG_6C6654;  /* 0x106C6654 */
int32_t BrG_6C6658;  /* 0x106C6658 */
int32_t BrG_6C665C;  /* 0x106C665C */
int32_t BrG_6C6660;  /* 0x106C6660 */
int32_t BrG_6C6664;  /* 0x106C6664 */
BR_GLOBAL_EXTENT(int32_t, BrG_6C6668, , 0xC);  /* 0x106C6668 */
BR_GLOBAL_EXTENT(uint8_t *, BrG_6C6678, , 0x15BC);  /* 0x106C6678 */
BR_GLOBAL_EXTENT(uint32_t, g_6C7C38, , 0x20);  /* 0x106C7C38 */
BR_GLOBAL_EXTENT(BrVec3 *, g_pBrCollVerts, , 0x8);  /* 0x106C7C5C */
BR_GLOBAL_EXTENT(const uint16_t *, g_pBrTriTable, , 0x14);  /* 0x106C7C68 */
float BrG_6C7C80;  /* 0x106C7C80 */
BR_GLOBAL_EXTENT(float, BrG_6C7C84, , 0x40);  /* 0x106C7C84 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C7CC8, [3], 0x11);  /* 0x106C7CC8 */
const uint8_t *g_pBrCollTriFlags;  /* 0x106C7CDC */
BrPathSeg BrPathSegs[10];  /* 0x106C7CE0 */
BR_GLOBAL_EXTENT(int32_t, BrPathSegCount, , 0x1F4E0);  /* 0x106C7DA8 */
uint8_t DAT_106e728c[4];  /* 0x106E728C */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C0200, , 0x3);  /* 0x106E7290 */
int DAT_106e7294;  /* 0x106E7294 */
int DAT_106e7298;  /* 0x106E7298 */
int DAT_106e729c;  /* 0x106E729C */
BR_GLOBAL_EXTENT(float, g_BrCamDist, , 0x4);  /* 0x106E72A0 */
BrMat4 g_BrProjMat;  /* 0x106E72A8 */
BR_GLOBAL_EXTENT(uint32_t, g_BrEnvOthermode, , 0x4);  /* 0x106E72E8 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C0260, , 0x40F);  /* 0x106E72F0 */
BrVec3 g_BrVisLightDefault;  /* 0x106E7700 */
BR_GLOBAL_EXTENT(uint16_t, g_BrPerspNorm, , 0x2);  /* 0x106E770C */
uint32_t *g_BrGfxPtr;  /* 0x106E7710 */
int g_scrW4;  /* 0x106E7714 */
BR_GLOBAL_EXTENT(uint32_t, BrG_6C0688, , 0x4);  /* 0x106E7718 */
BrVec3 g_BrCamExtentU;  /* 0x106E7720 */
int DAT_106e772c;  /* 0x106E772C */
BR_GLOBAL_EXTENT(char, DAT_106e7730, , 0x3);  /* 0x106E7730 */
int DAT_106e7734;  /* 0x106E7734 */
BR_GLOBAL_EXTENT(int, DAT_106e7738, , 0x1B4);  /* 0x106E7738 */
BrMat4 g_BrDrawCombined;  /* 0x106E78F0 */
BrMat4 g_BrDrawScale;  /* 0x106E7930 */
BrMat4 g_brRaceSpecialM;  /* 0x106E7970 */
BR_GLOBAL_EXTENT(int, DAT_106e79b0, , 0x4);  /* 0x106E79B0 */
BR_GLOBAL_EXTENT(char, DAT_106e79b8, , 0xF);  /* 0x106E79B8: four 4-byte rows to 0x106E79C8 */
BR_GLOBAL_EXTENT(uint32_t, DAT_106e79c8, , 0x4);  /* 0x106E79C8 */
int DAT_106e79d0;  /* 0x106E79D0 */
BR_GLOBAL_EXTENT(void *, DAT_106e79d4, , 0x8);  /* 0x106E79D4 */
unsigned int DAT_106e79e0[4];  /* 0x106E79E0 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C0960, , 0x3);  /* 0x106E79F0 */
BrGameStepFn g_pfnStep;  /* 0x106E79F4 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C0968, , 0x807);  /* 0x106E79F8 */
int DAT_106e8200;  /* 0x106E8200 */
int32_t BrG_6C1174;  /* 0x106E8204 */
BR_GLOBAL_EXTENT(int, DAT_106e8208, , 0x404);  /* 0x106E8208 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C1580, , 0x7);  /* 0x106E8610 */
BrFrameTask DAT_106e8618[2];  /* 0x106E8618 */
int DAT_106e8698;  /* 0x106E8698 */
int DAT_106e869c;  /* 0x106E869C */
int DAT_106e86a0;  /* 0x106E86A0 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C1614, , 0x3);  /* 0x106E86A4 */
int DAT_106e86a8;  /* 0x106E86A8 */
int32_t g_6C161C;  /* 0x106E86AC */
BR_GLOBAL_EXTENT(int, DAT_106e86b0, , 0x4);  /* 0x106E86B0 */
BR_GLOBAL_EXTENT(BrView, g_aBrView, [2], 0xB0);  /* 0x106E86B8 */
BR_GLOBAL_EXTENT(char, DAT_106e8818, , 0x1FF);  /* 0x106E8818: 16-byte viewport rows to 0x106E8A18, fields named by their first row's address */
int32_t g_BrEnvFlagCount;  /* 0x106E8A18 */
void (*DAT_106e8a1c)(void);  /* 0x106E8A1C */
BrVec3 g_BrCamCentre;  /* 0x106E9A20 */
int32_t g_brRaceCueBase;  /* 0x106E9A2C */
int DAT_106e9a30;  /* 0x106E9A30 */
int32_t g_brRace6E9A34;  /* 0x106E9A34 */
BrMat4 g_BrCurMat;  /* 0x106E9A38 */
BR_GLOBAL_EXTENT(unsigned int, DAT_106e9a78, , 0x4);  /* 0x106E9A78 */
unsigned char DAT_106e9a80[768];  /* 0x106E9A80 */
void *g_BrLogArg;  /* 0x106E9D80 */
int DAT_106e9d84;  /* 0x106E9D84 */
Br63Race *g_pBr63Race;  /* 0x106E9D88 */
float g_brRaceFlyStep;  /* 0x106E9D8C */
int DAT_106e9d90[260];  /* 0x106E9D90 */
BR_GLOBAL_EXTENT(int, DAT_106ea1a0, , 0x1B4);  /* 0x106EA1A0 */
int DAT_106ea358;  /* 0x106EA358 */
int DAT_106ea35c;  /* 0x106EA35C */
BR_GLOBAL_EXTENT(void *, g_BrMtxSlot, , 0x24);  /* 0x106EA360 */
BR_GLOBAL_EXTENT(int, DAT_106ea388, , 0x4);  /* 0x106EA388 */
BR_GLOBAL_EXTENT(uint32_t, DAT_106ea390, , 0x4);  /* 0x106EA390 */
BR_GLOBAL_EXTENT(void *, BrG_6C3308, , 0x4);  /* 0x106EA398 */
float g_aBrSpanPt[6][3];  /* 0x106EA3A0 */
unsigned char DAT_106ea3e8[4];  /* 0x106EA3E8 */
BR_GLOBAL_EXTENT(uint8_t, BrG_6C335C, , 0x3);  /* 0x106EA3EC */
float g_BrCamNear;  /* 0x106EA3F0 */
BR_GLOBAL_EXTENT(int32_t, g_brRaceBeginDifficulty, , 0x18);  /* 0x106EA3F4 */
int DAT_106ea410[6];  /* 0x106EA410 */
BR_GLOBAL_EXTENT(int, DAT_106ea428, , 0x4);  /* 0x106EA428 */
int DAT_106ea430[6];  /* 0x106EA430 */
BR_GLOBAL_EXTENT(int, DAT_106ea448, , 0x2004);  /* 0x106EA448 */
BR_GLOBAL_EXTENT(float, g_BrCamFovIn, , 0xA4);  /* 0x106EC450 */
float g_Br6C5468[4];  /* 0x106EC4F8 */
BR_GLOBAL_EXTENT(char, DAT_106ec508, , 0x19F);  /* 0x106EC508 */
BR_GLOBAL_EXTENT(int, DAT_106ec6a8, , 0x14);  /* 0x106EC6A8 */
BR_GLOBAL_EXTENT(int, DAT_106ec6c0, , 0x7C);  /* 0x106EC6C0 */
BR_GLOBAL_EXTENT(unsigned long long, DAT_106ec740, , 0x18);  /* 0x106EC740 */
BR_GLOBAL_EXTENT(int32_t, g_brRace6EC760, , 0x4);  /* 0x106EC760 */
int DAT_106ec768;  /* 0x106EC768 */
int DAT_106ec76c;  /* 0x106EC76C */
int _DAT_106ec770;  /* 0x106EC770 */
int DAT_106ec774;  /* 0x106EC774 */
int DAT_106ec778;  /* 0x106EC778 */
void *_DAT_106ec77c;  /* 0x106EC77C */
uint8_t DAT_106ec780[8];  /* 0x106EC780 */
BrVec3 g_BrCamExtentR;  /* 0x106EC788 */
int DAT_106ec794;  /* 0x106EC794 */
BR_GLOBAL_EXTENT(int32_t, g_BrEnvSection, , 0x1B4);  /* 0x106EC798 */
BR_GLOBAL_EXTENT(BrMat4, g_BrViewMat, , 0x1B0);  /* 0x106EC950 */
unsigned int DAT_106ecb40;  /* 0x106ECB40 */
float g_BrCamFar;  /* 0x106ECB44 */
BR_GLOBAL_EXTENT(int, DAT_106ecb48, , 0x81C);  /* 0x106ECB48 */
BR_GLOBAL_EXTENT(int, DAT_106ed368, , 0x4);  /* 0x106ED368 */
BR_GLOBAL_EXTENT(int, DAT_106ed370, , 0x1AC);  /* 0x106ED370 */
BrCamera *g_BrCamera;  /* 0x106ED520 */
unsigned char DAT_106ed524[4];  /* 0x106ED524 */
uint16_t g_BrEnvFlagIndices[32];  /* 0x106ED528 */
BR_GLOBAL_EXTENT(int, DAT_106ed568, , 0x4);  /* 0x106ED568 */
BR_GLOBAL_EXTENT(int, DAT_106ed570, , 0x14);  /* 0x106ED570 */
BR_GLOBAL_EXTENT(int, DAT_106ed588, , 0x4);  /* 0x106ED588 */
uint8_t DAT_106ed590[64];  /* 0x106ED590 */
BR_GLOBAL_EXTENT(int, DAT_106ed5d0, , 0x14);  /* 0x106ED5D0 */
int32_t g_aiBrSlotCar[16];  /* 0x106ED5E8  the car each slot holds */
BR_GLOBAL_EXTENT(int, DAT_106ed628, , 0x4);  /* 0x106ED628 */
BrEntRec g_aBrEntRecs[6432];  /* 0x106ED630 */
BrEnt g_aBrEnts[16];  /* 0x106ED708 */
uint32_t g_brRace6EECC8;  /* 0x106EECC8 */
BrDevCtx *g_brP6EECCC;  /* 0x106EECCC */
uint32_t g_brPendDropped;  /* 0x106EECD0 */
uint32_t g_6C7C44;  /* 0x106EECD4 */
BR_GLOBAL_EXTENT(char, DAT_106eef08, , 0x3);  /* 0x106EEF08 */
BR_GLOBAL_EXTENT(BrKeyEnt, g_aBrKeyEnts, [64], 0xBFC);  /* 0x106EEF0C */
BR_GLOBAL_EXTENT(uint16_t, g_uPoolFree, , 0x6);  /* 0x10A99BA8 */
BR_GLOBAL_EXTENT(uint16_t, g_uPoolHead, , 0x6);  /* 0x10A99BB0 */
BR_GLOBAL_EXTENT(BrPoolNode, g_aPoolNodes, [288], 0x18);  /* 0x10A99BB8 */
BR_GLOBAL_EXTENT(uint32_t, g_brA9BFD0, , 0x8);  /* 0x10A9BFD0 */
BR_GLOBAL_EXTENT(uint32_t, g_brA9BFDC, , 0x101C);  /* 0x10A9BFDC */
int32_t g_brA9CFFC;  /* 0x10A9CFFC */
int32_t g_brA9D000;  /* 0x10A9D000 */
int32_t g_brA9D004;  /* 0x10A9D004 */
BR_GLOBAL_EXTENT(uint32_t *, g_A9D008, , 0x4);  /* 0x10A9D008 */
BR_GLOBAL_EXTENT(uint32_t, g_brA9D010, , 0x4);  /* 0x10A9D010 */
char g_aBrA9D018[260];  /* 0x10A9D018 */
const int16_t g_awA9D068[2];  /* 0x10A9D068 */
int32_t g_brA9D06C;  /* 0x10A9D06C */
BR_GLOBAL_EXTENT(int32_t, g_brA9D070, , 0x12EC);  /* 0x10A9D070 */
BR_GLOBAL_EXTENT(BrUiAssetRec, g_aBrUiAssetRec, [145], 0x84);  /* 0x10A9E360 */
BR_GLOBAL_EXTENT(uint32_t, g_brAA2598, , 0x14C);  /* 0x10AA2598 */
const int8_t g_abAA26E8[372];  /* 0x10AA26E8 */
BR_GLOBAL_EXTENT(int32_t, g_brAA285C, , 0x30);  /* 0x10AA285C */
int32_t g_brAA2890;  /* 0x10AA2890 */
BR_GLOBAL_EXTENT(int32_t, g_brAA2894, , 0x4);  /* 0x10AA2894 */
BR_GLOBAL_EXTENT(int32_t, g_brAA289C, , 0x1C);  /* 0x10AA289C */
int32_t g_brAA28BC;  /* 0x10AA28BC */
BR_GLOBAL_EXTENT(int32_t, g_brAA28C0, , 0x4);  /* 0x10AA28C0 */
int32_t g_brAA28C8;  /* 0x10AA28C8 */
int32_t g_brAA28CC;  /* 0x10AA28CC */
int32_t g_brAA28D0;  /* 0x10AA28D0 */
uint32_t g_brAA28D4;  /* 0x10AA28D4 */
BR_GLOBAL_EXTENT(int32_t, g_iAA28D8, , 0xC);  /* 0x10AA28D8 */
BR_GLOBAL_EXTENT(int32_t, g_brAA28E8, , 0x8);  /* 0x10AA28E8 */
int32_t g_brAA28F4;  /* 0x10AA28F4 */
BR_GLOBAL_EXTENT(int32_t, g_brAA28F8, , 0xC);  /* 0x10AA28F8 */
BR_GLOBAL_EXTENT(BrOptObj *, g_brPAA2908, , 0x34);  /* 0x10AA2908 */
BR_GLOBAL_EXTENT(BrOptObj *, g_brPAA2940, , 0x4);  /* 0x10AA2940 */
BrOptObj *g_brPAA2948;  /* 0x10AA2948 */
BrOptObj *g_brPAA294C;  /* 0x10AA294C */
BrPhase *g_brAA2950;  /* 0x10AA2950 */
BrOptObj *g_brPAA2954;  /* 0x10AA2954 */
int32_t g_brAA2958;  /* 0x10AA2958 */
BR_GLOBAL_EXTENT(BrPhase *, g_brAA295C, , 0x4);  /* 0x10AA295C */
BrPhase *g_brAA2964;  /* 0x10AA2964 */
BrPhase *g_brAA2968;  /* 0x10AA2968 */
BrOptObj *g_brPAA296C;  /* 0x10AA296C */
BrOptObj *g_brPAA2970;  /* 0x10AA2970 */
BR_GLOBAL_EXTENT(BrPhase *, g_brAA2974, , 0x4);  /* 0x10AA2974 */
BR_GLOBAL_EXTENT(BrPhase_ *, g_brAA297C, , 0xC);  /* 0x10AA297C */
BR_GLOBAL_EXTENT(BrOptObj *, g_brPAA298C, , 0x8);  /* 0x10AA298C */
BR_GLOBAL_EXTENT(BrOptObj *, g_brPAA2998, , 0xC);  /* 0x10AA2998 */
BR_GLOBAL_EXTENT(int32_t, g_brAA29A8, , 0x1C);  /* 0x10AA29A8 */
BR_GLOBAL_EXTENT(BrPhase *, g_brAA29C8, , 0x14);  /* 0x10AA29C8 */
int32_t g_brAA29E0;  /* 0x10AA29E0 */
int32_t g_brAA29E4;  /* 0x10AA29E4 */
BR_GLOBAL_EXTENT(int32_t, g_brAA29E8, , 0x18);  /* 0x10AA29E8 */
BR_GLOBAL_EXTENT(int32_t, g_brAA2A04, , 0x14);  /* 0x10AA2A04 */
int32_t g_brAA2A1C;  /* 0x10AA2A1C */
int32_t g_brAA2A20;  /* 0x10AA2A20 */
int32_t g_brAA2A24;  /* 0x10AA2A24 */
int32_t g_brAA2A28;  /* 0x10AA2A28 */
BR_GLOBAL_EXTENT(int32_t, g_iAA2A2C, , 0x4);  /* 0x10AA2A2C */
BR_GLOBAL_EXTENT(int32_t, g_iAA2A34, , 0x8);  /* 0x10AA2A34 */
BR_GLOBAL_EXTENT(int32_t, g_brAA2A40, , 0x2C);  /* 0x10AA2A40 */
BR_GLOBAL_EXTENT(char, g_BrAA2A70, [8], 0x910);  /* 0x10AA2A70 */
BR_GLOBAL_EXTENT(int32_t, g_BrBtnPrev, [4], 0x28);  /* 0x10AA3388 */
int32_t g_BrBtnRaw[4];  /* 0x10AA33C0 */
BR_GLOBAL_EXTENT(int32_t, g_BrBtnEdge, [4], 0x64);  /* 0x10AA33D0 */
BR_GLOBAL_EXTENT(int, g_i10AA3444, , 0x18);  /* 0x10AA3444 */
BR_GLOBAL_EXTENT(int, g_i10AA3460, , 0x2C);  /* 0x10AA3460 */
BR_GLOBAL_EXTENT(void *, BrG_AA3490, , 0x2CC);  /* 0x10AA3490 */
BR_GLOBAL_EXTENT(void *, BrG_AA3760, , 0x5EC);  /* 0x10AA3760 */
BR_GLOBAL_EXTENT(void *, BrG_AA3D50, , 0x2CC);  /* 0x10AA3D50 */
BR_GLOBAL_EXTENT(void *, BrG_AA4020, , 0x1C7E4);  /* 0x10AA4020 */
int32_t g_brKeyCount;  /* 0x10AC0808 */
uint32_t g_brKeyBias;  /* 0x10AC080C */
BR_GLOBAL_EXTENT(BrPodArc, g_brModelMgr, , 0x4);  /* 0x10AC0810 */
BR_GLOBAL_EXTENT(uint16_t, g_iPfxFree, , 0x2);  /* 0x10AC0C38 */
int32_t g_iPfxHeadAC;  /* 0x10AC0C3C */
int32_t g_iPfxHeadB0;  /* 0x10AC0C40 */
int32_t g_iPfxHeadB4;  /* 0x10AC0C44 */
BrPfxRec g_aPfxRec[256];  /* 0x10AC0C48 */
BR_GLOBAL_EXTENT(int, DAT_10ac2c48, , 0x4);  /* 0x10AC2C48 */
int32_t g_brSpanColHi;  /* 0x10AC2C50 */
int g_BrVisRowHi;  /* 0x10AC2C54 */
int32_t g_brSpanColLo;  /* 0x10AC2C58 */
int g_BrVisRowLo;  /* 0x10AC2C5C */
int g_BrVisColLo[64];  /* 0x10AC2C60 */
int g_BrVisColHi[64];  /* 0x10AC2D60 */
int32_t g_aBrSpanRowLo[64];  /* 0x10AC2E60 */
int32_t g_aBrSpanRowHi[64];  /* 0x10AC2F60 */
BR_GLOBAL_EXTENT(uint32_t, g_A9BFD0, , 0x4);  /* 0x10AC3060 */
int *DAT_10ac3068;  /* 0x10AC3068 */
int DAT_10ac306c;  /* 0x10AC306C */
char DAT_10ac3070[16];  /* 0x10AC3070 */
BrNetSession g_aBrNetSession[16];  /* 0x10AC3080 */
BR_GLOBAL_EXTENT(char, g_aBrA9CDF0, [260], 0x4);  /* 0x10AC3E80 */
char DAT_10ac3f88[260];  /* 0x10AC3F88 */
int g_guardA;  /* 0x10AC408C */
int g_guardB;  /* 0x10AC4090 */
int DAT_10ac4094;  /* 0x10AC4094 */
BR_GLOBAL_EXTENT(BrOptUi *, g_brPA9D008, , 0x4);  /* 0x10AC4098 */
BR_GLOBAL_EXTENT(int32_t, DAT_10ac40a0, , 0x4);  /* 0x10AC40A0 */
DWORD DAT_10ac40a8[20];  /* 0x10AC40A8 */
short g_brVal40F8[2];  /* 0x10AC40F8 */
float DAT_10ac40fc;  /* 0x10AC40FC */
char g_aBrA9D078[264];  /* 0x10AC4100 */
int32_t g_aBrSprRectA[68][4];  /* 0x10AC4208 */
int g_brTbl4648[22];  /* 0x10AC4648 */
char DAT_10ac46a0[332];  /* 0x10AC46A0 */
int32_t g_aBrSprRectB[20][4];  /* 0x10AC46C0 */
BR_GLOBAL_EXTENT(int, g_rec, [180], 0x8);  /* 0x10AC4800 */
int32_t g_aBrSprRectC[15][4];  /* 0x10AC4AD8 */
int32_t g_aBrSprRectD[9][4];  /* 0x10AC4BC8 */
BR_GLOBAL_EXTENT(int, DAT_10ac4c58, , 0x4);  /* 0x10AC4C58 */
BR_GLOBAL_EXTENT(int32_t, g_aBrA9DBD8, [83], 0x4);  /* 0x10AC4C60 */
char g_szBrName4DB0[1064];  /* 0x10AC4DB0 */
int32_t g_aBrA9E150[32];  /* 0x10AC51D8 */
int g_zero[100];  /* 0x10AC5258 */
Img g_img[145];  /* 0x10AC53E8 */
char g_aBrAA2518[260];  /* 0x10AC5870 */
BrSlot g_aBrAA2538[8];  /* 0x10AC5890 */
BR_GLOBAL_EXTENT(int32_t, DAT_10ac58f0, , 0x4);  /* 0x10AC58F0 */
float g_brFTbl58F8[12];  /* 0x10AC58F8 */
int DAT_10ac5928;  /* 0x10AC5928 */
BR_GLOBAL_EXTENT(char, DAT_10ac592c, , 0x3);  /* 0x10AC592C */
int DAT_10ac5930;  /* 0x10AC5930 */
BR_GLOBAL_EXTENT(int, DAT_10ac5934, , 0x108);  /* 0x10AC5934 */
char g_brVal5A40[8];  /* 0x10AC5A40 */
int DAT_10ac5a48[5556];  /* 0x10AC5A48 */
uint8_t g_aBrAA26F4[4];  /* 0x10AC5A4C */
uint8_t g_aBrAA26F6[672];  /* 0x10AC5A4E */
uint8_t g_aBrAA270E[50];  /* 0x10AC5A66 */
uint8_t g_aBrAA2740[96];  /* 0x10AC5A98 */
float DAT_10ac5af8[16];  /* 0x10AC5AF8 */
BR_GLOBAL_EXTENT(int, DAT_10ac5b38, , 0x8);  /* 0x10AC5B38 */
int DAT_10ac5b44;  /* 0x10AC5B44 */
int DAT_10ac5b48;  /* 0x10AC5B48 */
int DAT_10ac5b4c;  /* 0x10AC5B4C */
int DAT_10ac5b50;  /* 0x10AC5B50 */
float g_brFTbl5B54[17];  /* 0x10AC5B54 */
int g_brSel5B98;  /* 0x10AC5B98 */
int32_t BrGlNavOff5B9C;  /* 0x10AC5B9C */
int g_brGate5BA0;  /* 0x10AC5BA0 */
int32_t g_nAA284C;  /* 0x10AC5BA4 */
int DAT_10ac5ba8;  /* 0x10AC5BA8 */
int g_track;  /* 0x10AC5BAC */
int DAT_10ac5bb0;  /* 0x10AC5BB0 */
BR_GLOBAL_EXTENT(int, g_5BB4, , 0x4);  /* 0x10AC5BB4 */
int _DAT_10ac5bbc;  /* 0x10AC5BBC */
int g_bc0;  /* 0x10AC5BC0 */
BR_GLOBAL_EXTENT(uint16_t, BrGlNavCur5BC4, , 0x2);  /* 0x10AC5BC4 */
BR_GLOBAL_EXTENT(uint16_t, g_wAA2870, , 0x2);  /* 0x10AC5BC8 */
int DAT_10ac5bcc;  /* 0x10AC5BCC */
int DAT_10ac5bd0;  /* 0x10AC5BD0 */
int DAT_10ac5bd4;  /* 0x10AC5BD4 */
int g_5BD8;  /* 0x10AC5BD8 */
int g_host;  /* 0x10AC5BDC */
int g_inited;  /* 0x10AC5BE0 */
int DAT_10ac5be4;  /* 0x10AC5BE4 */
int DAT_10ac5be8;  /* 0x10AC5BE8 */
int DAT_10ac5bec;  /* 0x10AC5BEC */
int DAT_10ac5bf0;  /* 0x10AC5BF0 */
int g_5BF4;  /* 0x10AC5BF4 */
int g_brPhase5BF8;  /* 0x10AC5BF8 */
int g_brIdx5BFC;  /* 0x10AC5BFC */
BR_GLOBAL_EXTENT(char, DAT_10ac5c00, , 0x3);  /* 0x10AC5C00 */
int g_brIdx5C04;  /* 0x10AC5C04 */
int DAT_10ac5c08;  /* 0x10AC5C08 */
int DAT_10ac5c0c;  /* 0x10AC5C0C */
int DAT_10ac5c10;  /* 0x10AC5C10 */
int DAT_10ac5c14;  /* 0x10AC5C14 */
int DAT_10ac5c18;  /* 0x10AC5C18 */
int32_t DAT_10ac5c1c;  /* 0x10AC5C1C */
float g_brTime5C20;  /* 0x10AC5C20 */
float g_brTime5C24;  /* 0x10AC5C24 */
uint32_t DAT_10ac5c28;  /* 0x10AC5C28 */
int DAT_10ac5c2c;  /* 0x10AC5C2C */
BR_GLOBAL_EXTENT(int, g_5C30, , 0x4);  /* 0x10AC5C30 */
int g_5C38;  /* 0x10AC5C38 */
int g_5C3C;  /* 0x10AC5C3C */
int DAT_10ac5c40;  /* 0x10AC5C40 */
int32_t g_brUinAA28EC;  /* 0x10AC5C44 */
int32_t g_br6EE1D8_fLowAlways;  /* 0x10AC5C48 */
int DAT_10ac5c4c;  /* 0x10AC5C4C */
int DAT_10ac5c50;  /* 0x10AC5C50 */
int DAT_10ac5c54;  /* 0x10AC5C54 */
struct Obj400 *g_obj400;  /* 0x10AC5C58 */
BrOptObj *g_brPAA29B8;  /* 0x10AC5C5C */
struct Phase *g_2908;  /* 0x10AC5C60 */
struct Phase *g_5C64;  /* 0x10AC5C64 */
void *g_5C68;  /* 0x10AC5C68 */
struct Phase *g_5C6C;  /* 0x10AC5C6C */
struct Phase *g_5C70;  /* 0x10AC5C70 */
struct Phase *g_5C74;  /* 0x10AC5C74 */
struct Ph *DAT_10ac5c78;  /* 0x10AC5C78 */
struct Phase *g_5C7C;  /* 0x10AC5C7C */
void *g_5C80;  /* 0x10AC5C80 */
struct Ph *g_brPhaseAA292C;  /* 0x10AC5C84 */
struct Phase *g_5C88;  /* 0x10AC5C88 */
struct Phase *g_5C8C;  /* 0x10AC5C8C */
struct Phase *g_5C90;  /* 0x10AC5C90 */
struct Phase *g_5C94;  /* 0x10AC5C94 */
struct Phase *g_5C98;  /* 0x10AC5C98 */
struct Ph *DAT_10ac5c9c;  /* 0x10AC5C9C */
struct Phase8 *g_2948;  /* 0x10AC5CA0 */
struct Phase *g_294C;  /* 0x10AC5CA4 */
BrOptObj *g_brPAA2950;  /* 0x10AC5CA8 */
struct Phase *g_5CAC;  /* 0x10AC5CAC */
struct Phase *g_5CB0;  /* 0x10AC5CB0 */
struct Phase *g_5CB4;  /* 0x10AC5CB4 */
struct Ph *DAT_10ac5cb8;  /* 0x10AC5CB8 */
void *DAT_10ac5cbc;  /* 0x10AC5CBC */
struct Phase *g_5CC0;  /* 0x10AC5CC0 */
struct Ph *DAT_10ac5cc4;  /* 0x10AC5CC4 */
struct Phase *DAT_10ac5cc8;  /* 0x10AC5CC8 */
struct Ph *g_brPhaseAA2974;  /* 0x10AC5CCC */
struct Phase *DAT_10ac5cd0;  /* 0x10AC5CD0 */
struct Phase *g_5CD4;  /* 0x10AC5CD4 */
struct Phase *g_5CD8;  /* 0x10AC5CD8 */
void *g_5CDC;  /* 0x10AC5CDC */
void *g_5CE0;  /* 0x10AC5CE0 */
struct Phase *g_298C;  /* 0x10AC5CE4 */
struct Ph *DAT_10ac5ce8;  /* 0x10AC5CE8 */
void *g_5CEC;  /* 0x10AC5CEC */
BR_GLOBAL_EXTENT(void *, g_5CF0, , 0xC);  /* 0x10AC5CF0 */
struct BrCtl *DAT_10ac5d00;  /* 0x10AC5D00 */
struct Phase *g_hookObj;  /* 0x10AC5D04 */
void *DAT_10ac5d08;  /* 0x10AC5D08 */
void *DAT_10ac5d0c;  /* 0x10AC5D0C */
struct Phase *g_29B8;  /* 0x10AC5D10 */
struct BrCtl *DAT_10ac5d14;  /* 0x10AC5D14 */
void *DAT_10ac5d18;  /* 0x10AC5D18 */
struct BrCtl *DAT_10ac5d1c;  /* 0x10AC5D1C */
BrUiCtl_ *g_brUipAA29C8;  /* 0x10AC5D20 */
void *g_5D24;  /* 0x10AC5D24 */
unsigned char *g_brPAA29D0;  /* 0x10AC5D28 */
BrObj29D4 *g_brPAA29D4;  /* 0x10AC5D2C */
BR_GLOBAL_EXTENT(BrOptFlagObj *, g_brPAA29D8, , 0x4);  /* 0x10AC5D30 */
struct GameObjS *g_pGame;  /* 0x10AC5D38 */
struct BrCtl *g_brPAA29E4;  /* 0x10AC5D3C */
struct BrUiCtl_ *DAT_10ac5d40;  /* 0x10AC5D40 */
void *DAT_10ac5d44;  /* 0x10AC5D44 */
int DAT_10ac5d48;  /* 0x10AC5D48 */
BrUiCtl_ *g_brUipAA29F4;  /* 0x10AC5D4C */
BR_GLOBAL_EXTENT(unsigned short, g_wAC5D50, , 0x2);  /* 0x10AC5D50 */
BR_GLOBAL_EXTENT(unsigned short, g_wAC5D54, , 0x2);  /* 0x10AC5D54 */
int DAT_10ac5d58;  /* 0x10AC5D58 */
int DAT_10ac5d5c;  /* 0x10AC5D5C */
uint32_t DAT_10ac5d60;  /* 0x10AC5D60 */
int g_brKind5D64;  /* 0x10AC5D64 */
int DAT_10ac5d68;  /* 0x10AC5D68 */
int DAT_10ac5d6c;  /* 0x10AC5D6C */
int DAT_10ac5d70;  /* 0x10AC5D70 */
int g_brSel5D74;  /* 0x10AC5D74 */
uint32_t DAT_10ac5d78;  /* 0x10AC5D78 */
int g_brSel5D7C;  /* 0x10AC5D7C */
int g_brSel5D80;  /* 0x10AC5D80 */
void *DAT_10ac5d84;  /* 0x10AC5D84 */
int32_t g_iAA2A30;  /* 0x10AC5D88 */
int g_5D8C;  /* 0x10AC5D8C */
int DAT_10ac5d90;  /* 0x10AC5D90 */
int DAT_10ac5d94;  /* 0x10AC5D94 */
int g_5D98;  /* 0x10AC5D98 */
int32_t g_brAA2A44;  /* 0x10AC5D9C */
int g_brKeyRingPos;  /* 0x10AC5DA0 */
int DAT_10ac5da4;  /* 0x10AC5DA4 */
int DAT_10ac5da8;  /* 0x10AC5DA8 */
int g_5DAC;  /* 0x10AC5DAC */
int g_5DB0;  /* 0x10AC5DB0 */
int g_brAC5DB4;  /* 0x10AC5DB4 */
int g_brAC5DB8;  /* 0x10AC5DB8 */
float g_brAC5DBC;  /* 0x10AC5DBC */
float g_brAC5DC0;  /* 0x10AC5DC0 */
int DAT_10ac5dc4;  /* 0x10AC5DC4 */
struct Node *g_head;  /* 0x10AC5DC8 */
int g_count;  /* 0x10AC5DCC */
char g_szBrAC5DD0[8];  /* 0x10AC5DD0 */
BR_GLOBAL_EXTENT(void *, BrGlNavThis5DD8, , 0x4);  /* 0x10AC5DD8 */
int32_t g_BrDikEdge[256];  /* 0x10AC5DE0 */
BR_GLOBAL_EXTENT(BrPointI *, g_pBrAA2E80, , 0x4);  /* 0x10AC61E0 */
int32_t g_BrDikPrev[256];  /* 0x10AC61E8 */
uint8_t g_BrDikState[256];  /* 0x10AC65E8 */
BR_GLOBAL_EXTENT(int *, DAT_10ac66e8, , 0xC);  /* 0x10AC66E8 */
int32_t g_BrAA3398[7];  /* 0x10AC66F8 */
int32_t BrGlNavMaxY;  /* 0x10AC6714 */
BR_GLOBAL_EXTENT(int32_t, BrGlNavMaxX, , 0x4);  /* 0x10AC6718 */
int32_t BrGlNavEdge6720;  /* 0x10AC6720 */
int32_t BrGlNavEdge6724;  /* 0x10AC6724 */
int32_t BrGlNavEdge6728;  /* 0x10AC6728 */
int32_t BrGlNavEdge672C;  /* 0x10AC672C */
int32_t g_act0;  /* 0x10AC6730 */
int32_t g_act1;  /* 0x10AC6734 */
int32_t g_act2;  /* 0x10AC6738 */
int32_t g_act3;  /* 0x10AC673C */
uint32_t g_BrAA33E0;  /* 0x10AC6740 */
int DAT_10ac6744;  /* 0x10AC6744 */
BR_GLOBAL_EXTENT(int32_t, BrGlNavLast6748, , 0x54);  /* 0x10AC6748 */
BrImgState BrImgTintState;  /* 0x10AC67A0 */
BR_GLOBAL_EXTENT(short, DAT_10ac67cc, , 0x2);  /* 0x10AC67CC */
int g_BrSndAA3470;  /* 0x10AC67D0 */
BR_GLOBAL_EXTENT(BrAiPathNode *, g_pBrAiScanBestNode, , 0x18);  /* 0x10AC67D4 */
char DAT_10ac67f0[28];  /* 0x10AC67F0 */
BR_GLOBAL_EXTENT(int, DAT_10ac680c, , 0x2B0);  /* 0x10AC680C */
char DAT_10ac6ac0[1520];  /* 0x10AC6AC0 */
char DAT_10ac70b0[720];  /* 0x10AC70B0 */
char DAT_10ac7380[24848];  /* 0x10AC7380 */
BR_GLOBAL_EXTENT(int32_t, BrPathWalkIndex, , 0x18A0);  /* 0x10ACD490 */
BR_GLOBAL_EXTENT(const int32_t *, g_brPACED34, , 0x154);  /* 0x10ACED34 */
BR_GLOBAL_EXTENT(int32_t, g_brACEE8C, , 0x4);  /* 0x10ACEE8C */
BR_GLOBAL_EXTENT(int32_t, g_brACEE94, , 0x1AE0);  /* 0x10ACEE94 */
int32_t g_brAD0978;  /* 0x10AD0978 */
int32_t g_brAD097C;  /* 0x10AD097C */
int32_t g_brAD0980;  /* 0x10AD0980 */
int32_t g_brAD0984;  /* 0x10AD0984 */
int32_t g_brAD0988;  /* 0x10AD0988 */
int32_t g_brAD098C;  /* 0x10AD098C */
BR_GLOBAL_EXTENT(unsigned char, g_brAD0990, [128], 0x1FDE0);  /* 0x10AD0990 */
BR_GLOBAL_EXTENT(uint32_t, g_brRacePathIndex, , 0x4);  /* 0x10AF07F0 */
BrDriver g_aBrRaceDriver[20];  /* 0x10AF07F8 */
BR_GLOBAL_EXTENT(struct BrVec3, DAT_10af11f8, , 0x4);  /* 0x10AF11F8 */
BrDriverCar g_aBrRaceCar[16];  /* 0x10AF1208 */
int32_t g_brAiScanBestPt;  /* 0x10B1C888 */
/* the corridor scan's rows: br_vec.h */
BrVec3 g_aScanMidA[9];  /* 0x10B1C884 (row; [0] unused) */
BrVec3 g_aScanMidB[9];  /* 0x10B1C8E4 (row; [0] unused) */
BrVec3 g_aScanOut3[8];  /* 0x10B1C958 */
BrVec3 g_aBrAiScanA[8];  /* 0x10B1C9B8 */
int32_t g_brAiScanFlag18;  /* 0x10B1CA18 */
int DAT_10b1ca1c;  /* 0x10B1CA1C */
BR_GLOBAL_EXTENT(int32_t, DAT_10b1ca20, , 0x4);  /* 0x10B1CA20 */
BrVec3 g_aBrAiScanB[8];    /* 0x10B1CA28; [7] lies on the next row's [0] */
BrVec3 g_aScanCentre[9];  /* 0x10B1CA7C (row; [0] unused) */
BrVec3 g_aScanInsetB[9];  /* 0x10B1CADC (row; [0] unused) */
BrVec3 g_aScanInsetA[9];  /* 0x10B1CB3C (row; [0] unused) */
unsigned char g_abBrVarBlock40[0x40];  /* 0x10B1CBA8 */
int32_t g_brAiBiasPos;  /* 0x10B1CBE8 */
RcNode *g_brRacePathNode;  /* 0x10B1CBEC */
uint32_t g_brPairStaticA[83];  /* 0x10B1CBF0 */
uint32_t g_brPairStaticB[83];  /* 0x10B1CD3C */
BR_GLOBAL_EXTENT(struct BrVec3, DAT_10b1ce88, , 0x4);  /* 0x10B1CE88 */
BrVec3 g_brRacePathPos;  /* 0x10B1CE98 */
BR_GLOBAL_EXTENT(int32_t, DAT_10b1cea4, , 0x10);  /* 0x10B1CEA4 */
BrSndNearest g_BrSndNearest;  /* 0x10B1CEB8 */
int DAT_10b1cf04;  /* 0x10B1CF04 */
int DAT_10b1cf08;  /* 0x10B1CF08 */
int DAT_10b1cf0c;  /* 0x10B1CF0C */
int32_t g_BrCamHold2;  /* 0x10B1CF10 */
int32_t g_BrCamHold;  /* 0x10B1CF14 */
BR_GLOBAL_EXTENT(int, DAT_10b1cf18, , 0x4);  /* 0x10B1CF18 */
uint8_t BrG_AF9BC0[9000];  /* 0x10B1CF20 */
BR_GLOBAL_EXTENT(int, g_B1F248, , 0x1CD4);  /* 0x10B1F248 */
uint8_t BrG_AFDBC0[16512];  /* 0x10B20F20 */
int32_t BrG_B01C40;  /* 0x10B24FA0 */
int32_t BrG_B01C44;  /* 0x10B24FA4 */
BR_GLOBAL_EXTENT(int32_t, BrG_B01C48, , 0x4);  /* 0x10B24FA8 */
uint8_t BrG_B01C50[640];  /* 0x10B24FB0 */
uint8_t BrG_B01ED0[704];  /* 0x10B25230 */
uint8_t BrG_B02190[320];  /* 0x10B254F0 */
uint8_t BrG_B022D0[356];  /* 0x10B25630 */
int DAT_10b25794;  /* 0x10B25794 */
BR_GLOBAL_EXTENT(char, DAT_10b25798, , 0x28A3F);  /* 0x10B25798 */
int32_t g_brB4E1D8;  /* 0x10B4E1D8 */
BR_GLOBAL_EXTENT(int32_t, g_brB4E1DC, , 0x528);  /* 0x10B4E1DC */
uint32_t g_uB4E708;  /* 0x10B4E708 */
BR_GLOBAL_EXTENT(uint32_t, g_uB4E70C, , 0x90);  /* 0x10B4E70C */
BR_GLOBAL_EXTENT(int32_t, g_brB4E7A0, , 0x1444);  /* 0x10B4E7A0 */
unsigned char g_aBrB4FBE8[1504];  /* 0x10B4FBE8 */
BR_GLOBAL_EXTENT(uint32_t, g_B501C8, , 0x4);  /* 0x10B501C8 */
void (*BrG_B501D0)(uintptr_t);  /* 0x10B501D0 */
uint32_t g_B502E4;  /* 0x10B502E4 */
uint32_t BrG_B502E8;  /* 0x10B502E8 */
BR_GLOBAL_EXTENT(uint32_t, BrG_B502EC, , 0x20F98);  /* 0x10B502EC */
BR_GLOBAL_EXTENT(int32_t, g_brRaceB71288, , 0x4);  /* 0x10B71288 */
BrCtrlCfg g_BrCtrlCfg;  /* 0x10B71290 */
BrCfgRec39580 g_aBrCtlNameMouse[10];  /* 0x10B71B08 */
BR_GLOBAL_EXTENT(char, g_aBrDevName1B0C, [9][36], 0x20);  /* 0x10B71B0C */
BrCfgRec39580 g_aBrCtlNameJoy[134];  /* 0x10B71C70 */
BR_GLOBAL_EXTENT(char, g_aBrDevName1C74, [133][36], 0x20);  /* 0x10B71C74 */
BR_GLOBAL_EXTENT(int, g_navArg, , 0x3FC);  /* 0x10B72F48 */
int32_t g_aBrFpsSamplesB[120];  /* 0x10B73348 */
funcptr DAT_10b73528;  /* 0x10B73528 */
funcptr DAT_10b7352c;  /* 0x10B7352C */
void (*DAT_10b73530)(void *);  /* 0x10B73530 */
funcptr DAT_10b73534;  /* 0x10B73534 */
BR_GLOBAL_EXTENT(int32_t, g_BrFpsGuard, , 0x4);  /* 0x10B73538 */
char g_aBrCfgBaseDir[260];  /* 0x10B73540 */
int DAT_10b73644;  /* 0x10B73644 */
int32_t g_BrReplayCount[8];  /* 0x10B73648 */
BrReplaySlot g_BrReplayBuf[524288];  /* 0x10B73668 */
BrFxRecord g_BrFx1750338[600];  /* 0x11750338 */
BR_GLOBAL_EXTENT(int32_t, g_BrX1754E38, , 0x14);  /* 0x11754E38 */
BR_GLOBAL_EXTENT(uint32_t, g_BrFx1754E50, [200][2], 0x10);  /* 0x11754E50 */
BR_GLOBAL_EXTENT(const uint16_t *, g_pBrCollGridCount, , 0x24);  /* 0x117554A0 */
uint32_t g_aBrCollGridStamp[4];  /* 0x117554C8 */
int16_t g_aBrCollGridKey[4];  /* 0x117554D8 */
BR_GLOBAL_EXTENT(int32_t, g_BrX17554E0, , 0x1E184);  /* 0x117554E0 */
BR_GLOBAL_EXTENT(int32_t, g_BrReplayOn, , 0x4);  /* 0x11773668 */
int32_t g_BrReplayCursor[8];  /* 0x11773670 */
BR_GLOBAL_EXTENT(const float *, g_pBrCarPhysGrip, , 0x4);  /* 0x11773690 */
BrCollPlane DAT_11773698[4][150];  /* 0x11773698 */
BrCollRespNode *g_pBrCollRespList;  /* 0x11778198 */
const BrCollPlane *g_pBrCrCurPlane;  /* 0x1177819C */
BR_GLOBAL_EXTENT(BrVec3, g_brCrPlaneOut, , 0x4);  /* 0x117781A0 */
BrCollRespNode s_aNode[200];  /* 0x117781B0 */
BrCrPlaneState g_brCrPlane;  /* 0x117787F0 */
BrCollRespNode *g_pBrCrCursor;  /* 0x11778844 */
BR_GLOBAL_EXTENT(int32_t, g_brRaceBeginMirrorOff, , 0x4);  /* 0x11778848 */
BR_GLOBAL_EXTENT(uint8_t, g_aBrRaceBeginRecIn, [8], 0xA370);  /* 0x11778850 */
BR_GLOBAL_EXTENT(char, g_aBr1782BC8, [260], 0x4);  /* 0x11782BC8 */
BR_GLOBAL_EXTENT(const char *const, g_pszBrRallySeasonDat, , 0x4B7C);  /* 0x11782CD0 */
BR_GLOBAL_EXTENT(char, g_1787850, [4], 0x1E0BC);  /* 0x11787850 */
BR_GLOBAL_EXTENT(int, g_17A5910, , 0x5F4);  /* 0x117A5910 */
short DAT_117a5f08[2];  /* 0x117A5F08 */
short DAT_117a5f0c[2];  /* 0x117A5F0C */
short DAT_117a5f10[2];  /* 0x117A5F10 */
short DAT_117a5f14[2];  /* 0x117A5F14 */
short DAT_117a5f18[2];  /* 0x117A5F18 */
short DAT_117a5f1c[2];  /* 0x117A5F1C */
BR_GLOBAL_EXTENT(short, g_17A5F20, , 0x6);  /* 0x117A5F20 */
char DAT_117a5f28[264];  /* 0x117A5F28 */
char DAT_117a6030[268];  /* 0x117A6030 */
BR_GLOBAL_EXTENT(char, g_17A613C, , 0x4B);  /* 0x117A613C */
int DAT_117a6188[3712];  /* 0x117A6188 */
BrPeerRec g_aBrPeer71[16];  /* 0x117A9B88 */
int g_178FEE8;  /* 0x117B3248 */
int DAT_117b324c;  /* 0x117B324C */
BR_GLOBAL_EXTENT(int, DAT_117b3250, , 0x4);  /* 0x117B3250 */
BrPeerRec g_aBr178FEF8[16][16];  /* 0x117B3258 */
BR_GLOBAL_EXTENT(int, DAT_11849e58, , 0x4);  /* 0x11849E58 */
void *g_hBrSndWake86;  /* 0x11849E60 */
int DAT_11849e64;  /* 0x11849E64 */
int g_aBrPeerOrder[16];  /* 0x11849E68 */
BR_GLOBAL_EXTENT(unsigned int, DAT_11849ea8, , 0x4);  /* 0x11849EA8 */
BrPeerRankEnt g_aBrPeerRank[16];  /* 0x11849EB0 */
BrPeerMsg g_aBrPeerMsg[16];  /* 0x11849F30 */
unsigned int DAT_1184c070;  /* 0x1184C070 */
unsigned int DAT_1184c074;  /* 0x1184C074 */
int32_t g_fBrSndThread86;  /* 0x1184C078 */
void *g_hBrSndThread86;  /* 0x1184C07C */
BrSfxChan g_aBrSfxChanApplied[15];  /* 0x1184C080 */
double g_aBrSfxChanRate[15];  /* 0x1184C1E8 */
BR_GLOBAL_EXTENT(int, DAT_1184c260, , 0x4);  /* 0x1184C260 */
BR_GLOBAL_EXTENT(struct BrSndVoice *, g_apBrSfxChanVoice, [15], 0x4);  /* 0x1184C268 */
BrSndVoice g_BrSndPrimary;  /* 0x1184C2A8 */
int g_184C454;  /* 0x1184C454 */
LPDIRECTSOUND BrSndPDS;  /* 0x1184C458 */
void *BrSndG18290FC;  /* 0x1184C45C */
uint32_t g_BrEnvTexLookup[2];  /* 0x1184C460: env-map texture id per section */
unsigned int DAT_1184c468;  /* 0x1184C468 */
int DAT_1184c46c;  /* 0x1184C46C */
int DAT_1184c470;  /* 0x1184C470 */
uint32_t g_BrDrawReflectTexA;  /* 0x1184C474 */
uint32_t g_BrEnvTexDefault;  /* 0x1184C478 */
int DAT_1184c47c;  /* 0x1184C47C */
uint32_t g_BrDrawReflectTexB;  /* 0x1184C480 */
int DAT_1184c484;  /* 0x1184C484 */
unsigned char DAT_1184c488[131072];  /* 0x1184C488 */
void * g_apBrStrTable[303];  /* 0x1186C488 */
char *g_pBrStrResBlob;  /* 0x1186C944 */
int32_t g_brStrResUsed;  /* 0x1186C948 */
int32_t g_brStrResSize;  /* 0x1186C94C */
int BrGbiRectG_186C950;  /* 0x1186C950 */
int BrGbiRectG_186C954;  /* 0x1186C954 */
int DAT_1186c958;  /* 0x1186C958 */
uint32_t s_texmem;  /* 0x1186C95C */
BR_GLOBAL_EXTENT(uint32_t, g_brTexLowThreshold, , 0x4);  /* 0x1186C960 */
unsigned int g_BrX1829850[8];  /* 0x1186C968 */
unsigned short DAT_1186c988[125822];  /* 0x1186C988 */
void (*g_brTexSlot18AA084)(void);  /* 0x118AA084 */
void (*g_brTexSlot18AA0A4)(void);  /* 0x118AA0A4 */
void (*g_brTexSlot18AA0A8)(void);  /* 0x118AA0A8 */
void (*g_brTexSlot18AA0AC)(void);  /* 0x118AA0AC */
void (*g_brTexSlot18AA0B0)(void);  /* 0x118AA0B0 */
void (*g_brTexSlot18AA0B4)(void);  /* 0x118AA0B4 */
void (*g_brTexSlot18AA0B8)(void);  /* 0x118AA0B8 */
void (*g_brTexSlot18AA0BC)(void);  /* 0x118AA0BC */
void (*g_brTexSlot18AA0C0)(void);  /* 0x118AA0C0 */
void (*g_brTexSlot18AA0C4)(void);  /* 0x118AA0C4 */
void (*g_brTexSlot18AA0C8)(void);  /* 0x118AA0C8 */
void (*g_brTexSlot18AA0CC)(void);  /* 0x118AA0CC */
void (*g_brTexSlot18AA0D0)(void);  /* 0x118AA0D0 */
int BrGbiRectG_18EC988;  /* 0x118EC988 */
uint32_t DAT_118ec98c;  /* 0x118EC98C */
BR_GLOBAL_EXTENT(int32_t, g_br18A9878, , 0x4);  /* 0x118EC990 */
BrTexQueueEnt g_aBrTexQueue[0x100];  /* 0x118EC998 */
int BrGbiRectG_18ED198;  /* 0x118ED198 */
int (*g_pfn18AA084)(int, const void *, const void *);  /* 0x118ED19C */
int DAT_118ed1a0;  /* 0x118ED1A0 */
float DAT_118ed1a4;  /* 0x118ED1A4 */
float DAT_118ed1a8;  /* 0x118ED1A8 */
int DAT_118ed1ac;  /* 0x118ED1AC */
int32_t g_br18AA098;  /* 0x118ED1B0 */
int g_18ED1B4;  /* 0x118ED1B4 */
void *g_br18AA0A0;  /* 0x118ED1B8 */
void (*g_BrDrawModelDlHook)(uint32_t, uint32_t);  /* 0x118ED1BC */
int (*g_18ED1C0)(unsigned short *, unsigned char *, unsigned char *, int, int, int, int, int);  /* 0x118ED1C0 */
BrGbiBlitFn g_pfn18ED1C4;  /* 0x118ED1C4 */
BrGbiTexCreateFn g_pfn18AA0B0;  /* 0x118ED1C8 */
funcptr DAT_118ed1cc;  /* 0x118ED1CC */
void (*DAT_118ed1d0)(int, int *);  /* 0x118ED1D0 */
void (*DAT_118ed1d4)(void);  /* 0x118ED1D4 */
void (*g_BrGfxSubmit)(uint32_t);  /* 0x118ED1D8 */
void (*g_pfn18AA0C4)(void *);  /* 0x118ED1DC */
void (*g_pfn18AA0C8)(void *, int);  /* 0x118ED1E0 */
void (*DAT_118ed1e4)(struct BrTexRec *, int);  /* 0x118ED1E4 */
int (*g_18ED1E8)();  /* 0x118ED1E8 */
BR_GLOBAL_EXTENT(int, DAT_118ed1f0, , 0x1C);  /* 0x118ED1F0 */
BR_GLOBAL_EXTENT(int, DAT_118ed210, , 0x7FC);  /* 0x118ED210 */
BR_GLOBAL_EXTENT(int, DAT_118eda10, , 0x7FC);  /* 0x118EDA10 */
BR_GLOBAL_EXTENT(int, DAT_118ee210, , 0x1C);  /* 0x118EE210 */
BR_GLOBAL_EXTENT(unsigned int, DAT_118ee230, , 0x4);  /* 0x118EE230 */
long long DAT_118ee238;  /* 0x118EE238 */
int DAT_118ee240;  /* 0x118EE240 */
unsigned int DAT_118ee244;  /* 0x118EE244 */
int DAT_118ee248;  /* 0x118EE248 */
unsigned int DAT_118ee24c;  /* 0x118EE24C */
int64_t g_br86PerfFreq;  /* 0x118EE250 */
int32_t g_br86Probed;  /* 0x118EE258 */
BR_GLOBAL_EXTENT(int32_t, g_br86HasPerf, , 0x8);  /* 0x118EE25C */
int DAT_118ee268[4];  /* 0x118EE268 */
int DAT_118ee278[196];  /* 0x118EE278 */
BR_GLOBAL_EXTENT(int32_t, g_brRaceNFinished, , 0x4);  /* 0x118EE588 */
char DAT_118ee590[1032];  /* 0x118EE590 */
BrDiEffect g_brDiEffSpring;  /* 0x118EE998 */
int32_t g_brInKeyPrev;  /* 0x118EE9CC */
uint8_t g_brInKeys[2][256];  /* 0x118EE9D0 */
BR_GLOBAL_EXTENT(int, DAT_118eebd0, , 0x4);  /* 0x118EEBD0 */
BrDiPeriodic g_brDiSquarePeriod;  /* 0x118EEBD8 */
uint32_t g_BrX18ABAD0;  /* 0x118EEBE8 */
int32_t g_brInMousePrev;  /* 0x118EEBEC */
BR_GLOBAL_EXTENT(int32_t, g_brInKeyCur, , 0x4);  /* 0x118EEBF0 */
BrInJoy g_brInJoy[2];  /* 0x118EEBF8 */
BR_GLOBAL_EXTENT(int32_t, g_br118EEE18, , 0x4);  /* 0x118EEE18 */
BrDiCondition g_brDiSpringCond[2];  /* 0x118EEE20 */
int g_18ABD38[14];  /* 0x118EEE50 */
BrDiObj *g_pBr18ABD70;  /* 0x118EEE88 */
int32_t g_br118EEE8C;  /* 0x118EEE8C */
int32_t g_br18ABD78;  /* 0x118EEE90 */
int32_t g_brInJoyPrev;  /* 0x118EEE94 */
BR_GLOBAL_EXTENT(int, g_18ABD80, , 0x4);  /* 0x118EEE98 */
BrDiEffect g_brDiEffSquare;  /* 0x118EEEA0 */
int DAT_118eeed4;  /* 0x118EEED4 */
int32_t g_brRace18EEED8;  /* 0x118EEED8 */
int g_demoFlag;  /* 0x118EEEDC */
int DAT_118eeee0;  /* 0x118EEEE0 */
int DAT_118eeee4;  /* 0x118EEEE4 */
BrDInputDev *g_pBrDik18ABDD0;  /* 0x118EEEE8 */
BrFfb g_brFfb;  /* 0x118EEEEC */
int64_t g_18ABDE0_64;  /* 0x118EEEF8 */
int g_BrDInputUsers;  /* 0x118EEF00 */
int *DAT_118eef04;  /* 0x118EEF04 */
int32_t g_brDiSpringDir[2];  /* 0x118EEF08 */
int32_t g_br18ABDF8;  /* 0x118EEF10 */
int *DAT_118eef14;  /* 0x118EEF14 */
int DAT_118eef18;  /* 0x118EEF18 */
BR_GLOBAL_EXTENT(void *, g_brhInstance2, , 0xC);  /* 0x118EEF1C */
BR_GLOBAL_EXTENT(int, g_18EEF2C, , 0x10);  /* 0x118EEF2C */
BR_GLOBAL_EXTENT(BrSfxChan, g_aBrSfxChan, [15], 0x10);  /* 0x118EEF40 */
BR_GLOBAL_EXTENT(int, g_18EF0B8, , 0xBC);  /* 0x118EF0B8 */
int DAT_118ef178;  /* 0x118EF178 */
int DAT_118ef17c;  /* 0x118EF17C */
BR_GLOBAL_EXTENT(int, DAT_118ef180, , 0x1428);  /* 0x118EF180 */

BrTrkHdr g_brTrkHdr;  /* 0x106EECD8 */
uint8_t g_abBrTrkImage[BR_TRK_IMAGE_MAX];  /* 0x106EFF08 */
