#include "slice1_10.h"   /* br_globals: its objects */
#include "slice3_39.h"   /* br_globals: its objects */
/* WHAT IT DOES: bring DirectInput up on the first caller only, showing a
 * message box and failing if it is unavailable. Later callers just raise the
 * use count. */
/* @implements 0x10071FC0 glide Ctl71FC0
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl71FC0@@QAEHXZ
 *
 * Refcount-gated DirectInput installer. new T of 0x54 (ctor DECLARED, no
 * dtor). DirectInputCreateA is NOT dllimport (orig E8 to a JMP thunk);
 * MessageBoxA IS dllimport (orig FF 15). No NULL-return after new.
 */
#define _CRTIMP __declspec(dllimport)

class DiDev {
public:
    char _[0x54];
    DiDev();
    void Init(void *);
};

typedef char chk_sz[sizeof(DiDev) == 0x54 ? 1 : -1];

/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: g_obj is defined once, in br_globals.c */

/* GetStr: prototype in br_funcs.h */
/* DirectInputCreateA: prototype in br_funcs.h */
/* 64-bit core: MessageBoxA is declared by the platform headers */

class Ctl71FC0 {
public:
    int Activate();
};

int Ctl71FC0::Activate()
{
    DiDev *p;

    if (++g_BrDInputUsers != 1)
        return 1;
    if (DirectInputCreateA((HINSTANCE)g_brhInstance2, 0x500, (void **)&g_pBr18ABD70, 0) < 0) {
        MessageBoxA((HWND)(*(void * *)&g_brOwner5BC72C), BrStrGet(0x127), BrStrGet(0x126), 0x10);
        return 0;
    }
    p = new DiDev;
    (*(DiDev * *)&g_pBrAA2E80) = p;
    p->Init((*(void * *)&g_brOwner5BC72C));
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl71FC0_fn(void *self)
{
    return ((class Ctl71FC0 *)self)->Activate();
}
/* end of C entry points */
