#!/usr/bin/env python3
"""C entry points for C++ methods the original calls as plain functions.

The verified build placed some addresses under a class's name: the function
at that address is a method (thiscall, `this` first), and C code calls it
through a function pointer or under an alias. The 64-bit core links by name,
so each such method gets a forwarder with C linkage, under the placed name,
appended to the file that defines the class:

    extern "C" int Ctl3E730(class Ctl3E730 *self) { return self->Activate(); }

`this` becomes the first parameter, which is how the original passed it.
The method is the one the file's @cpp_symbol names (or, without one, the
file's only method body of that class). funcproto.py then writes the
prototype like any other.

Usage: methodfwd.py [--dry]
"""
import csv
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rawscan  # noqa: E402

ROOT = rawscan.ROOT
BEGIN = '/* C entry points (generated by ports/64b/tools/methodfwd.py) */\n'
END = '/* end of C entry points */\n'


def methods_of(ast, cls):
    """[(method name, return type, [(param type, name)], static, has body)]"""
    out = []

    def visit(nodes, owner):
        for n in nodes or []:
            k = n.get('kind')
            if k == 'CXXRecordDecl' and n.get('name') == cls:
                visit(n.get('inner'), cls)
            elif k == 'LinkageSpecDecl' or k == 'NamespaceDecl':
                visit(n.get('inner'), owner)
            elif k in ('CXXMethodDecl', 'CXXDestructorDecl', 'CXXConstructorDecl'):
                parent = owner
                if parent is None:
                    pd = n.get('parentDeclContextId')
                    parent = ids.get(pd)
                if parent != cls:
                    continue
                body = any(c.get('kind') == 'CompoundStmt' for c in n.get('inner', []) or [])
                qt = n.get('type', {}).get('qualType', '')
                ret = re.match(r'^(.*?)\s*\(', qt)
                ps = [(p.get('type', {}).get('qualType'), p.get('name') or 'a%d' % i)
                      for i, p in enumerate(c for c in n.get('inner', []) or [] if c.get('kind') == 'ParmVarDecl')]
                out.append((n.get('name'), ret.group(1).strip() if ret else 'void', ps,
                            n.get('storageClass') == 'static', body))
    ids = {}
    for n in ast.get('inner', []):
        if n.get('kind') == 'CXXRecordDecl' and n.get('name'):
            ids[n.get('id')] = n.get('name')
    visit(ast.get('inner'), None)
    return out


def main():
    os.chdir(ROOT)
    done, skipped = 0, []
    for r in csv.DictReader(open('build/wasm/placement.csv')):
        f = 'ports/64b/' + r['src']
        placed = r['name']
        if not f.endswith('.cpp') or not os.path.exists(f):
            continue
        s = open(f, encoding='latin-1').read()
        s = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), '', s, flags=re.S)
        cls = placed
        if not re.search(r'\b%s\s*::\s*~?\w+\s*\(' % re.escape(cls), s):
            # a placed name that is no class: the method its @cpp_symbol names
            m = re.search(r'@implements 0x%s\b[^\n]*\n(?:[^\n]*\n){0,6}?[^\n]*@cpp_symbol\s+\?(\?[01]|\w+)@?(\w+)@@'
                          % r['va'][2:].upper(), s, re.I) or \
                re.search(r'@cpp_symbol\s+\?(\?[01]|\w+)@?(\w+)@@', s)
            if not m or re.search(r'^[^\n]*(?<![:~])\b%s\s*\([^;{]*\)\s*\{' % re.escape(placed), s, re.M):
                continue
            cls = m.group(2)
            if not re.search(r'\b%s\s*::\s*~?\w+\s*\(' % re.escape(cls), s):
                continue
        base = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), '', s, flags=re.S)
        # a C function of that name already exists
        if placed == cls and re.search(r'^[^\n]*(?<![:~])\b%s(?:_fn)?\s*\([^;{]*\)\s*\{' % re.escape(cls), base, re.M) and \
                not re.search(re.escape(BEGIN), s):
            continue
        a = rawscan.ast(f)
        if a is None:
            skipped.append((f, cls, 'no syntax tree'))
            continue
        ms = [m for m in methods_of(a, cls) if m[4]]
        want = None
        m = re.search(r'@cpp_symbol\s+\?(\?[01]|\w+)@?%s@@' % re.escape(cls), s)
        if m:
            want = {'?0': cls, '?1': '~' + cls}.get(m.group(1), m.group(1))
            ms = [x for x in ms if x[0] == want]
        if len(ms) != 1:
            skipped.append((f, cls, 'methods %s' % [x[0] for x in ms]))
            continue
        name, ret, ps, static, _ = ms[0]
        params = ([] if static else ['void *self']) + ['%s %s' % (t, n) for t, n in ps]
        if name == cls:
            call = 'new (self) %s' % cls             # construct in place, as the original's ctor call does
        else:
            call = ('%s::%s' % (cls, name)) if static else '((class %s *)self)->%s' % (cls, name)
        body = '%s(%s)' % (call, ', '.join(n for _, n in ps))
        if name == cls:
            ret, body = 'void *', '(void *)new (self) %s(%s)' % (cls, ', '.join(n for _, n in ps))
        fname = placed + '_fn' if placed == cls else placed
        fwd = 'extern "C" %s %s(%s)\n{\n    %s%s;\n}\n' % (
            ret, fname, ', '.join(params) or 'void', '' if ret == 'void' else 'return ', body)
        if 'new (self)' in fwd:
            fwd = '#include <new>\n' + fwd
        new = base.rstrip('\n') + '\n\n' + BEGIN + fwd + END
        if new != s:
            if '--dry' not in sys.argv:
                open(f, 'w', encoding='latin-1').write(new)
            done += 1
    with open('build/portable/method_fwd.csv', 'w') as fh:
        fh.write('placed,forwarder\n')
        for f in sorted(glob.glob('ports/64b/src/core/**/*.cpp', recursive=True)):
            for m in re.finditer(r'^extern "C" [^\n]*?\b(\w+)_fn\(', open(f, encoding='latin-1').read(), re.M):
                fh.write('%s,%s_fn\n' % (m.group(1), m.group(1)))
            for m in re.finditer(r'^extern "C" [^\n]*?\b(\w+)\(void \*self', open(f, encoding='latin-1').read(), re.M):
                if not m.group(1).endswith('_fn'):
                    fh.write('%s,%s\n' % (m.group(1), m.group(1)))
    print('C entry points for methods: %d written; %d skipped' % (done, len(skipped)))
    for f, c, why in skipped:
        print('  skip %s (%s): %s' % (c, f, why))


if __name__ == '__main__':
    main()
