#!/usr/bin/env python3
"""assets.py -- what the port needs from the cartridge, taken out at build time.

The port is the game's code compiled from source, so of the ROM it needs
only the data: the initialised .data/.rodata (ROM 0x70AB0..0xAD400, lifted
into the arena at start-up) and everything after it, the tracks, models,
textures and sounds the game streams in over the PI.  The header, the boot
code and the compiled code (0x0..0x70AB0) are left behind; nothing reads
them at run time.  The data is written next to the build and assembled into
the executable (romdata.S, .incbin), so a built game needs no ROM.

    assets.py OUT_DIR [--rom FILE]

The ROM is FILE, else $TGR_ROM, else reference/tgrally/Top Gear Rally (USA).z64;
.z64, .v64 or .n64 byte order; it must be Top Gear Rally (USA).  Written only
when it changes (a stamp of its digest), so a rebuild does not redo it.
"""
import argparse
import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DEFAULT = os.path.join(ROOT, 'reference/tgrally/Top Gear Rally (USA).z64')
SHA1 = 'bfc51f086ebdb78904dc24ad0c3a2d946e26d022'   # Top Gear Rally (USA), .z64 order
BASE = 0x70AB0                                      # the first byte the port reads


def big_endian(rom):
    """the cartridge's own order: .v64 swaps bytes in pairs, .n64 in words"""
    if rom[:2] == b'\x37\x80':
        b = bytearray(rom)
        b[0::2], b[1::2] = rom[1::2], rom[0::2]
        return bytes(b)
    if rom[:2] == b'\x40\x12':
        b = bytearray(rom)
        b[0::4], b[1::4], b[2::4], b[3::4] = rom[3::4], rom[2::4], rom[1::4], rom[0::4]
        return bytes(b)
    return rom


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('out')
    ap.add_argument('--rom', default=os.environ.get('TGR_ROM') or DEFAULT)
    a = ap.parse_args()
    if not os.path.isfile(a.rom):
        sys.exit('assets: no ROM at %s: the build takes the game\'s data from your cartridge\'s ROM '
                 '(Top Gear Rally (USA), .z64, .v64 or .n64); name it with TGR_ROM=FILE' % a.rom)
    rom = big_endian(open(a.rom, 'rb').read())
    digest = hashlib.sha1(rom).hexdigest()
    if digest != SHA1:
        sys.exit('assets: %s is not Top Gear Rally (USA) (sha1 %s, expected %s)' % (a.rom, digest, SHA1))
    os.makedirs(a.out, exist_ok=True)
    stamp = os.path.join(a.out, 'romdata.sha1')
    blob = os.path.join(a.out, 'romdata.bin')
    if os.path.exists(stamp) and open(stamp).read().strip() == digest + ' 2' and os.path.exists(blob):
        return
    open(blob, 'wb').write(rom[BASE:])
    with open(os.path.join(a.out, 'romdata.S'), 'w') as f:
        f.write('/* generated by ports/tgrally/tools/assets.py: the cartridge\'s data from ROM 0x%X on */\n' % BASE)
        f.write('#ifdef __APPLE__\n#define SYM(x) _##x\n    .section __DATA,__const\n'
                '#else\n#define SYM(x) x\n    .section .rodata\n#endif\n')
        f.write('    .globl SYM(tgr_romdata_blob)\n    .globl SYM(tgr_romdata_blob_end)\n    .p2align 4\n')
        f.write('SYM(tgr_romdata_blob):\n    .incbin "%s"\nSYM(tgr_romdata_blob_end):\n' % os.path.abspath(blob))
    open(stamp, 'w').write(digest + ' 2\n')   # 2: the blob's symbols are tgr_romdata_blob*
    print('assets: %d bytes of the cartridge\'s data (ROM 0x%X..0x%X) for the build' % (len(rom) - BASE, BASE, len(rom)))


if __name__ == '__main__':
    main()
