#!/bin/sh
# Build "Top Gear Rally" for the iPhone.
#   the games:  Top Gear Rally, libtgrally.a (link.sh, HOST=ios: the cartridge's
#               data from your ROM built in, tools/assets.py) and Boss Rally,
#               libbrally.a (ports/brally/link64.sh, HOST=ios: BRGlide.dll's data
#               built in), whose engine runs the races when the Remastered flag
#               is on (host_race.h).  Each is linked into one object that shows
#               only its entry points (the two share some hundred function
#               names), and the two go into libgames.a
#   the disc:   Boss Rally's data track, from your disc image (the extract
#               ports/brally/package_app.sh makes), in the app as Resources/disc
#   the app:    the Swift host in Sources, an Xcode project generated by
#               xcodegen into build/tgrally/ios-metal, signed automatically
#
# Usage: ports/tgrally/ios/build.sh [--rom FILE] [--bin FILE] [--sim] [--install [--device ID]]
#   --bin FILE   Boss Rally's disc image (default reference/brally/BossRally.BIN)
#   --sim        build for the Simulator instead (build/tgrally/ios-sim-metal)
#   --install    put it on the phone (devicectl's identifier or name with
#                --device; default: the first paired physical iPhone)
set -e
cd "$(dirname "$0")/../../.."
INSTALL=0
DEVICE=
SIM=
BIN=reference/brally/BossRally.BIN
while [ $# -gt 0 ]; do
    case $1 in
        --rom) TGR_ROM=$2; export TGR_ROM; shift 2 ;;
        --bin) BIN=$2; shift 2 ;;
        --install) INSTALL=1; shift ;;
        --device) DEVICE=$2; shift 2 ;;
        --sim) SIM=1; shift ;;
        *) echo "ios/build.sh: unknown argument $1" >&2; exit 2 ;;
    esac
done
OUT=build/tgrally/ios-metal BROUT=build/brally/ios-metal SDK=iphoneos DEST=generic/platform=iOS
if [ -n "$SIM" ]; then
    OUT=build/tgrally/ios-sim-metal BROUT=build/brally/ios-sim-metal SDK=iphonesimulator
    DEST="generic/platform=iOS Simulator"
    TGR_IOS_SIM=1; export TGR_IOS_SIM
    INSTALL=0
fi
PY=.venv/bin/python
[ -x $PY ] || PY=python3

# ---- Boss Rally's disc: the extract package_app.sh keeps, else made here -------
EX=build/brally/macos-metal/extract
if [ ! -f $EX/disc/BRGlide.dll ]; then
    [ -f "$BIN" ] || { echo "ios/build.sh: no Boss Rally disc image at $BIN" >&2; exit 1; }
    mkdir -p $EX
    $PY tools/brally/extract_disc.py "$BIN" $EX/disc
fi
# the data track as the game's CD root, less the installer and the video
rm -rf $OUT/disc
rsync -a --exclude 'brally.avi' --exclude '*.cab' --exclude '*.exe' --exclude '*.EXE' \
    --exclude '_INST32I.EX_' --exclude '_SETUP.DLL' --exclude 'dsetup*.dll' --exclude 'Msvcrt.dll' \
    --exclude 'BRD3D.dll' --exclude 'SETUP.INI' --exclude 'setup.*' --exclude 'Setup.BMP' \
    --exclude 'Autorun.inf' --exclude '*.url' --exclude 'layout.bin' \
    $EX/disc/ $OUT/disc/

# ---- the two games, each behind its entry points -------------------------------
OUT=$OUT HOST=ios RENDER=metal CC=ports/tgrally/ios/cc.sh GFLAG=-g0 ports/tgrally/link.sh
OUT=$BROUT HOST=ios RENDER=metal CC=ports/tgrally/ios/cc.sh GFLAG=-g0 DLL=$EX/disc/BRGlide.dll ports/brally/link64.sh
engine() {   # engine NAME LIB SYMBOLS...: LIB's objects as one, only SYMBOLS global
    lib=$(pwd)/$1; name=$2; shift 2
    rm -rf $OUT/$name.x && mkdir -p $OUT/$name.x
    (cd $OUT/$name.x && ar x "$lib")
    for s in "$@"; do echo "_$s"; done > $OUT/$name.exp
    if [ -n "$SIM" ]; then PLAT=ios-simulator; else PLAT=ios; fi
    xcrun -sdk $SDK ld -r -arch arm64 -platform_version $PLAT 16.0 16.0 \
        -exported_symbols_list $OUT/$name.exp -o $OUT/$name.o $OUT/$name.x/*.o
    rm -rf $OUT/$name.x
}
engine $OUT/libtgrally.a tgrally tgr_main tgr_view_driving tgr_touch_tap tgr_touch_swipe tgr_touch_press \
    tgr_touch_input tgr_audio_lowpass tgr_race_engine tgr_race_speed
engine $BROUT/libbrally.a brally br_main br_race_run br_race_serve br_race_driving br_race_key
rm -f $OUT/libgames.a
ar rcs $OUT/libgames.a $OUT/tgrally.o $OUT/brally.o

# ---- the app ---------------------------------------------------------------------
xcodegen generate --quiet --spec ports/tgrally/ios/project.yml --project $OUT --project-root $OUT
xcodebuild -project $OUT/TopGearRally.xcodeproj -scheme TopGearRally -configuration Release \
    -destination "$DEST" -derivedDataPath $OUT/derived -allowProvisioningUpdates \
    ARCHS=arm64 ONLY_ACTIVE_ARCH=NO -quiet build
APP="$OUT/derived/Build/Products/Release-$SDK/Top Gear Rally.app"
echo "built $APP"
[ $INSTALL = 1 ] || exit 0
if [ -z "$DEVICE" ]; then
    DEVICE=$(xcrun devicectl list devices 2>/dev/null | awk '/physical/ && /iPhone/ && /available/ { for (i = 1; i <= NF; i++) if ($i ~ /^[0-9A-F]{8}-[0-9A-F]{16}$/) { print $i; exit } }')
fi
[ -n "$DEVICE" ] || { echo "ios/build.sh: no paired iPhone found" >&2; exit 1; }
xcrun devicectl device install app --device "$DEVICE" "$APP"
