#!/usr/bin/env python3
"""One name per original function; every other name an alias of it.

The decompiled files call one original function under several names (the
32-bit lane resolved them all by address). The 64-bit core links by name, so:

  * the canonical name of a function is the one the verified build placed at
    its address (build/brally/wasm32/placement.csv);
  * every other C name a file uses for that address (build/brally/wasm32/sites.csv)
    becomes `#define ALIAS CANONICAL` in that file's alias header
    (ports/brally/alias/<file>.h, appended to what unify.py wrote);
  * a body defined under an alias name -- a stand-in stub -- is removed, so
    the real function is the only one that links;
  * C++ method names that the original resolved to a C function (thiscall
    written as __fastcall) are listed for forwarding definitions.

Usage: funcs.py [--dry]
"""
import collections
import csv
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import stubaudit  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
TEXT_LO, TEXT_HI = 0x10001000, 0x10077000
DRY = '--dry' in sys.argv


def main():
    os.chdir(ROOT)
    place = {int(r['va'], 16): r['name'] for r in csv.DictReader(open('build/brally/wasm32/placement.csv'))}
    canon_names = set(place.values())
    fwd = {}
    if os.path.exists('build/brally/null-soft/method_fwd.csv'):
        fwd = {r['placed']: r['forwarder'] for r in csv.DictReader(open('build/brally/null-soft/method_fwd.csv'))}
    per_file = collections.defaultdict(dict)    # fork file -> {alias: canonical}
    methods = collections.defaultdict(set)      # canonical -> {Class::Method}
    # import thunks (jmp [IAT]): a call through one is a call of the import
    thunk = {}
    if os.path.exists('build/brally/null-soft/thunks.csv'):
        ORD = {'DPLAYX.dll#4': 'DirectPlayCreate', 'DPLAYX.dll#5': 'DirectPlayEnumerateA',
               '?terminate@@YAXXZ': 'abort', '??3@YAXPAX@Z': 'BrOperatorDelete',
               '??2@YAPAXI@Z': 'BrOperatorNew'}
        for r in csv.DictReader(open('build/brally/null-soft/thunks.csv')):
            n = ORD.get(r['name'], re.sub(r'@\d+$', '', r['name']).lstrip('_'))
            if re.match(r'^[A-Za-z_]\w*$', n):
                thunk[int(r['va'], 16)] = n
    for r in csv.DictReader(open('build/brally/wasm32/sites.csv')):
        va = int(r['va'], 16)
        if va in thunk and r['name'] != thunk[va] and re.match(r'^[A-Za-z_]\w*$', r['name']):
            fork = 'ports/brally/' + r['src']
            if os.path.exists(fork):
                per_file[fork][r['name']] = thunk[va]
            continue
        if not (TEXT_LO <= va < TEXT_HI) or va not in place:
            continue
        nm, cn = r['name'], place[va]
        if nm == cn or nm.startswith('$'):
            continue
        if '::' in nm:
            methods[cn].add(nm)
            continue
        if not re.match(r'^[A-Za-z_]\w*$', nm):
            continue
        fork = 'ports/brally/' + r['src']
        if os.path.exists(fork):
            per_file[fork][nm] = cn
    # stub bodies under alias names
    removed = 0
    for f, amap in per_file.items():
        s = open(f, encoding='latin-1').read()
        o = s
        for nm in amap:
            if nm in canon_names:
                continue        # it is also some function's real name
            for m in list(re.finditer(r'^[^\n;{}#]*\b%s\s*\([^;{}]*\)\s*\{' % re.escape(nm), s, re.M)):
                # only a definition at file scope (or in an extern "C" block):
                # the same pattern inside a function is an `if (NAME(...)) {`
                enc = stubaudit.enclosing(s, m.start())
                if enc is not None and not re.search(r'extern\s+"C"\s*$', enc.rstrip()):
                    continue
                # not an @implements body
                head = s[max(0, m.start() - 400):m.start()]
                if re.search(r'@implements[^\n]*\b%s\b' % re.escape(nm), head):
                    continue
                i, d = m.end() - 1, 0
                while i < len(s):
                    if s[i] == '{':
                        d += 1
                    elif s[i] == '}':
                        d -= 1
                        if d == 0:
                            break
                    i += 1
                s = s[:m.start()] + '/* %s: the original function is %s */' % (nm, amap[nm]) + s[i + 1:]
                removed += 1
                break
        if s != o and not DRY:
            open(f, 'w', encoding='latin-1').write(s)
    # alias headers
    outdir = 'ports/brally/alias'
    os.makedirs(outdir, exist_ok=True)
    n = 0
    for f, amap in per_file.items():
        key = f[len('ports/brally/src/core/'):].replace('/', '__')
        p = os.path.join(outdir, key + '.h')
        body = open(p).read() if os.path.exists(p) else '/* generated by ports/brally/tools/funcs.py */\n'
        body = re.sub(r'\n/\* functions \*/\n.*', '\n', body, flags=re.S)
        lines = ['#define %s %s' % (a, fwd.get(c, c)) for a, c in sorted(amap.items()) if a not in canon_names]
        # a C file calls a C++ method by its placed (class) name: the forwarder
        if f.endswith('.c'):
            src_t = open(f, encoding='latin-1').read()
            lines += ['#define %s %s' % (c, fv) for c, fv in sorted(fwd.items())
                      if re.search(r'\b%s\s*\(' % re.escape(c), src_t)]
        if lines:
            body = body.rstrip('\n') + '\n/* functions */\n' + '\n'.join(lines) + '\n'
            n += len(lines)
            if not DRY:
                open(p, 'w').write(body)
    open('build/brally/null-soft/method_aliases.csv', 'w').write(
        'canonical,methods\n' + ''.join('%s,%s\n' % (c, ' '.join(sorted(m))) for c, m in sorted(methods.items())))
    print('function aliases: %d in %d files; stub bodies removed: %d; C++ methods resolved to C functions: %d' % (
        n, len(per_file), removed, sum(len(v) for v in methods.values())))


if __name__ == '__main__':
    main()
