#!/usr/bin/env python3
"""winnames.py -- the private names the Win32 emulation takes on Windows.

platform/common implements the game's Win32, CRT, DirectX and Glide surface
under the real API's names (CreateMutexA, Sleep, _errno ...). On macOS and
Linux nothing else defines those names. On Windows the system's import
libraries do, and the OS host (host/win32) calls the real ones, so the two
would collide at link time. This writes platform/include/br_winemu.h: a
#define per symbol platform/common defines, renaming it brw_<name>. A Windows
build force-includes it into the core and platform/common (never into the OS
host), so the game binds to the emulation and the host to the system.

The list comes from the platform/common objects of a host build (nm), so
run it after any change to what platform/common defines:

    tools/brally/winnames.py [OBJDIR]      (default build/brally/null-soft/plat)
"""
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
OUT = os.path.join(ROOT, 'ports', 'brally', 'platform', 'include', 'br_winemu.h')
KEEP = re.compile(r'^(main$|plat_|brr_|host_|g_plat|br_|kthread)')


def main():
    objdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'build', 'brally', 'null-soft', 'plat')
    src = os.path.join(ROOT, 'ports', 'brally', 'platform', 'common')
    commons = {os.path.splitext(f)[0] for f in os.listdir(src) if f.endswith('.c')}
    names = set()
    for f in sorted(os.listdir(objdir)):
        base = f[:-len('.c.o')] if f.endswith('.c.o') else None
        if base not in commons:
            continue
        out = subprocess.run(['nm', '-g', '--defined-only', os.path.join(objdir, f)],
                             capture_output=True, text=True).stdout
        for line in out.splitlines():
            parts = line.split()
            if len(parts) != 3 or parts[1] not in 'TDBSC':
                continue
            name = parts[2][1:] if sys.platform == 'darwin' and parts[2].startswith('_') else parts[2]
            if not KEEP.match(name):
                names.add(name)
    with open(OUT, 'w') as fh:
        fh.write('/* br_winemu.h: generated by ports/brally/tools/winnames.py -- do not edit.\n'
                 ' *\n'
                 ' * On Windows the Win32 emulation in platform/common takes private names,\n'
                 ' * so the system\'s own functions of the same names stay the OS host\'s.\n'
                 ' * Force-included into the core and platform/common of a Windows build. */\n'
                 '#ifndef BR_WINEMU_H\n#define BR_WINEMU_H\n#ifdef _WIN32\n')
        for n in sorted(names):
            fh.write('#define %s brw_%s\n' % (n, n))
        fh.write('#endif\n#endif\n')
    print('%d names -> %s' % (len(names), os.path.relpath(OUT, ROOT)))


if __name__ == '__main__':
    main()
