/* WHAT IT DOES: look one entry up in the archive's table of contents by key,
 * aborting with a message if it is not there. The callers treat a missing
 * entry as unrecoverable. */
/* @implements 0x10008930 glide M8930
 * @cpp_kind method
 * @cpp_symbol ?M8930@Tbl8900@@QAEHH@Z
 *
 * Container-class method family (0x10008930..0x10008A30): thiscall
 * with stack args (`ret 4`), slot-2 vcall on self with the vtbl read
 * before the arg pushes (`mov eax,[ecx]` at +0: C++ member-call
 * order), error printf through 0x10008EC0 on -1. No EH.
 */
#define _CRTIMP __declspec(dllimport)

class Tbl8900 {
public:
    virtual void v0();
    virtual void v1();
    virtual int v2(int);
    int M8930(int a);
};

extern "C" {
extern "C" char DAT_1007b52c[1];   /* the original global; was a per-file stand-in definition */
#define s_err DAT_1007b52c
/* BrLogFatalPrintf: prototype in br_funcs.h */
}

int Tbl8900::M8930(int a)
{
    int r;

    r = v2(a);
    if (r == -1) {
        BrLogFatalPrintf(s_err, a);
        return -1;
    }
    return r;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int M8930(void *self, int a)
{
    return ((class Tbl8900 *)self)->M8930(a);
}
/* end of C entry points */
