/* WHAT IT DOES: return the size of the entry at an index, aborting if the
 * index is out of range. */
/* @implements 0x10008960 glide M8960
 * @cpp_kind method
 * @cpp_symbol ?M8960@Tbl8900@@QAEHI@Z
 *
 * Tbl8900 family: bounds-checked getter: warn printf on overflow,
 * then return items[i].f4 (76-byte entries, field at +4).
 */
#define _CRTIMP __declspec(dllimport)

struct Ent {
    int f0;
    int f4;
    int rest[17];
};

class Tbl8900 {
public:
    virtual void v0();
    virtual void v1();
    virtual int v2(int);
    int pad[3];
    unsigned count;
    int f14;
    Ent *items;
    int M8960(unsigned i);
};



typedef char chk_ent[sizeof(Ent) == 76 ? 1 : -1];

extern "C" {
extern "C" char DAT_1007b54c[1];   /* the original global; was a per-file stand-in definition */
#define s_err DAT_1007b54c
/* BrLogFatalPrintf: prototype in br_funcs.h */
}

int Tbl8900::M8960(unsigned i)
{
    if (i >= count)
        BrLogFatalPrintf(s_err, i);
    return items[i].f4;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int M8960(void *self, unsigned int i)
{
    return ((class Tbl8900 *)self)->M8960(i);
}
/* end of C entry points */
