/* WHAT IT DOES: read one archive entry into the caller's buffer -- seeks to
 * its offset and reads its recorded length. */
/* @implements 0x10008990 glide M8990
 * @cpp_kind method
 * @cpp_symbol ?M8990@Tbl8900@@QAEXIPAX@Z
 *
 * Tbl8900 family: bounds warn, fseek(fFile, items[i].f0, SEEK_SET),
 * then sub.Read(fFile, dst, items[i].f4): thiscall on the member
 * object at +4 (0x10008E60).
 */
#define _CRTIMP __declspec(dllimport)
#include <stdio.h>

struct Ent {
    int f0;
    int f4;
    int rest[17];
};

class Sub8E60 {
public:
    int d0;
    int d4;
    int d8;
    void Read(FILE *f, void *dst, int n);
};

class Tbl8900 {
public:
    virtual void v0();
    virtual void v1();
    virtual int v2(int);
    Sub8E60 sub;
    unsigned count;
    int f14;
    Ent *items;
    FILE *fFile;
    void M8990(unsigned i, void *dst);
};





typedef char chk_ent[sizeof(Ent) == 76 ? 1 : -1];

extern "C" {
extern "C" char DAT_1007b56c[1];   /* the original global; was a per-file stand-in definition */
#define s_err DAT_1007b56c
/* BrLogFatalPrintf: prototype in br_funcs.h */
}

void Tbl8900::M8990(unsigned i, void *dst)
{
    Ent *e;

    if (i >= count)
        BrLogFatalPrintf(s_err, i);
    e = &items[i];
    fseek(fFile, e->f0, 0);
    sub.Read(fFile, dst, e->f4);
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" void M8990(void *self, unsigned int i, void * dst)
{
    ((class Tbl8900 *)self)->M8990(i, dst);
}
/* end of C entry points */
