/* WHAT IT DOES: allocate a buffer the size of one archive entry, remember it
 * against that entry, and return it. */
/* @implements 0x100089F0 glide M89F0
 * @cpp_kind method
 * @cpp_symbol ?M89F0@Tbl8900@@QAEHI@Z
 *
 * Tbl8900 family: bounds warn, p = alloc(v4(i)), v5(i, p), return p.
 * Vtbl cached in edi across both vcalls.
 */
#define _CRTIMP __declspec(dllimport)

class Tbl8900 {
public:
    virtual void v0();
    virtual void v1();
    virtual int v2(int);
    virtual void v3();
    virtual int v4(int);
    virtual void v5(int, int);
    int pad[3];
    unsigned count;
    int M89F0(unsigned i);
};



extern "C" {
extern "C" char DAT_1007b584[1];   /* the original global; was a per-file stand-in definition */
#define s_err DAT_1007b584
/* BrLogFatalPrintf: prototype in br_funcs.h */
/* BrAlloc74572: prototype in br_funcs.h */
}

int Tbl8900::M89F0(unsigned i)
{
    int p;

    if (i >= count)
        BrLogFatalPrintf(s_err, i);
    p = BrOperatorNew(v4(i));
    v5(i, p);
    return p;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int M89F0(void *self, unsigned int i)
{
    return ((class Tbl8900 *)self)->M89F0(i);
}
/* end of C entry points */
