/* @implements 0x10056260 glide BrUiBootPreLoopGate
 * @cpp_kind method
 * @cpp_symbol ?BrUiBootPreLoopGate@@YAHXZ
 *
 * 8349 B. C++ EH, maxState=2, both unwind actions `operator delete`.
 * Body is 145 scalar `operator new(0x104)` + inlined strcpy, then
 * `new Phase` (0xC8) and `new Obj400` (0x400). Compile /O2 /GX /MD.
 *
 * Do not dllimport operator new: orig calls the 0x10074572 thunk (E8),
 * not the IAT (FF 15). Member dtors/ctors stay declared, not defined.
 */
void *__cdecl operator new(unsigned int);

extern "C" char *strcpy(char *, const char *);

/* C++ linkage: after `new Obj400` the compiler only stores trylevel=-1
 * if a later call can throw. extern "C" is nothrow and the store vanishes
 * (8 bytes, the whole remaining residue). */
void Tables64Clear(void);
void RectTablesInit(void);
void ErrShow(int);
void PhaseEnter(void);

#pragma intrinsic(strcpy)

class Phase {
public:
    void *vptr;
    void *pfnEnter;
    char rest[0xC0];
    Phase();
};

class Obj400 {
    char b[0x400];
public:
    Obj400();
};

typedef char chk_phase[sizeof(Phase) == 0xC8 ? 1 : -1];
typedef char chk_obj[sizeof(Obj400) == 0x400 ? 1 : -1];

struct Img {
    void *surf;
    char *path;
};

Img g_img[145];
unsigned short g_cLoaded;
unsigned short g_wAC5D50;
unsigned short g_wAC5D54;

int g_rec[0xB4];
int g_zero[0x64];

Phase *g_phaseRoot;
Phase *g_phaseCur;
Obj400 *g_obj400;

char g_season[0x104];
char g_ghost[0x104];

int BrUiBootPreLoopGate(void)
{
    char *p;
    int n;
    int *q;
    Phase *ph;
    Obj400 *ob;

    n = 0x122;
    q = (int *)g_img;
    for (; n != 0; n--) {
        *q++ = 0;
    }
    g_cLoaded = 0;
    g_wAC5D50 = 0;
    g_wAC5D54 = 0;
    Tables64Clear();
    p = (char *)operator new(0x104);
    g_img[0].path = p;
    strcpy(p, "images\\\\work1a.bmp");
    p = (char *)operator new(0x104);
    g_img[1].path = p;
    strcpy(p, "images\\\\cursor.bmp");
    p = (char *)operator new(0x104);
    g_img[2].path = p;
    strcpy(p, "images\\\\type_gry.bmp");
    p = (char *)operator new(0x104);
    g_img[3].path = p;
    strcpy(p, "images\\\\type_wit.bmp");
    p = (char *)operator new(0x104);
    g_img[4].path = p;
    strcpy(p, "images\\\\type_mid.bmp");
    p = (char *)operator new(0x104);
    g_img[5].path = p;
    strcpy(p, "images\\\\bignums.bmp");
    p = (char *)operator new(0x104);
    g_img[6].path = p;
    strcpy(p, "images\\\\champ.bmp");
    p = (char *)operator new(0x104);
    g_img[7].path = p;
    strcpy(p, "images\\\\mp.bmp");
    p = (char *)operator new(0x104);
    g_img[8].path = p;
    strcpy(p, "images\\\\ta.bmp");
    p = (char *)operator new(0x104);
    g_img[9].path = p;
    strcpy(p, "images\\\\op.bmp");
    p = (char *)operator new(0x104);
    g_img[10].path = p;
    strcpy(p, "images\\\\qr.bmp");
    p = (char *)operator new(0x104);
    g_img[11].path = p;
    strcpy(p, "images\\\\carmt.bmp");
    p = (char *)operator new(0x104);
    g_img[12].path = p;
    strcpy(p, "images\\\\mshft.bmp");
    p = (char *)operator new(0x104);
    g_img[13].path = p;
    strcpy(p, "images\\\\softshok.bmp");
    p = (char *)operator new(0x104);
    g_img[14].path = p;
    strcpy(p, "images\\\\medshok.bmp");
    p = (char *)operator new(0x104);
    g_img[15].path = p;
    strcpy(p, "images\\\\hardshok.bmp");
    p = (char *)operator new(0x104);
    g_img[16].path = p;
    strcpy(p, "images\\\\desrttrk.bmp");
    p = (char *)operator new(0x104);
    g_img[17].path = p;
    strcpy(p, "images\\\\coasttrk.bmp");
    p = (char *)operator new(0x104);
    g_img[18].path = p;
    strcpy(p, "images\\\\trakc.bmp");
    p = (char *)operator new(0x104);
    g_img[19].path = p;
    strcpy(p, "images\\\\fog.bmp");
    p = (char *)operator new(0x104);
    g_img[20].path = p;
    strcpy(p, "images\\\\nite.bmp");
    p = (char *)operator new(0x104);
    g_img[21].path = p;
    strcpy(p, "images\\\\rain.bmp");
    p = (char *)operator new(0x104);
    g_img[22].path = p;
    strcpy(p, "images\\\\snow.bmp");
    p = (char *)operator new(0x104);
    g_img[23].path = p;
    strcpy(p, "images\\\\sunweth.bmp");
    p = (char *)operator new(0x104);
    g_img[24].path = p;
    strcpy(p, "images\\\\drytire.bmp");
    p = (char *)operator new(0x104);
    g_img[25].path = p;
    strcpy(p, "images\\\\medtire.bmp");
    p = (char *)operator new(0x104);
    g_img[26].path = p;
    strcpy(p, "images\\\\wettire.bmp");
    p = (char *)operator new(0x104);
    g_img[27].path = p;
    strcpy(p, "images\\\\trakd.bmp");
    p = (char *)operator new(0x104);
    g_img[28].path = p;
    strcpy(p, "images\\\\trake.bmp");
    p = (char *)operator new(0x104);
    g_img[29].path = p;
    strcpy(p, "images\\\\ashft.bmp");
    p = (char *)operator new(0x104);
    g_img[30].path = p;
    strcpy(p, "images\\\\carTR.bmp");
    p = (char *)operator new(0x104);
    g_img[31].path = p;
    strcpy(p, "images\\\\carCE.bmp");
    p = (char *)operator new(0x104);
    g_img[32].path = p;
    strcpy(p, "images\\\\carCU.bmp");
    p = (char *)operator new(0x104);
    g_img[33].path = p;
    strcpy(p, "images\\\\carES.bmp");
    p = (char *)operator new(0x104);
    g_img[34].path = p;
    strcpy(p, "images\\\\carFH.bmp");
    p = (char *)operator new(0x104);
    g_img[35].path = p;
    strcpy(p, "images\\\\carIP.bmp");
    p = (char *)operator new(0x104);
    g_img[36].path = p;
    strcpy(p, "images\\\\carLD.bmp");
    p = (char *)operator new(0x104);
    g_img[37].path = p;
    strcpy(p, "images\\\\carM3.bmp");
    p = (char *)operator new(0x104);
    g_img[38].path = p;
    strcpy(p, "images\\\\carMN.bmp");
    p = (char *)operator new(0x104);
    g_img[39].path = p;
    strcpy(p, "images\\\\carNS.bmp");
    p = (char *)operator new(0x104);
    g_img[40].path = p;
    strcpy(p, "images\\\\carPJ.bmp");
    p = (char *)operator new(0x104);
    g_img[41].path = p;
    strcpy(p, "images\\\\carPS.bmp");
    p = (char *)operator new(0x104);
    g_img[42].path = p;
    strcpy(p, "images\\\\carRS.bmp");
    p = (char *)operator new(0x104);
    g_img[43].path = p;
    strcpy(p, "images\\\\carSP.bmp");
    p = (char *)operator new(0x104);
    g_img[44].path = p;
    strcpy(p, "images\\\\carBB.bmp");
    p = (char *)operator new(0x104);
    g_img[45].path = p;
    strcpy(p, "images\\\\arrowdd.bmp");
    p = (char *)operator new(0x104);
    g_img[46].path = p;
    strcpy(p, "images\\\\arrowdu.bmp");
    p = (char *)operator new(0x104);
    g_img[47].path = p;
    strcpy(p, "images\\\\arrowud.bmp");
    p = (char *)operator new(0x104);
    g_img[48].path = p;
    strcpy(p, "images\\\\arrowuu.bmp");
    p = (char *)operator new(0x104);
    g_img[49].path = p;
    strcpy(p, "images\\\\joystk.bmp");
    p = (char *)operator new(0x104);
    g_img[50].path = p;
    strcpy(p, "images\\\\keybd.bmp");
    p = (char *)operator new(0x104);
    g_img[51].path = p;
    strcpy(p, "images\\\\steerinp.bmp");
    p = (char *)operator new(0x104);
    g_img[52].path = p;
    strcpy(p, "images\\\\type_yel.bmp");
    p = (char *)operator new(0x104);
    g_img[53].path = p;
    strcpy(p, "images\\\\steerarr.bmp");
    p = (char *)operator new(0x104);
    g_img[54].path = p;
    strcpy(p, "images\\\\steeradj.bmp");
    p = (char *)operator new(0x104);
    g_img[55].path = p;
    strcpy(p, "images\\\\spkr.bmp");
    p = (char *)operator new(0x104);
    g_img[56].path = p;
    strcpy(p, "images\\\\monitr.bmp");
    p = (char *)operator new(0x104);
    g_img[57].path = p;
    strcpy(p, "images\\\\namebar.bmp");
    p = (char *)operator new(0x104);
    g_img[58].path = p;
    strcpy(p, "images\\\\slidebox.bmp");
    p = (char *)operator new(0x104);
    g_img[59].path = p;
    strcpy(p, "images\\\\boxtile2.bmp");
    p = (char *)operator new(0x104);
    g_img[60].path = p;
    strcpy(p, "images\\\\rboxend.bmp");
    p = (char *)operator new(0x104);
    g_img[61].path = p;
    strcpy(p, "images\\\\lboxend.bmp");
    p = (char *)operator new(0x104);
    g_img[62].path = p;
    strcpy(p, "images\\\\trakc_.bmp");
    p = (char *)operator new(0x104);
    g_img[63].path = p;
    strcpy(p, "images\\\\trakd_.bmp");
    p = (char *)operator new(0x104);
    g_img[64].path = p;
    strcpy(p, "images\\\\trake_.bmp");
    p = (char *)operator new(0x104);
    g_img[65].path = p;
    strcpy(p, "images\\\\desrttr_.bmp");
    p = (char *)operator new(0x104);
    g_img[66].path = p;
    strcpy(p, "images\\\\coasttr_.bmp");
    p = (char *)operator new(0x104);
    g_img[67].path = p;
    strcpy(p, "images\\\\mpmodem.bmp");
    p = (char *)operator new(0x104);
    g_img[68].path = p;
    strcpy(p, "images\\\\mptcpip.bmp");
    p = (char *)operator new(0x104);
    g_img[69].path = p;
    strcpy(p, "images\\\\mpipx.bmp");
    p = (char *)operator new(0x104);
    g_img[70].path = p;
    strcpy(p, "images\\\\mpserial.bmp");
    p = (char *)operator new(0x104);
    g_img[71].path = p;
    strcpy(p, "images\\\\seasn2a.bmp");
    p = (char *)operator new(0x104);
    g_img[72].path = p;
    strcpy(p, "images\\\\seasn2b.bmp");
    p = (char *)operator new(0x104);
    g_img[73].path = p;
    strcpy(p, "images\\\\seasn3a.bmp");
    p = (char *)operator new(0x104);
    g_img[74].path = p;
    strcpy(p, "images\\\\seasn3b.bmp");
    p = (char *)operator new(0x104);
    g_img[75].path = p;
    strcpy(p, "images\\\\seasn4a.bmp");
    p = (char *)operator new(0x104);
    g_img[76].path = p;
    strcpy(p, "images\\\\seasn4b.bmp");
    p = (char *)operator new(0x104);
    g_img[77].path = p;
    strcpy(p, "images\\\\seasn5a.bmp");
    p = (char *)operator new(0x104);
    g_img[78].path = p;
    strcpy(p, "images\\\\bgdim.bmp");
    p = (char *)operator new(0x104);
    g_img[79].path = p;
    strcpy(p, "images\\\\congrat.bmp");
    p = (char *)operator new(0x104);
    g_img[80].path = p;
    strcpy(p, "images\\\\noadv1.bmp");
    p = (char *)operator new(0x104);
    g_img[81].path = p;
    strcpy(p, "images\\\\noadv2.bmp");
    p = (char *)operator new(0x104);
    g_img[82].path = p;
    strcpy(p, "images\\\\but-main.bmp");
    p = (char *)operator new(0x104);
    g_img[83].path = p;
    strcpy(p, "images\\\\but-maind.bmp");
    p = (char *)operator new(0x104);
    g_img[84].path = p;
    strcpy(p, "images\\\\but-op.bmp");
    p = (char *)operator new(0x104);
    g_img[85].path = p;
    strcpy(p, "images\\\\but-opd.bmp");
    p = (char *)operator new(0x104);
    g_img[86].path = p;
    strcpy(p, "images\\\\cars1a.bmp");
    p = (char *)operator new(0x104);
    g_img[87].path = p;
    strcpy(p, "images\\\\cars2a.bmp");
    p = (char *)operator new(0x104);
    g_img[88].path = p;
    strcpy(p, "images\\\\cars2b.bmp");
    p = (char *)operator new(0x104);
    g_img[89].path = p;
    strcpy(p, "images\\\\cars3a.bmp");
    p = (char *)operator new(0x104);
    g_img[90].path = p;
    strcpy(p, "images\\\\cars3b.bmp");
    p = (char *)operator new(0x104);
    g_img[91].path = p;
    strcpy(p, "images\\\\cars4a.bmp");
    p = (char *)operator new(0x104);
    g_img[92].path = p;
    strcpy(p, "images\\\\cars4b.bmp");
    p = (char *)operator new(0x104);
    g_img[93].path = p;
    strcpy(p, "images\\\\cars5a.bmp");
    p = (char *)operator new(0x104);
    g_img[94].path = p;
    strcpy(p, "images\\\\cars5b.bmp");
    p = (char *)operator new(0x104);
    g_img[95].path = p;
    strcpy(p, "images\\\\chatbar2.bmp");
    p = (char *)operator new(0x104);
    g_img[96].path = p;
    strcpy(p, "images\\\\mousinpt.bmp");
    p = (char *)operator new(0x104);
    g_img[97].path = p;
    strcpy(p, "images\\\\ffstick.bmp");
    p = (char *)operator new(0x104);
    g_img[98].path = p;
    strcpy(p, "images\\\\carwnoshad2.bmp");
    p = (char *)operator new(0x104);
    g_img[99].path = p;
    strcpy(p, "images\\\\carwshad2.bmp");
    p = (char *)operator new(0x104);
    g_img[100].path = p;
    strcpy(p, "images\\\\specoff.bmp");
    p = (char *)operator new(0x104);
    g_img[101].path = p;
    strcpy(p, "images\\\\specon.bmp");
    p = (char *)operator new(0x104);
    g_img[102].path = p;
    strcpy(p, "images\\\\noffstik.bmp");
    p = (char *)operator new(0x104);
    g_img[103].path = p;
    strcpy(p, "images\\\\listbox.bmp");
    p = (char *)operator new(0x104);
    g_img[104].path = p;
    strcpy(p, "images\\\\engsound.bmp");
    p = (char *)operator new(0x104);
    g_img[105].path = p;
    strcpy(p, "images\\\\music.bmp");
    p = (char *)operator new(0x104);
    g_img[106].path = p;
    strcpy(p, "images\\\\soundtik.bmp");
    p = (char *)operator new(0x104);
    g_img[107].path = p;
    strcpy(p, "images\\\\soundptr.bmp");
    p = (char *)operator new(0x104);
    g_img[108].path = p;
    strcpy(p, "images\\\\trrwd.bmp");
    p = (char *)operator new(0x104);
    g_img[109].path = p;
    strcpy(p, "images\\\\pjrwd.bmp");
    p = (char *)operator new(0x104);
    g_img[110].path = p;
    strcpy(p, "images\\\\mnrwd.bmp");
    p = (char *)operator new(0x104);
    g_img[111].path = p;
    strcpy(p, "images\\\\mirrwd.bmp");
    p = (char *)operator new(0x104);
    g_img[112].path = p;
    strcpy(p, "images\\\\bbrwd.bmp");
    p = (char *)operator new(0x104);
    g_img[113].path = p;
    strcpy(p, "images\\\\curwd.bmp");
    p = (char *)operator new(0x104);
    g_img[114].path = p;
    strcpy(p, "images\\\\fbrwd.bmp");
    p = (char *)operator new(0x104);
    g_img[115].path = p;
    strcpy(p, "images\\\\mtrwd.bmp");
    p = (char *)operator new(0x104);
    g_img[116].path = p;
    strcpy(p, "images\\\\sndlevl2.bmp");
    p = (char *)operator new(0x104);
    g_img[117].path = p;
    strcpy(p, "images\\\\sndlevl3.bmp");
    p = (char *)operator new(0x104);
    g_img[118].path = p;
    strcpy(p, "images\\\\trakraceb.bmp");
    p = (char *)operator new(0x104);
    g_img[119].path = p;
    strcpy(p, "images\\\\trakracel.bmp");
    p = (char *)operator new(0x104);
    g_img[120].path = p;
    strcpy(p, "images\\\\but-sav.bmp");
    p = (char *)operator new(0x104);
    g_img[121].path = p;
    strcpy(p, "images\\\\but-savd.bmp");
    p = (char *)operator new(0x104);
    g_img[122].path = p;
    strcpy(p, "images\\\\z-carMT.bmp");
    p = (char *)operator new(0x104);
    g_img[123].path = p;
    strcpy(p, "images\\\\z-carTR.bmp");
    p = (char *)operator new(0x104);
    g_img[124].path = p;
    strcpy(p, "images\\\\z-carCE.bmp");
    p = (char *)operator new(0x104);
    g_img[125].path = p;
    strcpy(p, "images\\\\z-carCU.bmp");
    p = (char *)operator new(0x104);
    g_img[126].path = p;
    strcpy(p, "images\\\\z-carES.bmp");
    p = (char *)operator new(0x104);
    g_img[127].path = p;
    strcpy(p, "images\\\\z-carFH.bmp");
    p = (char *)operator new(0x104);
    g_img[128].path = p;
    strcpy(p, "images\\\\z-carIP.bmp");
    p = (char *)operator new(0x104);
    g_img[129].path = p;
    strcpy(p, "images\\\\z-carLD.bmp");
    p = (char *)operator new(0x104);
    g_img[130].path = p;
    strcpy(p, "images\\\\z-carM3.bmp");
    p = (char *)operator new(0x104);
    g_img[131].path = p;
    strcpy(p, "images\\\\z-carMN.bmp");
    p = (char *)operator new(0x104);
    g_img[132].path = p;
    strcpy(p, "images\\\\z-carNS.bmp");
    p = (char *)operator new(0x104);
    g_img[133].path = p;
    strcpy(p, "images\\\\z-carPJ.bmp");
    p = (char *)operator new(0x104);
    g_img[134].path = p;
    strcpy(p, "images\\\\z-carPS.bmp");
    p = (char *)operator new(0x104);
    g_img[135].path = p;
    strcpy(p, "images\\\\z-carRS.bmp");
    p = (char *)operator new(0x104);
    g_img[136].path = p;
    strcpy(p, "images\\\\z-carSP.bmp");
    p = (char *)operator new(0x104);
    g_img[137].path = p;
    strcpy(p, "images\\\\z-carBB.bmp");
    p = (char *)operator new(0x104);
    g_img[138].path = p;
    strcpy(p, "images\\\\lightr.bmp");
    p = (char *)operator new(0x104);
    g_img[139].path = p;
    strcpy(p, "images\\\\lightg.bmp");
    p = (char *)operator new(0x104);
    g_img[140].path = p;
    strcpy(p, "images\\\\tire2on.bmp");
    p = (char *)operator new(0x104);
    g_img[141].path = p;
    strcpy(p, "images\\\\tire2off.bmp");
    p = (char *)operator new(0x104);
    g_img[142].path = p;
    strcpy(p, "images\\\\listbox2.bmp");
    p = (char *)operator new(0x104);
    g_img[143].path = p;
    strcpy(p, "images\\\\trakQ.bmp");
    p = (char *)operator new(0x104);
    g_img[144].path = p;
    strcpy(p, "images\\\\trakQ_.bmp");

    n = 0xB4;
    q = g_rec;
    for (; n != 0; n--) {
        *q++ = -1;
    }
    n = 0x64;
    q = g_zero;
    for (; n != 0; n--) {
        *q++ = 0;
    }
    q = (int *)((char *)g_rec + 8);
    do {
        *q = 0;
        q += 3;
    } while ((int)q < (int)((char *)g_rec + 0x2D8));

    ph = new Phase;
    g_phaseRoot = ph;
    g_phaseCur = ph;
    if (ph == 0) {
        return 0;
    }
    ph->pfnEnter = (void *)PhaseEnter;

    if (g_obj400 == 0) {
        ob = new Obj400;
        g_obj400 = ob;
        if (ob == 0) {
            ErrShow(1);
        }
    }

    strcpy(g_season, "c:\\RallySeason.dat");
    strcpy(g_ghost, "c:\\RallyGhost.dat");
    RectTablesInit();
    return 1;
}
