#include "br_phase.h"   /* BrPhase_, the canonical record */
/* WHAT IT DOES: release every control on every page this phase owns -- 200
 * slots per page, cleared and nulled. */
/* @implements 0x10041ED0 glide BrPhaseReleasePages_10048AA0
 * @cpp_kind method
 * @cpp_symbol ?ReleasePages@Phase32P@@QAEXXZ
 *
 * 119 B thiscall, void. Outer loop over the +0x14 page array (this and i
 * spilled -- sub esp,8), inner countdown over the page's 200 member
 * pointers at +0x18: delete (slot-0 scalar-deleting vcall, flag 1) and
 * zero each, then delete the page itself. Word global cleared at the end.
 */
class PageMember {
public:
    virtual ~PageMember();
};

class Page {
public:
    virtual ~Page();
    char pad[0x14];             /* +0x04 */
    PageMember *m[200];         /* +0x18 */
};

class Phase32P {
public:
    virtual void v0();
    char pad04[0xC];            /* +0x04 */
    unsigned short f10;         /* +0x10 */
    unsigned short f12;         /* +0x12 */
    Page *a14[20];              /* +0x14 */
    void ReleasePages();
};

extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
}

void Phase32P::ReleasePages()
{
    int i;

    for (i = 0; i < (*(unsigned short *)&((BrPhase_ *)(this))->nPages); ++i) {
        Page *p = (*(Page * (*)[20])&((BrPhase_ *)(this))->aPages)[i];
        int k;

        for (k = 0; k < 200; ++k) {
            delete (*(PageMember * (*)[200])&((BrPhase_ *)(p))->aPages[1])[k];
            (*(PageMember * (*)[200])&((BrPhase_ *)(p))->aPages[1])[k] = 0;
        }
        delete p;
    }
    (*(unsigned short *)&BrGlNavCur5BC4) = 0;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" void BrPhaseReleasePages_10048AA0(void *self)
{
    ((class Phase32P *)self)->ReleasePages();
}
/* end of C entry points */
