#include "slice2_25.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
#include "slice3_42.h"   /* br_globals: its objects */
/* WHAT IT DOES: run the phase to completion: on the first pass it saves the
 * control configuration and restarts, and afterwards it steps normally. This
 * is what makes the settings page persist a change before acting on it. */
/* @implements 0x10041DD0 glide BrPhaseRun_100489A0
 * @cpp_kind method
 * @cpp_symbol ?Run@BrPhase41@@QAEHXZ
 *
 * Phase step driver: thiscall on the phase object (`mov esi,ecx`), returns
 * int, no stack args.  Head and tail both take the "phase finished" exit:
 * FUN_10037920, the CtrlCfg save (thiscall on the 0x10B71290 object with
 * the pushed 0x10B72F48 path), idx=0, then the +0x18 vcall with a pushed 0
 * (EAX-pattern head, tail reuses the vtbl CSEd into edi across the +8
 * call).  The middle swaps g_cur to g_next around the 0x100592D0 thiscall
 * on *(0x10AC5C58), latches g_AC5BC0 = (cur==next), and walks the item
 * table: items[] at +0x14, flags[] at +0x6C, cur at +0x64, count/idx are
 * 16-bit at +0x10/+0x12; the per-item vcall is slot +4 on a re-read of
 * this->cur (EDX pattern).  No EH (no new).
 */
#define _CRTIMP __declspec(dllimport)

class BrPhaseItem41 {
public:
    virtual int i0();
    virtual int i1();          /* slot +4, the per-item poll */
};

class BrCtrlCfg41 {
public:
    void Save(void *pPath);    /* 0x100634B0 BrGlCfgSave */
};

class BrPhase41 {
public:
    virtual int s0();
    virtual int s1();          /* +0x04 */
    virtual int s2();          /* +0x08 */
    virtual int s3();
    virtual int s4();
    virtual int s5();
    virtual int f18(void *);   /* +0x18, callee pops the one arg */

    char            pad04[0x10 - 4];
    unsigned short  count;     /* +0x10 */
    unsigned short  idx;       /* +0x12 */
    BrPhaseItem41  *items[20]; /* +0x14 */
    BrPhaseItem41  *cur;       /* +0x64 */
    int             done;      /* +0x68 */
    int             flags[1];  /* +0x6C.. */

    int  Run();
    void Hand();               /* 0x100592D0, non-virtual thiscall */
};

extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* FUN_10037920: prototype in br_funcs.h */
/* BrDikPollAndEdge: prototype in br_funcs.h */
}

/* 64-bit core: declared once, in br_globals.h or its struct's header */      /* 0x10B71290 */

int BrPhase41::Run()
{
    int i;

    if ((*(int *)&((BrPhase_ *)(this))->f68) == 0) {
        BrOptSave();
        (*(BrCtrlCfg41 *)&g_BrCtrlCfg).Save(&g_navArg);
        (*(unsigned short *)&((BrPhase_ *)(this))->iPage) = 0;
        this->f18(0);
        return 0;
    }

    this->s1();

    {
        BrPhase41 *pSave = (*(BrPhase41 * *)&g_brPAA29B8);
        (*(BrPhase41 * *)&g_brPAA29B8) = (BrPhase41 *)((BrOptObj *)((*(BrPhase41 * *)&g_2908)));
        (*(BrPhase41 * *)&g_obj400)->Hand();
        (*(BrPhase41 * *)&g_brPAA29B8) = (BrPhase41 *)((BrOptObj *)((struct Ph *)((BrOptObj *)(pSave))));
    }

    BrDikPollAndEdge();
    g_bc0 = ((*(BrPhase41 * *)&g_brPAA29B8) == (*(BrPhase41 * *)&g_2908));

    (*(unsigned short *)&((BrPhase_ *)(this))->iPage) = 0;
    for (i = 0; i < (*(unsigned short *)&((BrPhase_ *)(this))->nPages); i++) {
        (*(BrPhaseItem41 * *)&((BrPhase_ *)(this))->pCur) = (*(BrPhaseItem41 * (*)[20])&((BrPhase_ *)(this))->aPages)[i];
        if ((*(BrPhaseItem41 * *)&((BrPhase_ *)(this))->pCur) == 0) {
            return 0;
        }
        (*(unsigned short *)&((BrPhase_ *)(this))->iPage) = (unsigned short)i;
        if ((*(int (*)[1])&((BrPhase_ *)(this))->aFlags[0])[i] != 0) {
            if ((*(BrPhaseItem41 * *)&((BrPhase_ *)(this))->pCur)->i1() == 0) {
                return 0;
            }
        }
    }

    this->s2();

    if ((*(int *)&((BrPhase_ *)(this))->f68) == 0) {
        BrOptSave();
        (*(BrCtrlCfg41 *)&g_BrCtrlCfg).Save(&g_navArg);
        (*(unsigned short *)&((BrPhase_ *)(this))->iPage) = 0;
        this->f18(0);
        return 0;
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int BrPhaseRun_100489A0(void *self)
{
    return ((class BrPhase41 *)self)->Run();
}
/* end of C entry points */
