#include "slice2_25.h"   /* br_globals: its objects */
#include "br_ui.h"   /* BrUiPage_, the canonical record */
#include "br_phase.h"   /* BrPhase_, the canonical record */
#include "slice3_39.h"   /* br_globals: its objects */
/* WHAT IT DOES: tick a phase, deciding on this frame whether its periodic
 * work is due -- every frame in one mode, and otherwise once every 120
 * ticks. */
/* @implements 0x10041D10 glide BrPhaseTick_100488C0
 * @cpp_kind method
 * @cpp_symbol ?Tick@Phase32T@@QAEHXZ
 *
 * 160 B thiscall, no stack args. Early-out on flag 0x10; a 120-frame
 * cadence gate (idiv, memory inc); CD-track capture minus 2; then the
 * current-object swap around a slot-3 vcall, and a guarded slot-5
 * self-vcall. All state loose globals.
 */
struct BrTickPair { int i0; int i4; };

class PhaseInner {
public:
    virtual void s0();
    virtual void s1();
    virtual void s2();
    virtual void s3();          /* +0x0C */
    char pad[0x38];
    float f3C;                  /* +0x3C */
    float f40;                  /* +0x40 */
};

class PhaseHolder2 {
public:
    char pad[0x334];
    PhaseInner *p334;           /* +0x334 */
};

class PhaseHolder {
public:
    char pad[0x14];
    PhaseHolder2 *f14;          /* +0x14 */
};

class Phase32T {
public:
    virtual void v0();
    virtual void v1();
    virtual void v2();
    virtual void v3();
    virtual void v4();
    virtual void v5();          /* +0x14 */
    int f04;
    int f08;                    /* +0x08 */
    int Tick();
};

extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* BrCdTrackGet: prototype in br_funcs.h */
}

int Phase32T::Tick()
{
    if (f08 & 0x10)
        return 0;

    int go = 0;
    if (DAT_1007b074 == 2) {
        go = 1;
    } else {
        if (DAT_10ac5da4 % 0x78 == 0)
            go = 1;
        DAT_10ac5da4 = DAT_10ac5da4 + 1;
    }
    if (go)
        g_5D8C = BrCdTrackGet() - 2;

    PhaseHolder *pSaved = (*(PhaseHolder * *)&g_brPAA29B8);
    PhaseHolder *pCur   = (*(PhaseHolder * *)&g_2908);
    (*(PhaseHolder * *)&g_brPAA29B8) = (PhaseHolder *)((BrOptObj *)(pCur));
    PhaseInner *p = (*(PhaseInner * *)&((BrUiPage_ *)((*(PhaseHolder2 * *)&((BrPhase_ *)(pCur))->aPages[0])))->apCtl[199]);
    /* the cursor control follows the mouse: its x and y (+0x3C/+0x40 on
     * i386; 64-bit core: the canonical record's fields, which sit further in) */
    ((BrUiCtl_ *)(void *)p)->x = (float)(*(BrTickPair * *)&g_pBrAA2E80)->i0;
    ((BrUiCtl_ *)(void *)p)->y = (float)(*(BrTickPair * *)&g_pBrAA2E80)->i4;
    p->s3();
    (*(PhaseHolder * *)&g_brPAA29B8) = (PhaseHolder *)((BrOptObj *)(pSaved));
    if (DAT_10ac5bcc == 0)
        v5();
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int BrPhaseTick_100488C0(void *self)
{
    return ((class Phase32T *)self)->Tick();
}
/* end of C entry points */
