/* WHAT IT DOES: poll one save slot: refresh it, and return without doing
 * anything more if the slot is empty. */
/* @implements 0x100549A0 glide BrSlotPoll_100549A0
 * @cpp_kind method
 * @cpp_symbol ?Poll@Slots549A0@@QAEHH@Z
 *
 * Thiscall, one stack arg (`ret 4`), 132 B. Same object as
 * 0x10054E20: the 0x438-stride slot array based at `this + 0x2C`, so
 * the record pointer is `this + idx*0x438` with 0x2C folded into every
 * displacement. Tick the record's own object (its +0x04 vcall), and if
 * the record's +0x420 "busy" word is set, ask it for a result with the
 * +0x14 vcall; a positive result means keep waiting. Zero or negative
 * clears the busy word and the shared global, then hands the owner's
 * +0x14 callback either the slot index (result 0) or -1 (negative).
 * Returns 0 only when the record was not busy.
 *
 * The zero is materialised once (`xor edx,edx`) and serves both stores
 * and all three comparisons, which is why the null test on the callback
 * reads `cmp eax,edx` and not `test eax,eax`.
 */
#define _CRTIMP __declspec(dllimport)
#include "slice3_39.h"   /* BrTextList */

class Rec549A0 {
public:
    virtual void s0();
    virtual void s1();          /* +0x04 -- tick */
    virtual void s2();
    virtual void s3();
    virtual void s4();
    virtual char s5();          /* +0x14 -- result */
};

typedef int (*BrFn549A0)(void *pObj, int idx);

class Slots549A0 {
public:
    int Poll(int idx);
};



extern "C" {
/* 64-bit core: g_brAA28D8 is defined once, in br_globals.c */
}

/* the 0x438-stride rows at +0x2C are the list's aItems; +0x14 is its f14 */
int Slots549A0::Poll(int idx)
{
    BrTextList *pList = (BrTextList *)this;
    BrTextBox *pBox = &pList->aItems[idx];
    Rec549A0 *pRec = (Rec549A0 *)pBox;
    BrFn549A0 pfn = (BrFn549A0)pList->f14;
    int c;

    pRec->s1();

    if (pBox->f420 == 0)
        return 0;

    c = pRec->s5();

    if (c <= 0) {
        g_5C30 = 0;
        pBox->f420 = 0;

        if (pfn != 0) {
            if (c >= 0)
                pfn(this, idx);
            else
                pfn(this, -1);
        }
    }

    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int BrSlotPoll_100549A0(void *self, int idx)
{
    return ((class Slots549A0 *)self)->Poll(idx);
}
/* end of C entry points */
