/* WHAT IT DOES: wrap the page's selection index back into range, at both
 * ends, so moving past the last entry lands on the first. */
/* @implements 0x10041940 glide BrUiPageSelect_100484F0
 * @cpp_kind method
 * @cpp_symbol ?Adv@Phase32F@@QAEHXZ
 *
 * 64 B frameless thiscall: the Adv() the 0x10041980 Frame twin calls.
 * The limit word is read into a register var FIRST (dx, zero-extended
 * with and 0xffff at the compare); the paced counter is DIRECT REREADS
 * of the global (a short local spills and grows a frame: the
 * direct-global-reread idiom), CSEd into ax across the branches;
 * wrap-to-0 vs clamp-to-lim-1 share the cross-jumped word store, then
 * w346 latches the forwarded value.
 */
class Phase32F {
public:
    char pad[0x344];
    unsigned short w344;            /* +0x344 */
    short w346;                     /* +0x346 */
    int Adv();
};

extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
}

int Phase32F::Adv()
{
    unsigned short lim;

    lim = w344;
    if ((short)(*(unsigned short *)&BrGlNavCur5BC4) >= lim) {
        (*(unsigned short *)&BrGlNavCur5BC4) = 0;
    } else if ((short)(*(unsigned short *)&BrGlNavCur5BC4) < 0) {
        (*(unsigned short *)&BrGlNavCur5BC4) = (unsigned short)(lim - 1);
    }
    w346 = (short)(*(unsigned short *)&BrGlNavCur5BC4);
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int BrUiPageSelect_100484F0(void *self)
{
    return ((class Phase32F *)self)->Adv();
}
/* end of C entry points */
