#include "br_uispr.h"   /* br_globals: its objects */
/* WHAT IT DOES: draw the code-entry row currently selected, using that row's
 * stored rectangle and colour. Draws nothing when no row is selected. */
/* @implements 0x10040D80 glide BrUiDrawCode_10047930
 * @cpp_kind method
 * @cpp_symbol ?Draw@Draw40D80@@QAEHXZ
 *
 * Thiscall, no args (`ret`), 79 B. Draw the current code row, taking the
 * label, the rectangle and the trailing field all from the row's entry in
 * the 24-byte table at 0x100AAD08. A negative row number draws nothing.
 * Returns 1 either way.
 *
 * The port body in slice3_32.c takes a globals-struct pointer it does not
 * need; the original is a bare thiscall. Same split as the siblings.
 *
 * The row's own short reaches the callee via the SHORT PUSH; the two
 * `(int)` casts are `call __ftol`.
 */
#define _CRTIMP __declspec(dllimport)

struct BrRow40D80 {
    short w00;                  /* +0x00 */
    short pad02;
    int   a04[4];               /* +0x04 */
    int   f14;                  /* +0x14 */
};                              /* 24 -- base 0x100AAD08 */

class Draw40D80 {
public:
    char  pad000[0x3C];
    float f03C;                 /* +0x03C */
    float f040;                 /* +0x040 */
    char  pad044[0x1E20C - 0x44];
    short w1E20C;               /* +0x1E20C */

    int Draw();
};

typedef char chk_f03C_40D80[(unsigned)&((Draw40D80 *)0)->f03C == 0x3C ? 1 : -1];
typedef char chk_w_40D80[(unsigned)&((Draw40D80 *)0)->w1E20C == 0x1E20C ? 1 : -1];

extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* BrDraw10058380: prototype in br_funcs.h */
}

int Draw40D80::Draw()
{
    if (w1E20C >= 0) {
        BrDraw10058380((int)f03C, (int)f040, (*(short *)&g_aBrUiSprite[w1E20C].iImage),
                       (*(int (*)[4])&g_aBrUiSprite[w1E20C].rect[0]),
                       g_aBrUiSprite[w1E20C].fBlit);
    }

    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int BrUiDrawCode_10047930(void *self)
{
    return ((class Draw40D80 *)self)->Draw();
}
/* end of C entry points */
