/* WHAT IT DOES: brings the front menu screen up. The first time through it
 * builds the screen -- creating the underlying dialog (a failure puts up
 * message 0xAB and exits the game), running the screen's own enter hook and
 * marking it built. Every time, it then reacts to how the game got here:
 * back from a race it clears the race scratch, finishing race setup it
 * re-opens the main page, and the "just finished" and "quit to menu" paths
 * each open their own follow-up screen. Finally the one-shot post-join
 * screen is opened if the network flag asks for it. */
/* @implements 0x10053D20 glide BrUiFrontActivate
 * @cpp_kind method
 * @cpp_symbol ?Activate@Phase53D20@@QAEHXZ
 *
 * Thiscall, no args (`ret`), 305 B. The phase object's +4 is a CDECL
 * function-pointer field (push esi; call [esi+4]), not a vtable slot.
 * The dialog Create is a true thiscall with one stack arg
 * (`mov ecx,[0x10AC5C58]; push hwnd`), which is what routes this body to
 * the C++ lane. ebx/ebp are the 0/1 constant webs.
 */
#define _CRTIMP __declspec(dllimport)
#include "br_coretypes.h"   /* br_globals: its objects */
#include "br_race.h"   /* br_globals: its objects */
#include <stdlib.h>
#include <string.h>

class BrDlg53 {
public:
    int Create(void *hwnd);          /* 0x10059280 */
};

class Phase53D20;
extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* FUN_100379b0: prototype in br_funcs.h */
/* FUN_100583c0: prototype in br_funcs.h */
/* BrStrGet: prototype in br_funcs.h */
/* BrMsgBoxAA: prototype in br_funcs.h */
/* FUN_10058680: prototype in br_funcs.h */
/* BrPhaseActivate_10045EA0: prototype in br_funcs.h */
/* BrMenuAutoSaveName: prototype in br_funcs.h */
/* BrPhaseActivate_100447D0: prototype in br_funcs.h */
/* BrMenuLeaveTo2: prototype in br_funcs.h */
/* BrOpt41A0: prototype in br_funcs.h */
}

class Phase53D20 {
public:
    int   f00;
    int (__cdecl *pfnEnter)(Phase53D20 *);   /* +0x04 */
    int   f08;
    int   fBuilt;                            /* +0x0C */
    char  pad10[0x68 - 0x10];
    int   f68;                               /* +0x68 */

    int Activate();
};





int Phase53D20::Activate()
{
    int m;

    BrSub1003E3A0();
    if (fBuilt == 0) {
        FUN_100583c0();
        if ((*(BrDlg53 * *)&g_obj400)->Create((*(void * *)&g_brOwner5BC72C)) == 0) {
            BrMsgBoxAA((*(void * *)&g_brOwner5BC72C), 0, BrStrGet(0xAB));
            exit(1);
        }
        pfnEnter(this);
        fBuilt = 1;
        f68    = 1;
    }

    m = (*(int *)&g_a220B20);
    if (m == 5) {
        g_brIdx5BFC = 0;
        memset((*(int (*)[8])&DAT_10ac46a0), 0, 0x20);
        (*(unsigned char *)&g_aBrAA26F4[1]) = 0;
    }

    if ((*(int *)&g_brRaceRules.mode) == 4 && g_5bc760 == 2 && g_5BF4 != 0) {
        CtlF340_fn();
        (*(int *)&g_brRaceRules.mode) = 0;
        m = (*(int *)&g_a220B20);
    }

    if ((*(int *)&g_brRaceRules.mode) == 0 && (m == 0 || m == 5)) {
        if (BrSeasonApply() == 0) {
            return 0;
        }
        CtlF340_fn();
        BrMenuAutoSaveName();
        g_5BF4 = 1;
    } else if ((*(int *)&g_brRaceRules.mode) == 6) {
        DAT_10ac5bd0 = 1;
        Fn3DD20();
        DAT_10ac5bd0 = 0;
    } else if ((*(int *)&g_brRaceRules.mode) == 2) {
        DAT_10ac5bd0 = 1;
        BrMenuLeaveTo2();
        DAT_10ac5bd0 = 0;
    }

    if (g_guardB != 0 && DAT_10ac5da8 == 0) {
        DAT_10ac5da8 = 1;
        BrOpt41A0();
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int BrUiFrontActivate(void *self)
{
    return ((class Phase53D20 *)self)->Activate();
}
/* end of C entry points */
