#include "slice3_39.h"   /* br_globals: its objects */
/* WHAT IT DOES: test whether the mouse is inside a rectangle, with an extra
 * condition for controls flagged as needing it. The hit test behind mouse-
 * driven menus. */
/* @implements 0x10055330 glide BrUiHitTest_10055330
 * @cpp_kind method
 * @cpp_symbol ?HitTest@Ui55330@@QAEHPAURect55330@@@Z
 *
 * Thiscall, one stack arg (`ret 4`), 117 B. Point-in-rect against the
 * cursor at 0x10AC5DD8; miss returns 0 without touching state. On a hit,
 * the widget's +0x18 flag word gets bit 1 set or cleared depending on
 * which "is something else grabbing input" test applies -- the 0x40000
 * flag picks between the two windows at 0x10AC61E0 (+0x2C / +0x30) and
 * the 0x10037720 helper -- and bit 5 is set unconditionally afterwards.
 *
 * The flag word is stored TWICE (`mov [esi+0x18],eax; or al,0x20; mov
 * [esi+0x18],eax`) because the arms each write it and the `| 0x20` is a
 * separate statement on the member; VC5 tail-merges the three arms onto
 * one store and keeps the value live for the second.
 */
#define _CRTIMP __declspec(dllimport)

struct Rect55330 {
    int x0;     /* +0x00 */
    int y0;     /* +0x04 */
    int x1;     /* +0x08 */
    int y1;     /* +0x0C */
};

struct Point55330 {
    int x;
    int y;
};

struct Grab55330 {
    char pad[0x2C];
    int  f2C;
    int  f30;
};

class Ui55330 {
public:
    char pad[0x18];
    int  f18;       /* +0x18 -- flag word */

    int HitTest(Rect55330 *pRect);
};

typedef char chk_f18[(unsigned)&((Ui55330 *)0)->f18 == 0x18 ? 1 : -1];

extern "C" {
/* 64-bit core: g_AC5DD8 is defined once, in br_globals.c */
/* 64-bit core: g_AC61E0 is defined once, in br_globals.c */
/* Fn10037720: prototype in br_funcs.h */
}

int Ui55330::HitTest(Rect55330 *pRect)
{
    if (pRect->x0 > (*(Point55330 * *)&BrGlNavThis5DD8)->x || pRect->x1 < (*(Point55330 * *)&BrGlNavThis5DD8)->x ||
        pRect->y0 > (*(Point55330 * *)&BrGlNavThis5DD8)->y || pRect->y1 < (*(Point55330 * *)&BrGlNavThis5DD8)->y)
        return 0;

    if (f18 & 0x40000) {
        if ((*(Grab55330 * *)&g_pBrAA2E80)->f2C != 0 || (*(Grab55330 * *)&g_pBrAA2E80)->f30 != 0)
            f18 |= 0x80002;
        else
            f18 &= ~2;
    } else if (BrInputAnyActive() != 0) {
        f18 |= 2;
    } else {
        f18 &= ~2;
    }

    f18 |= 0x20;
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int BrUiHitTest_10055330(void *self, Rect55330 * pRect)
{
    return ((class Ui55330 *)self)->HitTest(pRect);
}
/* end of C entry points */
