#include "slice2_25.h"   /* br_globals: its objects */
#include "slice3_41.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and
 * this one copies two values into the page's inputs before opening, so the
 * page starts on the caller's selection. */
/* @implements 0x1003E370 glide Ctl3E370
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3E370@@QAEHXZ
 *
 * Same shared-return activate as the 201 B family, plus two global copies
 * before the slot test (orig 223 B). Do not name temps for the copies:
 * `int t0 = src` keeps eax/ecx live and flips the post-call flag stores
 * from `mov edx,[g_cur]` / c7 to the 201 B eax/ecx coloring (18 diffs).
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};






/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot DAT_10ac5cc0
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls FUN_10053590 (?FUN_10053590@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* FUN_10053590: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))FUN_10053590)

class Ctl3E370 {
public:
    int Activate();
};

int Ctl3E370::Activate()
{
    Phase *p;

    g_dst1 = g_src1;
    p = g_slot;
    g_dst2 = g_src2;
    if (p == 0) {
        p = new Phase;
        g_slot = p;
        g_cur = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        p->pfnEnter = EnterFn;
        g_slot->pfnEnter(g_slot);
        g_cur->f0C = 1;
        g_cur->f68 = 1;
    } else {
        g_cur = (Phase *)((BrOptObj *)(p));
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3E370_fn(void *self)
{
    return ((class Ctl3E370 *)self)->Activate();
}
/* end of C entry points */
