#include "slice2_25.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and it
 * opens ONLY if the CD check passes -- this is a page whose content lives on
 * the disc. */
/* @implements 0x1003ED90 glide Ctl3ED90
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3ED90@@QAEHXZ
 *
 * CD-gated installer (slice3_31 BrPhaseActivate_10045900). Polarity is
/* CdCheck: the original function is FUN_1003ee90 */ fail; return 0` so the large
 * path is fall-through (orig `je` far to the fail block at the end).
/* CdCheck: the original function is FUN_1003ee90 */ success` inverts to a short jne.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot DAT_10ac5c74
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls BrExt_1004F2B0 (?BrExt_1004F2B0@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrExt_1004F2B0: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrExt_1004F2B0)
/* CdCheck: prototype in br_funcs.h */
/* GetStr: prototype in br_funcs.h */
/* ResetBuf: prototype in br_funcs.h */

class Ctl3ED90 {
public:
    int Activate();
};

int Ctl3ED90::Activate()
{
    Phase *p;

    if (CdCheck() != 0) {
        ResetBuf(&g_buf);
        p = g_slot;
        if (p == 0) {
            p = new Phase;
            g_slot = p;
            g_cur = p;
            if (p == 0)
                return 0;
            p->pfnEnter = EnterFn;
            g_slot->pfnEnter(g_slot);
            g_cur->f0C = 1;
            g_cur->f68 = 1;
        } else {
            g_cur = p;
        }
        return 1;
    }
    ResetBuf(GetStr(0xD));
    return 0;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3ED90_fn(void *self)
{
    return ((class Ctl3ED90 *)self)->Activate();
}
/* end of C entry points */
