#include "br_race.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
#include "slice2_25.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run. */
/* @implements 0x1003DC20 glide Ctl3DC20
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3DC20@@QAEHXZ
 *
 * Family-1 installer plus BrOptOpen2954 tail. First-time path returns 1
 * after HostGo so g_host stays live in eax across the g_inited test
 * (mov ecx,[g_inited], not a1). The inited path is a second `if (g_host)
 * HostGo()`: that is the orig `test eax; je` before the shared call.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot g_5CAC
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_mode (*(int *)&g_brRaceRules.mode)
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_kind DAT_10ac5bd4

/* EnterFn was a stand-in; the original calls FUN_10051600 (?FUN_10051600@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* FUN_10051600: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))FUN_10051600)
/* HostStart: prototype in br_funcs.h */
/* HostInit: prototype in br_funcs.h */
/* HostGo: prototype in br_funcs.h */

class Ctl3DC20 {
public:
    int Activate();
};

int Ctl3DC20::Activate()
{
    Phase *p;

    p = g_slot;
    if (p == 0) {
        p = ((Phase *)br_new_obj(sizeof(BrPhase_), (void *(*)(void *))BrOptObjCtor));
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = 1;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    g_mode = 6;
    if (g_host != 0) {
        if (g_inited == 0) {
            if (g_kind == 2 || g_kind == 3)
                BrTimerStart1003C230();
            BrSub1003C150();
            g_inited = 1;
            BrSub1003CDA0();
            return 1;
        }
    }
    if (g_host != 0)
        BrSub1003CDA0();
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3DC20_fn(void *self)
{
    return ((class Ctl3DC20 *)self)->Activate();
}
/* end of C entry points */
