#include "br_race.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
#include "slice2_25.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run. */
/* @implements 0x1003D3C0 glide Ctl3D3C0
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3D3C0@@QAEHXZ
 *
 * Family-1 installer plus a shared tail after both arms (slice2_25
 * BrOptOpen2948): if two guards are clear and the mode is 0 or 1, call
 * NetFn. return 1 AFTER that tail so the flag stores stay c7.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot (*(Phase * *)&g_2948)
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_mode DAT_10ac5bd4

/* EnterFn was a stand-in; the original calls FUN_1004fea0 (?FUN_1004fea0@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* FUN_1004fea0: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))FUN_1004fea0)
/* NetFn was a stand-in; the original calls C function FUN_100356b0.  Declared under
 * its real symbol so the relocation resolves by name. */
/* FUN_100356b0: prototype in br_funcs.h */
#define NetFn ((void (*)(void))FUN_100356b0)

class Ctl3D3C0 {
public:
    int Activate();
};

int Ctl3D3C0::Activate()
{
    Phase *p;

    p = (Phase *)(g_slot);
    if (p == 0) {
        p = ((Phase *)br_new_obj(sizeof(BrPhase_), (void *(*)(void *))BrOptObjCtor));
        g_slot = (Phase *)((struct Phase8 *)(p));
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = 1;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    if (g_guardA == 0 && g_guardB == 0 && (g_mode == 0 || g_mode == 1))
        NetFn();
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3D3C0_fn(void *self)
{
    return ((class Ctl3D3C0 *)self)->Activate();
}
/* end of C entry points */
