#include "slice2_25.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run. */
/* @implements 0x1003F410 glide Ctl3F410
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3F410@@QAEHXZ
 *
 * Two sequential `new Phase` (maxState=2, both toState=-1, both unwind
 * operator delete). Second allocation is only on the just-built path of
 * the first and writes only its own slot + f0C (no g_cur, no f68).
 *
 * Live local `one` plus a *shared* `return one` after the if/else is what
 * hoists `mov esi,1` into the flags gap (`test eax,eax; mov esi,1; jne`).
 * `return one` inside both arms rematerializes the existing path as
 * `mov eax,1` and delays esi=1 until after the first enter (82 diffs).
 * Ctor DECLARED, no dtor.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot g_5C90
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot2 DAT_10ac5cd0

/* EnterFn was a stand-in; the original calls FUN_1004cba0 (?FUN_1004cba0@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* FUN_1004cba0: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))FUN_1004cba0)
/* Enter2Fn was a stand-in; the original calls FUN_10043690 (?FUN_10043690@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* FUN_10043690: prototype in br_funcs.h */
#define Enter2Fn ((void (*)(Phase *))FUN_10043690)

class Ctl3F410 {
public:
    int Activate();
};

int Ctl3F410::Activate()
{
    Phase *p;
    Phase *q;
    int one;

    p = g_slot;
    one = 1;
    if (p == 0) {
        p = ((Phase *)br_new_obj(sizeof(Phase), (void *(*)(void *))BrOptObjCtor));
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = one;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = one;
        q = ((Phase *)br_new_obj(sizeof(Phase), (void *(*)(void *))BrOptObjCtor));
        g_slot2 = q;
        if (q == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(q))->pfnEnter) = Enter2Fn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot2))->pfnEnter)(g_slot2);
        (*(int *)&((BrPhase_ *)(g_slot2))->f0C) = one;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    return one;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3F410_fn(void *self)
{
    return ((class Ctl3F410 *)self)->Activate();
}
/* end of C entry points */
