#include "slice2_25.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and it
 * also marks the session as hosted and picks the session kind before
 * opening. */
/* @implements 0x1003D930 glide Ctl3D930
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3D930@@QAEHXZ
 *
 * Slot load, then three global stores, then shared-return activate
 * (BrOptOpen2950B). After both arms, write pfnHook at +8 of a third
 * Phase *. Do not name temps for the stores.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};




/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot (*(Phase * *)&g_brPAA2950)
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_kind (*(int *)&g_brRaceNet)
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_flag DAT_10ac5bf0

/* EnterFn was a stand-in; the original calls BrOptFn10057C10 (?BrOptFn10057C10@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrOptFn10057C10: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrOptFn10057C10)
/* HookFn was a stand-in; the original calls Opt3DF80::Leave (?Leave@Opt3DF80@@YAHPAVGameObj3DF80@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameObj3DF80;
namespace Opt3DF80 { int Leave(GameObj3DF80 *); }
#define HookFn ((void (*)(Phase *))Opt3DF80::Leave)

class Ctl3D930 {
public:
    int Activate();
};

int Ctl3D930::Activate()
{
    Phase *p;

    p = g_slot;
    g_host = 1;
    g_kind = 2;
    g_flag = 0;
    if (p == 0) {
        p = new Phase;
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        p->pfnEnter = EnterFn;
        g_slot->pfnEnter(g_slot);
        (*(Phase * *)&g_brPAA29B8)->f0C = 1;
        (*(Phase * *)&g_brPAA29B8)->f68 = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    g_29B8->pfnHook = HookFn;
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3D930_fn(void *self)
{
    return ((class Ctl3D930 *)self)->Activate();
}
/* end of C entry points */
