#include "slice2_25.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and
 * this one zeroes two counters before opening. */
/* @implements 0x1003E250 glide Ctl3E250
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3E250@@QAEHXZ
 *
 * p = g_slot; g_c20 = 0; g_c24 = 0; then shared-return activate.
 * Slot load BEFORE the two zero stores (cpp-family2-notes.md).
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot (*(Phase * *)&DAT_10ac5cbc)
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls FUN_10052a60 (?FUN_10052a60@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* FUN_10052a60: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))FUN_10052a60)

class Ctl3E250 {
public:
    int Activate();
};

int Ctl3E250::Activate()
{
    Phase *p;

    p = g_slot;
    (*(int *)&g_brTime5C20) = 0;
    (*(int *)&g_brTime5C24) = 0;
    if (p == 0) {
        p = new Phase;
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = 1;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3E250_fn(void *self)
{
    return ((class Ctl3E250 *)self)->Activate();
}
/* end of C entry points */
