#include "slice2_25.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run. */
/* @implements 0x1003E9B0 glide Ctl3E9B0
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3E9B0@@QAEHXZ
 *
 * Shared-tail activate: new-path and existing-path both fall into
 * TailFn(); return 1. That keeps `mov eax,1` out of the flag stores
 * so they stay `c7` immediates (maxState=1, op-delete).
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot (*(Phase * *)&g_5CEC)
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn / TailFn were stand-ins; the original calls FUN_100469b0
 * (?FUN_100469b0@@YAHPAVGameUi@@@Z) and the C function BrExt_1007AC00.
 * Declared under their real symbols so the relocations resolve by name. */
class GameUi;
/* FUN_100469b0: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))FUN_100469b0)
/* BrExt_1007AC00: prototype in br_funcs.h */
#define TailFn BrExt_1007AC00

class Ctl3E9B0 {
public:
    int Activate();
};

int Ctl3E9B0::Activate()
{
    Phase *p;

    p = g_slot;
    if (p == 0) {
        p = ((Phase *)br_new_obj(sizeof(Phase), (void *(*)(void *))BrOptObjCtor));
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = 1;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    TailFn();
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3E9B0_fn(void *self)
{
    return ((class Ctl3E9B0 *)self)->Activate();
}
/* end of C entry points */
