#include "br_race.h"   /* br_globals: its objects */
#include "slice2_25.h"   /* br_globals: its objects */
#include "slice3_41.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and
 * this one sets several mode flags first -- it is the page that changes what
 * the rest of the front end is doing, not just what is on screen. */
/* @implements 0x1003F700 glide Ctl3F700
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3F700@@QAEHXZ
 *
 * Shared-return activate with a 1-register (esi) because five stores of 1
 * sit in the prologue. Flag stores are `mov r/m, esi` not `c7`. Extra
 * just-built tail (three calls + hook) lives inside the new arm, so each
 * arm returns 1. Ctor DECLARED, no dtor: unwind is operator delete
 * (maxState=1).
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */
typedef int (*PhaseHookFn)(void *);

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    PhaseHookFn pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};






/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot DAT_10ac5c64
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_mode DAT_100a9360
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls BrPhaseEnterPlaceholder_1004B430 (?BrPhaseEnterPlaceholder_1004B430@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrPhaseEnterPlaceholder_1004B430: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrPhaseEnterPlaceholder_1004B430)
/* HookFn was a stand-in; the original calls BrOpt4CB0 (?BrOpt4CB0@@YAHPAVGameObj@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameObj;
/* BrOpt4CB0: prototype in br_funcs.h */
#define HookFn ((int (*)(void *))BrOpt4CB0)
/* ResetBuf: prototype in br_funcs.h */
/* Fn08D60: prototype in br_funcs.h */
/* Fn37660: prototype in br_funcs.h */
/* Fn37B20: prototype in br_funcs.h */

class Ctl3F700 {
public:
    int Activate();
};

int Ctl3F700::Activate()
{
    Phase *p;

    g_mode = 2;
    ResetBuf();
    p = g_slot;
    g_AF2094 = 0;
    g_AF3CE4 = 1;
    g_mode = 2;
    g_0ABAA4 = 1;
    g_5BC8E0 = (char)0xFF;
    if (p == 0) {
        g_0ABAA4 = 1;
        p = new Phase;
        g_slot = p;
        g_cur = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        p->pfnEnter = EnterFn;
        g_slot->pfnEnter(g_slot);
        g_cur->f0C = 1;
        g_cur->f68 = 1;
        Fn08D60();
        Fn37660();
        Fn37B20();
        g_hookObj->pfnHook = HookFn;
        return 1;
    } else {
        g_cur = (Phase *)((BrOptObj *)(p));
        return 1;
    }
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3F700_fn(void *self)
{
    return ((class Ctl3F700 *)self)->Activate();
}
/* end of C entry points */
