#include "slice2_25.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run. */
/* @implements 0x1003F130 glide Ctl3F130
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3F130@@QAEHXZ
 *
 * Twin of 0x1003F410. Shared `return one` after the if/else hoists
 * `mov esi,1` between `test eax,eax` and the far `jne`. Ctor DECLARED,
 * no dtor.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot (*(Phase * *)&g_brPhaseAA292C)
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot2 (*(Phase * *)&g_brPhaseAA2974)

/* EnterFn was a stand-in; the original calls FUN_100498a0 (?FUN_100498a0@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* FUN_100498a0: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))FUN_100498a0)
/* Enter2Fn was a stand-in; the original calls BrExt_10049F40 (?BrExt_10049F40@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrExt_10049F40: prototype in br_funcs.h */
#define Enter2Fn ((void (*)(Phase *))BrExt_10049F40)

class Ctl3F130 {
public:
    int Activate();
};

int Ctl3F130::Activate()
{
    Phase *p;
    Phase *q;
    int one;

    p = (Phase *)(g_slot);
    one = 1;
    if (p == 0) {
        p = new Phase;
        g_slot = (Phase *)((struct Ph *)(p));
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        p->pfnEnter = EnterFn;
        g_slot->pfnEnter(g_slot);
        (*(Phase * *)&g_brPAA29B8)->f0C = one;
        (*(Phase * *)&g_brPAA29B8)->f68 = one;
        q = new Phase;
        g_slot2 = (Phase *)((struct Ph *)(q));
        if (q == 0)
            return 0;
        q->pfnEnter = Enter2Fn;
        g_slot2->pfnEnter(g_slot2);
        g_slot2->f0C = one;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    return one;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3F130_fn(void *self)
{
    return ((class Ctl3F130 *)self)->Activate();
}
/* end of C entry points */
