#include "slice2_25.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run. */
/* @implements 0x1003CA10 glide Ctl3CA10
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3CA10@@QAEHXZ
 *
 * Family-1 201 B installer. Shared-return activate; ctor DECLARED, no dtor.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};






/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot DAT_10ac5cf0
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls BrOptFn1004CAC0 (?BrOptFn1004CAC0@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrOptFn1004CAC0: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrOptFn1004CAC0)

class Ctl3CA10 {
public:
    int Activate();
};

int Ctl3CA10::Activate()
{
    Phase *p;

    p = g_slot;
    if (p == 0) {
        p = new Phase;
        g_slot = p;
        g_cur = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        p->pfnEnter = EnterFn;
        g_slot->pfnEnter(g_slot);
        g_cur->f0C = 1;
        g_cur->f68 = 1;
    } else {
        g_cur = (Phase *)((BrOptObj *)(p));
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3CA10_fn(void *self)
{
    return ((class Ctl3CA10 *)self)->Activate();
}
/* end of C entry points */
