#include "slice2_25.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and
 * this one clears its buffer and runs a preparation step before opening. */
/* @implements 0x1003D140 glide Ctl3D140
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3D140@@QAEHXZ
 *
 * ResetBuf(&g_buf); PrepFn(); then shared-return activate.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot g_5CB0
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls BrUiMultiEnter_1004F290 (?BrUiMultiEnter_1004F290@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrUiMultiEnter_1004F290: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrUiMultiEnter_1004F290)
/* ResetBuf: prototype in br_funcs.h */
/* PrepFn was a stand-in; the original calls C function BrSub1003E510.  Declared under
 * its real symbol so the relocation resolves by name. */
/* BrSub1003E510: prototype in br_funcs.h */
#define PrepFn ((void (*)(void))BrSub1003E510)

class Ctl3D140 {
public:
    int Activate();
};

int Ctl3D140::Activate()
{
    Phase *p;

    BrExt_100419D0(&(g_strA[0]));
    PrepFn();
    p = g_slot;
    if (p == 0) {
        p = ((Phase *)br_new_obj(sizeof(BrPhase_), (void *(*)(void *))BrOptObjCtor));
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = 1;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3D140_fn(void *self)
{
    return ((class Ctl3D140 *)self)->Activate();
}
/* end of C entry points */
