#include "br_race.h"   /* br_globals: its objects */
#include "slice2_25.h"   /* br_globals: its objects */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run, and
 * this one clears its buffer, sets a mode and runs a preparation step before
 * opening. */
/* @implements 0x1003E4A0 glide Ctl3E4A0
 * @cpp_kind method
 * @cpp_symbol ?Activate@Ctl3E4A0@@QAEHXZ
 *
 * ResetBuf + g_mode=1 + PrepFn, then shared-return activate. Three extra
 * cdecls run ONLY on the just-built path (slice2_26 BrPhaseActivate_10044F50).
 * return 1 sits after the if/else.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};



/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot g_5C64
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_mode (*(int *)((char *)&g_brRaceRules + 0xC)) /* BR_LP64_BYTE_VIEW */

/* EnterFn was a stand-in; the original calls BrPhaseEnterPlaceholder_1004B430 (?BrPhaseEnterPlaceholder_1004B430@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrPhaseEnterPlaceholder_1004B430: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrPhaseEnterPlaceholder_1004B430)
/* ResetBuf: prototype in br_funcs.h */
/* PrepFn was a stand-in; the original calls C function BrSub1003E680.  Declared under
 * its real symbol so the relocation resolves by name. */
/* 64-bit core: declared once, by its definition's header */
#define PrepFn ((void (*)(void))BrSub1003E680)
/* EmptyFn was a stand-in; the original calls C function BrPodNop.  Declared under
 * its real symbol so the relocation resolves by name. */
/* BrPodNop: prototype in br_funcs.h */
#define EmptyFn ((void (*)(void))BrPodNop)
/* SetupA: prototype in br_funcs.h */
/* SetupB: prototype in br_funcs.h */

class Ctl3E4A0 {
public:
    int Activate();
};

int Ctl3E4A0::Activate()
{
    Phase *p;

    BrExt_100419D0(&(g_strA[0]));
    g_mode = 1;
    PrepFn();
    p = g_slot;
    if (p == 0) {
        p = new Phase;
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        p->pfnEnter = EnterFn;
        g_slot->pfnEnter(g_slot);
        (*(Phase * *)&g_brPAA29B8)->f0C = 1;
        (*(Phase * *)&g_brPAA29B8)->f68 = 1;
        EmptyFn();
        BrUiFn1003DFC0();
        BrSub1003E510();
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int Ctl3E4A0_fn(void *self)
{
    return ((class Ctl3E4A0 *)self)->Activate();
}
/* end of C entry points */
