#include "slice3_39.h"   /* br_globals: its objects */
/* WHAT IT DOES: rebuild the bounds tree from scratch -- releases the
 * existing one and re-inserts every entry from the width/height pairs. */
/* @implements 0x10058D40 glide Ctl58D40
 * @cpp_kind method
 * @cpp_symbol ?Rebuild@Ctl58D40@@QAEXXZ
 *
 * Tear down the existing Node list, then new Node (0x14) per table row
 * whose w*h*6 fits in (g_mem << 20). maxState=1: one live new at a time.
 * Ctor and dtor DECLARED (unwind is operator delete of the in-flight new,
 * not the list teardown).
 */
#define _CRTIMP __declspec(dllimport)

class Node {
public:
    int w;
    int h;
    int f8;
    int fC;
    Node *next;
    Node();
    ~Node();
    void Append(Node *);
};


/* Node: br_coretypes.h */

/* Dim: br_coretypes.h */

/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* 64-bit core: declared once, in br_globals.h or its struct's header */

class Ctl58D40 {
public:
    void Rebuild();
};

void Ctl58D40::Rebuild()
{
    Node *p;
    Node *n;
    int *d;

    p = g_head;
    if (p != 0) {
        br_vdelete(p);
        g_head = 0;
        g_count = 0;
    }
    /* esi walks the .h of each pair ([esi]=h, [esi-4]=w) up to &g_tab[7].h */
    for (d = &(*(int *)&g_BrCharMapImage[98 + 0].ch); d < &(*(int *)&g_BrCharMapImage[98 + 7].ch); d += 2) {
        if (d[-1] * d[0] * 6 > ((*(int *)&BrGlHwParamB) << 20))
            continue;
        n = ((Node *)br_new_obj(sizeof(Node), (void *(*)(void *))FUN_10058c70));
        n->w = d[-1];
        n->h = d[0];
        n->f8 = 0x10;
        n->fC = 0;
        if (g_head == 0)
            g_head = n;
        else
            g_head->Append(n);
        g_count++;
    }
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" void Ctl58D40_fn(void *self)
{
    ((class Ctl58D40 *)self)->Rebuild();
}
/* end of C entry points */
