#include "slice2_25.h"   /* br_globals: its objects */
#include "br_phase.h"   /* BrPhase_, the canonical record */
/* WHAT IT DOES: open this menu page: create its object the first time it is
 * asked for, run its enter routine and make it the current page. One of a
 * family of near-identical page openers -- each owns its own page slot, and
 * the page object is created ONCE and reused for the rest of the run. */
/* @implements 0x1003EA70 glide CtlEA70
 * @cpp_kind method
 * @cpp_symbol ?Activate@CtlEA70@@QAEHXZ
 *
 * Shared-return activate: `return 1` sits after the if/else so `mov eax,1`
 * stays out of the flag stores (they remain `c7` immediates). Ctor
 * DECLARED, no dtor: unwind is operator delete (maxState=1).
 *
 * 0xC8 Phase: +0 vtbl, +4 pfnEnter, +0xC f0C, +0x68 f68.
 */
#define _CRTIMP __declspec(dllimport)

class Phase;

/* Phase: br_coretypes.h */

class Phase {
public:
    void *vtbl;
    PhaseEnterFn pfnEnter;
    void *pfnHook;
    int f0C;
    char _pad[0x58];
    int f68;
    char _rest[0x5C];
    Phase();
};






/* 64-bit core: declared once, in br_globals.h or its struct's header */
#define g_slot (*(Phase * *)&g_5CDC)
/* 64-bit core: declared once, in br_globals.h or its struct's header */

/* EnterFn was a stand-in; the original calls BrExt_1004DFC0 (?BrExt_1004DFC0@@YAHPAVGameUi@@@Z).  Declared under
 * its real symbol so the relocation resolves by name. */
class GameUi;
/* BrExt_1004DFC0: prototype in br_funcs.h */
#define EnterFn ((void (*)(Phase *))BrExt_1004DFC0)

class CtlEA70 {
public:
    int Activate();
};

int CtlEA70::Activate()
{
    Phase *p;

    p = g_slot;
    if (p == 0) {
        p = ((Phase *)br_new_obj(sizeof(Phase), (void *(*)(void *))BrOptObjCtor));
        g_slot = p;
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
        if (p == 0)
            return 0;
        (*(PhaseEnterFn *)&((BrPhase_ *)(p))->pfnEnter) = EnterFn;
        (*(PhaseEnterFn *)&((BrPhase_ *)(g_slot))->pfnEnter)(g_slot);
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f0C) = 1;
        (*(int *)&((BrPhase_ *)((*(Phase * *)&g_brPAA29B8)))->f68) = 1;
    } else {
        (*(Phase * *)&g_brPAA29B8) = (Phase *)((BrOptObj *)(p));
    }
    return 1;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" int CtlEA70_fn(void *self)
{
    return ((class CtlEA70 *)self)->Activate();
}
/* end of C entry points */
