/* WHAT IT DOES: leave this menu page: run its leave routine, destroy the
 * page object, and make its parent current again. One of a family that
 * differ only in which parent they return to and which state flags they
 * clear. */
/* @implements 0x1003FA80 glide BrOpt65E0
 * @cpp_kind method
 * @cpp_symbol ?BrOpt65E0@@YAHPAVGameObj@@@Z
 *
 * Phase-leave family member, generated by tools/gen_phaseleave.py.
 * Slot+0x1C no-arg virtual thiscall, then the slot-0 one-stack-arg
 * vcall (`mov eax,[ecx]; push 1; call [eax]`) that only a real C++
 * virtual call reaches. No EH (no `new`).
 */
#ifdef BR_MATCHING_BUILD
#define _CRTIMP __declspec(dllimport)
#endif

class GameSub {
public:
    virtual void s0();
    virtual void s1();
    virtual void s2();
    virtual void s3();
    virtual void s4();
    virtual void s5();
    virtual void s6(int);
    virtual void s7();
};

class GameObj {
public:
    char pad[0x2AE8];
    GameSub *pSub;
};

class Phase {
public:
    virtual void *f00(int);
};

typedef char chk_sub[(unsigned)&((GameObj *)0)->pSub == 0x2AE8 ? 1 : -1];

Phase *g_cur;
Phase *g_5C70;
int g_5CD8;

int BrOpt65E0(GameObj *pGame)
{
    Phase *pObj;

    pGame->pSub->s7();
    pObj = g_cur;
    if (pObj != 0)
        pObj->f00(1);
    g_5CD8 = 0;
    g_cur = g_5C70;
    return 0;
}
