#!/usr/bin/env python3
"""Generate C++ TUs for the UI text-refresh family (0x10038D30-class).

All members are byte-identical to the 0x10038D30 skeleton outside four
reloc/rel-masked parameter sites (index global, string table, getter
call, apply call): strcpy a looked-up string into the item's text
buffer, slot-1 virtual thiscall on the embedded item, apply, return 1.
The vtbl load scheduled INSIDE the strcpy intrinsic is C++ frontend
member-call order — the C fastcall spelling leaves it after the copy
(18 diffs) and no C temp reaches it (hoists to ebp, +1 push). Proven
byte-exact 0x10038D30 (see the UI-text entry in docs/VC5-IDIOMS.md).

Usage: python3 tools/gen_uitext.py [--dry-run]
Then:  python3 tools/cpp_sweep.py src/core/cpp/<VA>.cpp
"""
import csv
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORIG_DIR = os.path.join(ROOT, 'build', 'match', 'orig')
CPP_DIR = os.path.join(ROOT, 'src', 'core', 'cpp')
REF_VA = '0x10038D30'
# parameter bytes: idx-global imm, table-base imm, getter rel32, apply rel32
MASKED = {1, 2, 3, 0xB, 0xC, 0x11, 0x12, 0x13, 0x14, 0x54, 0x55, 0x56, 0x57}

TEMPLATE = '''/* @implements 0x{va:08X} glide {name}
 * @cpp_kind method
 * @cpp_symbol ?{name}@@YAHPAVGameObj@@@Z
 *
 * UI text-refresh family member, generated by tools/gen_uitext.py from
 * the 0x10038D30 skeleton (strcpy looked-up string into the item text
 * buffer, slot-1 virtual thiscall on the embedded item, apply). No EH.
 */
#ifdef BR_MATCHING_BUILD
#define _CRTIMP __declspec(dllimport)
#endif
#include <string.h>

class Item {{
public:
    virtual void i0();
    virtual void i1();
}};

class GameObj {{
public:
    char pad[0x2B5C];
    Item item;
    char pad2[5];
    char text[256];
}};

typedef char chk_item[(unsigned)&((GameObj *)0)->item == 0x2B5C ? 1 : -1];
typedef char chk_text[(unsigned)&((GameObj *)0)->text == 0x2B65 ? 1 : -1];

extern "C" {{
int g_idx;
char *g_tab[1];
char *BrStrGet(char *);
int Br85ItemApply(GameObj *, int);
}}

int {name}(GameObj *pGame)
{{
    strcpy(pGame->text, BrStrGet(g_tab[g_idx]));
    pGame->item.i1();
    Br85ItemApply(pGame, 0);
    return 1;
}}
'''


def main():
    dry = '--dry-run' in sys.argv
    ref = open(os.path.join(ORIG_DIR, REF_VA + '.bin'), 'rb').read()
    twins = {}
    with open(os.path.join(ROOT, 'config', 'shared.csv')) as f:
        for r in csv.DictReader(f):
            if r.get('glide_va') and r.get('d3d_va'):
                twins[int(r['glide_va'], 16)] = int(r['d3d_va'], 16)
    matched = set()
    for rep in ('report.csv', 'report_cpp.csv'):
        p = os.path.join(ROOT, 'build', 'match', rep)
        if os.path.exists(p):
            with open(p) as f:
                matched |= {r['va'].lower() for r in csv.DictReader(f)
                            if r['status'] == 'match'}
    wrote = 0
    for p in sorted(glob.glob(os.path.join(ORIG_DIR, '0x*.bin'))):
        va_hex = os.path.basename(p)[:-4]
        if va_hex.lower() in matched:
            continue
        b = open(p, 'rb').read()
        if len(b) != len(ref) or not all(
                b[i] == ref[i] for i in range(len(ref)) if i not in MASKED):
            continue
        va = int(va_hex, 16)
        out = os.path.join(CPP_DIR, '0x%08X.cpp' % va)
        if os.path.exists(out):
            continue
        twin = twins.get(va)
        name = ('BrUiText%05X' % (twin & 0xFFFFF) if twin
                else 'BrUiText%05X' % (va & 0xFFFFF))
        tu = TEMPLATE.format(va=va, name=name)
        if not dry:
            with open(out, 'w') as f:
                f.write(tu)
        print('WROTE  %s  %s' % (va_hex, name))
        wrote += 1
    print('%d written' % wrote)


if __name__ == '__main__':
    main()
