#!/usr/bin/env python3
"""Generate C++ TUs for the phase-leave family (the 0x1003E..0x10040 UI
handlers).

Skeleton, proven byte-exact by hand on 0x1003D4A0 / 0x1003D510 (see the
"Slot 0 with one stack arg" entry in docs/VC5-IDIOMS.md):

    mov eax,[esp+4]; mov ecx,[eax+2AE8]; mov edx,[ecx]; call [edx+1C]
    mov ecx,[g_cur]; test ecx,ecx; je tail
    mov eax,[ecx]; push 1; call [eax]        ; EAX-pattern slot-0 vcall --
                                             ; only a real C++ virtual call
                                             ; reaches this shape
    tail: mov ecx,[SRC]
          mov [Zi],0            (1..n zero stores, byte order)
          mov [g_cur],ecx
          call helper           (0..n plain cdecl calls)
          xor eax,eax; ret

Each member differs only in SRC / the zeroed globals / trailing helper
calls, so the whole family is stamped from one template. Members whose
tail leaves this grammar (extra vcalls, thiscall helpers) are reported
and left for the hand pass.

Usage:
    python3 tools/gen_phaseleave.py            # write src/core/cpp/<VA>.cpp
    python3 tools/gen_phaseleave.py --dry-run  # parse + report only

Then score with: python3 tools/cpp_sweep.py src/core/cpp/<VA>.cpp
"""
import csv
import glob
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORIG_DIR = os.path.join(ROOT, 'build', 'match', 'orig')
CPP_DIR = os.path.join(ROOT, 'src', 'core', 'cpp')
G_CUR = 0x10AC5C5C

PREFIX = bytes.fromhex('8b4424048b88e82a00008b11ff521c8b0d'
                       '5c5cac10'
                       '85c974068b016a01ff10')


def d3d_twins():
    tw = {}
    with open(os.path.join(ROOT, 'config', 'shared.csv')) as f:
        for r in csv.DictReader(f):
            g, d = r.get('glide_va', ''), r.get('d3d_va', '')
            if g and d:
                tw[int(g, 16)] = int(d, 16)
    return tw


def parse_tail(b, off):
    """Parse the post-prefix tail. Returns (src, zeros, calls) or None."""
    src, zeros, calls = None, [], []
    state = 'load'
    while off < len(b):
        if b[off:off + 2] == bytes((0x33, 0xC0)) and b[off + 2] == 0xC3:
            return (src, zeros, calls) if src is not None else None
        if state == 'load' and b[off:off + 2] == bytes((0x8B, 0x0D)):
            src = struct.unpack('<I', b[off + 2:off + 6])[0]
            off += 6
            state = 'zeros'
        elif state == 'zeros' and b[off:off + 2] == bytes((0xC7, 0x05)) \
                and b[off + 6:off + 10] == b'\x00\x00\x00\x00':
            zeros.append(struct.unpack('<I', b[off + 2:off + 6])[0])
            off += 10
        elif state == 'zeros' and b[off:off + 2] == bytes((0x89, 0x0D)):
            if struct.unpack('<I', b[off + 2:off + 6])[0] != G_CUR:
                return None
            off += 6
            state = 'calls'
        elif state == 'calls' and b[off] == 0xE8:
            calls.append('rel')  # target resolved by caller with the VA base
            off += 5
        else:
            return None
    return None


def call_targets(b, va):
    """VAs of E8 rel32 calls in the tail (after the fixed prefix)."""
    out, off = [], len(PREFIX)
    while off < len(b) - 4:
        if b[off] == 0xE8:
            rel = struct.unpack('<i', b[off + 1:off + 5])[0]
            out.append(va + off + 5 + rel)
            off += 5
        else:
            off += 1
    return out


TEMPLATE = '''/* @implements 0x{va:08X} glide {name}
 * @cpp_kind method
 * @cpp_symbol ?{name}@@YAHPAVGameObj@@@Z
 *
 * Phase-leave family member, generated by tools/gen_phaseleave.py.
 * Slot+0x1C no-arg virtual thiscall, then the slot-0 one-stack-arg
 * vcall (`mov eax,[ecx]; push 1; call [eax]`) that only a real C++
 * virtual call reaches. No EH (no `new`).
 */
#ifdef BR_MATCHING_BUILD
#define _CRTIMP __declspec(dllimport)
#endif

class GameSub {{
public:
    virtual void s0();
    virtual void s1();
    virtual void s2();
    virtual void s3();
    virtual void s4();
    virtual void s5();
    virtual void s6(int);
    virtual void s7();
}};

class GameObj {{
public:
    char pad[0x2AE8];
    GameSub *pSub;
}};

class Phase {{
public:
    virtual void *f00(int);
}};

typedef char chk_sub[(unsigned)&((GameObj *)0)->pSub == 0x2AE8 ? 1 : -1];

Phase *g_cur;
Phase *g_{src:04X};
{zero_decls}{fn_decls}
int {name}(GameObj *pGame)
{{
    Phase *pObj;

    pGame->pSub->s7();
    pObj = g_cur;
    if (pObj != 0)
        pObj->f00(1);
{zero_stmts}    g_cur = g_{src:04X};
{call_stmts}    return 0;
}}
'''


def emit(va, b, twins):
    tail = parse_tail(b, len(PREFIX))
    if tail is None:
        return None, 'tail leaves the family grammar'
    src, zeros, calls = tail
    twin = twins.get(va)
    name = 'BrOpt%04X' % (twin & 0xFFFF) if twin else 'BrPhaseLv%04X' % (va & 0xFFFF)
    tgts = call_targets(b, va)
    if len(tgts) != len(calls):
        return None, 'call parse mismatch'
    zd = ''.join('int g_%04X;\n' % (z & 0xFFFF) for z in zeros)
    fd = ('\n' + ''.join('void Fn%04X(void);\n' % (t & 0xFFFF) for t in tgts)
          if tgts else '')
    zs = ''.join('    g_%04X = 0;\n' % (z & 0xFFFF) for z in zeros)
    cs = ''.join('    Fn%04X();\n' % (t & 0xFFFF) for t in tgts)
    return TEMPLATE.format(va=va, name=name, src=src & 0xFFFF,
                           zero_decls=zd, fn_decls=fd,
                           zero_stmts=zs, call_stmts=cs), name


def main():
    dry = '--dry-run' in sys.argv
    twins = d3d_twins()
    matched = set()
    for rep in ('report.csv', 'report_cpp.csv'):
        p = os.path.join(ROOT, 'build', 'match', rep)
        if os.path.exists(p):
            with open(p) as f:
                matched |= {r['va'].lower() for r in csv.DictReader(f)
                            if r['status'] == 'match'}
    wrote, skipped = [], []
    for p in sorted(glob.glob(os.path.join(ORIG_DIR, '0x*.bin'))):
        va_hex = os.path.basename(p)[:-4]
        if va_hex.lower() in matched:
            continue
        b = open(p, 'rb').read()
        if not b.startswith(PREFIX):
            continue
        va = int(va_hex, 16)
        out = os.path.join(CPP_DIR, '0x%08X.cpp' % va)
        if os.path.exists(out):
            continue
        tu, info = emit(va, b, twins)
        if tu is None:
            skipped.append((va_hex, info))
            continue
        if not dry:
            with open(out, 'w') as f:
                f.write(tu)
        wrote.append((va_hex, info))
    for v, n in wrote:
        print('WROTE  %s  %s' % (v, n))
    for v, why in skipped:
        print('SKIP   %s  %s' % (v, why))
    print('%d written, %d skipped (hand pass)' % (len(wrote), len(skipped)))


if __name__ == '__main__':
    main()
