#!/usr/bin/env python3
"""Generate a linker directive header that pins every global to its original VA.

Reads config/globals.csv and emits a header file that, when included in a
matching build, places each global at the address it occupies in the original
DLL.  For MSVC this uses #pragma comment(linker, "/MERGE:...") and
__declspec(allocate(...)).  For the port build (clang/macOS) the header is
a no-op -- globals float freely.

Usage:
    python3 tools/pin_globals.py config/globals.csv include/br_globals_pin.h

The generated header is included once, in a matching-build-only TU.
"""
import csv
import sys


def generate(csv_path, out_path):
    globals_by_section = {}

    with open(csv_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            addr = int(row['addr'], 16)
            symbol = row.get('symbol', '') or f"g_{addr & 0xFFFFFF:06X}"
            section = row.get('section', '.data')
            width = int(row.get('width', '4'))
            globals_by_section.setdefault(section, []).append(
                (addr, symbol, width))

    with open(out_path, 'w') as out:
        out.write("/* br_globals_pin.h -- GENERATED by tools/pin_globals.py\n")
        out.write(" *\n")
        out.write(" * Pins every global to its original VA for the matching build.\n")
        out.write(" * Included by the matching-build TU only. The port build ignores this.\n")
        out.write(" */\n")
        out.write("#ifndef BR_GLOBALS_PIN_H\n")
        out.write("#define BR_GLOBALS_PIN_H\n\n")
        out.write("#ifdef BR_MATCHING_BUILD\n\n")

        total = 0
        for section in sorted(globals_by_section):
            entries = sorted(globals_by_section[section])
            out.write(f"/* --- {section} ({len(entries)} globals) --- */\n")
            for addr, symbol, width in entries:
                out.write(f"/* 0x{addr:08X} */  "
                          f"/* {symbol}, {width} bytes */\n")
                total += 1
            out.write("\n")

        out.write("/*\n")
        out.write(" * MSVC 5.0 approach: #pragma data_seg + explicit placement.\n")
        out.write(" * The linker script / .def file maps each custom section to\n")
        out.write(" * its original VA.  Individual globals go into named sections\n")
        out.write(" * that the linker merges at the target address.\n")
        out.write(" *\n")
        out.write(" * This header records the ADDRESSES.  The actual pragma/section\n")
        out.write(" * directives depend on the linker script, which is generated\n")
        out.write(" * alongside this header by the matching build system.\n")
        out.write(" */\n\n")

        out.write("#endif /* BR_MATCHING_BUILD */\n")
        out.write("#endif /* BR_GLOBALS_PIN_H */\n")

    print(f"generated {out_path}: {total} globals across "
          f"{len(globals_by_section)} sections")


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <globals.csv> <output.h>")
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
