#!/usr/bin/env python3
"""gen_drive_sandbox.py -- assemble a self-contained driving sandbox for the
port from the raw Ghidra decompilation.

The port needs the driving code (control chain, car-vs-car, race step) to RUN.
Those functions and their transitive callees exist only as raw Ghidra drafts
(build/ghidra_decomp/<va>.c) -- they are not cleaned into the compiled tree,
and the byte-matched ones are behind BR_MATCHING_BUILD so the port cannot see
them either.

Rather than integrate 752 functions into the tree one by one, we emit ONE
self-contained translation unit:
  * every function in the closure as a file-local `static` FUN_<va>,
  * every DAT_/global it references as file-local storage, initialised from
    the ACTUAL bytes in orig/BRGlide.dll (so physics constants are real),
  * typedefs for Ghidra's pseudo-types.
Nothing here is exported except the entry points the race harness calls, so it
cannot clash with the port's own symbols. It is NOT byte-exact and NOT in the
matching tree; it is a port-only fallback that puts the existing C to work.
"""
import os, re, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
G = os.path.join(ROOT, 'build', 'ghidra_decomp')
DLL = os.path.join(ROOT, 'orig', 'BRGlide.dll')
OUT = os.path.join(ROOT, 'ports', 'macos', 'drive_sandbox.c')

# ---- PE image: VA -> file bytes ------------------------------------------
_img = open(DLL, 'rb').read()
_pe = struct.unpack_from('<I', _img, 0x3c)[0]
_nsec = struct.unpack_from('<H', _img, _pe + 6)[0]
_opt = struct.unpack_from('<H', _img, _pe + 20)[0]
_base = struct.unpack_from('<I', _img, _pe + 24 + 28)[0]
_secs = []
_soff = _pe + 24 + _opt
for i in range(_nsec):
    o = _soff + i * 40
    vsz, va, rsz, rptr = struct.unpack_from('<IIII', _img, o + 8)
    _secs.append((_base + va, vsz, rptr, rsz))

def va_bytes(va, n):
    """n bytes at virtual address va, or None if unmapped/in .bss."""
    for sva, vsz, rptr, rsz in _secs:
        if sva <= va < sva + vsz:
            off = rptr + (va - sva)
            if off + n <= rptr + rsz:
                return _img[off:off + n]
            return b'\0' * n            # mapped but beyond raw (.bss tail)
    return None

# ---- closure over FUN_ references ----------------------------------------
def draft(va):
    p = os.path.join(G, va + '.c')
    return open(p, errors='ignore').read() if os.path.exists(p) else None

# A few drafts have Ghidra output that resists mechanical repair (variadic
# indirect calls, a vtable dispatch typed through a scalar, a static/non-static
# clash). Force them to no-op stubs; the stub loop handles the rest.
FORCE_STUB = {'0x10004A40', '0x100099D0', '0x1006CFA0'}

SEED = ['0x1006F170', '0x10068F80', '0x10019A70']
seen = set(); frontier = set(SEED)
while frontier:
    nxt = set()
    for va in frontier:
        if va in seen:
            continue
        seen.add(va)
        t = draft(va)
        if t:
            nxt |= set('0x' + m.upper() for m in re.findall(r'FUN_([0-9a-f]{8})', t))
    frontier = nxt - seen

funcs = sorted(v for v in seen if draft(v))
print(f"closure: {len(seen)} functions, {len(funcs)} with drafts", file=sys.stderr)

# ---- gather every global symbol the drafts reference ---------------------
# Ghidra names: DAT_xxxxxxxx, _DAT_xxxxxxxx, PTR_xxx_xxxxxxxx, etc. We treat
# any bare identifier of the form (_?)(DAT|PTR|...)_<8 hex> plus &LAB_/UNK_.
bodies = {va: draft(va) for va in funcs}
alltext = '\n'.join(bodies.values())

# Ghidra data globals: DAT_/_DAT_/__DAT_, PTR_..._xxxx, LAB_/UNK_/s_/u_ with a
# trailing 8-hex VA. Capture the VA (last 8 hex) for byte extraction.
# DATA globals only -- NOT LAB_ (code labels / goto targets) or s_/u_ string
# labels. DAT_/_DAT_/PTR_/UNK_/BYTE_/WORD_/DWORD_ with a trailing 8-hex VA.
data_re = re.compile(r'\b(_{0,2}(?:DAT|PTR|UNK|BYTE|WORD|DWORD)_'
                     r'(?:[A-Za-z0-9]+_)*?([0-9a-f]{8}))\b')
globals_found = {}
for m in data_re.finditer(alltext):
    name, hexva = m.group(1), m.group(2)
    globals_found[name] = int(hexva, 16)

print(f"data globals referenced: {len(globals_found)}", file=sys.stderr)

# ---- emit ----------------------------------------------------------------
H = []
H.append('/* drive_sandbox.c -- GENERATED by ports/macos/gen_drive_sandbox.py')
H.append(' * Self-contained raw-Ghidra driving layer for the port. Not byte-exact,')
H.append(' * not in the matching tree. Do not hand-edit; regenerate. */')
H.append('#include <stdint.h>')
H.append('#include <string.h>')
H.append('#include <math.h>')
H.append('#include <stdbool.h>')
H.append('')
H.append('/* Ghidra pseudo-types */')
H.append('typedef uint8_t  undefined1; typedef uint16_t undefined2;')
H.append('typedef uint32_t undefined4; typedef uint64_t undefined8;')
H.append('typedef uint8_t  undefined;  typedef uint8_t byte;')
H.append('typedef uint16_t ushort; typedef uint32_t uint; typedef uint64_t ulonglong;')
H.append('typedef int64_t  longlong;')
H.append('typedef long double float10;')
H.append('typedef uint32_t code();  /* Ghidra uses code* for function pointers */')
H.append('/* odd-width Ghidra types: widen to the next real integer */')
H.append('typedef uint32_t uint3; typedef uint64_t uint5, uint6, uint7;')
H.append('typedef uint64_t uint9, uint10;')
H.append('typedef long double unkbyte10, unkuint9, unkuint10;')
H.append('typedef int32_t int3; typedef int64_t int5, int6, int7;')
H.append('/* Windows types a few Win32/mmio drafts pull in (all stubbed anyway) */')
H.append('typedef const char *LPCSTR; typedef char *LPSTR;')
H.append('typedef void *LPVOID, *LPCVOID, *HANDLE, *HWND, *HDC, *HGLOBAL, *HPSTR;')
H.append('typedef uint32_t DWORD, UINT, BOOL, MMRESULT; typedef uint16_t WORD;')
H.append('typedef void *HMMIO, *LPMMCKINFO, *LPCRITICAL_SECTION, *FILE;')
H.append('typedef struct { uint32_t a,b,c,d,e; } MMCKINFO;')
H.append('')
H.append('/* Ghidra intrinsic helpers */')
H.append('#define CONCAT11(a,b) ((((uint16_t)(uint8_t)(a))<<8)|(uint8_t)(b))')
H.append('#define CONCAT22(a,b) ((((uint32_t)(uint16_t)(a))<<16)|(uint16_t)(b))')
H.append('#define CONCAT44(a,b) ((((uint64_t)(uint32_t)(a))<<32)|(uint32_t)(b))')
H.append('#define CONCAT31(a,b) ((((uint32_t)(a))<<8)|(uint8_t)(b))')
H.append('#define CONCAT13(a,b) ((((uint32_t)(uint8_t)(a))<<24)|((uint32_t)(b)&0xffffff))')
H.append('#define CONCAT12(a,b) ((((uint32_t)(uint8_t)(a))<<16)|(uint16_t)(b))')
H.append('#define CONCAT21(a,b) ((((uint32_t)(uint16_t)(a))<<8)|(uint8_t)(b))')
H.append('#define CONCAT111(a,b,c) CONCAT12((a),CONCAT11((b),(c)))')
H.append('#define CONCAT211(a,b,c) CONCAT31(CONCAT21((a),(b)),(c))')
H.append('#define CONCAT41(a,b) ((((uint64_t)(uint32_t)(a))<<8)|(uint8_t)(b))')
H.append('#define CONCAT53(a,b) (((uint64_t)(a)<<24)|((uint32_t)(b)&0xffffff))')
H.append('#define CONCAT62(a,b) (((uint64_t)(a)<<16)|(uint16_t)(b))')
H.append('#define CONCAT71(a,b) (((uint64_t)(a)<<8)|(uint8_t)(b))')
H.append('#define SUB84(a,b) ((uint32_t)((uint64_t)(a)>>((b)*8)))')
H.append('#define SUB41(a,b) ((uint8_t)((uint32_t)(a)>>((b)*8)))')
H.append('#define SUB42(a,b) ((uint16_t)((uint32_t)(a)>>((b)*8)))')
H.append('#define SUB21(a,b) ((uint8_t)((uint16_t)(a)>>((b)*8)))')
H.append('#define SUB81(a,b) ((uint8_t)((uint64_t)(a)>>((b)*8)))')
H.append('#define SUB82(a,b) ((uint16_t)((uint64_t)(a)>>((b)*8)))')
H.append('#define SUB83(a,b) ((uint32_t)((uint64_t)(a)>>((b)*8))&0xffffff)')
H.append('#define ZEXT14(a) ((uint32_t)(uint8_t)(a))')
H.append('#define ZEXT18(a) ((uint64_t)(uint8_t)(a))')
H.append('#define ZEXT24(a) ((uint32_t)(uint16_t)(a))')
H.append('#define ZEXT28(a) ((uint64_t)(uint16_t)(a))')
H.append('#define ZEXT48(a) ((uint64_t)(uint32_t)(a))')
H.append('#define ZEXT12(a) ((uint16_t)(uint8_t)(a))')
H.append('#define SEXT14(a) ((int32_t)(int8_t)(a))')
H.append('#define SEXT18(a) ((int64_t)(int8_t)(a))')
H.append('#define SEXT24(a) ((int32_t)(int16_t)(a))')
H.append('#define SEXT48(a) ((int64_t)(int32_t)(a))')
H.append('#define SEXT28(a) ((int64_t)(int16_t)(a))')
H.append('#define ABS(x) ((x)<0?-(x):(x))')
H.append('#define NAN(x) (0)')
H.append('/* MSVC / x87 helpers Ghidra emits as calls */')
H.append('static int64_t ftol(double d){ return (int64_t)d; }')
H.append('static int64_t _ftol(double d){ return (int64_t)d; }')
H.append('static double fsin(double x){ return sin(x); }')
H.append('static double fcos(double x){ return cos(x); }')
H.append('static double fsqrt(double x){ return sqrt(x); }')
H.append('static double fabs_(double x){ return fabs(x); }')
H.append('static double fptan(double x){ return tan(x); }')
H.append('static double fpatan(double y,double x){ return atan2(y,x); }')
H.append('static double fyl2x(double x,double y){ return y*log2(x); }')
H.append('#define SQRT(x) sqrt((double)(x))')
H.append('#define POW(a,b) pow((double)(a),(double)(b))')
H.append('')

# data globals: file-local storage, initialised from the DLL bytes.
# width is unknown; give each a small union backed by 8 bytes of real data,
# and expose it under the exact Ghidra name as the right scalar. Ghidra reads
# them as float/int/char via casts, so a raw 8-byte store covers all.
H.append('/* data constants, initialised from orig/BRGlide.dll .rdata/.data */')
for name in sorted(globals_found):
    va = globals_found[name]
    b = va_bytes(va, 8) or b'\0' * 8
    ints = ','.join(str(x) for x in b)
    # a generous 4KB backing so struct/array reads past the symbol stay in-bounds
    H.append(f'static union {{ uint8_t b[4096]; uint32_t u; float f; }} '
             f'_stor_{name} = {{ .b = {{ {ints} }} }};')
    H.append(f'#define {name} (*(uint32_t*)_stor_{name}.b)')
H.append('')

# forward-declare all funcs (static), then bodies. Strip the leading Ghidra
# comment; make each definition static.
# Ghidra register/placeholder pseudo-identifiers: declare as file-local so any
# reference compiles. These stand for values Ghidra could not track; reading
# them yields 0, which is the honest "unknown" and keeps the code compiling.
placeholders = set()
for pat in (r'\b(unaff_[A-Za-z0-9]+)', r'\b(extraout_[A-Za-z0-9]+)',
            r'\b(in_[A-Za-z][A-Za-z0-9]*)', r'\b(unique0x[0-9a-fA-F]+)',
            r'\b(in_stack_[A-Za-z0-9]+)', r'\b(register0x[0-9a-fA-F]+)'):
    placeholders |= set(re.findall(pat, alltext))
H.append('/* Ghidra untracked-value placeholders (read as 0) */')
for p in sorted(placeholders):
    H.append(f'static uint64_t {p};')
H.append('')
# code labels referenced by address (&LAB_xxxx) -- give them addressable bytes
labels = set(re.findall(r'&(LAB_[0-9a-f]{8})', alltext))
labels |= set(re.findall(r'=\s*(LAB_[0-9a-f]{8})\b', alltext))
if labels:
    H.append('/* code labels taken by address */')
    for lb in sorted(labels):
        H.append(f'static char {lb};')
    H.append('')

# All FUN_ get UNPROTOTYPED forward decls: `static T FUN_x();` accepts calls of
# any arity, which is exactly what raw Ghidra needs (caller/callee arity often
# disagree across functions). The definition supplies the real signature.
# Win32 API functions the closure calls -- file-local no-op stubs, declared
# BEFORE any use so no implicit-declaration clash. Any that actually mattered
# to driving would show as wrong behaviour, not a link error.
winapis = set(re.findall(r'\b(WaitForSingleObject|ReleaseMutex|CreateMutex[AW]?'
                         r'|EnterCriticalSection|LeaveCriticalSection|Sleep'
                         r'|GetTickCount|timeGetTime|OutputDebugString[AW]?'
                         r'|InterlockedIncrement|InterlockedDecrement'
                         r'|GetLastError|SetLastError|CloseHandle|mmioClose|GlobalAlloc|GlobalFree|GlobalLock'
                         r'|GlobalUnlock|GlobalHandle|GlobalReAlloc'
                         r'|mmioAscend|mmioDescend|mmioRead|mmioOpen[AW]?)\b', alltext))
if winapis:
    H.append('/* Win32 API stubs (no-ops) */')
    for w in sorted(winapis):
        H.append(f'static uint32_t {w}() {{ return 0; }}')
    H.append('')

H.append('/* forward decls -- unprototyped so any call arity compiles.')
H.append(' * The return type is the EXACT text from the definition (pointer')
H.append(' * stars included) so proto and definition never conflict. */')
protos = []
for va in funcs:
    t = bodies[va]
    low = va[2:].lower()
    # grab everything from the definition line start up to the "(" -- this is
    # "<return type incl *> [__conv] FUN_<va>". Strip conv keywords; keep stars.
    m = re.search(r'^([A-Za-z][^\n(;{]*?\bFUN_' + low + r')\s*\(', t, re.M)
    if m:
        head = m.group(1)
        head = re.sub(r'__(fastcall|thiscall|cdecl)\s*', '', head)
        protos.append(f'static {head.strip()}();')
    else:
        protos.append(f'static undefined4 FUN_{low}();')
H += protos
H.append('')

# bodies
for va in funcs:
    low = va[2:].lower()
    if va in FORCE_STUB:
        # minimal stub with the definition's real return type
        mm = re.search(r'^([A-Za-z][^\n(;{]*?\bFUN_' + low + r')\s*\(', bodies[va], re.M)
        head = re.sub(r'__(fastcall|thiscall|cdecl)\s*', '', mm.group(1)) if mm else 'undefined4 FUN_' + low
        ret = head.split('FUN_')[0].strip()
        H.append(f'static {head.strip()}() ' + ('{ }' if ret == 'void' else '{ return 0; }'))
        H.append('')
        continue
    t = bodies[va]
    t = re.sub(r'^/\*.*?\*/\s*', '', t, flags=re.S)   # drop leading comment
    # drop calling-convention keywords clang on arm64 rejects loudly
    t = t.replace('__fastcall', '').replace('__thiscall', '').replace('__cdecl', '')

    # Rewrite the DEFINITION header to OLD-STYLE (K&R): a K&R definition does
    # NOT provide a prototype, so NO call anywhere is argument-count checked --
    # which is exactly right for raw Ghidra, where caller and callee arity
    # routinely disagree. Turns
    #   <ret> FUN_x(int param_1, undefined4 *param_2) {
    # into
    #   static <ret> FUN_x(param_1, param_2) int param_1; undefined4 *param_2; {
    m = re.search(r'(^|\n)([A-Za-z][^\n(;{]*?)\bFUN_' + low + r'\s*\(([^;{]*)\)\s*\n\{',
                  t)
    if m:
        ret = m.group(2).strip()
        params = m.group(3).strip()
        if params in ('', 'void'):
            newhdr = f'static {ret} FUN_{low}(void)\n{{'
        else:
            parts = [p.strip() for p in params.split(',') if p.strip()]
            names, decls = [], []
            for p in parts:
                pm = re.search(r'([A-Za-z_]\w*)\s*$', p)
                nm = pm.group(1) if pm else p
                names.append(nm)
                decls.append(p + ';')
            newhdr = (f'static {ret} FUN_{low}(' + ','.join(names) + ') '
                      + ' '.join(decls) + '\n{')
        t = t[:m.start()] + (m.group(1)) + newhdr + t[m.end():]
    H.append(t)
    H.append('')

# entry point the harness calls
H.append('/* entry: run the per-car control chain on one car struct */')
H.append('void BrDriveSandboxCar(void *pCar) { FUN_1006f170((int)(intptr_t)pCar); }')

open(OUT, 'w').write('\n'.join(H))
print(f"wrote {OUT} ({len(funcs)} funcs, {len(globals_found)} globals)", file=sys.stderr)
