/* WHAT IT DOES: set a car up in one race slot: applies its paint scheme,
 * loads its model, resets its state and binds it to the slot. */
/* @implements 0x1006FCE0 glide BrCarSlotSetup_1006FCE0
 * @cpp_kind method
 * @cpp_symbol ?SlotSetup@Car6FCE0@@QAEXHH@Z
 *
 * Thiscall, two stack args (`ret 8`), 104 B. Car slot setup: push the
 * three tint bytes at +0x29AC..AE through the tint-scale helper, load the
 * slot, reset the +0x2A70 record, zero the eight dwords at +0x2A90, then
 * hand the slot to the +0x29C4 binder (0x1006FCB0, the one br_carphys.c
 * relies on to have run).
 *
 * The tint bytes are `unsigned char` members widened to int arguments,
 * which VC5 spells `xor r,r; mov r8,[m]` rather than movzx -- all three
 * zeroing instructions hoist above the loads.
 *
 * BYTE-EXACT 2026-09-13 (13 cpp probes).  The eight-dword zero at +0x2A90
 * is an INDEXED for loop (`for (i = 0; i < 8; i++) a2A90[i] = 0;`), not a
 * memset: VC5 turns the loop into the same `rep stosd` but materialises
 * the destination BEFORE the fill value (`lea edi / mov ecx,8 / xor eax`),
 * where every memset spelling emits `mov ecx / xor eax / lea edi`.  The
 * memset forms and every flag set were dead (12 diffs, one permutation);
 * the loop is the source fact.  See docs/VC5-IDIOMS.md "rep stosd order".
 */
#define _CRTIMP __declspec(dllimport)
#include <string.h>
#include "slice3_41.h"   /* BrDriverCar, the canonical record */

class Car6FCE0 {
public:
    char          pad[0x29AC];
    unsigned char b29AC;        /* +0x29AC */
    unsigned char b29AD;        /* +0x29AD */
    unsigned char b29AE;        /* +0x29AE */
    char          pad29AF[0x2A70 - 0x29AF];
    int           f2A70;        /* +0x2A70 */
    char          pad2A74[0x2A90 - 0x2A74];
    int           a2A90[8];     /* +0x2A90 */

    void Bind(int slot);        /* 0x1006FCB0 */
    void SlotSetup(int slot, int a);
};


extern "C" {
/* BrImgTintSetScale: prototype in br_funcs.h */
/* BrCarSlotLoad: prototype in br_funcs.h */
/* BrSub10074E20: prototype in br_funcs.h */
}

void Car6FCE0::SlotSetup(int slot, int a)
{
    int i;

    BrImgTintSetScale((*(unsigned char *)&((BrDriverCar *)(this))->f29AC), (*(unsigned char *)&((BrDriverCar *)(this))->f29AD), (*(unsigned char *)&((BrDriverCar *)(this))->f29AE));
    BrCarSlotLoad(slot, a, 0);
    BrSub10074E20((unsigned int *)(&(*(int *)&((BrDriverCar *)(this))->f2A70)));
    for (i = 0; i < 8; i++)
        (*(int (*)[8])&((BrDriverCar *)(this))->f2A90[0])[i] = 0;
    Bind(slot);
}

/* 0x1006FCB0 -- not yet transcribed in src/; read off the original:
 * thiscall, one stack arg (`ret 4`).  Points the car at its slot's model
 * record (slot * 0x15F88 into the car-slot area at 0x100BCDD0, which
 * BrCarSlotLoad filled) and refreshes its colours (0x1006FC70). */
void Car6FCE0::Bind(int slot)
{
    ((BrDriverCar *)this)->pModel = &g_ab0C12A0[slot * 0x15F88];
    BrEntRefreshColour((struct BrEntCar *)this);
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" void BrCarSlotBind_1006FCB0(void *self, int slot)
{
    ((class Car6FCE0 *)self)->Bind(slot);
}
extern "C" void BrCarSlotSetup_1006FCE0(void *self, int slot, int a)
{
    ((class Car6FCE0 *)self)->SlotSetup(slot, a);
}
/* end of C entry points */
