#include "slice3_41.h"   /* BrDriverCar, the canonical record */
/* WHAT IT DOES: the per-driver end-of-step bookkeeping.  If the car left a
 * skid this step it kicks the force-feedback wheel one way or the other by
 * the skid's heading, drops a ripple for a long enough skid and clears it;
 * then it runs the car's clocks, messages, wrong-way check, the driver's
 * checkpoint gate and the car's grid cell, rebuilds the world velocity from
 * the last two positions, refreshes the car's heading and counts down its
 * hold timer.  Nothing happens while the race is paused. */
/* @implements 0x100623E0 glide BrRaceDriverPost
 * @cpp_symbol ?m_100623E0@Driver_623E0@@QAEXXZ
 *
 * A __thiscall on the driver whose callees are __thiscall on the car
 * (0x1000C4E0 the ripple, 0x1006E9E0/EA70/EB00/EBC0) and on the driver
 * (0x1005FF00): C++.  Members are VA-named so every thiscall maps to its
 * address.  Source facts that carry the bytes:
 *   - the wheel kick is an if/else with the `<= 180` arm (-1) first: VC5
 *     tail-merges the two calls into `push -1 / jmp / push 1 / call`, where
 *     a ternary argument becomes setcc arithmetic;
 *   - the skid length is read into an unsigned-char local and passed as
 *     (short) -- the original's `movzx ax, al`;
 *   - pCar is re-read through `this` for every statement (it is a member). */


class Car_623E0 {
public:
    void m_1000C4E0(const float *pDir, short mag);   /* the ripple */
    void m_1006E9E0();
    void m_1006EA70();
    void m_1006EB00();
    void m_1006EBC0();

    char          pad000[0x30];
    BrVec3        pos;          /* +0x030 */
    char          pad03c[0x350 - 0x3c];
    float         skid[2];      /* +0x350 */
    char          pad358[8];
    unsigned char skidLen;      /* +0x360 */
    char          pad361[0xF04 - 0x361];
    int           fF04;         /* +0xF04 */
    char          padF08[0xF80 - 0xF08];
    BrVec3        posPrev;      /* +0xF80 */
    char          padF8C[0x1024 - 0xF8C];
    BrVec3        vel;          /* +0x1024 */
    char          pad1030[0x2718 - 0x1030];
    float         f2718;        /* +0x2718 */
    char          pad271C[0x2734 - 0x271C];
    float        *p2734;        /* +0x2734 */
};

class Driver_623E0 {
public:
    void m_1005FF00();
    void m_100623E0();

    char       pad[0x60];
    Car_623E0 *pCar;            /* +0x60 */
};

extern "C" {
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* 64-bit core: declared once, in br_globals.h or its struct's header */
/* BrAtan2: prototype in br_funcs.h */
/* BrFfbSetDirection: prototype in br_funcs.h */
/* 64-bit core: declared once, by its definition's header */
/* 64-bit core: declared once, by its definition's header */
}

void Driver_623E0::m_100623E0()
{
    if ((*(int *)&g_BrX06909B4) != 0 || pCar == 0)
        return;

    if ((*(unsigned char *)&((BrDriverCar *)(pCar))->aBody[0].f01FC) != 0) {
        /* radians -> degrees with the original's own float, 0x42652EE0 --
         * one ULP under what 57.29578f rounds to (0x42652EE1). */
        if ((int)(BrAtan2((*(float (*)[2])&((BrDriverCar *)(pCar))->aBody[0].f01EC)[0], (*(float (*)[2])&((BrDriverCar *)(pCar))->aBody[0].f01EC)[1]) * 57.2957763671875f) <= 180)
            BrFfbSetDirection(-1);
        else
            BrFfbSetDirection(1);
        {
            unsigned char n = (*(unsigned char *)&((BrDriverCar *)(pCar))->aBody[0].f01FC);
            if (n >= 10)
                pCar->m_1000C4E0((*(float (*)[2])&((BrDriverCar *)(pCar))->aBody[0].f01EC), (short)n);
        }
        (*(unsigned char *)&((BrDriverCar *)(pCar))->aBody[0].f01FC) = 0;
    }
    pCar->m_1006E9E0();
    pCar->m_1006EA70();
    pCar->m_1006EB00();
    m_1005FF00();
    pCar->m_1006EBC0();

    BrVec3Sub(&(*(struct BrVec3 *)&((BrDriverCar *)(pCar))->f1024), &(*(struct BrVec3 *)&((BrDriverCar *)(pCar))->pos), &(*(struct BrVec3 *)&((BrDriverCar *)(pCar))->posPrev));
    BrVec3ScaleBy(&(*(struct BrVec3 *)&((BrDriverCar *)(pCar))->f1024), 1.0f / g_brRaceFlyStep);
    (*(float *)&((BrDriverCar *)(pCar))->f2718) = BrAtan2((*(float * *)&((BrDriverCar *)(pCar))->pMatA)[0], (*(float * *)&((BrDriverCar *)(pCar))->pMatA)[1]);

    if ((*(int *)&((BrDriverCar *)(pCar))->fF04) != 0)
        (*(int *)&((BrDriverCar *)(pCar))->fF04)--;
}

/* C entry points (generated by ports/64b/tools/methodfwd.py) */
extern "C" void BrRaceDriverPost(void *self)
{
    ((class Driver_623E0 *)self)->m_100623E0();
}
/* end of C entry points */

/* Methods of the local classes above that other files define: each is
 * the function at its original address, reached through its C entry. */
/* 0x1000C4E0: the original calls BrRippleApply_1000C4E0 by address */
void Car_623E0::m_1000C4E0(const float * a1, short a2)
{
    BrRippleApply_1000C4E0((void *)this, (const float *)a1, (short)a2);
}

/* 0x1006E9E0: the original calls BrCarTickClocks by address */
void Car_623E0::m_1006E9E0()
{
    BrCarTickClocks((struct BrDriverCar *)this);
}

/* 0x1006EA70: the original calls BrCarTickMessages by address */
void Car_623E0::m_1006EA70()
{
    BrCarTickMessages((struct BrDriverCar *)this);
}

/* 0x1006EB00: the original calls FUN_1006eb00 by address */
void Car_623E0::m_1006EB00()
{
    FUN_1006eb00((struct BrDriverCar *)this);
}

/* 0x1006EBC0: the original calls BrCarTickGridCell by address */
void Car_623E0::m_1006EBC0()
{
    BrCarTickGridCell((struct BrDriverCar *)this);
}

/* 0x1005FF00: the original calls BrRaceGateStep by address */
void Driver_623E0::m_1005FF00()
{
    BrRaceGateStep((struct BrDriver *)this);
}
